SWORDS = [
    {
        "rank": "ace",
        "astrology": None,
        "keywords_up": ["kejernihan", "kebenaran", "terobosan", "keputusan tegas"],
        "keywords_rev": ["pikiran kabur", "salah paham", "keputusan keliru", "kata yang melukai"],
        "symbolism": "Sebuah tangan muncul dari awan menggenggam pedang tegak. Ujungnya dilingkari mahkota yang dihiasi ranting zaitun dan daun palem, dengan pegunungan tandus di bawahnya.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kejernihan pikiran dan kebenaran yang memotong kebingungan. Ada terobosan, ide tajam, atau keputusan tegas yang membuka jalan.",
            "cinta": "Percakapan jujur yang menjernihkan hubungan. Kebenaran mungkin tajam, tapi membebaskan.",
            "karier": "Ide cemerlang, keputusan strategis, atau kemenangan lewat argumen yang kuat.",
            "keuangan": "Keputusan finansial yang rasional dan berbasis data. Saat yang baik untuk merapikan rencana.",
            "saran": "Katakan yang benar dengan jelas, dan ambil keputusan berdasarkan fakta.",
        },
        "rev": {
            "umum": "Pikiran yang kabur, informasi yang keliru, atau kata-kata yang dipakai untuk melukai. Keputusan sebaiknya ditunda sampai kepala lebih jernih.",
            "cinta": "Salah paham atau ucapan tajam yang menyakiti. Pilih kata dengan hati-hati.",
            "karier": "Ide belum matang atau komunikasi yang membingungkan. Periksa ulang sebelum menyampaikan.",
            "keuangan": "Keputusan berdasarkan informasi yang salah. Verifikasi semua data lebih dulu.",
            "saran": "Jernihkan pikiranmu sebelum bicara atau memutuskan sesuatu yang penting.",
        },
    },
    {
        "rank": "two",
        "astrology": "Bulan di Libra",
        "keywords_up": ["dilema", "jalan buntu", "menghindari keputusan", "keseimbangan rapuh"],
        "keywords_rev": ["kebingungan memuncak", "informasi baru", "harus memilih", "beban emosi"],
        "symbolism": "Seorang wanita bermata tertutup duduk memegang dua pedang yang disilangkan di depan dadanya. Laut berbatu terbentang di belakangnya di bawah bulan sabit.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kamu berada di persimpangan dan memilih untuk tidak melihat. Keseimbangan yang terasa tenang ini rapuh, karena keputusan yang ditunda tetap menunggu.",
            "cinta": "Ragu menentukan sikap, atau menghindari pembicaraan penting demi menjaga suasana.",
            "karier": "Dilema antara dua pilihan atau dua pihak. Kumpulkan informasi yang selama ini kamu hindari.",
            "keuangan": "Keputusan finansial tertahan karena takut salah. Bandingkan pilihan secara objektif.",
            "saran": "Buka penutup matamu. Lihat semua fakta, termasuk yang tidak nyaman, sebelum memilih.",
        },
        "rev": {
            "umum": "Kebimbangan memuncak dan menunda tidak lagi mungkin. Informasi baru muncul, dan kamu terdorong untuk akhirnya memilih.",
            "cinta": "Perasaan yang selama ini ditahan mulai keluar. Kejujuran dibutuhkan agar semua pihak tidak terus menggantung.",
            "karier": "Tekanan untuk memilih datang dari luar. Ambil keputusan sebelum orang lain mengambilnya untukmu.",
            "keuangan": "Situasi memaksa keputusan segera. Pilih yang paling bisa kamu pertanggungjawabkan.",
            "saran": "Pilih saja, lalu bertanggung jawablah atas pilihan itu. Tidak memilih juga sebuah pilihan.",
        },
    },
    {
        "rank": "three",
        "astrology": "Saturnus di Libra",
        "keywords_up": ["patah hati", "kesedihan", "kebenaran yang menyakitkan", "duka"],
        "keywords_rev": ["pemulihan", "memaafkan", "melepaskan duka", "luka mulai sembuh"],
        "symbolism": "Sebuah hati merah ditembus tiga pedang dengan latar awan kelabu dan hujan yang turun deras.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Rasa sakit karena kebenaran yang terungkap, kehilangan, atau kata-kata yang melukai. Duka ini nyata dan perlu dirasakan, bukan disangkal.",
            "cinta": "Patah hati, pengkhianatan, atau perpisahan yang menyakitkan. Beri dirimu waktu untuk pulih.",
            "karier": "Kekecewaan di tempat kerja, kritik yang menyakitkan, atau berita yang tidak menyenangkan.",
            "keuangan": "Kerugian yang terasa berat secara emosional. Pisahkan dulu perasaan dari langkah pemulihan.",
            "saran": "Izinkan dirimu bersedih. Air mata adalah bagian dari proses penyembuhan.",
        },
        "rev": {
            "umum": "Luka mulai sembuh perlahan. Kamu mulai bisa membicarakan rasa sakit itu dan melepaskan sebagian bebannya.",
            "cinta": "Memaafkan atau berdamai setelah konflik yang menyakitkan, meski bekasnya masih ada.",
            "karier": "Bangkit setelah kekecewaan di tempat kerja dan mengambil pelajaran darinya.",
            "keuangan": "Pemulihan pelan setelah kerugian. Fokus pada langkah ke depan.",
            "saran": "Teruskan proses pemulihanmu. Bicarakan lukamu dengan orang yang kamu percaya.",
        },
    },
    {
        "rank": "four",
        "astrology": "Yupiter di Libra",
        "keywords_up": ["istirahat", "pemulihan", "jeda", "kontemplasi"],
        "keywords_rev": ["gelisah", "kelelahan", "kembali bergerak", "menolak beristirahat"],
        "symbolism": "Patung seorang ksatria terbaring di atas makam dengan tangan terkatup seperti berdoa. Tiga pedang tergantung di dinding, satu lagi terletak di sisinya, di bawah jendela kaca patri.",
        "answer_up": "belum",
        "answer_rev": "belum",
        "up": {
            "umum": "Waktu untuk beristirahat dan memulihkan diri. Setelah masa yang berat, tubuh dan pikiranmu butuh jeda sebelum menghadapi langkah berikutnya.",
            "cinta": "Hubungan butuh ruang tenang. Jeda sejenak bisa membantu kalian melihat semuanya dengan lebih jernih.",
            "karier": "Ambil cuti, kurangi beban, atau rencanakan ulang strategi dengan tenang.",
            "keuangan": "Tahan keputusan finansial yang besar dan biarkan situasinya stabil dulu.",
            "saran": "Beristirahatlah dengan sungguh-sungguh. Pemulihan juga bagian dari kemajuan.",
        },
        "rev": {
            "umum": "Kelelahan yang tidak diberi ruang, atau kegelisahan setelah terlalu lama berdiam. Kamu mungkin perlu kembali bergerak, atau justru akhirnya berhenti.",
            "cinta": "Jeda yang terlalu lama membuat hubungan dingin, atau kalian sama-sama terlalu lelah untuk bicara.",
            "karier": "Kelelahan kerja mulai berdampak. Jangan tunggu sampai tubuh memaksamu berhenti.",
            "keuangan": "Menunda terlalu lama membuat kesempatan lewat. Mulailah bergerak perlahan.",
            "saran": "Dengarkan tubuhmu. Kalau lelah, berhentilah. Kalau sudah pulih, mulailah bergerak.",
        },
    },
    {
        "rank": "five",
        "astrology": "Venus di Aquarius",
        "keywords_up": ["konflik", "menang dengan cara curang", "kehilangan", "harga diri terluka"],
        "keywords_rev": ["berdamai", "menyesal", "mengakhiri konflik", "memaafkan"],
        "symbolism": "Seorang pria tersenyum sinis sambil memungut pedang, sementara dua orang berjalan menjauh dengan kepala tertunduk. Dua pedang tergeletak di tanah di bawah langit berawan tajam.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Konflik yang menyisakan rasa pahit, bahkan bagi pihak yang menang. Pertanyaannya bukan siapa yang benar, melainkan apa harga yang dibayar.",
            "cinta": "Pertengkaran yang menyakitkan atau ego yang lebih penting dari hubungan. Kemenangan dalam debat bisa berarti kekalahan dalam hubungan.",
            "karier": "Persaingan tidak sehat, intrik, atau kemenangan yang merusak hubungan kerja.",
            "keuangan": "Sengketa yang lebih banyak menguras daripada menghasilkan. Pertimbangkan jalan damai.",
            "saran": "Tanyakan apakah pertarungan ini layak. Kadang mundur adalah pilihan yang paling bijak.",
        },
        "rev": {
            "umum": "Keinginan untuk berdamai setelah konflik. Ada penyesalan, permintaan maaf, atau kesadaran bahwa pertarungan tidak lagi perlu dilanjutkan.",
            "cinta": "Membuka pintu rekonsiliasi atau menyadari kesalahan sendiri.",
            "karier": "Ketegangan mereda dan ada peluang memperbaiki hubungan kerja.",
            "keuangan": "Menyelesaikan sengketa lewat kompromi lebih menguntungkan daripada terus bertahan.",
            "saran": "Ulurkan tangan lebih dulu bila memang perlu. Damai sering lebih berharga dari menang.",
        },
    },
    {
        "rank": "six",
        "astrology": "Merkurius di Aquarius",
        "keywords_up": ["transisi", "meninggalkan kesulitan", "pemulihan", "perjalanan"],
        "keywords_rev": ["tertahan", "sulit pergi", "masalah terbawa", "perjalanan tertunda"],
        "symbolism": "Seorang tukang perahu mendayung perahu yang membawa seorang wanita dan anak menuju pantai seberang. Enam pedang berdiri tegak di perahu, dan air di satu sisi tampak tenang.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Perpindahan dari masa sulit menuju keadaan yang lebih tenang. Belum semuanya sempurna, tapi arah perjalananmu sudah membaik.",
            "cinta": "Hubungan melewati masa sulit menuju fase yang lebih damai, atau kamu mulai pulih dari luka lama.",
            "karier": "Pindah kerja, pindah tim, atau transisi ke situasi yang lebih kondusif.",
            "keuangan": "Perlahan keluar dari kesulitan finansial. Teruskan langkah yang sudah berjalan.",
            "saran": "Teruslah bergerak menjauh dari yang menyakitimu, walau langkahnya pelan.",
        },
        "rev": {
            "umum": "Ingin pergi tapi tertahan, atau masalah lama ikut terbawa ke tempat baru. Ada urusan yang perlu diselesaikan dulu sebelum benar-benar bisa melangkah.",
            "cinta": "Sulit melepaskan masa lalu sehingga hubungan baru pun terbebani.",
            "karier": "Transisi tertunda atau perpindahan yang tidak menyelesaikan masalah utama.",
            "keuangan": "Rencana keluar dari kesulitan terhambat. Cari tahu apa yang membuatmu tertahan.",
            "saran": "Selesaikan apa yang perlu diselesaikan agar kamu bisa pergi dengan ringan.",
        },
    },
    {
        "rank": "seven",
        "astrology": "Bulan di Aquarius",
        "keywords_up": ["strategi diam-diam", "ketidakjujuran", "menghindar", "bertindak sendiri"],
        "keywords_rev": ["ketahuan", "hati nurani", "mengaku", "berhenti menipu diri"],
        "symbolism": "Seorang pria mengendap-endap meninggalkan perkemahan sambil membawa lima pedang, menoleh ke belakang. Dua pedang lain masih tertancap di tanah.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Ada sesuatu yang dilakukan diam-diam, entah oleh orang lain atau olehmu sendiri. Strategi itu mungkin cerdik, tapi kejujuran tetap dipertaruhkan.",
            "cinta": "Ada hal yang disembunyikan atau kepercayaan yang diuji. Perhatikan apa yang tidak dikatakan.",
            "karier": "Waspadai persaingan licik atau orang yang mengambil pujian atas kerjamu. Lindungi ide dan dokumenmu.",
            "keuangan": "Hati-hati dengan penipuan atau kesepakatan yang tidak transparan.",
            "saran": "Bertindak cerdik boleh, asal tetap jujur. Perhatikan juga apa yang terjadi di belakangmu.",
        },
        "rev": {
            "umum": "Rahasia mulai terungkap atau hati nurani mulai bicara. Ada kesempatan untuk berterus terang dan memperbaiki keadaan.",
            "cinta": "Kejujuran akhirnya muncul, atau kamu berhenti membohongi diri soal hubungan ini.",
            "karier": "Hal yang ditutupi mulai terlihat. Lebih baik terbuka sebelum dibuka orang lain.",
            "keuangan": "Saat yang tepat untuk membereskan urusan yang tidak transparan.",
            "saran": "Berterus teranglah. Kejujuran memang berat di awal, tapi meringankan di akhir.",
        },
    },
    {
        "rank": "eight",
        "astrology": "Yupiter di Gemini",
        "keywords_up": ["terjebak", "pikiran membatasi", "tak berdaya", "takut bergerak"],
        "keywords_rev": ["melepaskan diri", "perspektif baru", "kebebasan", "berani bergerak"],
        "symbolism": "Seorang wanita terikat dan bermata tertutup berdiri di antara delapan pedang yang tertancap di tanah. Celah untuk berjalan keluar sebenarnya ada, dan sebuah kastel berdiri di atas tebing di kejauhan.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Merasa terjebak dan tak berdaya, padahal sebagian besar kurungannya dibangun oleh pikiran sendiri. Jalan keluar ada, hanya belum terlihat.",
            "cinta": "Merasa terkekang dalam hubungan atau oleh ketakutan sendiri untuk mengambil langkah.",
            "karier": "Merasa tidak punya pilihan di pekerjaan. Daftar ulang pilihanmu dengan lebih jujur.",
            "keuangan": "Merasa buntu secara finansial. Cari nasihat, karena mungkin ada opsi yang belum kamu pertimbangkan.",
            "saran": "Tanyakan mana batasan yang nyata dan mana yang hanya ketakutan. Mulailah dari satu langkah kecil.",
        },
        "rev": {
            "umum": "Mulai melepaskan diri dari ketakutan dan pola pikir yang membatasi. Kamu menemukan sudut pandang baru dan keberanian untuk bergerak.",
            "cinta": "Keluar dari hubungan atau pola pikir yang mengekang. Kamu mulai memilih dirimu sendiri.",
            "karier": "Menemukan jalan keluar dari situasi kerja yang membuat frustrasi.",
            "keuangan": "Mulai menemukan solusi untuk masalah yang tadinya terasa buntu.",
            "saran": "Teruskan langkahmu keluar. Kebebasan dimulai dari keyakinan bahwa kamu boleh bergerak.",
        },
    },
    {
        "rank": "nine",
        "astrology": "Mars di Gemini",
        "keywords_up": ["kecemasan", "sulit tidur", "rasa bersalah", "beban pikiran"],
        "keywords_rev": ["mulai lega", "mencari bantuan", "ketakutan berkurang", "berbagi beban"],
        "symbolism": "Seorang wanita terduduk di ranjang sambil menutup wajah dengan kedua tangan. Sembilan pedang tergantung di dinding gelap, dan selimutnya bermotif mawar dan simbol zodiak.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Kecemasan dan pikiran berlebihan yang paling terasa di malam hari. Kekhawatiran sering lebih menakutkan daripada kenyataannya.",
            "cinta": "Rasa cemas, curiga, atau bersalah yang mengganggu ketenangan dalam hubungan.",
            "karier": "Stres kerja yang terbawa sampai ke rumah dan mengganggu tidur.",
            "keuangan": "Kekhawatiran soal uang yang membuatmu sulit tenang. Tulis angkanya, karena kenyataan biasanya lebih bisa diatasi.",
            "saran": "Ceritakan kekhawatiranmu pada orang yang kamu percaya. Kecemasan mengecil saat dibagi.",
        },
        "rev": {
            "umum": "Kecemasan mulai mereda, atau kamu mulai mencari bantuan. Ada cahaya setelah malam yang panjang.",
            "cinta": "Membicarakan ketakutan dengan pasangan dan menemukan bahwa keadaannya tidak seburuk yang dibayangkan.",
            "karier": "Tekanan berkurang dan kamu mulai menemukan cara menghadapinya.",
            "keuangan": "Mulai menghadapi masalah keuangan secara langsung, dan rasa takut pun berkurang.",
            "saran": "Teruslah mencari dukungan. Kamu tidak harus menghadapi pikiran-pikiran berat itu sendirian.",
        },
    },
    {
        "rank": "ten",
        "astrology": "Matahari di Gemini",
        "keywords_up": ["titik terendah", "akhir yang menyakitkan", "berakhir", "pengkhianatan"],
        "keywords_rev": ["bangkit", "yang terburuk berlalu", "pemulihan", "menolak berakhir"],
        "symbolism": "Seorang pria tertelungkup dengan sepuluh pedang menancap di punggungnya. Langit di atasnya gelap, tapi di garis cakrawala fajar kekuningan mulai menyingsing di atas air yang tenang.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Titik terendah dari sebuah situasi. Sesuatu benar-benar berakhir, dan walau rasanya menyakitkan, tidak ada lagi yang bisa lebih buruk dari ini. Fajar sudah terlihat di cakrawala.",
            "cinta": "Akhir yang menyakitkan atau rasa dikhianati. Ini penutupan, dan dari penutupan itulah pemulihan dimulai.",
            "karier": "Kegagalan atau akhir sebuah fase kerja yang terasa berat. Berhentilah melawan dan mulai menata ulang.",
            "keuangan": "Titik terendah secara finansial. Mulai dari dasar, susun rencana pemulihan yang realistis.",
            "saran": "Terima bahwa bab ini sudah selesai. Dari titik terendah, satu-satunya arah adalah naik.",
        },
        "rev": {
            "umum": "Mulai bangkit setelah masa terburuk. Kamu masih memulihkan diri, tapi yang paling berat sudah lewat.",
            "cinta": "Pemulihan setelah perpisahan atau pengkhianatan. Perlahan kamu mulai percaya lagi.",
            "karier": "Bangkit kembali dari kegagalan dengan pelajaran yang berharga.",
            "keuangan": "Pemulihan bertahap setelah masa sulit. Jangan ulangi pola yang sama.",
            "saran": "Bangunlah pelan-pelan. Beri waktu untuk sembuh dan jangan kembali ke luka yang sama.",
        },
    },
    {
        "rank": "page",
        "astrology": None,
        "keywords_up": ["rasa ingin tahu", "waspada", "ide baru", "komunikasi"],
        "keywords_rev": ["gosip", "terburu bicara", "defensif", "mengintai"],
        "symbolism": "Seorang pemuda lincah memegang pedang tegak sambil melangkah di tanah berbukit. Awan bergerak dan burung-burung terbang di langit, seolah ia sedang berjaga terhadap sesuatu.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Rasa ingin tahu yang tajam dan pikiran yang sigap. Ada keinginan untuk belajar, bertanya, dan memahami situasi sebelum bertindak.",
            "cinta": "Percakapan yang membuka banyak hal, atau seseorang yang ingin mengenal lebih dalam lewat pikiran.",
            "karier": "Ide baru, riset, atau kesempatan untuk belajar keterampilan komunikasi.",
            "keuangan": "Pelajari dulu sebelum mengambil keputusan. Rasa ingin tahumu adalah pelindung.",
            "saran": "Ajukan pertanyaan dan cari informasi yang lengkap sebelum menarik kesimpulan.",
        },
        "rev": {
            "umum": "Kata-kata yang terlalu cepat keluar, gosip, atau sikap defensif. Rasa ingin tahu bisa berubah menjadi kecurigaan.",
            "cinta": "Komunikasi yang tajam atau saling memata-matai. Kepercayaan perlu dibangun ulang.",
            "karier": "Gosip di kantor atau ide yang disampaikan sebelum matang. Jaga ucapanmu.",
            "keuangan": "Jangan mengambil keputusan keuangan berdasarkan kabar burung atau rumor.",
            "saran": "Pikirkan dulu sebelum bicara, dan jauhi kebiasaan menghakimi terlalu cepat.",
        },
    },
    {
        "rank": "knight",
        "astrology": "20° Taurus sampai 20° Gemini",
        "keywords_up": ["ambisi", "bergerak cepat", "tegas", "langsung"],
        "keywords_rev": ["gegabah", "kasar", "tergesa-gesa", "tanpa rencana"],
        "symbolism": "Seorang ksatria memacu kudanya dengan kecepatan penuh sambil mengacungkan pedang. Awan dan pepohonan terlihat tertiup angin kencang.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Gerak cepat yang didorong ambisi dan keyakinan. Kamu tahu apa yang ingin dicapai dan siap menerobos hambatan.",
            "cinta": "Pendekatan yang langsung dan berani, atau pembicaraan jujur yang tidak bertele-tele.",
            "karier": "Bergerak cepat untuk mengejar target. Ketegasanmu membantu, asal tetap mendengarkan orang lain.",
            "keuangan": "Tindakan cepat untuk mengambil peluang. Pastikan risikonya sudah dihitung.",
            "saran": "Bergeraklah dengan berani, tapi pastikan arahmu tepat dan tidak melukai orang di sekitarmu.",
        },
        "rev": {
            "umum": "Terlalu tergesa-gesa dan agresif. Kata-kata atau tindakan yang cepat bisa merusak lebih banyak dari yang diselesaikan.",
            "cinta": "Ucapan kasar atau keputusan terburu-buru dalam hubungan. Tenangkan diri sebelum bicara.",
            "karier": "Bertindak tanpa rencana atau melukai rekan karena terlalu fokus pada target.",
            "keuangan": "Keputusan finansial yang terburu-buru. Tunggu sampai semua informasi lengkap.",
            "saran": "Perlambat langkahmu. Kecepatan tanpa arah hanya membawa kekacauan.",
        },
    },
    {
        "rank": "queen",
        "astrology": "20° Virgo sampai 20° Libra",
        "keywords_up": ["jernih", "jujur", "mandiri", "tegas dan adil"],
        "keywords_rev": ["dingin", "kritis berlebihan", "kepahitan", "menutup hati"],
        "symbolism": "Seorang ratu duduk di singgasana berhias kupu-kupu, mengangkat pedang tegak sementara tangan lainnya terulur. Awan berkumpul di bawah, dan seekor burung terbang tinggi di langit.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Pikiran yang jernih dan kejujuran yang tegas. Pengalaman membuatmu bijak, dan kamu mampu melihat situasi tanpa terbawa perasaan.",
            "cinta": "Kejujuran dan batas yang jelas dalam hubungan. Kamu tahu apa yang kamu mau dan tidak takut mengatakannya.",
            "karier": "Analisis yang tajam, komunikasi lugas, dan penilaian yang objektif.",
            "keuangan": "Keputusan finansial yang rasional, mandiri, dan tidak mudah terbawa bujukan.",
            "saran": "Bicaralah dengan jujur dan jelas, tapi tetap sertakan sedikit kelembutan.",
        },
        "rev": {
            "umum": "Ketegasan yang berubah menjadi dingin atau terlalu kritis. Luka lama mungkin membuatmu menutup hati dan sulit percaya.",
            "cinta": "Kata-kata tajam atau sikap dingin yang menjauhkan. Biarkan dirimu sedikit lebih terbuka.",
            "karier": "Kritik yang terlalu keras atau sulit bekerja sama. Seimbangkan logika dengan empati.",
            "keuangan": "Terlalu curiga pada semua tawaran sampai melewatkan peluang yang baik.",
            "saran": "Lembutkan sedikit penilaianmu, terhadap orang lain dan terhadap dirimu sendiri.",
        },
    },
    {
        "rank": "king",
        "astrology": "20° Capricorn sampai 20° Aquarius",
        "keywords_up": ["otoritas intelektual", "kebenaran", "objektif", "keputusan adil"],
        "keywords_rev": ["manipulatif", "kejam", "menyalahgunakan kuasa", "kaku"],
        "symbolism": "Seorang raja duduk menghadap ke depan dengan pedang terhunus, seperti sedang memberi keputusan. Kupu-kupu menghiasi singgasananya dan awan rendah menggantung di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Otoritas yang didasari logika, etika, dan kejernihan. Keputusan diambil dengan adil berdasarkan fakta, bukan perasaan sesaat.",
            "cinta": "Hubungan yang dibangun di atas kejujuran dan saling menghormati. Komunikasi berjalan matang.",
            "karier": "Peran sebagai penasihat, ahli, atau pengambil keputusan. Keahlianmu dihargai.",
            "keuangan": "Keputusan berbasis analisis dan nasihat ahli. Tepat untuk urusan hukum dan kontrak.",
            "saran": "Ambil keputusan dengan kepala dingin dan prinsip yang jelas.",
        },
        "rev": {
            "umum": "Kecerdasan yang dipakai untuk mengendalikan atau memanipulasi. Kekuasaan tanpa empati bisa terasa kejam.",
            "cinta": "Sikap yang terlalu dingin, mengendalikan, atau memakai logika untuk menang sendiri.",
            "karier": "Atasan atau pihak berwenang yang menyalahgunakan posisi. Ketahui hakmu.",
            "keuangan": "Hati-hati dengan nasihat yang menguntungkan pihak lain. Periksa ulang dokumen hukum.",
            "saran": "Gunakan kecerdasanmu untuk kebaikan bersama, bukan untuk menguasai.",
        },
    },
]
