CUPS = [
    {
        "rank": "ace",
        "astrology": None,
        "keywords_up": ["cinta baru", "perasaan meluap", "welas asih", "intuisi"],
        "keywords_rev": ["perasaan terpendam", "hati tertutup", "kosong", "cinta pada diri kurang"],
        "symbolism": "Sebuah tangan muncul dari awan memegang piala yang meluap menjadi lima aliran air. Seekor merpati turun membawa wafer, dan bunga teratai mengapung di kolam di bawahnya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Awal yang baru di wilayah perasaan. Hati terasa penuh, terbuka, dan siap memberi maupun menerima. Kebaikan dan kasih sayang mengalir dengan alami.",
            "cinta": "Cinta yang baru tumbuh atau perasaan yang semakin dalam. Kartu ini kuat sekali untuk awal hubungan yang tulus.",
            "karier": "Pekerjaan yang menyentuh hati, kolaborasi yang hangat, atau proyek yang bermakna secara emosional.",
            "keuangan": "Rezeki yang datang lewat hubungan baik atau kemurahan hati. Berbagi juga membawa kepuasan tersendiri.",
            "saran": "Buka hatimu, untuk orang lain dan untuk dirimu sendiri. Biarkan perasaan mengalir tanpa ditahan.",
        },
        "rev": {
            "umum": "Perasaan yang tertahan atau hati yang sedang menutup diri. Ada rasa kosong yang perlu diisi, dimulai dari cara kamu memperlakukan dirimu sendiri.",
            "cinta": "Sulit mengungkapkan atau menerima cinta. Mungkin luka lama membuatmu berhati-hati secara berlebihan.",
            "karier": "Pekerjaan terasa hampa atau kurang dihargai. Cari kembali bagian yang membuatmu peduli.",
            "keuangan": "Pengeluaran untuk mengisi kekosongan emosional. Perhatikan apa yang sebenarnya kamu cari.",
            "saran": "Mulailah dengan bersikap lembut pada dirimu sendiri sebelum berharap orang lain melakukannya.",
        },
    },
    {
        "rank": "two",
        "astrology": "Venus di Cancer",
        "keywords_up": ["kebersamaan", "saling tertarik", "kemitraan", "keselarasan"],
        "keywords_rev": ["ketidakseimbangan", "renggang", "salah paham", "putus komunikasi"],
        "symbolism": "Seorang pemuda dan pemudi saling bertukar piala seperti mengikat janji. Di atas mereka melayang tongkat caduceus dengan kepala singa bersayap.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Hubungan yang saling menghargai dan setara. Ada rasa terhubung yang tulus antara dua pihak, entah dalam cinta, persahabatan, maupun kerja sama.",
            "cinta": "Ketertarikan yang saling berbalas dan ikatan yang menguat. Kartu yang sangat baik untuk hubungan yang sedang tumbuh.",
            "karier": "Kemitraan yang saling melengkapi, kesepakatan yang adil, atau rekan kerja yang sejalan.",
            "keuangan": "Kerja sama finansial yang seimbang dan saling menguntungkan.",
            "saran": "Rawat hubungan yang saling menghargai. Memberi dan menerima dengan setara membuat ikatan bertahan.",
        },
        "rev": {
            "umum": "Ketidakseimbangan dalam hubungan atau komunikasi yang tersendat. Rasa saling percaya perlu dipulihkan agar ikatan kembali hangat.",
            "cinta": "Salah paham, jarak, atau perasaan yang tidak lagi berbalas dengan setara. Bicarakan sebelum menjauh.",
            "karier": "Kemitraan yang mulai timpang atau kesepakatan yang dilanggar. Perjelas peran dan harapan.",
            "keuangan": "Perselisihan soal uang dengan pasangan atau rekan. Transparansi menjadi kuncinya.",
            "saran": "Perbaiki komunikasi lebih dulu. Hubungan yang seimbang dimulai dari keberanian untuk jujur.",
        },
    },
    {
        "rank": "three",
        "astrology": "Merkurius di Cancer",
        "keywords_up": ["persahabatan", "perayaan", "komunitas", "sukacita bersama"],
        "keywords_rev": ["pesta berlebihan", "gosip", "orang ketiga", "menjauh dari teman"],
        "symbolism": "Tiga gadis mengangkat piala bersama di sebuah taman, menari dalam lingkaran. Buah-buahan hasil panen bertebaran di kaki mereka.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kebersamaan dan sukacita bersama teman atau komunitas. Ada alasan untuk merayakan, dan dukungan orang-orang di sekitarmu terasa nyata.",
            "cinta": "Hubungan yang ceria dan didukung lingkaran pertemanan. Bisa juga perkenalan lewat acara atau teman.",
            "karier": "Kerja tim yang menyenangkan dan pencapaian yang dirayakan bersama. Jejaring sedang mendukungmu.",
            "keuangan": "Rezeki yang dirayakan bersama. Tetap sisihkan sebagian agar perayaan tidak berlebihan.",
            "saran": "Luangkan waktu untuk teman-temanmu dan rayakan hal-hal baik bersama mereka.",
        },
        "rev": {
            "umum": "Kesenangan yang berlebihan atau dinamika pertemanan yang mulai rumit. Gosip, kecemburuan, atau rasa tersisih bisa muncul.",
            "cinta": "Ada orang ketiga, atau terlalu banyak campur tangan teman dalam hubungan. Jaga batas privasi kalian.",
            "karier": "Kerja tim terganggu oleh gosip atau kelompok-kelompok kecil. Tetap profesional.",
            "keuangan": "Pengeluaran sosial yang membengkak. Kurangi acara yang hanya menguras dompet.",
            "saran": "Pilih lingkaran yang benar-benar mendukungmu, dan jaga keseimbangan antara bersenang-senang dan bertanggung jawab.",
        },
    },
    {
        "rank": "four",
        "astrology": "Bulan di Cancer",
        "keywords_up": ["apatis", "merenung", "tidak puas", "melewatkan peluang"],
        "keywords_rev": ["bangkit dari apatis", "menerima tawaran", "kesadaran baru", "keluar dari cangkang"],
        "symbolism": "Seorang pemuda duduk bersilang tangan di bawah pohon, menatap tiga piala di rumput. Sebuah tangan dari awan menyodorkan piala keempat yang belum ia sadari.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Rasa jenuh atau tidak puas yang membuatmu menutup diri. Kamu mungkin terlalu sibuk dengan apa yang kurang sampai tidak melihat tawaran yang sudah ada di depan mata.",
            "cinta": "Hubungan terasa hambar, atau kamu kurang tertarik pada perhatian yang ditawarkan. Tanyakan apa yang sebenarnya kamu cari.",
            "karier": "Bosan dengan pekerjaan dan cenderung mengabaikan peluang baru. Coba lihat lagi dengan pikiran terbuka.",
            "keuangan": "Peluang kecil terlewat karena kamu menunggu yang lebih besar. Jangan remehkan yang sudah tersedia.",
            "saran": "Angkat pandanganmu sejenak. Kesempatan yang kamu butuhkan mungkin sudah ditawarkan.",
        },
        "rev": {
            "umum": "Mulai bangkit dari rasa jenuh dan kembali tertarik pada kehidupan. Kamu siap menerima tawaran baru dan melihat peluang dengan mata segar.",
            "cinta": "Kembali membuka hati atau mulai menghargai perhatian yang selama ini ada.",
            "karier": "Motivasi kembali tumbuh. Saat yang tepat untuk menerima tantangan atau tawaran baru.",
            "keuangan": "Kamu mulai melihat peluang yang sebelumnya terlewat. Tindak lanjuti dengan hati-hati.",
            "saran": "Sambut kesempatan yang datang. Keluar dari cangkang tidak harus sekaligus.",
        },
    },
    {
        "rank": "five",
        "astrology": "Mars di Scorpio",
        "keywords_up": ["kehilangan", "kesedihan", "penyesalan", "fokus pada yang hilang"],
        "keywords_rev": ["menerima", "memaafkan", "bangkit", "melihat yang tersisa"],
        "symbolism": "Sosok berjubah hitam menunduk menatap tiga piala yang tumpah. Di belakangnya masih berdiri dua piala utuh, dan sebuah jembatan menuju kastel di seberang sungai.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Kesedihan atas sesuatu yang hilang atau tidak berjalan sesuai harapan. Rasa kecewa itu nyata, tapi masih ada yang tersisa dan bisa diselamatkan.",
            "cinta": "Patah hati, kekecewaan, atau penyesalan dalam hubungan. Beri dirimu waktu untuk berduka dengan jujur.",
            "karier": "Kegagalan proyek atau peluang yang terlepas. Ambil pelajarannya, lalu lihat apa yang masih bisa dibangun.",
            "keuangan": "Kerugian yang menyakitkan. Hitung apa yang tersisa dan susun langkah pemulihan.",
            "saran": "Izinkan dirimu bersedih, lalu perlahan berbaliklah. Dua piala yang masih berdiri menunggu untuk dilihat.",
        },
        "rev": {
            "umum": "Mulai menerima kehilangan dan bergerak maju. Kesedihan perlahan mereda, dan kamu kembali melihat hal-hal yang masih berharga.",
            "cinta": "Memaafkan, berdamai dengan masa lalu, atau membuka hati kembali setelah luka.",
            "karier": "Bangkit setelah kegagalan dengan pelajaran yang berharga. Saatnya mencoba lagi.",
            "keuangan": "Pemulihan bertahap setelah kerugian. Fokus pada langkah kecil yang konsisten.",
            "saran": "Berdamailah dengan yang sudah terjadi, lalu bawa pelajarannya ke langkah berikutnya.",
        },
    },
    {
        "rank": "six",
        "astrology": "Matahari di Scorpio",
        "keywords_up": ["nostalgia", "kenangan manis", "kepolosan", "kebaikan sederhana"],
        "keywords_rev": ["terjebak masa lalu", "idealisasi", "sulit move on", "kekanak-kanakan"],
        "symbolism": "Dua anak berada di taman sebuah rumah tua. Si anak laki-laki menyerahkan piala berisi bunga putih kepada anak perempuan, dan enam piala penuh bunga tersebar di sekitar mereka.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kenangan manis dan kebaikan yang sederhana. Masa lalu menghadirkan rasa hangat, dan ada ketulusan dalam memberi tanpa banyak perhitungan.",
            "cinta": "Hubungan yang manis dan polos, atau kembalinya seseorang dari masa lalu. Bisa juga cinta yang tumbuh dari persahabatan lama.",
            "karier": "Kembali ke minat lama, bekerja dengan anak-anak, atau bertemu lagi dengan rekan lama.",
            "keuangan": "Bantuan dari keluarga atau orang lama, atau kemurahan hati yang tulus.",
            "saran": "Ambil kehangatan dari kenangan baikmu, lalu bawa kebaikan itu ke masa sekarang.",
        },
        "rev": {
            "umum": "Terlalu terikat pada masa lalu sehingga sulit menerima keadaan sekarang. Kenangan mungkin diingat lebih indah daripada kenyataannya.",
            "cinta": "Membandingkan pasangan dengan masa lalu atau sulit melupakan mantan. Hidup ada di masa sekarang.",
            "karier": "Bertahan pada cara lama yang sudah tidak relevan. Beradaptasilah dengan perubahan.",
            "keuangan": "Keputusan keuangan dipengaruhi kebiasaan lama yang tidak lagi cocok.",
            "saran": "Hargai masa lalu tanpa tinggal di dalamnya. Pelajaran lama berguna untuk hari ini.",
        },
    },
    {
        "rank": "seven",
        "astrology": "Venus di Scorpio",
        "keywords_up": ["banyak pilihan", "angan-angan", "ilusi", "bingung memilih"],
        "keywords_rev": ["kejelasan", "fokus", "kembali realistis", "keputusan diambil"],
        "symbolism": "Seseorang terpana di depan tujuh piala yang melayang di awan. Isinya beragam: kepala, sosok berselubung, ular, kastel, perhiasan, karangan bunga, dan naga.",
        "answer_up": "belum",
        "answer_rev": "ya",
        "up": {
            "umum": "Terlalu banyak pilihan dan angan-angan, sementara tidak semuanya nyata. Kamu perlu memilah mana yang sungguh bisa diwujudkan dan mana yang hanya terlihat memikat.",
            "cinta": "Bingung di antara beberapa pilihan, atau membayangkan seseorang lebih ideal dari kenyataannya.",
            "karier": "Banyak ide dan tawaran, tapi belum ada yang jelas. Uji kelayakannya sebelum berkomitmen.",
            "keuangan": "Waspadai tawaran yang terlihat menggiurkan. Tidak semua yang berkilau benar-benar berharga.",
            "saran": "Turunkan pilihanmu menjadi satu atau dua yang paling realistis, lalu fokuslah ke sana.",
        },
        "rev": {
            "umum": "Kabut mulai hilang dan kamu bisa melihat pilihan dengan lebih jernih. Saatnya berhenti berangan-angan dan mulai memutuskan.",
            "cinta": "Mulai melihat seseorang apa adanya, atau akhirnya tahu apa yang sebenarnya kamu inginkan.",
            "karier": "Prioritas mulai jelas. Pilih satu jalur dan curahkan tenagamu di sana.",
            "keuangan": "Kembali realistis soal uang dan menyingkirkan rencana yang tidak masuk akal.",
            "saran": "Ambil keputusan selagi pandanganmu jernih, lalu jalani dengan sepenuh hati.",
        },
    },
    {
        "rank": "eight",
        "astrology": "Saturnus di Pisces",
        "keywords_up": ["meninggalkan", "mencari makna", "melepaskan", "perjalanan batin"],
        "keywords_rev": ["takut pergi", "ragu meninggalkan", "kembali ke pola lama", "berputar-putar"],
        "symbolism": "Seorang pria bertongkat berjalan menjauhi delapan piala yang tersusun rapi, menuju pegunungan di bawah bulan yang menatap ke bawah.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Meninggalkan sesuatu yang secara lahir tampak cukup, tapi tidak lagi memberi makna. Ini keputusan sulit yang lahir dari kebutuhan batin untuk mencari yang lebih bermakna.",
            "cinta": "Melepas hubungan yang sudah tidak memberi ruang tumbuh, atau mengambil jarak untuk menemukan diri sendiri.",
            "karier": "Meninggalkan pekerjaan atau jalur yang sudah tidak sesuai, walau terlihat aman.",
            "keuangan": "Rela melepas kenyamanan finansial demi tujuan yang lebih bermakna. Persiapkan transisinya dengan matang.",
            "saran": "Beranilah pergi dari yang tidak lagi mengisi hatimu, walau orang lain mungkin tidak mengerti alasannya.",
        },
        "rev": {
            "umum": "Tahu harus pergi, tapi masih ragu melangkah. Kamu mungkin berputar di tempat yang sama karena takut pada apa yang ada di luar sana.",
            "cinta": "Bertahan karena takut sendiri, atau terus kembali ke hubungan yang sama.",
            "karier": "Ingin pindah tapi menunda karena takut tidak stabil. Susun rencana keluar yang realistis.",
            "keuangan": "Rasa takut kehilangan kenyamanan menahanmu mengambil keputusan yang perlu.",
            "saran": "Tanyakan apa yang sebenarnya membuatmu bertahan: alasan yang kuat atau sekadar rasa takut.",
        },
    },
    {
        "rank": "nine",
        "astrology": "Yupiter di Pisces",
        "keywords_up": ["keinginan terkabul", "kepuasan", "rasa syukur", "kenyamanan"],
        "keywords_rev": ["puas diri", "keinginan dangkal", "berlebihan", "kepuasan semu"],
        "symbolism": "Seorang pria duduk puas dengan tangan bersilang di depan sembilan piala yang tersusun melengkung di belakangnya, seperti tuan rumah yang bangga dengan jamuannya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kartu ini dikenal sebagai kartu harapan yang terkabul. Ada rasa puas, nyaman, dan syukur atas apa yang sudah kamu dapatkan.",
            "cinta": "Hubungan yang membuatmu bahagia dan merasa cukup. Keinginan dalam hal cinta sedang didukung.",
            "karier": "Pencapaian yang memuaskan dan rasa bangga atas hasil kerjamu.",
            "keuangan": "Keadaan finansial yang nyaman. Nikmati dengan bersyukur dan tetap bijak.",
            "saran": "Syukuri apa yang sudah ada. Kebahagiaan juga perlu disadari, bukan hanya dikejar.",
        },
        "rev": {
            "umum": "Kepuasan yang dangkal atau terlalu bergantung pada hal-hal materi. Keinginan tercapai, tapi rasanya tidak seindah yang dibayangkan.",
            "cinta": "Hubungan tampak sempurna di luar, tapi ada kebutuhan batin yang belum terpenuhi.",
            "karier": "Puas diri membuatmu berhenti berkembang. Tetapkan tujuan yang lebih bermakna.",
            "keuangan": "Konsumsi berlebihan demi kesenangan sesaat. Bedakan keinginan dan kebutuhan.",
            "saran": "Tanyakan pada dirimu apa yang sebenarnya membuatmu bahagia, lalu kejar itu.",
        },
    },
    {
        "rank": "ten",
        "astrology": "Mars di Pisces",
        "keywords_up": ["kebahagiaan keluarga", "keharmonisan", "kepuasan batin", "rumah yang hangat"],
        "keywords_rev": ["keluarga tidak harmonis", "nilai berbeda", "harapan tidak realistis", "rumah yang renggang"],
        "symbolism": "Sepasang suami istri merentangkan tangan ke arah pelangi berisi sepuluh piala, sementara dua anak menari di dekat mereka. Sebuah rumah yang tenang berdiri di kejauhan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kebahagiaan yang utuh dan bertahan lama. Ada rasa damai, keharmonisan dengan orang terdekat, dan perasaan sudah pulang ke tempat yang tepat.",
            "cinta": "Hubungan yang matang dan penuh kasih, sering mengarah pada keluarga dan kehidupan bersama yang bahagia.",
            "karier": "Pekerjaan yang selaras dengan nilai hidupmu dan lingkungan yang terasa seperti keluarga.",
            "keuangan": "Keadaan yang cukup untuk membuat keluarga merasa aman dan bahagia.",
            "saran": "Hargai orang-orang yang membuatmu merasa di rumah, dan rawat kebersamaan itu.",
        },
        "rev": {
            "umum": "Keharmonisan yang terganggu, entah di rumah atau dalam hubungan dekat. Harapan tentang keluarga ideal mungkin berbenturan dengan kenyataan.",
            "cinta": "Nilai atau tujuan hidup yang berbeda mulai terasa. Bicarakan masa depan yang kalian inginkan.",
            "karier": "Pekerjaan mengganggu kehidupan keluarga, atau suasana kerja tidak harmonis.",
            "keuangan": "Perbedaan pandangan soal uang di dalam keluarga. Sepakati prioritas bersama.",
            "saran": "Lepaskan gambaran ideal dan rawat hubungan yang nyata, dengan segala kekurangannya.",
        },
    },
    {
        "rank": "page",
        "astrology": None,
        "keywords_up": ["kepekaan", "pesan perasaan", "kreativitas", "ketulusan"],
        "keywords_rev": ["terlalu sensitif", "kekanak-kanakan", "perasaan disembunyikan", "kreativitas tersumbat"],
        "symbolism": "Seorang pemuda bertunik biru bermotif teratai berdiri di tepi laut, memegang piala yang dari dalamnya seekor ikan menyembul keluar.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kepekaan, imajinasi, dan pesan yang menyentuh hati. Ada kejutan kecil yang manis atau ide kreatif yang muncul dari tempat tak terduga.",
            "cinta": "Pernyataan perasaan, ajakan yang tulus, atau awal hubungan yang manis dan sedikit malu-malu.",
            "karier": "Ide kreatif yang segar atau kesempatan belajar di bidang seni dan pelayanan.",
            "keuangan": "Peluang kecil dari bakat kreatif. Hargai karyamu dengan layak.",
            "saran": "Dengarkan intuisimu dan izinkan dirimu bermain dengan imajinasi.",
        },
        "rev": {
            "umum": "Perasaan yang mudah tersinggung atau emosi yang belum matang. Kamu mungkin menyimpan perasaan karena takut ditolak.",
            "cinta": "Rasa tidak aman atau sikap kekanak-kanakan dalam hubungan. Ungkapkan perasaan dengan cara yang dewasa.",
            "karier": "Kreativitas tersumbat atau kritik terasa terlalu personal. Pisahkan karya dari harga dirimu.",
            "keuangan": "Keputusan finansial yang didorong suasana hati. Tunggu sampai emosi lebih tenang.",
            "saran": "Akui perasaanmu dengan jujur, tanpa membiarkannya mengambil alih kemudi.",
        },
    },
    {
        "rank": "knight",
        "astrology": "20° Aquarius sampai 20° Pisces",
        "keywords_up": ["romantis", "tawaran", "idealisme", "mengikuti hati"],
        "keywords_rev": ["tidak realistis", "murung", "janji kosong", "mudah cemburu"],
        "symbolism": "Seorang ksatria bersayap di helm dan tumitnya menunggang kuda putih dengan langkah tenang, mengulurkan piala ke depan seperti membawa tawaran. Sungai mengalir di dekatnya.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Tawaran yang datang dengan niat baik dan hati yang tulus. Kamu digerakkan oleh perasaan dan idealisme, dan itu membawa keindahan ke dalam hidupmu.",
            "cinta": "Pendekatan yang romantis, ajakan, atau lamaran. Seseorang datang dengan perasaan yang tulus.",
            "karier": "Tawaran kerja yang menarik secara emosional atau proyek kreatif. Pastikan detailnya juga masuk akal.",
            "keuangan": "Tawaran yang terlihat indah. Periksa angka-angkanya dengan teliti sebelum menerima.",
            "saran": "Ikuti hatimu, tapi bawa juga logika dan akal sehat dalam perjalanan itu.",
        },
        "rev": {
            "umum": "Idealisme yang tidak berpijak pada kenyataan, atau janji manis yang tidak ditepati. Suasana hati mudah berubah-ubah.",
            "cinta": "Rayuan yang tidak tulus, kecemburuan, atau harapan yang terlalu romantis. Perhatikan konsistensi.",
            "karier": "Tawaran yang tidak sesuai kenyataan atau rekan yang tidak bisa diandalkan.",
            "keuangan": "Keputusan finansial yang terlalu emosional. Jangan tergoda janji yang terlalu indah.",
            "saran": "Bedakan antara apa yang kamu harapkan dan apa yang benar-benar terjadi.",
        },
    },
    {
        "rank": "queen",
        "astrology": "20° Gemini sampai 20° Cancer",
        "keywords_up": ["empati", "intuisi", "kasih sayang", "ketenangan emosi"],
        "keywords_rev": ["terlalu menyerap emosi", "bergantung", "batas lemah", "tenggelam perasaan"],
        "symbolism": "Seorang ratu duduk di singgasana di tepi laut, menatap dalam-dalam piala tertutup berhias malaikat. Singgasananya dihiasi anak-anak duyung, dan kakinya hampir menyentuh air.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kepekaan yang matang dan penuh kasih. Kamu mampu memahami perasaan orang lain tanpa kehilangan dirimu sendiri, dan intuisimu bisa dipercaya.",
            "cinta": "Hubungan yang penuh pengertian dan kelembutan. Kamu atau pasanganmu mampu menjadi tempat pulang yang aman.",
            "karier": "Pekerjaan yang membutuhkan empati, seperti mendampingi, merawat, atau berkarya. Kepekaanmu adalah aset.",
            "keuangan": "Pengelolaan yang bijak dengan mempertimbangkan kebutuhan keluarga dan orang terdekat.",
            "saran": "Percayai intuisimu dan beri kasih sayang, tapi jangan lupa menyisakan sebagian untuk dirimu sendiri.",
        },
        "rev": {
            "umum": "Terlalu menyerap emosi orang lain sampai kelelahan, atau batas diri yang mulai kabur. Perasaanmu butuh perhatian juga.",
            "cinta": "Ketergantungan emosional atau rasa cemas yang berlebihan dalam hubungan.",
            "karier": "Kelelahan karena terlalu banyak mengurus perasaan orang lain di tempat kerja.",
            "keuangan": "Sulit menolak permintaan orang lain sehingga keuanganmu sendiri terganggu.",
            "saran": "Tetapkan batas yang sehat. Peduli pada orang lain tidak berarti mengorbankan dirimu.",
        },
    },
    {
        "rank": "king",
        "astrology": "20° Libra sampai 20° Scorpio",
        "keywords_up": ["kematangan emosi", "tenang", "bijak", "diplomasi"],
        "keywords_rev": ["emosi ditekan", "manipulatif", "murung", "dingin"],
        "symbolism": "Seorang raja duduk di singgasana yang mengapung di tengah laut bergelombang, memegang piala dan tongkat kerajaan. Kapal berlayar di satu sisi dan ikan melompat di sisi lain.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Ketenangan di tengah gelombang. Kamu mampu mengelola perasaan dengan dewasa, tetap peduli tanpa larut, dan bijak saat menghadapi situasi emosional.",
            "cinta": "Pasangan atau sikap yang stabil, setia, dan penuh pengertian. Konflik diselesaikan dengan kepala dingin.",
            "karier": "Kepemimpinan yang tenang dan diplomatis. Kamu dipercaya menengahi dan menenangkan suasana.",
            "keuangan": "Keputusan finansial yang seimbang antara logika dan kepedulian.",
            "saran": "Tetap tenang dan hadir sepenuhnya. Kendalikan emosimu tanpa harus menyangkalnya.",
        },
        "rev": {
            "umum": "Emosi yang ditekan terlalu lama atau dipakai untuk mengendalikan orang lain. Di balik sikap tenang, ada gejolak yang belum diakui.",
            "cinta": "Pasangan yang dingin, tertutup, atau sulit diajak bicara soal perasaan.",
            "karier": "Kepemimpinan yang pasif-agresif atau tidak konsisten. Perhatikan dinamika di balik layar.",
            "keuangan": "Keputusan finansial yang dipengaruhi suasana hati atau dimanipulasi orang lain.",
            "saran": "Akui perasaanmu dengan jujur. Ketenangan sejati datang dari penerimaan, bukan penekanan.",
        },
    },
]
