PENTACLES = [
    {
        "rank": "ace",
        "astrology": None,
        "keywords_up": ["peluang nyata", "kemakmuran", "awal yang kokoh", "manifestasi"],
        "keywords_rev": ["peluang terlewat", "perencanaan buruk", "kurang modal", "fondasi goyah"],
        "symbolism": "Sebuah tangan muncul dari awan memegang pentakel emas di atas taman berbunga lili. Gerbang dari tanaman pagar membuka jalan ke arah pegunungan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Peluang nyata yang bisa dipegang. Ada awal baru yang kokoh, entah dalam pekerjaan, keuangan, atau kesehatan, yang siap ditumbuhkan dengan kerja nyata.",
            "cinta": "Hubungan yang membumi dan bisa diandalkan, dengan komitmen yang terlihat dari tindakan sehari-hari.",
            "karier": "Tawaran kerja, proyek, atau usaha baru dengan prospek yang jelas.",
            "keuangan": "Peluang finansial yang solid, seperti penghasilan baru, bonus, atau awal tabungan yang sehat.",
            "saran": "Ambil peluang ini dan tanam dengan sabar. Hal besar tumbuh dari fondasi yang kokoh.",
        },
        "rev": {
            "umum": "Peluang yang terlewat atau rencana yang belum punya fondasi kuat. Kamu mungkin perlu memperbaiki dasar sebelum membangun lebih tinggi.",
            "cinta": "Hubungan yang belum memberi rasa aman, atau janji yang belum terlihat dalam tindakan.",
            "karier": "Tawaran yang tidak jadi atau rencana usaha yang kurang perhitungan.",
            "keuangan": "Kurang modal, pengeluaran tak terduga, atau peluang yang tidak dimanfaatkan.",
            "saran": "Periksa fondasi rencanamu. Perbaiki yang rapuh sebelum melangkah lebih jauh.",
        },
    },
    {
        "rank": "two",
        "astrology": "Yupiter di Capricorn",
        "keywords_up": ["menyeimbangkan", "adaptasi", "mengatur prioritas", "fleksibel"],
        "keywords_rev": ["kewalahan", "kacau", "terlalu banyak beban", "prioritas kabur"],
        "symbolism": "Seorang pemuda menari sambil memainkan dua pentakel yang dihubungkan pita berbentuk lambang tak terhingga. Di belakangnya, kapal-kapal naik turun diterpa ombak.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Menyeimbangkan banyak hal sekaligus dengan luwes. Hidup sedang naik turun, tapi kamu masih mampu mengaturnya selama tetap fleksibel.",
            "cinta": "Menyeimbangkan hubungan dengan kesibukan lain. Kalian perlu sama-sama luwes.",
            "karier": "Mengelola beberapa proyek atau tanggung jawab sekaligus. Atur prioritas dengan cermat.",
            "keuangan": "Mengatur arus kas, membagi anggaran, atau menyeimbangkan pemasukan dan pengeluaran.",
            "saran": "Tetap luwes dan atur prioritasmu. Tidak semua hal harus selesai di waktu yang sama.",
        },
        "rev": {
            "umum": "Terlalu banyak yang dipegang sampai mulai berantakan. Keseimbangan hilang dan kamu merasa kewalahan.",
            "cinta": "Hubungan terabaikan karena kesibukan. Sisihkan waktu yang benar-benar untuk berdua.",
            "karier": "Beban kerja berlebihan dan prioritas kabur. Kurangi komitmen yang tidak penting.",
            "keuangan": "Arus kas kacau atau tagihan menumpuk. Susun ulang anggaran dari awal.",
            "saran": "Letakkan beberapa hal. Fokus pada yang paling penting dulu sebelum mengambil yang baru.",
        },
    },
    {
        "rank": "three",
        "astrology": "Mars di Capricorn",
        "keywords_up": ["kerja sama", "keahlian", "pengakuan", "membangun bersama"],
        "keywords_rev": ["tim tidak solid", "kualitas rendah", "kurang dihargai", "rencana tidak sejalan"],
        "symbolism": "Seorang pemahat bekerja di dalam katedral, sementara seorang biarawan dan seorang arsitek yang membawa rancangan berdiskusi dengannya. Tiga pentakel terukir di lengkungan atas.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kerja sama yang saling menghargai keahlian masing-masing. Hasil yang baik lahir dari kolaborasi, perencanaan, dan ketelitian.",
            "cinta": "Hubungan yang dibangun bersama dengan usaha kedua pihak, misalnya merencanakan rumah atau masa depan.",
            "karier": "Kerja tim yang produktif dan keahlianmu mulai diakui. Saat yang baik untuk proyek kolaboratif.",
            "keuangan": "Usaha bersama atau investasi yang direncanakan dengan baik membawa hasil.",
            "saran": "Bekerjasamalah dan hargai keahlian orang lain. Hasil terbaik lahir dari banyak tangan.",
        },
        "rev": {
            "umum": "Kerja sama yang tidak berjalan baik. Ada perbedaan visi, kurang koordinasi, atau kualitas yang dikorbankan demi kecepatan.",
            "cinta": "Satu pihak merasa berusaha sendirian. Bicarakan pembagian peran dengan adil.",
            "karier": "Tim yang tidak kompak atau kerja kerasmu kurang dihargai. Perjelas peran dan standar kerja.",
            "keuangan": "Proyek bersama terhambat karena perencanaan yang buruk. Tinjau ulang kesepakatannya.",
            "saran": "Samakan dulu tujuan dan pembagian tugas sebelum melanjutkan pekerjaan bersama.",
        },
    },
    {
        "rank": "four",
        "astrology": "Matahari di Capricorn",
        "keywords_up": ["menjaga", "keamanan", "kendali", "hemat"],
        "keywords_rev": ["kikir", "takut kehilangan", "melepaskan kendali", "boros"],
        "symbolism": "Seorang pria bermahkota duduk memeluk erat sebuah pentakel. Satu pentakel bertengger di atas kepalanya, dua lagi diinjak di bawah kakinya, dan kota terlihat di belakangnya.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kebutuhan akan rasa aman dan kendali. Menjaga apa yang dimiliki itu wajar, tapi genggaman yang terlalu erat bisa menghalangi hal baru untuk masuk.",
            "cinta": "Rasa ingin memiliki atau takut kehilangan dalam hubungan. Rasa aman sejati butuh kepercayaan, bukan genggaman.",
            "karier": "Mempertahankan posisi dengan hati-hati. Stabil, tapi jangan sampai menolak perkembangan.",
            "keuangan": "Menabung dan menjaga aset dengan disiplin. Pastikan berhemat tidak berubah menjadi kikir.",
            "saran": "Jaga yang penting, tapi longgarkan genggamanmu agar hal baru bisa masuk.",
        },
        "rev": {
            "umum": "Ketakutan kehilangan yang berlebihan, atau sebaliknya, melepaskan kendali secara tiba-tiba. Hubunganmu dengan rasa aman sedang diuji.",
            "cinta": "Posesif yang mulai mengekang, atau mulai belajar memberi ruang pada pasangan.",
            "karier": "Terlalu takut mengambil risiko sehingga tertinggal, atau kehilangan kendali atas sumber daya.",
            "keuangan": "Kikir yang merugikan atau pengeluaran besar yang tiba-tiba. Cari keseimbangan.",
            "saran": "Tinjau ulang hubunganmu dengan uang dan rasa aman. Kontrol yang sehat tidak harus menyesakkan.",
        },
    },
    {
        "rank": "five",
        "astrology": "Merkurius di Taurus",
        "keywords_up": ["kesulitan", "kekurangan", "merasa terasing", "masa sulit"],
        "keywords_rev": ["pemulihan", "menerima bantuan", "keadaan membaik", "kembali bangkit"],
        "symbolism": "Dua orang berjalan tertatih di tengah salju, satu bertongkat penyangga, melewati jendela kaca patri yang terang berisi lima pentakel tanpa melihat ke arahnya.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Masa sulit, baik secara materi, kesehatan, maupun perasaan terasing. Bantuan sebenarnya ada di dekatmu, tapi kamu mungkin belum melihat atau belum mau memintanya.",
            "cinta": "Merasa sendiri atau diabaikan dalam hubungan, atau melewati masa sulit bersama pasangan.",
            "karier": "Kehilangan pekerjaan, proyek gagal, atau merasa tidak dihargai. Cari dukungan dari jejaringmu.",
            "keuangan": "Kesulitan keuangan atau kehilangan penghasilan. Jangan malu meminta bantuan dan susun rencana darurat.",
            "saran": "Mintalah bantuan. Jendela yang terang itu dekat, kamu hanya perlu menoleh dan mengetuk pintunya.",
        },
        "rev": {
            "umum": "Masa sulit perlahan berlalu. Kamu mulai menerima bantuan, keadaan membaik, dan rasa terasing berkurang.",
            "cinta": "Kembali terhubung setelah masa renggang, atau menemukan dukungan yang tulus.",
            "karier": "Mendapat pekerjaan baru atau situasi kerja membaik setelah masa sulit.",
            "keuangan": "Keuangan mulai pulih. Tetap disiplin agar tidak kembali ke titik yang sama.",
            "saran": "Terima uluran tangan yang datang dan teruslah membangun kembali, sedikit demi sedikit.",
        },
    },
    {
        "rank": "six",
        "astrology": "Bulan di Taurus",
        "keywords_up": ["kemurahan hati", "memberi dan menerima", "berbagi", "bantuan"],
        "keywords_rev": ["utang budi", "pemberian bersyarat", "tidak seimbang", "memberi berlebihan"],
        "symbolism": "Seorang saudagar memegang timbangan di satu tangan dan membagikan koin kepada dua orang yang berlutut di hadapannya dengan tangan lainnya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Memberi dan menerima dalam keseimbangan yang sehat. Kemurahan hati mengalir, entah kamu yang membantu atau kamu yang sedang dibantu.",
            "cinta": "Hubungan yang saling memberi dengan tulus. Perhatian dan dukungan mengalir dua arah.",
            "karier": "Mendapat dukungan dari atasan atau mentor, atau kesempatan berbagi ilmu dengan orang lain.",
            "keuangan": "Bantuan finansial, pinjaman yang adil, atau kesempatan untuk berbagi rezeki.",
            "saran": "Berbagilah sesuai kemampuan, dan terima bantuan tanpa rasa malu.",
        },
        "rev": {
            "umum": "Pemberian yang tidak seimbang atau datang dengan syarat tersembunyi. Ada rasa berutang budi yang membebani.",
            "cinta": "Satu pihak merasa terus memberi atau dikendalikan lewat pemberian.",
            "karier": "Bantuan yang ternyata mengikat atau pembagian imbalan yang tidak adil.",
            "keuangan": "Waspadai pinjaman dengan syarat merugikan, atau memberi melebihi kemampuan.",
            "saran": "Periksa niat di balik setiap pemberian, baik yang kamu berikan maupun yang kamu terima.",
        },
    },
    {
        "rank": "seven",
        "astrology": "Saturnus di Taurus",
        "keywords_up": ["kesabaran", "investasi jangka panjang", "evaluasi", "menunggu hasil"],
        "keywords_rev": ["tidak sabar", "usaha sia-sia", "hasil mengecewakan", "salah investasi"],
        "symbolism": "Seorang petani bersandar pada cangkulnya, memandangi tujuh pentakel yang tumbuh di semak tanaman, seperti sedang menimbang hasil kerjanya.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Hasil dari usaha panjang sedang tumbuh, tapi belum waktunya dipanen. Saat yang tepat untuk mengevaluasi apa yang sudah ditanam dan bersabar menunggu.",
            "cinta": "Hubungan yang dibangun pelan-pelan. Evaluasi apakah usaha kalian sudah sepadan dan sejalan.",
            "karier": "Kemajuan karier yang lambat tapi pasti. Tinjau strategi tanpa terburu-buru mengganti arah.",
            "keuangan": "Investasi jangka panjang yang butuh kesabaran. Jangan tergoda untuk mencabutnya terlalu cepat.",
            "saran": "Bersabarlah dan nilai hasil kerjamu dengan jujur. Panen datang pada waktunya.",
        },
        "rev": {
            "umum": "Ketidaksabaran atau rasa kecewa karena usaha belum membuahkan hasil. Mungkin ada yang perlu diubah dalam caramu menanam.",
            "cinta": "Merasa usaha dalam hubungan tidak berbalas. Tinjau apakah kalian masih menanam di ladang yang sama.",
            "karier": "Kerja keras yang tidak sebanding dengan hasil. Pertimbangkan perubahan strategi.",
            "keuangan": "Investasi yang kurang menguntungkan. Evaluasi sebelum menambah modal.",
            "saran": "Tinjau ulang apa yang sudah kamu tanam. Ubah caranya kalau memang perlu, bukan hanya mempercepatnya.",
        },
    },
    {
        "rank": "eight",
        "astrology": "Matahari di Virgo",
        "keywords_up": ["ketekunan", "keahlian", "latihan", "kerja detail"],
        "keywords_rev": ["perfeksionis", "bosan", "kerja asal-asalan", "kurang fokus"],
        "symbolism": "Seorang pengrajin tekun memahat pentakel di meja kerjanya. Beberapa pentakel yang sudah jadi tergantung berjajar, dan sebuah kota tampak di kejauhan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Ketekunan dan kesungguhan mengasah keahlian. Kemajuan datang dari latihan yang konsisten, satu detail demi satu detail.",
            "cinta": "Hubungan yang dirawat dengan usaha nyata setiap hari. Komitmen terlihat dari hal-hal kecil.",
            "karier": "Fokus meningkatkan keahlian, menjalani pelatihan, atau mengerjakan proyek yang butuh ketelitian.",
            "keuangan": "Penghasilan tumbuh lewat kerja keras dan keahlian. Konsistensi membawa hasil.",
            "saran": "Tekuni keahlianmu dengan sabar. Kualitas tumbuh dari pengulangan yang sungguh-sungguh.",
        },
        "rev": {
            "umum": "Bosan pada rutinitas, kerja asal-asalan, atau justru perfeksionisme yang melelahkan. Keseimbangan antara kualitas dan kecepatan perlu dicari.",
            "cinta": "Terlalu sibuk bekerja sampai hubungan terabaikan, atau rutinitas yang membuat hubungan hambar.",
            "karier": "Kehilangan motivasi mengasah diri atau terjebak pada detail yang tidak penting.",
            "keuangan": "Usaha yang tidak fokus membuat penghasilan kurang optimal dari yang seharusnya.",
            "saran": "Ingat kembali mengapa kamu menekuni ini. Kerjakan dengan sepenuh hati, tapi tidak harus sempurna.",
        },
    },
    {
        "rank": "nine",
        "astrology": "Venus di Virgo",
        "keywords_up": ["kemandirian", "kemapanan", "menikmati hasil", "kepercayaan diri"],
        "keywords_rev": ["bergantung", "kemapanan semu", "boros", "kerja berlebihan"],
        "symbolism": "Seorang wanita berjubah elegan berdiri di kebun anggur yang subur, seekor burung elang bertudung bertengger di tangannya yang bersarung. Sembilan pentakel dan sebuah rumah besar ada di sekitarnya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kemandirian dan kemapanan yang lahir dari usahamu sendiri. Kamu berhak menikmati hasil kerja keras dan merasa nyaman dengan dirimu sendiri.",
            "cinta": "Merasa utuh dengan diri sendiri sehingga hubungan dijalani karena ingin, bukan karena butuh.",
            "karier": "Pencapaian yang memberi kebebasan dan keleluasaan. Kerja kerasmu berbuah nyata.",
            "keuangan": "Keadaan finansial yang mapan dan mandiri. Nikmati dengan bijak.",
            "saran": "Nikmati hasil kerjamu dan hargai kemandirianmu. Kamu sudah bekerja keras untuk sampai di sini.",
        },
        "rev": {
            "umum": "Kemapanan yang rapuh atau terlalu bergantung pada orang lain. Bisa juga terlalu sibuk bekerja sampai lupa menikmati hasilnya.",
            "cinta": "Ketergantungan finansial atau emosional yang membuat hubungan tidak setara.",
            "karier": "Kerja berlebihan tanpa waktu menikmati hidup, atau kemandirian yang terancam.",
            "keuangan": "Gaya hidup melebihi kemampuan atau ketergantungan pada sumber orang lain.",
            "saran": "Bangun kemandirianmu dari dasar, dan sisihkan waktu untuk menikmati apa yang sudah kamu miliki.",
        },
    },
    {
        "rank": "ten",
        "astrology": "Merkurius di Virgo",
        "keywords_up": ["warisan", "kemapanan jangka panjang", "keluarga", "stabilitas"],
        "keywords_rev": ["masalah warisan", "konflik keluarga", "kehilangan stabilitas", "nilai keluarga goyah"],
        "symbolism": "Seorang kakek berjubah duduk ditemani dua anjing di bawah gerbang lengkung, sementara sepasang suami istri dan seorang anak berada di dekatnya. Sepuluh pentakel tersusun membentuk pola Pohon Kehidupan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kemapanan yang bertahan lintas waktu. Ada rasa aman, keluarga yang kokoh, dan hasil kerja yang bisa diwariskan.",
            "cinta": "Hubungan dengan komitmen jangka panjang dan dukungan keluarga. Membangun masa depan bersama.",
            "karier": "Karier yang stabil, bisnis keluarga, atau institusi yang mapan.",
            "keuangan": "Kemakmuran jangka panjang, warisan, properti, atau perencanaan keuangan keluarga.",
            "saran": "Pikirkan jangka panjang. Bangun sesuatu yang bisa memberi manfaat bagi generasi berikutnya.",
        },
        "rev": {
            "umum": "Masalah yang menyentuh fondasi keluarga atau keuangan jangka panjang. Stabilitas yang selama ini diandalkan sedang diuji.",
            "cinta": "Konflik keluarga yang memengaruhi hubungan, atau perbedaan nilai soal masa depan.",
            "karier": "Ketidakstabilan dalam bisnis keluarga atau perusahaan yang dulu terasa aman.",
            "keuangan": "Sengketa warisan atau keputusan jangka panjang yang kurang matang. Rapikan dokumen dan kesepakatan.",
            "saran": "Bicarakan urusan keluarga dan keuangan dengan terbuka sebelum menjadi konflik.",
        },
    },
    {
        "rank": "page",
        "astrology": None,
        "keywords_up": ["belajar", "rencana baru", "tekun", "peluang awal"],
        "keywords_rev": ["menunda", "kurang fokus", "malas", "rencana tidak realistis"],
        "symbolism": "Seorang pemuda berdiri di padang rumput yang baru dibajak, mengangkat pentakel dengan kedua tangan dan menatapnya penuh perhatian.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Semangat belajar dan menanam sesuatu yang baru. Ada rencana yang membumi dan kesempatan untuk mulai membangun dengan tekun.",
            "cinta": "Hubungan yang dimulai pelan dan tulus, dengan niat untuk serius.",
            "karier": "Kesempatan belajar, kursus, atau pekerjaan awal yang menjanjikan.",
            "keuangan": "Mulai menabung, belajar mengelola uang, atau peluang penghasilan kecil yang bisa tumbuh.",
            "saran": "Mulailah belajar dan menanam dari sekarang. Langkah kecil yang tekun membawa hasil besar.",
        },
        "rev": {
            "umum": "Rencana bagus yang tidak kunjung dijalankan. Rasa malas atau kurang fokus membuat peluang awal terbuang.",
            "cinta": "Kurang usaha untuk membuat hubungan bertumbuh, atau niat baik yang belum diwujudkan.",
            "karier": "Menunda belajar atau tidak serius memanfaatkan kesempatan yang ada di depan mata.",
            "keuangan": "Rencana keuangan yang hanya tinggal rencana. Mulai dari satu kebiasaan kecil.",
            "saran": "Ubah rencanamu menjadi satu tindakan nyata hari ini, sekecil apa pun bentuknya.",
        },
    },
    {
        "rank": "knight",
        "astrology": "20° Leo sampai 20° Virgo",
        "keywords_up": ["tekun", "dapat diandalkan", "metodis", "konsisten"],
        "keywords_rev": ["kaku", "membosankan", "stagnan", "terlalu hati-hati"],
        "symbolism": "Seorang ksatria duduk tenang di atas kuda hitam yang kokoh dan diam di ladang yang sudah dibajak, memandangi pentakel di tangannya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kemajuan yang lambat tapi pasti. Ketekunan, tanggung jawab, dan kerja metodis menjadi kunci keberhasilan.",
            "cinta": "Pasangan atau sikap yang setia, sabar, dan bisa diandalkan. Hubungan berjalan stabil.",
            "karier": "Kerja rutin yang tekun dan bertanggung jawab. Hasilnya mungkin tidak instan, tapi kokoh.",
            "keuangan": "Pengelolaan keuangan yang hati-hati dan konsisten. Tabungan tumbuh pelan-pelan.",
            "saran": "Teruslah melangkah dengan tekun. Konsistensi lebih kuat daripada kecepatan.",
        },
        "rev": {
            "umum": "Ketekunan yang berubah menjadi kaku dan stagnan. Terlalu hati-hati bisa membuatmu tidak bergerak sama sekali.",
            "cinta": "Hubungan terasa monoton. Sedikit kejutan dan spontanitas bisa menyegarkan suasana.",
            "karier": "Terjebak dalam rutinitas tanpa perkembangan. Cari tantangan baru.",
            "keuangan": "Terlalu takut mengambil keputusan sehingga uang tidak berkembang.",
            "saran": "Jaga konsistensimu, tapi beranilah juga mencoba cara baru sesekali.",
        },
    },
    {
        "rank": "queen",
        "astrology": "20° Sagitarius sampai 20° Capricorn",
        "keywords_up": ["merawat", "praktis", "kenyamanan", "kelimpahan"],
        "keywords_rev": ["mengabaikan diri", "terlalu sibuk", "tidak seimbang", "cemas soal materi"],
        "symbolism": "Seorang ratu duduk di singgasana berhias kepala kambing di tengah taman bunga, memangku pentakel dengan penuh perhatian. Seekor kelinci berada di sudut taman.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kemampuan merawat yang praktis dan membumi. Kamu bisa menciptakan kenyamanan, mengurus kebutuhan nyata, dan tetap hangat.",
            "cinta": "Hubungan yang penuh perhatian dalam hal-hal nyata. Rumah terasa nyaman dan aman.",
            "karier": "Kemampuan mengelola sumber daya dengan cerdas sambil tetap peduli pada tim.",
            "keuangan": "Pengelolaan rumah tangga dan keuangan yang bijak. Ada kelimpahan yang dijaga dengan baik.",
            "saran": "Rawat dirimu dan orang terdekat dengan cara yang nyata dan sederhana.",
        },
        "rev": {
            "umum": "Terlalu sibuk mengurus semua hal sampai lupa merawat diri. Keseimbangan antara pekerjaan, rumah, dan dirimu sendiri terganggu.",
            "cinta": "Perhatian tercurah ke urusan praktis sampai lupa kedekatan emosional.",
            "karier": "Kewalahan mengatur banyak hal sekaligus. Mintalah bantuan sebelum kelelahan.",
            "keuangan": "Kecemasan soal materi atau pengeluaran untuk orang lain yang berlebihan.",
            "saran": "Sisihkan waktu, tenaga, dan sumber daya untuk dirimu sendiri juga.",
        },
    },
    {
        "rank": "king",
        "astrology": "20° Aries sampai 20° Taurus",
        "keywords_up": ["kemakmuran", "keamanan", "kepemimpinan praktis", "kesuksesan materi"],
        "keywords_rev": ["materialistis", "keras kepala", "keserakahan", "kaku soal uang"],
        "symbolism": "Seorang raja berjubah motif buah anggur duduk di singgasana berhias kepala banteng, memegang tongkat kerajaan dan pentakel. Sebuah kastel berdiri megah di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kesuksesan yang dibangun dari kerja keras dan pengelolaan yang bijak. Kamu mampu menciptakan stabilitas dan melindungi orang-orang di sekitarmu.",
            "cinta": "Pasangan atau sikap yang setia, mapan, dan memberi rasa aman yang nyata.",
            "karier": "Kepemimpinan yang praktis, bisnis yang berkembang, dan kemampuan mengelola sumber daya.",
            "keuangan": "Kemakmuran dan keamanan finansial. Keputusan investasimu cenderung matang.",
            "saran": "Kelola sumber dayamu dengan bijak, dan gunakan keberhasilanmu untuk menopang orang lain juga.",
        },
        "rev": {
            "umum": "Fokus berlebihan pada materi dan status. Keras kepala atau keserakahan bisa merusak apa yang sudah dibangun.",
            "cinta": "Mengukur hubungan dengan materi, atau pasangan yang kaku dan mengendalikan soal uang.",
            "karier": "Kepemimpinan yang otoriter atau keputusan bisnis yang terlalu berorientasi keuntungan.",
            "keuangan": "Investasi spekulatif demi keuntungan cepat, atau terlalu kaku hingga melewatkan peluang.",
            "saran": "Ingat bahwa kekayaan sejati juga mencakup waktu, kesehatan, dan hubungan.",
        },
    },
]
