MAJOR_ARCANA = [
    {
        "slug": "fool",
        "number": 0,
        "name": "The Fool",
        "name_id": "Si Pandir",
        "element": "udara",
        "astrology": "Unsur udara",
        "hebrew": "Aleph (א)",
        "keywords_up": ["awal baru", "spontanitas", "keberanian", "kepolosan"],
        "keywords_rev": ["ceroboh", "ragu memulai", "kurang persiapan", "impulsif"],
        "symbolism": "Seorang pemuda melangkah ringan di tepi jurang sambil menatap langit. Ia membawa buntelan kecil dan setangkai mawar putih, ditemani seekor anjing kecil, di bawah matahari pagi yang terang.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Awal yang baru dan masih polos. Kamu berdiri di ambang sesuatu yang belum pernah kamu jalani, dengan rasa ingin tahu yang lebih besar daripada rasa takut.",
            "cinta": "Perasaan atau hubungan yang masih segar dan spontan. Ada ruang untuk saling mengenal tanpa beban ekspektasi yang berat, selama keduanya jujur soal apa yang dicari.",
            "karier": "Langkah pertama di bidang, proyek, atau peran yang baru. Pengalamanmu mungkin belum banyak, tapi kemauan untuk mulai dan belajar sambil jalan justru jadi modal utama.",
            "keuangan": "Ada dorongan untuk mencoba hal baru dengan uang, entah usaha kecil atau cara mengelola yang berbeda. Semangatnya bagus, asal tetap disertai hitungan sederhana.",
            "saran": "Ambil langkah pertama tanpa menunggu semuanya sempurna, tapi tetap perhatikan ke mana kakimu berpijak.",
        },
        "rev": {
            "umum": "Kebebasan yang kehilangan arah. Bisa berupa keputusan yang diambil terlalu terburu-buru, atau sebaliknya, rasa takut yang membuatmu tidak berani memulai sama sekali.",
            "cinta": "Ada kecenderungan masuk ke hubungan tanpa memperhatikan tanda-tanda penting, atau menghindari komitmen dengan alasan ingin tetap bebas.",
            "karier": "Rencana yang belum matang atau langkah yang diambil tanpa persiapan. Bisa juga keraguan berlebihan yang membuat kesempatan baru lewat begitu saja.",
            "keuangan": "Waspadai pengeluaran impulsif dan keputusan finansial yang didorong euforia sesaat. Periksa ulang angka sebelum berkomitmen pada apa pun.",
            "saran": "Berhenti sebentar dan tanyakan pada dirimu apakah ini keberanian atau kecerobohan. Jawabannya menentukan langkah berikutnya.",
        },
    },
    {
        "slug": "magician",
        "number": 1,
        "name": "The Magician",
        "name_id": "Sang Penyihir",
        "element": None,
        "astrology": "Merkurius",
        "hebrew": "Beth (ב)",
        "keywords_up": ["kemauan", "keterampilan", "fokus", "inisiatif"],
        "keywords_rev": ["manipulasi", "potensi terpendam", "tidak fokus", "tipu daya"],
        "symbolism": "Sang Penyihir mengangkat tongkat ke langit dan menunjuk bumi dengan tangan lainnya. Di mejanya terletak piala, pedang, pentakel, dan tongkat, sementara lambang tak terhingga melayang di atas kepalanya.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Semua yang kamu butuhkan sebenarnya sudah ada di tanganmu. Kartu ini bicara tentang kemampuan mengubah niat menjadi tindakan nyata lewat fokus dan keterampilan.",
            "cinta": "Ada daya tarik yang kuat dan kemampuan untuk menyampaikan perasaan dengan jelas. Inisiatif darimu bisa membuka arah baru dalam hubungan.",
            "karier": "Saat yang baik untuk menunjukkan kemampuan, mempresentasikan ide, atau memulai proyek sendiri. Keterampilan dan komunikasimu sedang berada di puncaknya.",
            "keuangan": "Peluang menambah penghasilan lewat keahlian yang sudah kamu punya. Gunakan sumber daya yang ada dengan cerdik sebelum mencari yang baru.",
            "saran": "Satukan niat, rencana, dan tindakan. Mulailah dari alat yang sudah ada di mejamu, bukan dari yang belum kamu miliki.",
        },
        "rev": {
            "umum": "Potensi yang tidak tersalurkan atau dipakai untuk tujuan yang kurang jujur. Waspadai janji manis, baik dari orang lain maupun dari dirimu sendiri.",
            "cinta": "Ada pesona yang tidak sepenuhnya tulus, atau permainan kata yang menutupi niat sebenarnya. Perhatikan apakah ucapan dan tindakan sejalan.",
            "karier": "Kemampuanmu belum dimanfaatkan dengan baik, atau ada pihak yang bermain licik di lingkungan kerja. Rencana tanpa eksekusi juga termasuk di sini.",
            "keuangan": "Hati-hati dengan tawaran yang terdengar terlalu mudah atau skema yang tidak transparan. Baca detailnya sebelum menyerahkan uang.",
            "saran": "Periksa niatmu dengan jujur, lalu pusatkan tenaga pada satu hal yang benar-benar bisa kamu kerjakan sampai selesai.",
        },
    },
    {
        "slug": "high-priestess",
        "number": 2,
        "name": "The High Priestess",
        "name_id": "Pendeta Agung",
        "element": None,
        "astrology": "Bulan",
        "hebrew": "Gimel (ג)",
        "keywords_up": ["intuisi", "pengetahuan batin", "misteri", "ketenangan"],
        "keywords_rev": ["rahasia", "intuisi diabaikan", "menutup diri", "informasi tersembunyi"],
        "symbolism": "Seorang pendeta wanita duduk di antara dua pilar, hitam bertanda B dan putih bertanda J. Ia memegang gulungan bertulisan TORA, bulan sabit di kakinya, dan tirai bermotif delima di belakangnya.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Jawaban yang kamu cari tidak datang dari luar, melainkan dari dalam. Ada hal yang belum terungkap, dan kesabaran untuk diam serta mengamati akan lebih berguna daripada mendesak.",
            "cinta": "Perasaan yang dalam tapi belum diungkapkan. Ada tarikan emosional yang kuat, namun waktunya belum tentu tepat untuk membuka semuanya.",
            "karier": "Percayai insting profesionalmu dan kumpulkan informasi sebelum bergerak. Tidak semua hal di lingkungan kerja terlihat di permukaan.",
            "keuangan": "Tahan dulu keputusan besar sampai gambarannya lebih jelas. Ada detail yang belum kamu ketahui, dan intuisimu mungkin sudah menangkap tandanya.",
            "saran": "Beri ruang untuk hening. Dengarkan suara batinmu sebelum mendengarkan pendapat orang lain.",
        },
        "rev": {
            "umum": "Intuisi yang diabaikan atau rahasia yang mulai memengaruhi keadaan. Kamu mungkin terlalu sibuk dengan hal luar sampai lupa mendengarkan diri sendiri.",
            "cinta": "Ada hal yang disembunyikan, oleh pasangan atau olehmu sendiri. Jarak emosional bisa muncul karena perasaan yang tidak pernah dibicarakan.",
            "karier": "Informasi penting tertahan atau gosip mulai mengaburkan fakta. Pastikan kamu bekerja dengan data yang benar, bukan asumsi.",
            "keuangan": "Ada biaya atau risiko tersembunyi yang belum terlihat. Periksa ulang kontrak, tagihan, dan catatan sebelum melangkah.",
            "saran": "Akui apa yang sebenarnya sudah kamu rasakan. Mengabaikan firasat tidak membuatnya hilang.",
        },
    },
    {
        "slug": "empress",
        "number": 3,
        "name": "The Empress",
        "name_id": "Sang Permaisuri",
        "element": None,
        "astrology": "Venus",
        "hebrew": "Daleth (ד)",
        "keywords_up": ["kesuburan", "kelimpahan", "kasih sayang", "kreativitas"],
        "keywords_rev": ["ketergantungan", "kreativitas tersumbat", "mengabaikan diri", "berlebihan"],
        "symbolism": "Seorang permaisuri bermahkota dua belas bintang duduk di taman yang subur. Perisai berbentuk hati dengan lambang Venus bersandar di sisinya, gandum matang tumbuh di kakinya, dan sungai mengalir di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Masa tumbuh dan berbuah. Apa yang kamu rawat dengan sabar mulai menunjukkan hasil, dan ada kenyamanan yang bisa dinikmati tanpa rasa bersalah.",
            "cinta": "Hubungan yang hangat, penuh perhatian, dan saling merawat. Kartu ini juga sering muncul di sekitar keinginan membangun keluarga atau kehidupan bersama.",
            "karier": "Proyek kreatif berkembang dengan baik. Lingkungan kerja yang suportif dan pendekatan yang lebih manusiawi membawa hasil yang nyata.",
            "keuangan": "Kondisi yang cukup dan cenderung bertambah. Nikmati hasil kerjamu, sambil tetap menyisihkan sebagian untuk masa depan.",
            "saran": "Rawat dirimu sebaik kamu merawat orang lain. Hal yang tumbuh dengan sehat butuh waktu, perhatian, dan kesabaran.",
        },
        "rev": {
            "umum": "Energi merawat yang tidak seimbang. Bisa terlalu banyak memberi sampai lupa diri, atau terlalu bergantung pada orang lain untuk merasa aman.",
            "cinta": "Ada pola memanjakan atau mengekang yang membuat hubungan terasa sesak. Bisa juga rasa tidak dihargai karena perhatian hanya mengalir satu arah.",
            "karier": "Ide kreatif sedang mampet atau pekerjaan terasa kering. Kamu mungkin butuh jeda dan suasana baru sebelum gagasan kembali mengalir.",
            "keuangan": "Pengeluaran untuk kenyamanan mulai berlebihan, atau kamu menunda mengurus keuangan sendiri. Kembalikan kendali ke tanganmu.",
            "saran": "Isi ulang tenagamu dulu. Kamu tidak bisa terus memberi dari wadah yang kosong.",
        },
    },
    {
        "slug": "emperor",
        "number": 4,
        "name": "The Emperor",
        "name_id": "Sang Kaisar",
        "element": "api",
        "astrology": "Aries",
        "hebrew": "Heh (ה)",
        "keywords_up": ["struktur", "kepemimpinan", "stabilitas", "disiplin"],
        "keywords_rev": ["kaku", "otoriter", "kehilangan kendali", "dominasi"],
        "symbolism": "Seorang kaisar berjanggut putih duduk tegak di singgasana batu berhias kepala domba jantan. Ia memegang tongkat berbentuk ankh dan sebuah bola dunia, dengan pegunungan tandus di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Ketertiban, aturan yang jelas, dan kepemimpinan yang tegas. Situasi membutuhkan struktur dan seseorang yang berani mengambil tanggung jawab, mungkin itu kamu sendiri.",
            "cinta": "Hubungan yang stabil dan bisa diandalkan, dengan komitmen yang serius. Pastikan rasa aman itu tetap disertai kehangatan, bukan hanya aturan.",
            "karier": "Kesempatan memimpin, menata sistem, atau naik ke posisi yang lebih bertanggung jawab. Disiplin dan rencana yang rapi membuatmu dipercaya.",
            "keuangan": "Saat yang tepat untuk menyusun anggaran, membuat aturan keuangan pribadi, dan berpegang padanya. Stabilitas datang dari konsistensi.",
            "saran": "Buat batasan dan rencana yang jelas, lalu jalankan dengan konsisten. Ketegasan bukan berarti harus keras.",
        },
        "rev": {
            "umum": "Kendali yang terlalu ketat atau justru hilang sama sekali. Bisa muncul sebagai sikap kaku, figur otoritas yang menekan, atau kekacauan karena tidak ada yang mau memimpin.",
            "cinta": "Ada dominasi atau sikap mengatur dalam hubungan. Rasa aman berubah menjadi rasa terkekang ketika satu pihak selalu harus menang.",
            "karier": "Gesekan dengan atasan atau sistem yang terlalu birokratis. Bisa juga tanda kamu perlu lebih disiplin terhadap pekerjaanmu sendiri.",
            "keuangan": "Pengelolaan uang yang serampangan atau terlalu dikekang sampai menimbulkan stres. Cari aturan yang tegas tapi masih manusiawi.",
            "saran": "Bedakan antara memimpin dan mengendalikan. Struktur yang baik memberi ruang, bukan mengurung.",
        },
    },
    {
        "slug": "hierophant",
        "number": 5,
        "name": "The Hierophant",
        "name_id": "Imam Agung",
        "element": "tanah",
        "astrology": "Taurus",
        "hebrew": "Vav (ו)",
        "keywords_up": ["tradisi", "bimbingan", "nilai bersama", "pembelajaran"],
        "keywords_rev": ["memberontak", "dogma", "jalan sendiri", "aturan kaku"],
        "symbolism": "Seorang imam bermahkota tiga susun duduk di antara dua pilar, memegang tongkat salib bertingkat tiga. Dua murid berlutut di hadapannya, dan dua kunci bersilang terletak di kakinya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Jalan yang sudah teruji, nilai bersama, dan bimbingan dari orang yang lebih berpengalaman. Kadang jawaban terbaik justru ada pada cara-cara yang sudah lama dikenal.",
            "cinta": "Hubungan yang berlandaskan nilai yang sama dan mengarah pada komitmen yang diakui keluarga atau lingkungan. Restu dan kesepahaman menjadi bagian penting.",
            "karier": "Belajar dari mentor, mengikuti prosedur, atau bergabung dengan institusi yang mapan. Sertifikasi dan pendidikan formal sedang mendukungmu.",
            "keuangan": "Pilih cara yang konservatif dan terbukti, seperti tabungan, instrumen yang diawasi, atau nasihat dari penasihat terpercaya.",
            "saran": "Cari guru atau panduan yang kamu percayai, dan jangan malu belajar dari pengalaman orang lain.",
        },
        "rev": {
            "umum": "Ketegangan antara aturan lama dan keinginan menempuh jalan sendiri. Bisa juga tanda bahwa kamu mengikuti sesuatu hanya karena kebiasaan, bukan karena meyakininya.",
            "cinta": "Tekanan dari keluarga atau norma membuat hubungan terasa sempit. Atau kalian sedang mencari bentuk hubungan yang tidak mengikuti pola umum.",
            "karier": "Sistem kerja yang kaku mulai menghambat, atau kamu ingin keluar dari jalur konvensional. Pertimbangkan dengan matang sebelum melawan arus.",
            "keuangan": "Nasihat keuangan yang kamu terima mungkin tidak cocok dengan keadaanmu. Pelajari sendiri sebelum mengikuti saran siapa pun.",
            "saran": "Uji kembali aturan yang kamu pegang. Simpan yang masih bermakna dan lepaskan yang hanya tinggal formalitas.",
        },
    },
    {
        "slug": "lovers",
        "number": 6,
        "name": "The Lovers",
        "name_id": "Para Kekasih",
        "element": "udara",
        "astrology": "Gemini",
        "hebrew": "Zayin (ז)",
        "keywords_up": ["cinta", "keselarasan", "pilihan", "nilai pribadi"],
        "keywords_rev": ["ketidakselarasan", "pilihan yang ragu", "godaan", "nilai bertentangan"],
        "symbolism": "Seorang pria dan wanita berdiri di taman di bawah malaikat bersayap yang diterangi matahari. Di belakang wanita tumbuh pohon pengetahuan dengan ular, di belakang pria pohon berbuah nyala api.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Keselarasan dan pilihan yang lahir dari hati. Kartu ini menyorot keputusan penting yang perlu sejalan dengan nilai-nilai yang benar-benar kamu pegang.",
            "cinta": "Ketertarikan yang kuat dan rasa saling memahami. Hubungan berada di titik di mana keterbukaan dan komitmen bisa membawanya lebih dalam.",
            "karier": "Kerja sama atau kemitraan yang saling melengkapi. Bisa juga pilihan karier yang perlu diambil berdasarkan apa yang sungguh kamu pedulikan.",
            "keuangan": "Keputusan finansial bersama, misalnya dengan pasangan atau rekan usaha. Keterbukaan soal tujuan dan angka membuat semuanya lebih ringan.",
            "saran": "Pilih dengan jujur pada dirimu sendiri. Keputusan yang selaras dengan nilaimu akan lebih mudah dijalani dalam jangka panjang.",
        },
        "rev": {
            "umum": "Ada ketidakselarasan, entah antara dua orang atau antara apa yang kamu inginkan dan apa yang kamu yakini. Keputusan yang ditunda mulai membebani.",
            "cinta": "Komunikasi tersendat atau nilai yang berbeda mulai terasa. Bisa juga godaan dari luar yang menguji kesetiaan dan kejujuran.",
            "karier": "Kemitraan yang tidak seimbang atau pilihan karier yang bertentangan dengan hati nurani. Periksa apakah kalian masih menuju arah yang sama.",
            "keuangan": "Perbedaan pandangan soal uang dengan orang terdekat. Bicarakan prioritas sebelum keputusan diambil sepihak.",
            "saran": "Akui pilihan yang sebenarnya sedang kamu hadapi, lalu ambil keputusan dengan kesadaran penuh atas konsekuensinya.",
        },
    },
    {
        "slug": "chariot",
        "number": 7,
        "name": "The Chariot",
        "name_id": "Kereta Perang",
        "element": "air",
        "astrology": "Cancer",
        "hebrew": "Cheth (ח)",
        "keywords_up": ["tekad", "kemenangan", "kendali diri", "kemajuan"],
        "keywords_rev": ["kehilangan arah", "agresif", "tarik-menarik", "hambatan"],
        "symbolism": "Seorang ksatria berzirah berdiri di kereta beratap bintang, ditarik dua sfinks, satu hitam dan satu putih. Ia tidak memegang tali kekang, dan kota berbenteng tampak di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kemajuan yang lahir dari tekad dan kendali diri. Dua dorongan yang berlawanan bisa diarahkan ke satu tujuan bila kamu tetap fokus dan tidak mudah goyah.",
            "cinta": "Hubungan bergerak maju karena kedua pihak mau berusaha. Bisa juga tanda bahwa kamu perlu tegas soal apa yang kamu inginkan dari hubungan ini.",
            "karier": "Target tercapai berkat kerja keras dan disiplin. Saat yang baik untuk memperjuangkan posisi, menyelesaikan proyek besar, atau melangkah lebih jauh.",
            "keuangan": "Kemajuan finansial lewat usaha yang terarah. Tetapkan tujuan yang jelas dan jaga konsistensi sampai tercapai.",
            "saran": "Pegang kendali atas arahmu. Fokus pada tujuan dan jangan biarkan gangguan kecil membelokkan langkahmu.",
        },
        "rev": {
            "umum": "Arah yang kabur atau tenaga yang tercerai-berai. Kamu mungkin memaksakan diri terlalu keras, atau justru tertahan oleh keinginan yang saling bertentangan.",
            "cinta": "Tarik-menarik kepentingan membuat hubungan jalan di tempat. Hindari memenangkan perdebatan dengan cara mendesak pasangan.",
            "karier": "Proyek tersendat karena kurang koordinasi atau tujuan yang berubah-ubah. Ambisi tanpa arah yang jelas mudah berujung lelah.",
            "keuangan": "Rencana keuangan keluar jalur. Tinjau ulang tujuanmu sebelum mengejar target yang terlalu agresif.",
            "saran": "Turunkan kecepatan dan tentukan ulang tujuanmu. Kendali datang dari kejelasan, bukan dari paksaan.",
        },
    },
    {
        "slug": "strength",
        "number": 8,
        "name": "Strength",
        "name_id": "Kekuatan",
        "element": "api",
        "astrology": "Leo",
        "hebrew": "Teth (ט)",
        "keywords_up": ["keberanian lembut", "kesabaran", "welas asih", "ketahanan"],
        "keywords_rev": ["ragu diri", "emosi meledak", "lemah semangat", "kehilangan kendali"],
        "symbolism": "Seorang wanita berbaju putih dengan untaian bunga menutup mulut seekor singa dengan tenang. Lambang tak terhingga melayang di atas kepalanya, dan singa itu tampak tunduk tanpa paksaan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kekuatan yang tenang dan sabar. Situasi sulit bisa ditaklukkan bukan dengan paksaan, melainkan dengan ketekunan, keberanian, dan kelembutan.",
            "cinta": "Hubungan yang tumbuh lewat kesabaran dan pengertian. Kelembutanmu mampu meredakan ketegangan yang tidak bisa diselesaikan dengan adu argumen.",
            "karier": "Kamu mampu menghadapi tekanan dan orang-orang yang sulit dengan kepala dingin. Ketenangan itu menjadi kekuatan yang diakui orang lain.",
            "keuangan": "Disiplin yang sabar membawa hasil. Tahan godaan belanja dan tetap pada rencana walau hasilnya belum langsung terlihat.",
            "saran": "Hadapi tantangan dengan tenang. Kamu lebih kuat dari yang kamu kira, dan kelembutan juga sebuah kekuatan.",
        },
        "rev": {
            "umum": "Keraguan pada diri sendiri atau emosi yang sulit dikendalikan. Tenaga batin sedang menurun, dan hal kecil pun terasa berat dihadapi.",
            "cinta": "Rasa tidak percaya diri memengaruhi hubungan, atau emosi yang terpendam meledak di saat yang kurang tepat.",
            "karier": "Tekanan kerja menggerus rasa percaya diri. Kamu mungkin meragukan kemampuanmu padahal yang dibutuhkan hanyalah istirahat dan dukungan.",
            "keuangan": "Keputusan finansial diambil karena cemas atau panik. Tenangkan diri dulu sebelum memutuskan apa pun.",
            "saran": "Berbaik hatilah pada dirimu sendiri. Pulihkan tenaga, lalu ingat kembali alasan mengapa kamu memulai.",
        },
    },
    {
        "slug": "hermit",
        "number": 9,
        "name": "The Hermit",
        "name_id": "Sang Pertapa",
        "element": "tanah",
        "astrology": "Virgo",
        "hebrew": "Yod (י)",
        "keywords_up": ["introspeksi", "kesendirian", "kebijaksanaan", "pencarian makna"],
        "keywords_rev": ["menarik diri", "kesepian", "terisolasi", "menolak nasihat"],
        "symbolism": "Seorang pertapa tua berjubah abu-abu berdiri di puncak gunung bersalju. Ia memegang tongkat dan mengangkat lentera berisi bintang segi enam untuk menerangi jalan.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Waktu untuk menepi dan merenung. Jawaban yang kamu cari lebih mudah ditemukan dalam hening daripada di tengah keramaian dan pendapat orang lain.",
            "cinta": "Kamu butuh ruang untuk memahami perasaanmu sendiri. Dalam hubungan, ini bisa berarti masa jeda yang sehat, bukan tanda berakhirnya rasa sayang.",
            "karier": "Fokus pada pendalaman keahlian atau mencari makna dalam pekerjaan. Kerja mandiri dan riset mendalam sedang didukung.",
            "keuangan": "Tinjau keuanganmu dengan tenang dan jujur. Ini bukan waktu untuk mengikuti tren, melainkan memahami kebutuhanmu yang sebenarnya.",
            "saran": "Sisihkan waktu untuk sendiri dan dengarkan pikiranmu. Kejelasan datang saat kebisingan mereda.",
        },
        "rev": {
            "umum": "Menyendiri yang sudah berubah menjadi menarik diri. Kesepian atau keengganan menerima bantuan bisa membuat masalah terasa lebih besar dari aslinya.",
            "cinta": "Jarak emosional yang terlalu lama membuat hubungan terasa dingin. Atau kamu menutup diri karena takut terluka lagi.",
            "karier": "Bekerja terlalu sendiri sampai kehilangan dukungan dan masukan. Terbukalah pada kolaborasi dan pendapat orang lain.",
            "keuangan": "Menghindari urusan keuangan tidak membuatnya selesai. Mintalah pandangan orang yang kamu percaya.",
            "saran": "Kembali terhubung dengan orang-orang terdekat. Merenung itu baik, mengasingkan diri terlalu lama tidak.",
        },
    },
    {
        "slug": "wheel-of-fortune",
        "number": 10,
        "name": "Wheel of Fortune",
        "name_id": "Roda Nasib",
        "element": None,
        "astrology": "Yupiter",
        "hebrew": "Kaph (כ)",
        "keywords_up": ["siklus", "titik balik", "kesempatan", "perubahan nasib"],
        "keywords_rev": ["nasib menurun", "melawan perubahan", "siklus berulang", "tertunda"],
        "symbolism": "Sebuah roda besar bertuliskan TARO dan huruf Ibrani berputar di langit. Sfinks duduk di puncaknya, ular turun di satu sisi, sosok Anubis naik di sisi lain, dan empat makhluk bersayap membaca buku di keempat sudut.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Roda sedang berputar ke arah yang menguntungkan. Ada titik balik atau kesempatan yang datang di waktu yang tepat, dan kamu diajak ikut bergerak bersamanya.",
            "cinta": "Pertemuan atau perubahan yang terasa seperti takdir. Hubungan memasuki babak baru yang membawa semangat segar.",
            "karier": "Peluang tak terduga, promosi, atau perubahan arah yang menguntungkan. Bersiaplah agar bisa menangkapnya saat datang.",
            "keuangan": "Arus keuangan cenderung membaik. Manfaatkan masa baik ini untuk menyiapkan cadangan, karena roda selalu berputar.",
            "saran": "Terima perubahan dan ikuti arusnya. Kesempatan sering datang sekali, jadi bersiaplah.",
        },
        "rev": {
            "umum": "Roda berputar ke arah yang kurang nyaman, atau kamu menolak perubahan yang sebenarnya tak terhindarkan. Pola lama yang berulang minta diperhatikan.",
            "cinta": "Masalah lama muncul kembali dalam bentuk yang berbeda. Perhatikan pola yang terus terulang dalam hubunganmu.",
            "karier": "Hambatan di luar kendalimu menunda rencana. Fokus pada hal yang bisa kamu pengaruhi sambil menunggu keadaan berbalik.",
            "keuangan": "Masa yang kurang mujur untuk spekulasi. Kuatkan dana cadangan dan tunda keputusan yang berisiko.",
            "saran": "Pelajari pola yang terus berulang dalam hidupmu. Mengubah responsmu bisa mengubah arah putaran roda.",
        },
    },
    {
        "slug": "justice",
        "number": 11,
        "name": "Justice",
        "name_id": "Keadilan",
        "element": "udara",
        "astrology": "Libra",
        "hebrew": "Lamed (ל)",
        "keywords_up": ["keadilan", "kebenaran", "sebab-akibat", "keputusan jernih"],
        "keywords_rev": ["ketidakadilan", "berat sebelah", "menghindari tanggung jawab", "ketidakjujuran"],
        "symbolism": "Sosok berjubah merah duduk di antara dua pilar, memegang pedang tegak di tangan kanan dan timbangan di tangan kiri. Tirai ungu terbentang di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kebenaran, keseimbangan, dan hukum sebab-akibat. Apa yang kamu tanam akan kamu tuai, dan keputusan yang adil membutuhkan kejujuran penuh terhadap fakta.",
            "cinta": "Hubungan yang setara, di mana kedua pihak memberi dan menerima dengan adil. Kejujuran menjadi fondasi utama.",
            "karier": "Urusan kontrak, hukum, atau evaluasi kinerja berjalan objektif. Integritasmu diperhatikan dan dihargai.",
            "keuangan": "Selesaikan kewajiban, rapikan dokumen, dan pastikan semuanya tercatat jelas. Keputusan yang seimbang akan melindungimu.",
            "saran": "Lihat situasi dari semua sisi dan bertanggung jawablah atas pilihanmu. Kejujuran menyederhanakan banyak hal.",
        },
        "rev": {
            "umum": "Ketidakadilan, keputusan yang berat sebelah, atau keengganan menerima tanggung jawab. Ada hal yang perlu dihadapi dengan jujur, bukan dihindari.",
            "cinta": "Hubungan terasa tidak seimbang, atau ada ketidakjujuran yang mengganggu kepercayaan. Bicarakan apa yang dirasa tidak adil.",
            "karier": "Perlakuan yang kurang adil di tempat kerja atau masalah administratif yang berlarut. Simpan bukti dan catatan dengan rapi.",
            "keuangan": "Sengketa, denda, atau kewajiban yang terabaikan. Selesaikan sebelum menumpuk dan menjadi lebih rumit.",
            "saran": "Akui bagianmu dalam situasi ini. Memperbaiki keseimbangan dimulai dari kejujuran pada diri sendiri.",
        },
    },
    {
        "slug": "hanged-man",
        "number": 12,
        "name": "The Hanged Man",
        "name_id": "Orang yang Tergantung",
        "element": "air",
        "astrology": "Unsur air",
        "hebrew": "Mem (מ)",
        "keywords_up": ["jeda", "sudut pandang baru", "berserah", "pengorbanan"],
        "keywords_rev": ["menunda", "stagnan", "pengorbanan sia-sia", "menolak melepaskan"],
        "symbolism": "Seorang pria tergantung terbalik dengan satu kaki pada pohon berbentuk huruf T. Kaki satunya menyilang, tangannya di belakang punggung, dan lingkaran cahaya bersinar di sekitar kepalanya dengan wajah yang tenang.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Masa jeda yang memberi pemahaman baru. Kadang berhenti dan melihat dari sudut yang terbalik justru membuka jalan keluar yang selama ini tidak terlihat.",
            "cinta": "Hubungan sedang dalam fase menunggu. Gunakan waktu ini untuk memahami pasangan dan dirimu, bukan memaksakan kepastian.",
            "karier": "Proyek tertahan atau keputusan belum bisa diambil. Manfaatkan jeda untuk mengevaluasi strategi dan belajar hal baru.",
            "keuangan": "Tahan dulu keputusan besar. Kadang melepaskan keuntungan kecil hari ini memberi ruang untuk hasil yang lebih baik nanti.",
            "saran": "Lepaskan keinginan untuk mengendalikan segalanya. Lihat situasinya dari sudut yang berbeda.",
        },
        "rev": {
            "umum": "Penundaan yang sudah tidak produktif. Kamu mungkin terjebak menunggu sesuatu yang tidak kunjung datang, atau berkorban tanpa arah yang jelas.",
            "cinta": "Memberi terus tanpa menerima, atau bertahan dalam situasi yang menggantung terlalu lama. Saatnya meminta kejelasan.",
            "karier": "Kebuntuan yang dipertahankan karena takut mengambil keputusan. Bergeraklah, walau langkahnya kecil.",
            "keuangan": "Menunda urusan keuangan membuat masalah membesar. Ambil satu tindakan konkret hari ini.",
            "saran": "Akhiri masa menunggu yang tidak membawamu ke mana-mana. Putuskan sesuatu, lalu jalani.",
        },
    },
    {
        "slug": "death",
        "number": 13,
        "name": "Death",
        "name_id": "Kematian",
        "element": "air",
        "astrology": "Scorpio",
        "hebrew": "Nun (נ)",
        "keywords_up": ["akhir sebuah babak", "transformasi", "melepaskan", "pembaruan"],
        "keywords_rev": ["menolak perubahan", "terjebak", "takut melepas", "transisi lambat"],
        "symbolism": "Kerangka berbaju zirah menunggang kuda putih sambil membawa panji hitam bergambar mawar putih. Raja tergeletak, uskup berdoa, dan di kejauhan matahari terbit di antara dua menara.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Akhir dari satu babak yang membuka jalan bagi babak berikutnya. Kartu ini jarang berarti kematian harfiah. Ia bicara tentang transformasi yang tidak bisa ditawar.",
            "cinta": "Pola lama dalam hubungan berakhir. Bisa berupa perpisahan, bisa juga hubungan yang berubah total dan lahir kembali dalam bentuk yang lebih jujur.",
            "karier": "Satu fase pekerjaan selesai, entah peran, proyek, atau tempat kerja. Melepaskannya memberi ruang bagi sesuatu yang lebih sesuai.",
            "keuangan": "Hentikan kebiasaan finansial yang sudah tidak sehat. Penutupan satu sumber bisa menjadi awal pengaturan yang lebih baik.",
            "saran": "Relakan apa yang sudah selesai. Kamu tidak bisa memulai babak baru sambil terus memegang halaman yang lama.",
        },
        "rev": {
            "umum": "Perubahan yang ditolak atau ditunda. Kamu mungkin tahu sesuatu sudah selesai, tapi rasa takut membuatmu tetap bertahan di tempat yang sama.",
            "cinta": "Bertahan pada hubungan atau kenangan yang sudah tidak memberi ruang tumbuh. Melepas memang menyakitkan, tapi menunda juga melelahkan.",
            "karier": "Terjebak di posisi yang sudah tidak cocok karena takut pada ketidakpastian. Transisi akan lebih ringan bila direncanakan.",
            "keuangan": "Kebiasaan lama terus dipertahankan walau jelas merugikan. Mulailah perubahan secara bertahap.",
            "saran": "Akui apa yang perlu diakhiri. Perubahan kecil yang dimulai sekarang lebih ringan daripada perubahan besar yang dipaksakan nanti.",
        },
    },
    {
        "slug": "temperance",
        "number": 14,
        "name": "Temperance",
        "name_id": "Keseimbangan",
        "element": "api",
        "astrology": "Sagitarius",
        "hebrew": "Samekh (ס)",
        "keywords_up": ["keseimbangan", "kesabaran", "moderasi", "penyatuan"],
        "keywords_rev": ["tidak seimbang", "berlebihan", "tergesa-gesa", "bentrok"],
        "symbolism": "Malaikat bersayap dengan satu kaki di air dan satu di darat menuangkan air dari satu cawan ke cawan lain. Segitiga di dalam persegi menghias dadanya, dan jalan setapak menuju cahaya mahkota di kejauhan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Keseimbangan yang dicapai lewat kesabaran. Dua hal yang berbeda bisa dipadukan dengan takaran yang pas, asal kamu tidak terburu-buru.",
            "cinta": "Hubungan yang harmonis karena keduanya mau saling menyesuaikan. Kompromi terasa wajar, bukan pengorbanan.",
            "karier": "Kerja sama yang lancar dan ritme kerja yang sehat. Pendekatan yang moderat lebih efektif daripada langkah ekstrem.",
            "keuangan": "Keuangan stabil berkat pengelolaan yang seimbang. Jauhi godaan untuk berlebihan, baik dalam berhemat maupun belanja.",
            "saran": "Cari jalan tengah dan beri waktu bagi prosesnya. Hasil yang baik sering datang dari langkah yang tenang.",
        },
        "rev": {
            "umum": "Ada yang tidak seimbang, entah pola makan, kerja, emosi, atau hubungan. Sikap berlebihan atau tergesa-gesa membuat semuanya terasa tidak selaras.",
            "cinta": "Satu pihak memberi jauh lebih banyak, atau perbedaan dibiarkan tanpa usaha untuk menyesuaikan.",
            "karier": "Ritme kerja tidak sehat atau tim sulit bekerja sama. Kurangi beban sebelum kelelahan mengambil alih.",
            "keuangan": "Pengeluaran yang ekstrem ke satu arah. Kembalikan ke takaran yang wajar dan realistis.",
            "saran": "Identifikasi bagian hidupmu yang paling timpang dan mulai pulihkan dari situ, sedikit demi sedikit.",
        },
    },
    {
        "slug": "devil",
        "number": 15,
        "name": "The Devil",
        "name_id": "Iblis",
        "element": "tanah",
        "astrology": "Capricorn",
        "hebrew": "Ayin (ע)",
        "keywords_up": ["keterikatan", "godaan", "materialisme", "pola tidak sehat"],
        "keywords_rev": ["melepaskan diri", "kesadaran", "memutus rantai", "kebebasan kembali"],
        "symbolism": "Sosok bertanduk dan bersayap kelelawar duduk di atas balok, dengan pentagram terbalik di dahinya dan obor yang mengarah ke bawah. Seorang pria dan wanita dirantai longgar di lehernya, seolah bisa melepas diri kapan saja.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Keterikatan pada sesuatu yang menahanmu, entah kebiasaan, rasa takut, atau keinginan. Rantainya sering lebih longgar dari yang terasa, dan langkah pertama adalah menyadarinya.",
            "cinta": "Ketertarikan yang kuat tapi tidak sepenuhnya sehat, misalnya rasa memiliki yang berlebihan, kecemburuan, atau hubungan yang dipertahankan karena takut sendiri.",
            "karier": "Merasa terikat pada pekerjaan hanya demi uang atau status. Perhatikan apakah ambisi masih melayanimu, atau justru kamu yang melayaninya.",
            "keuangan": "Godaan konsumtif, utang, atau ketergantungan pada pola belanja tertentu. Kenali pemicunya sebelum mencari solusinya.",
            "saran": "Sebutkan dengan jujur apa yang mengikatmu. Kesadaran adalah kunci pertama untuk melepas rantai itu.",
        },
        "rev": {
            "umum": "Mulai melepaskan diri dari hal yang selama ini mengikat. Ada kesadaran baru, dan kebebasan terasa semakin dekat walau prosesnya belum selesai.",
            "cinta": "Keluar dari pola hubungan yang tidak sehat, atau berani menetapkan batas. Kamu mulai memilih dirimu sendiri.",
            "karier": "Keberanian meninggalkan situasi kerja yang menekan atau mengubah hubungan yang tidak seimbang dengan pekerjaan.",
            "keuangan": "Mulai melunasi utang atau memutus kebiasaan konsumtif. Pertahankan momentumnya.",
            "saran": "Teruskan langkah untuk lepas, sekecil apa pun. Mintalah dukungan agar tidak kembali ke pola yang sama.",
        },
    },
    {
        "slug": "tower",
        "number": 16,
        "name": "The Tower",
        "name_id": "Menara",
        "element": None,
        "astrology": "Mars",
        "hebrew": "Peh (פ)",
        "keywords_up": ["perubahan mendadak", "runtuhnya ilusi", "guncangan", "pencerahan"],
        "keywords_rev": ["menghindari krisis", "perubahan tertunda", "takut runtuh", "guncangan batin"],
        "symbolism": "Sebuah menara di puncak karang tersambar petir hingga mahkota di atasnya terlempar. Api menyembur dari jendela, dua orang terjatuh, dan butiran cahaya berbentuk huruf Yod berjatuhan di sekitarnya.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Perubahan mendadak yang mengguncang sesuatu yang dibangun di atas fondasi rapuh. Rasanya tidak nyaman, tapi kebenaran yang terungkap memberi kesempatan membangun ulang dengan lebih jujur.",
            "cinta": "Kejutan atau pengakuan yang mengubah cara kamu melihat hubungan. Yang runtuh biasanya ilusi, bukan cinta yang sesungguhnya.",
            "karier": "Perubahan tiba-tiba di tempat kerja, seperti restrukturisasi atau rencana yang batal. Fokus pada apa yang masih bisa kamu kendalikan.",
            "keuangan": "Pengeluaran tak terduga atau rencana yang buyar. Dana darurat dan kepala dingin menjadi penyelamat.",
            "saran": "Jangan mati-matian mempertahankan yang sudah retak. Biarkan runtuh, lalu bangun lagi di atas fondasi yang lebih kuat.",
        },
        "rev": {
            "umum": "Krisis yang dihindari atau ditunda. Perubahan yang perlu terjadi mungkin datang lebih pelan, atau kamu menahan diri dari menghadapi kenyataan yang sudah terlihat.",
            "cinta": "Masalah dalam hubungan sengaja tidak disentuh agar suasana tetap tenang. Ketegangannya tetap ada di bawah permukaan.",
            "karier": "Kamu nyaris lolos dari situasi buruk, atau bertahan di tempat yang sudah goyah. Siapkan rencana cadangan.",
            "keuangan": "Risiko yang sudah terlihat tapi belum ditangani. Perbaiki sekarang sebelum menjadi guncangan yang lebih besar.",
            "saran": "Hadapi perubahan yang sudah kamu tahu harus terjadi. Melakukannya dengan sadar lebih ringan daripada menunggu semuanya runtuh sendiri.",
        },
    },
    {
        "slug": "star",
        "number": 17,
        "name": "The Star",
        "name_id": "Bintang",
        "element": "udara",
        "astrology": "Aquarius",
        "hebrew": "Tzaddi (צ)",
        "keywords_up": ["harapan", "pemulihan", "ketenangan", "inspirasi"],
        "keywords_rev": ["putus asa", "kehilangan iman", "lelah batin", "tidak terinspirasi"],
        "symbolism": "Seorang wanita telanjang berlutut di tepi kolam, menuang air dari dua kendi ke kolam dan ke tanah. Di atasnya bersinar satu bintang besar berujung delapan dan tujuh bintang kecil, dengan seekor burung di pohon.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Harapan yang kembali setelah masa sulit. Ada ketenangan, pemulihan, dan keyakinan bahwa keadaan bisa membaik. Kamu diizinkan untuk percaya lagi.",
            "cinta": "Hubungan yang menenangkan dan penuh ketulusan, atau hati yang mulai pulih dari luka lama. Keterbukaan membawa kedekatan yang baru.",
            "karier": "Inspirasi dan visi jangka panjang kembali jelas. Saat yang baik untuk menunjukkan karya dan mengejar tujuan yang bermakna.",
            "keuangan": "Pemulihan bertahap setelah masa sulit. Keadaan membaik pelan-pelan selama kamu tetap konsisten.",
            "saran": "Rawat harapanmu dan biarkan dirimu pulih. Langkah kecil yang konsisten akan membawamu lebih jauh dari yang kamu kira.",
        },
        "rev": {
            "umum": "Harapan yang meredup atau rasa lelah yang membuatmu sulit percaya keadaan akan membaik. Cahayanya masih ada, hanya tertutup awan sesaat.",
            "cinta": "Kecewa membuatmu menutup hati, atau kamu merasa tidak cukup layak untuk dicintai. Mulailah dari berdamai dengan diri sendiri.",
            "karier": "Kehilangan motivasi atau merasa pekerjaan kehilangan makna. Kembali ke alasan awal bisa menyalakan semangat lagi.",
            "keuangan": "Pesimisme membuatmu enggan merencanakan. Buat satu target kecil yang realistis untuk memulihkan rasa percaya diri.",
            "saran": "Cari satu hal kecil yang masih memberimu harapan dan pegang itu. Pemulihan tidak harus terjadi sekaligus.",
        },
    },
    {
        "slug": "moon",
        "number": 18,
        "name": "The Moon",
        "name_id": "Bulan",
        "element": "air",
        "astrology": "Pisces",
        "hebrew": "Qoph (ק)",
        "keywords_up": ["ketidakpastian", "ilusi", "intuisi", "alam bawah sadar"],
        "keywords_rev": ["kebingungan mereda", "kebenaran muncul", "takut berlebihan", "menipu diri"],
        "symbolism": "Bulan berwajah bersinar di antara dua menara, meneteskan butiran cahaya. Seekor anjing dan serigala melolong ke arahnya, sementara udang karang merayap keluar dari kolam menuju jalan berliku ke pegunungan.",
        "answer_up": "belum",
        "answer_rev": "belum",
        "up": {
            "umum": "Situasi yang belum jelas dan mudah disalahpahami. Ketakutan dan imajinasi bisa membesar dalam gelap, jadi bedakan mana firasat dan mana kecemasan.",
            "cinta": "Ada keraguan, perasaan yang belum terbaca, atau informasi yang belum lengkap. Hindari menyimpulkan sebelum semuanya terang.",
            "karier": "Kabar yang simpang siur atau arah yang belum jelas. Lakukan pengecekan ulang dan jangan mengambil keputusan besar berdasarkan rumor.",
            "keuangan": "Detail yang samar dan potensi kesalahpahaman. Baca kontrak dengan teliti dan jauhi tawaran yang membingungkan.",
            "saran": "Bergeraklah pelan dan tetap waspada. Percayai intuisimu, tapi verifikasi dengan fakta sebelum memutuskan.",
        },
        "rev": {
            "umum": "Kabut mulai menipis. Kebingungan perlahan berkurang dan kebenaran mulai terlihat, walau mungkin tidak sepenuhnya nyaman untuk diterima.",
            "cinta": "Kesalahpahaman mulai terurai atau sesuatu yang tersembunyi akhirnya terungkap. Hadapi dengan tenang.",
            "karier": "Situasi yang membingungkan mulai jelas. Gunakan kejernihan baru ini untuk menyusun langkah.",
            "keuangan": "Masalah tersembunyi mulai terlihat sehingga bisa ditangani. Lebih baik tahu sekarang daripada nanti.",
            "saran": "Hadapi kenyataan yang mulai tampak, dan lepaskan ketakutan yang ternyata tidak berdasar.",
        },
    },
    {
        "slug": "sun",
        "number": 19,
        "name": "The Sun",
        "name_id": "Matahari",
        "element": None,
        "astrology": "Matahari",
        "hebrew": "Resh (ר)",
        "keywords_up": ["kebahagiaan", "keberhasilan", "kejelasan", "vitalitas"],
        "keywords_rev": ["kebahagiaan tertunda", "optimisme berlebihan", "redup sementara", "kurang percaya diri"],
        "symbolism": "Seorang anak telanjang menunggang kuda putih sambil membawa panji merah di bawah matahari besar berwajah. Bunga matahari tumbuh di balik tembok di belakangnya.",
        "answer_up": "ya",
        "answer_rev": "ya",
        "up": {
            "umum": "Kejelasan, keberhasilan, dan sukacita yang sederhana. Hal-hal menjadi terang, dan energi positif mengalir ke berbagai bidang hidupmu.",
            "cinta": "Hubungan yang hangat, terbuka, dan menggembirakan. Kebersamaan terasa ringan dan kalian bisa menjadi diri sendiri.",
            "karier": "Kerja kerasmu diakui dan hasilnya terlihat. Saat yang tepat untuk tampil dan menunjukkan apa yang sudah kamu capai.",
            "keuangan": "Keadaan finansial cerah dan stabil. Nikmati hasilnya dengan rasa syukur, sambil tetap bijak mengelolanya.",
            "saran": "Biarkan dirimu bahagia tanpa rasa bersalah. Bagikan kehangatan itu kepada orang-orang di sekitarmu.",
        },
        "rev": {
            "umum": "Kebahagiaan yang tertunda atau sedikit meredup, tapi tidak hilang. Kadang awan sesaat menutupi matahari, atau optimisme berlebihan membuatmu kurang waspada.",
            "cinta": "Hubungan baik-baik saja, hanya kurang dirayakan. Luangkan waktu untuk hal-hal sederhana yang dulu membuat kalian dekat.",
            "karier": "Keberhasilan datang sedikit lebih lambat dari harapan. Tetap realistis dan jangan meremehkan detail.",
            "keuangan": "Kondisi cukup baik, tapi hindari pengeluaran besar karena terlalu percaya diri.",
            "saran": "Cari lagi hal-hal kecil yang membuatmu bersemangat. Cahayanya masih ada, kamu hanya perlu membuka tirainya.",
        },
    },
    {
        "slug": "judgement",
        "number": 20,
        "name": "Judgement",
        "name_id": "Penghakiman",
        "element": "api",
        "astrology": "Unsur api",
        "hebrew": "Shin (ש)",
        "keywords_up": ["panggilan", "kebangkitan", "evaluasi diri", "keputusan penting"],
        "keywords_rev": ["menghakimi diri", "ragu menjawab panggilan", "menunda keputusan", "penyesalan"],
        "symbolism": "Malaikat meniup terompet berpanji salib dari balik awan. Di bawahnya, laki-laki, perempuan, dan anak-anak bangkit dari peti-peti yang mengapung, menengadah dengan tangan terbuka.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Saat untuk menjawab panggilan dan menilai perjalananmu dengan jernih. Ada kebangkitan, kesempatan kedua, atau keputusan besar yang menandai babak baru.",
            "cinta": "Hubungan dievaluasi dengan jujur, dan kalian bisa memulai lagi dengan pemahaman yang lebih dalam. Bisa juga kembalinya seseorang dari masa lalu.",
            "karier": "Panggilan untuk melangkah ke peran yang lebih sesuai dengan dirimu. Pengalaman yang sudah lewat kini menjadi bekal.",
            "keuangan": "Saat menilai ulang keputusan finansial dan memperbaiki yang perlu diperbaiki. Pelajaran lama membantu langkah berikutnya.",
            "saran": "Dengarkan panggilan batinmu dan berani menjawabnya. Maafkan masa lalu agar bisa bergerak maju.",
        },
        "rev": {
            "umum": "Terlalu keras menghakimi diri sendiri, atau ragu menjawab panggilan yang sebenarnya sudah jelas. Penyesalan lama mungkin masih menahan langkahmu.",
            "cinta": "Kesalahan lama terus diungkit sehingga hubungan sulit bergerak. Belajarlah memaafkan, termasuk memaafkan diri sendiri.",
            "karier": "Menunda keputusan penting karena takut salah. Evaluasi diri itu baik, asal tidak berubah menjadi kelumpuhan.",
            "keuangan": "Menyesali keputusan lama tidak mengubah keadaan. Ambil pelajarannya, lalu buat rencana baru.",
            "saran": "Berhenti menghukum dirimu atas masa lalu. Ambil pelajarannya, lalu jawab panggilan yang ada di depanmu.",
        },
    },
    {
        "slug": "world",
        "number": 21,
        "name": "The World",
        "name_id": "Dunia",
        "element": None,
        "astrology": "Saturnus",
        "hebrew": "Tav (ת)",
        "keywords_up": ["penyelesaian", "keutuhan", "pencapaian", "siklus lengkap"],
        "keywords_rev": ["belum tuntas", "mencari penutupan", "jalan pintas", "tertunda di garis akhir"],
        "symbolism": "Seorang penari berselendang ungu melayang di dalam karangan daun salam berbentuk oval yang diikat pita merah. Malaikat, elang, lembu, dan singa menghiasi keempat sudut kartu.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Sebuah siklus selesai dengan utuh. Ada rasa pencapaian, keselarasan, dan kesiapan untuk melangkah ke babak berikutnya dengan bekal yang lengkap.",
            "cinta": "Hubungan mencapai titik yang matang dan utuh, misalnya komitmen yang lebih dalam atau rasa saling melengkapi yang kuat.",
            "karier": "Proyek besar rampung dan diakui. Bisa juga peluang berskala lebih luas, termasuk pekerjaan lintas kota atau negara.",
            "keuangan": "Target keuangan tercapai. Saat yang baik untuk merayakan secukupnya dan menetapkan tujuan berikutnya.",
            "saran": "Rayakan apa yang sudah kamu selesaikan, lalu bersiaplah memulai perjalanan baru dengan percaya diri.",
        },
        "rev": {
            "umum": "Hampir selesai, tapi masih ada yang tertinggal. Kamu mungkin mencari jalan pintas atau belum menutup satu bab sehingga sulit melangkah ke bab berikutnya.",
            "cinta": "Ada urusan yang belum tuntas, baik dengan pasangan saat ini maupun dengan masa lalu. Penutupan yang jujur membantu semua pihak.",
            "karier": "Proyek tersendat di tahap akhir. Selesaikan detail yang tersisa sebelum mengambil tanggung jawab baru.",
            "keuangan": "Target hampir tercapai, tapi masih ada kewajiban kecil yang perlu diselesaikan dulu.",
            "saran": "Selesaikan apa yang sudah kamu mulai. Garis akhirnya dekat, jangan berhenti di sini.",
        },
    },
]
