WANDS = [
    {
        "rank": "ace",
        "astrology": None,
        "keywords_up": ["inspirasi", "awal baru", "potensi", "semangat"],
        "keywords_rev": ["tertunda", "kehilangan arah", "semangat padam", "awal yang keliru"],
        "symbolism": "Sebuah tangan muncul dari awan menggenggam tongkat yang bertunas, dengan daun-daun berguguran. Di kejauhan tampak kastel di atas bukit dan sungai yang mengalir.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Percikan inspirasi dan dorongan untuk memulai sesuatu. Ada ide atau peluang segar yang membawa energi besar, tinggal bagaimana kamu menyalakannya menjadi tindakan.",
            "cinta": "Ketertarikan baru yang penuh gairah, atau semangat yang kembali menyala dalam hubungan yang sudah ada.",
            "karier": "Ide proyek, usaha, atau arah karier baru yang membuatmu bersemangat. Ambil langkah pertamanya selagi energinya masih tinggi.",
            "keuangan": "Peluang penghasilan baru yang lahir dari kreativitas atau inisiatifmu sendiri.",
            "saran": "Tangkap ide yang muncul dan wujudkan langkah pertamanya sekarang, sekecil apa pun.",
        },
        "rev": {
            "umum": "Semangat ada, tapi belum menemukan jalan keluar. Rencana tertunda, ide terasa buntu, atau kamu memulai sesuatu tanpa arah yang jelas.",
            "cinta": "Gairah yang meredup atau ketertarikan yang tidak berlanjut. Jangan paksakan sesuatu yang memang belum menyala.",
            "karier": "Proyek baru tertunda atau kehilangan momentum. Tinjau ulang apakah ide ini benar-benar sesuai dengan tujuanmu.",
            "keuangan": "Rencana usaha atau penghasilan tambahan belum siap dijalankan. Matangkan dulu konsepnya.",
            "saran": "Cari tahu apa yang memadamkan semangatmu, lalu nyalakan lagi dari hal yang paling sederhana.",
        },
    },
    {
        "rank": "two",
        "astrology": "Mars di Aries",
        "keywords_up": ["perencanaan", "visi ke depan", "keputusan", "keluar dari zona nyaman"],
        "keywords_rev": ["takut melangkah", "rencana kabur", "ragu", "bermain aman"],
        "symbolism": "Seorang pria bertopi merah berdiri di atas benteng kastel, memegang bola dunia sambil menatap laut. Satu tongkat di tangannya, satu lagi terpasang di dinding bergambar mawar dan lili.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kamu sedang menimbang langkah besar dan melihat dunia yang lebih luas dari tempatmu berdiri. Saatnya merencanakan, bukan sekadar bermimpi.",
            "cinta": "Ada pertimbangan soal masa depan hubungan, misalnya apakah perlu melangkah lebih jauh atau tetap di tempat yang nyaman.",
            "karier": "Perencanaan jangka panjang, ekspansi, atau pilihan antara dua jalur. Susun strategi sebelum bergerak.",
            "keuangan": "Rencanakan investasi atau pengembangan usaha dengan matang. Peluangnya ada, tapi butuh keputusan yang jelas.",
            "saran": "Tetapkan tujuan yang konkret dan putuskan langkah pertamanya. Visi tanpa keputusan hanya akan tinggal di atas kertas.",
        },
        "rev": {
            "umum": "Takut keluar dari zona nyaman, atau rencana yang terlalu kabur untuk dijalankan. Kamu mungkin bermain aman padahal hatimu ingin lebih.",
            "cinta": "Ragu mengambil langkah serius, atau kalian punya bayangan masa depan yang berbeda. Bicarakan dengan terbuka.",
            "karier": "Rencana yang tidak kunjung dieksekusi atau keputusan yang terus ditunda karena takut gagal.",
            "keuangan": "Keputusan keuangan tertunda karena kurang informasi. Kumpulkan data, lalu tetapkan pilihan.",
            "saran": "Pilih satu arah dan mulailah. Rencana yang sempurna tidak akan pernah datang kalau kamu tidak bergerak.",
        },
    },
    {
        "rank": "three",
        "astrology": "Matahari di Aries",
        "keywords_up": ["ekspansi", "pandangan jauh", "kemajuan", "menanti hasil"],
        "keywords_rev": ["hambatan", "rencana tertunda", "kecewa", "kurang persiapan"],
        "symbolism": "Seorang pria berdiri membelakangi kita di tepi tebing, berpegangan pada satu dari tiga tongkat sambil memandangi kapal-kapal yang berlayar di laut keemasan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Usaha yang sudah kamu mulai mulai menunjukkan kemajuan. Pandanganmu meluas, dan peluang dari tempat yang lebih jauh mulai terlihat.",
            "cinta": "Hubungan berkembang dan kalian mulai merencanakan masa depan bersama. Bisa juga hubungan jarak jauh yang bertumbuh.",
            "karier": "Ekspansi, kerja sama dengan pihak luar, atau peluang lintas kota dan negara. Rencanamu mulai berbuah.",
            "keuangan": "Hasil dari usaha atau investasi mulai berdatangan. Pertahankan arah dan siapkan langkah berikutnya.",
            "saran": "Lihat lebih jauh dari tempatmu berdiri sekarang. Persiapkan diri untuk peluang yang sedang mendekat.",
        },
        "rev": {
            "umum": "Kemajuan tersendat oleh hambatan atau perencanaan yang kurang matang. Hasil yang ditunggu belum datang, dan rasa kecewa mulai muncul.",
            "cinta": "Rencana bersama tertunda, atau jarak, baik fisik maupun emosional, terasa semakin lebar.",
            "karier": "Proyek ekspansi terhambat atau mitra tidak memenuhi harapan. Evaluasi ulang strategi dan logistiknya.",
            "keuangan": "Hasil investasi atau usaha lebih lambat dari perkiraan. Hindari menambah modal sebelum masalahnya jelas.",
            "saran": "Periksa ulang persiapanmu. Kadang yang dibutuhkan bukan rencana baru, melainkan kesabaran dan perbaikan kecil.",
        },
    },
    {
        "rank": "four",
        "astrology": "Venus di Aries",
        "keywords_up": ["perayaan", "keharmonisan", "rumah", "pencapaian"],
        "keywords_rev": ["perayaan tertunda", "kurang dukungan", "transisi", "ketegangan di rumah"],
        "symbolism": "Empat tongkat berdiri dihiasi untaian bunga dan buah. Dua wanita mengangkat karangan bunga dengan gembira, dan di belakang mereka berdiri sebuah kastel yang megah.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Momen perayaan dan rasa syukur atas apa yang sudah dibangun. Ada kehangatan, kebersamaan, dan perasaan sudah sampai di tempat yang aman.",
            "cinta": "Hubungan yang stabil dan bahagia, sering dikaitkan dengan tunangan, pernikahan, atau kebahagiaan di rumah.",
            "karier": "Pencapaian sebuah tahap penting dan suasana kerja yang kompak. Layak dirayakan bersama tim.",
            "keuangan": "Stabilitas yang membuatmu bisa bernapas lega, misalnya untuk urusan rumah atau keperluan keluarga.",
            "saran": "Luangkan waktu untuk merayakan pencapaianmu bersama orang-orang yang mendukungmu.",
        },
        "rev": {
            "umum": "Perayaan yang tertunda atau suasana yang kurang hangat. Kamu mungkin berada di masa transisi, atau merasa kurang didukung oleh lingkungan.",
            "cinta": "Ada ketegangan di rumah atau rencana besar yang perlu ditunda. Rasa aman perlu dibangun kembali bersama.",
            "karier": "Tim kurang solid atau pencapaian kurang mendapat pengakuan. Fokus pada hubungan yang sehat dengan rekan kerja.",
            "keuangan": "Pengeluaran rumah tangga atau acara keluarga membebani. Sesuaikan rencana dengan kemampuan.",
            "saran": "Ciptakan rasa aman dari hal-hal kecil. Kebersamaan tidak selalu butuh perayaan besar.",
        },
    },
    {
        "rank": "five",
        "astrology": "Saturnus di Leo",
        "keywords_up": ["persaingan", "konflik", "perbedaan pendapat", "adu kekuatan"],
        "keywords_rev": ["menghindari konflik", "kesepakatan", "konflik batin", "gencatan"],
        "symbolism": "Lima pemuda mengayunkan tongkat ke berbagai arah, seperti sedang berkelahi atau bermain adu tanding. Tidak ada yang tampak terluka, tapi tidak ada pula yang mengalah.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Persaingan, gesekan, atau banyak suara yang saling bertabrakan. Konflik ini belum tentu berbahaya, tapi menguras tenaga bila tidak diarahkan.",
            "cinta": "Pertengkaran kecil, ego yang saling berbenturan, atau persaingan dengan pihak lain. Belajarlah berdebat tanpa saling menjatuhkan.",
            "karier": "Kompetisi ketat atau tim yang sulit sepakat. Tunjukkan kemampuanmu tanpa terjebak dalam drama.",
            "keuangan": "Persaingan harga atau perebutan sumber daya. Tetap tenang dan jangan terpancing keputusan reaktif.",
            "saran": "Pilih pertarungan yang memang penting. Tidak semua perbedaan pendapat perlu dimenangkan.",
        },
        "rev": {
            "umum": "Konflik mulai mereda atau sengaja dihindari. Bisa berarti tercapainya kesepakatan, bisa juga ketegangan yang hanya ditekan ke bawah permukaan.",
            "cinta": "Kalian memilih berdamai, atau menghindari pembicaraan penting demi menjaga suasana. Pastikan yang terjadi adalah penyelesaian, bukan penundaan.",
            "karier": "Gesekan di tempat kerja mereda dan kerja sama mulai mungkin. Manfaatkan untuk menyusun aturan main yang jelas.",
            "keuangan": "Sengketa atau persaingan mulai menemukan titik temu. Negosiasi lebih menguntungkan daripada adu keras.",
            "saran": "Hadapi konflik dengan tenang dan cari titik temu, bukan sekadar menghindarinya.",
        },
    },
    {
        "rank": "six",
        "astrology": "Yupiter di Leo",
        "keywords_up": ["kemenangan", "pengakuan", "kepercayaan diri", "keberhasilan"],
        "keywords_rev": ["ego", "kurang pengakuan", "jatuh dari puncak", "ragu diri"],
        "symbolism": "Seorang penunggang bermahkota daun salam menunggang kuda putih, membawa tongkat berhias karangan bunga. Orang-orang berjalan di sampingnya membawa tongkat, seperti arak-arakan kemenangan.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kemenangan dan pengakuan atas usahamu. Orang lain melihat apa yang sudah kamu capai, dan rasa percaya dirimu ikut tumbuh.",
            "cinta": "Hubungan yang membanggakan dan didukung lingkungan sekitar. Kamu merasa dihargai dan dipilih.",
            "karier": "Promosi, penghargaan, atau proyek yang berhasil diakui publik. Saat yang tepat untuk tampil.",
            "keuangan": "Hasil kerja keras terbayar dengan imbalan yang sepadan. Kelola dengan bijak agar keberhasilan bertahan.",
            "saran": "Terima pujian dengan rendah hati, dan bagikan keberhasilanmu dengan orang-orang yang ikut membantu.",
        },
        "rev": {
            "umum": "Keberhasilan yang belum diakui, atau rasa bangga yang mulai berubah menjadi kesombongan. Penilaian orang lain terlalu memengaruhi suasana hatimu.",
            "cinta": "Ada kebutuhan untuk terus dipuji, atau rasa tidak dihargai oleh pasangan. Bicarakan kebutuhanmu tanpa menuntut.",
            "karier": "Kerja keras kurang mendapat pengakuan, atau popularitas yang menurun. Tetap fokus pada kualitas.",
            "keuangan": "Jangan menghabiskan uang demi citra. Keberhasilan yang nyata tidak perlu dipamerkan.",
            "saran": "Ukur keberhasilanmu dari standar sendiri, bukan dari tepuk tangan orang lain.",
        },
    },
    {
        "rank": "seven",
        "astrology": "Mars di Leo",
        "keywords_up": ["bertahan", "mempertahankan posisi", "keyakinan", "keberanian"],
        "keywords_rev": ["kewalahan", "menyerah", "terlalu defensif", "kelelahan"],
        "symbolism": "Seorang pemuda berdiri di tempat yang lebih tinggi, menangkis enam tongkat yang mengarah dari bawah. Ia memakai sepatu yang tidak serasi, tanda ia bersiap terburu-buru.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kamu berada di posisi yang patut dipertahankan. Tantangan datang dari berbagai arah, tapi keyakinan dan keberanian membuatmu tetap berdiri.",
            "cinta": "Mempertahankan hubungan dari tekanan luar, atau berdiri teguh pada batas yang kamu tetapkan.",
            "karier": "Persaingan ketat untuk posisi yang sudah kamu raih. Pertahankan kualitasmu dan jangan mudah goyah.",
            "keuangan": "Lindungi aset dan rencana keuanganmu dari godaan atau tekanan orang lain.",
            "saran": "Bertahanlah pada apa yang kamu yakini benar, tapi pilih dengan bijak mana yang layak diperjuangkan.",
        },
        "rev": {
            "umum": "Rasa kewalahan karena terlalu banyak yang harus dihadapi sekaligus. Kamu mungkin mulai lelah bertahan, atau menjadi terlalu defensif terhadap semua hal.",
            "cinta": "Terus merasa diserang atau harus membela diri dalam hubungan. Tanyakan apakah ini masih sepadan.",
            "karier": "Kehilangan pijakan di tengah persaingan atau beban kerja. Minta dukungan sebelum kelelahan.",
            "keuangan": "Tekanan finansial dari banyak sisi. Prioritaskan satu masalah dalam satu waktu.",
            "saran": "Kamu tidak harus memenangkan semua pertempuran. Pilih yang penting dan lepaskan sisanya.",
        },
    },
    {
        "rank": "eight",
        "astrology": "Merkurius di Sagitarius",
        "keywords_up": ["kecepatan", "kabar", "gerak maju", "perjalanan"],
        "keywords_rev": ["tertunda", "terburu-buru", "salah komunikasi", "momentum hilang"],
        "symbolism": "Delapan tongkat melayang sejajar menembus udara di atas hamparan terbuka dan sungai, seolah sedang meluncur menuju tujuannya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Segalanya bergerak cepat. Kabar datang, rencana berjalan, dan hambatan yang lama mulai hilang. Ikuti momentumnya selagi arahnya jelas.",
            "cinta": "Perkembangan cepat dalam hubungan, pesan yang ditunggu, atau perasaan yang tumbuh dengan cepat.",
            "karier": "Proyek melaju, keputusan cepat diambil, atau ada perjalanan dinas. Responsif menjadi kuncinya.",
            "keuangan": "Arus uang bergerak cepat, baik masuk maupun keluar. Catat semuanya agar tetap terkendali.",
            "saran": "Bergeraklah selagi momentumnya ada, tapi pastikan arahnya sudah benar.",
        },
        "rev": {
            "umum": "Gerak yang tertahan atau justru terlalu terburu-buru. Pesan bisa terlambat, salah dipahami, atau rencana berjalan tanpa arah.",
            "cinta": "Komunikasi tersendat atau hubungan bergerak terlalu cepat untuk salah satu pihak. Samakan ritme.",
            "karier": "Penundaan, perubahan jadwal, atau keputusan tergesa-gesa yang perlu diperbaiki.",
            "keuangan": "Pembayaran tertunda atau keputusan finansial yang terburu-buru. Periksa ulang sebelum mengirim.",
            "saran": "Atur ulang ritmemu. Lebih baik sedikit lebih lambat tapi tepat sasaran.",
        },
    },
    {
        "rank": "nine",
        "astrology": "Bulan di Sagitarius",
        "keywords_up": ["ketahanan", "kegigihan", "waspada", "hampir sampai"],
        "keywords_rev": ["kelelahan", "curiga berlebihan", "menyerah", "pertahanan rapuh"],
        "symbolism": "Seorang pria berkepala diperban bersandar pada tongkatnya dengan tatapan waspada. Delapan tongkat berdiri berjajar di belakangnya seperti pagar pertahanan.",
        "answer_up": "belum",
        "answer_rev": "tidak",
        "up": {
            "umum": "Kamu sudah melewati banyak hal dan masih berdiri. Lelah itu wajar, tapi garis akhir sudah dekat. Ketahanan adalah kekuatan terbesarmu saat ini.",
            "cinta": "Hati yang pernah terluka menjadi lebih waspada. Lindungi dirimu, tapi jangan sampai menutup kesempatan untuk percaya lagi.",
            "karier": "Tahap akhir yang menguji kesabaran. Bertahan sedikit lagi, hasilnya akan sepadan.",
            "keuangan": "Masa sulit hampir terlewati. Tetap disiplin dan jaga cadangan yang tersisa.",
            "saran": "Bertahanlah sedikit lagi. Lindungi tenagamu dan selesaikan apa yang sudah kamu mulai.",
        },
        "rev": {
            "umum": "Tenaga hampir habis dan rasa curiga mulai berlebihan. Kamu mungkin terlalu lama bertahan sendiri sampai sulit membedakan ancaman nyata dan bayangan.",
            "cinta": "Luka lama membuatmu terus berjaga, sehingga sulit menerima kebaikan. Pertimbangkan untuk menurunkan sedikit pertahanan.",
            "karier": "Kelelahan kerja yang serius. Istirahat bukan tanda kalah, melainkan bagian dari strategi.",
            "keuangan": "Terus bertahan tanpa perubahan strategi hanya akan menguras tenaga. Cari bantuan atau cara baru.",
            "saran": "Akui bahwa kamu lelah. Beristirahat dan meminta bantuan adalah langkah yang bijak.",
        },
    },
    {
        "rank": "ten",
        "astrology": "Saturnus di Sagitarius",
        "keywords_up": ["beban berat", "tanggung jawab", "kerja berlebihan", "tekanan"],
        "keywords_rev": ["melepas beban", "mendelegasikan", "kelelahan", "ambruk"],
        "symbolism": "Seorang pria membungkuk memikul sepuluh tongkat yang berat, berjalan pelan menuju sebuah kota. Tumpukan tongkat itu menutupi pandangannya.",
        "answer_up": "tidak",
        "answer_rev": "belum",
        "up": {
            "umum": "Beban yang terlalu banyak dipikul sendiri. Kesuksesan atau tanggung jawab yang dulu diinginkan kini terasa berat dan menutupi pandanganmu.",
            "cinta": "Satu pihak menanggung terlalu banyak dalam hubungan, atau hubungan terasa seperti kewajiban.",
            "karier": "Beban kerja menumpuk dan tenaga terkuras. Saatnya membagi tugas atau menolak tambahan yang tidak perlu.",
            "keuangan": "Kewajiban finansial yang membebani. Susun prioritas dan cari cara meringankannya.",
            "saran": "Turunkan sebagian beban. Kamu tidak harus memikul semuanya sendirian.",
        },
        "rev": {
            "umum": "Mulai melepaskan beban yang tidak perlu, atau justru hampir ambruk karena terlalu lama memikulnya. Ada pilihan untuk mengubah keadaan.",
            "cinta": "Mulai berbagi tanggung jawab dengan lebih adil, atau menyadari bahwa beban emosional tidak bisa terus dipendam.",
            "karier": "Belajar mendelegasikan dan berkata tidak. Bila diabaikan, kelelahan akan memaksamu berhenti.",
            "keuangan": "Saatnya merestrukturisasi utang atau mengurangi komitmen yang menguras.",
            "saran": "Letakkan apa yang bukan tanggung jawabmu. Simpan tenaga untuk hal yang benar-benar penting.",
        },
    },
    {
        "rank": "page",
        "astrology": None,
        "keywords_up": ["antusiasme", "eksplorasi", "kabar baik", "rasa ingin tahu"],
        "keywords_rev": ["terburu-buru", "tidak fokus", "kabar tertunda", "ide mentah"],
        "symbolism": "Seorang pemuda bertopi bulu dan bertunik motif salamander berdiri di padang gurun, memandangi tongkat bertunas di tangannya. Piramida tampak di kejauhan.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Rasa ingin tahu dan semangat untuk mencoba hal baru. Bisa juga kabar baik atau ide segar yang memancing keberanianmu untuk bereksplorasi.",
            "cinta": "Pendekatan yang ceria dan penuh semangat, atau seseorang yang baru masuk dengan energi menyenangkan.",
            "karier": "Kesempatan belajar, magang, atau proyek kecil yang bisa berkembang. Antusiasmemu diperhatikan.",
            "keuangan": "Ide penghasilan baru yang masih tahap awal. Uji coba dulu dalam skala kecil.",
            "saran": "Ikuti rasa ingin tahumu dan coba sesuatu yang baru, tanpa harus langsung sempurna.",
        },
        "rev": {
            "umum": "Semangat yang mudah padam atau ide yang belum matang. Kamu mungkin melompat dari satu hal ke hal lain tanpa menyelesaikan apa pun.",
            "cinta": "Ketertarikan yang cepat datang dan cepat pergi, atau pesan yang tidak kunjung datang.",
            "karier": "Kurang fokus atau terlalu cepat bosan. Pilih satu proyek dan selesaikan.",
            "keuangan": "Rencana penghasilan yang masih mentah. Jangan menaruh banyak uang sebelum terbukti berjalan.",
            "saran": "Salurkan semangatmu ke satu hal dulu sampai benar-benar jalan.",
        },
    },
    {
        "rank": "knight",
        "astrology": "20° Scorpio sampai 20° Sagitarius",
        "keywords_up": ["gairah", "petualangan", "aksi cepat", "keberanian"],
        "keywords_rev": ["gegabah", "tidak sabar", "terburu nafsu", "frustrasi"],
        "symbolism": "Seorang ksatria berbaju zirah dengan tunik bermotif salamander menunggang kuda yang melompat. Bulu merah menyala di helmnya, dan piramida berdiri di padang gurun.",
        "answer_up": "ya",
        "answer_rev": "tidak",
        "up": {
            "umum": "Energi besar untuk bergerak dan berpetualang. Kamu siap mengejar sesuatu dengan penuh gairah, dan keberanian membuka banyak pintu.",
            "cinta": "Hubungan yang seru dan penuh gairah, atau seseorang yang hadir dengan pesona dan spontanitas.",
            "karier": "Gerak cepat, peluang yang menantang, atau perjalanan kerja. Semangatmu bisa menggerakkan tim.",
            "keuangan": "Keberanian mengambil peluang. Pastikan risikonya sudah dihitung sebelum melompat.",
            "saran": "Bergeraklah dengan berani, tapi tetap pegang kendali agar semangatmu tidak berubah menjadi kecerobohan.",
        },
        "rev": {
            "umum": "Gairah tanpa arah yang mudah berubah menjadi gegabah. Ketidaksabaran membuat keputusan diambil terlalu cepat atau rencana sering berganti.",
            "cinta": "Ketertarikan yang menggebu tapi tidak konsisten, atau sulit berkomitmen. Perhatikan tindakan, bukan janji.",
            "karier": "Proyek dimulai dengan semangat tapi ditinggalkan di tengah jalan. Selesaikan sebelum pindah ke hal lain.",
            "keuangan": "Keputusan impulsif yang berisiko. Tahan diri sebelum membeli atau berinvestasi.",
            "saran": "Perlambat langkah dan pikirkan konsekuensinya. Keberanian tetap butuh arah.",
        },
    },
    {
        "rank": "queen",
        "astrology": "20° Pisces sampai 20° Aries",
        "keywords_up": ["percaya diri", "kehangatan", "kemandirian", "karisma"],
        "keywords_rev": ["cemburu", "tidak percaya diri", "menuntut", "kelelahan"],
        "symbolism": "Seorang ratu duduk di singgasana berhias singa, memegang tongkat dan setangkai bunga matahari. Seekor kucing hitam duduk di kakinya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kepercayaan diri yang hangat dan menular. Kamu tahu apa yang kamu mau, mampu mengurus banyak hal, dan tetap bersinar tanpa harus meredupkan orang lain.",
            "cinta": "Pribadi yang menarik, percaya diri, dan tulus. Hubungan diwarnai kehangatan dan saling mendukung.",
            "karier": "Kepemimpinan yang karismatik dan cekatan. Kamu dipercaya mengelola banyak hal sekaligus.",
            "keuangan": "Pengelolaan yang mandiri dan percaya diri. Kamu mampu mengambil keputusan finansial sendiri.",
            "saran": "Tampilkan dirimu apa adanya dengan percaya diri. Kehangatanmu adalah kekuatanmu.",
        },
        "rev": {
            "umum": "Kepercayaan diri yang goyah, atau energi yang berubah menjadi menuntut dan cemburu. Kamu mungkin terlalu banyak memberi hingga lelah.",
            "cinta": "Rasa cemburu atau tidak aman mulai memengaruhi hubungan. Komunikasikan kebutuhanmu dengan tenang.",
            "karier": "Terlalu banyak tanggung jawab membuatmu kewalahan dan mudah tersinggung. Bagi tugas dengan tim.",
            "keuangan": "Keputusan finansial dipengaruhi emosi atau kebutuhan untuk diakui.",
            "saran": "Kembalikan fokus pada dirimu sendiri. Kepercayaan diri tumbuh dari merawat diri, bukan dari pengakuan orang lain.",
        },
    },
    {
        "rank": "king",
        "astrology": "20° Cancer sampai 20° Leo",
        "keywords_up": ["visi", "kepemimpinan", "wirausaha", "keberanian mengambil keputusan"],
        "keywords_rev": ["impulsif", "arogan", "ekspektasi tidak realistis", "keras kepala"],
        "symbolism": "Seorang raja duduk di singgasana berhias singa dan salamander, memegang tongkat yang bertunas. Seekor salamander kecil berada di dekat kakinya.",
        "answer_up": "ya",
        "answer_rev": "belum",
        "up": {
            "umum": "Kepemimpinan yang visioner dan berani. Kamu mampu melihat gambaran besar dan menggerakkan orang lain untuk mewujudkannya.",
            "cinta": "Pasangan atau sikap yang tegas, setia, dan penuh semangat. Hubungan diarahkan dengan visi yang jelas.",
            "karier": "Saat yang baik untuk memimpin, berwirausaha, atau mengambil keputusan strategis.",
            "keuangan": "Keputusan finansial yang berani namun terencana. Visi jangka panjang membawa hasil.",
            "saran": "Pimpin dengan memberi contoh. Tunjukkan arah dengan jelas dan tepati kata-katamu.",
        },
        "rev": {
            "umum": "Kepemimpinan yang berubah menjadi impulsif atau arogan. Ekspektasi terlalu tinggi, baik pada diri sendiri maupun orang lain.",
            "cinta": "Sikap mendominasi atau mudah tersulut emosi. Beri ruang bagi pasangan untuk ikut menentukan arah.",
            "karier": "Keputusan diambil tanpa mendengar tim, atau target yang tidak realistis. Turunkan ego dan dengarkan masukan.",
            "keuangan": "Ambisi yang melampaui kemampuan. Sesuaikan rencana dengan sumber daya yang ada.",
            "saran": "Dengarkan orang lain sebelum memutuskan. Pemimpin yang kuat tahu kapan harus menahan diri.",
        },
    },
]
