SHIO_FORTUNE_COOKIE_BANK = {
    "tikus": [
        {"message": "Pintar cari celah tapi bodoh baca chat gebetan. Makanya jangan kebanyakan di ghosting.", "lucky_item": "Screenshot promo expired"},
        {"message": "Tabungan aman, tapi circle pertemananmu butuh investasi. Keluar rumah dong!", "lucky_item": "Uang koin 200 perak di bawah sofa"},
        {"message": "Hari ini cocok buat bikin backup plan nomor 14. Ya kali aja plan 1-13 gagal semua.", "lucky_item": "Flashdisk isi tugas makalah 2015"},
        {"message": "Ada peluang emas hari ini, sayangnya kamu kesiangan karena scroll FYP sampai jam 3 pagi.", "lucky_item": "Alarm jam 6.00 yang di-snooze sampai jam 9.00"},
        {"message": "Networking itu bagus, tapi nggak usah SKSD sama kasir minimarket juga kali.", "lucky_item": "Kartu member gym yang nggak pernah dipakai"},
        {"message": "Kesuksesanmu sedekat cicilan PayLater bulan depan. Semangat kerja keras bagai quda (tapi kamu tikus).", "lucky_item": "Struk belanja yang tulisannya udah pudar"},
        {"message": "Banyak yang iri sama kepintaranmu ngeles pas ditagih utang. Bakat terpendam!", "lucky_item": "Kalkulator dengan layar pecah"},
        {"message": "Pikiranmu terlalu kalkulatif, sampai lupa ngitung kapan terakhir kali mandi.", "lucky_item": "Sabun batang yang tinggal seiprit"},
        {"message": "Nggak usah mikirin omongan orang, mereka aja belum tentu mikirin kamu.", "lucky_item": "Spion motor kanan yang kendor"},
        {"message": "Hidup itu kayak main saham, kadang hijau kadang merah. Kamu? Selalu nungguin dividen turun.", "lucky_item": "Lemari pendingin yang cuma ada es batu"},
        {"message": "Semua orang butuh kamu... buat ngerjain tugas kelompok. Kurang-kurangin jadi tumbal proyek.", "lucky_item": "Grup WA yang cuma di-read"},
        {"message": "Berhenti cari gratisan wifi cafe tanpa beli minum. Karma itu nyata.", "lucky_item": "Gelas bekas kopi yang ditinggal di meja"},
        {"message": "Keberuntunganmu hari ini: nemu duit 50 ribu di celana cucian. Sayangnya udah hancur kena mesin cuci.", "lucky_item": "Kertas lecek bau deterjen"},
        {"message": "Jangan terlalu perhitungan soal perasaan, nanti gebetanmu di-checkout orang lain.", "lucky_item": "Keranjang oren yang isinya 99+ barang"},
        {"message": "Hati-hati ngomongin orang dari belakang, ada yang lagi record dari depan.", "lucky_item": "Earphone sebelah kiri yang mati"},
        {"message": "Cinta itu buta, tapi kamu lebih suka pura-pura buta pas diajak jalan biar gak keluar ongkos.", "lucky_item": "Kacamata dengan frame isolasi"},
        {"message": "Rahasia umur panjangmu adalah selalu punya alasan buat kabur dari tanggung jawab.", "lucky_item": "Tombol escape di keyboard yang jebol"},
        {"message": "Ada yang diam-diam memperhatikanmu. Tapi itu cuma admin pinjol.", "lucky_item": "Nomor tak dikenal di riwayat panggilan"},
        {"message": "Coba deh sekali-kali traktir temanmu, biar mereka yakin kamu belum bangkrut.", "lucky_item": "Dompet kulit sintesis yang ngelotok"},
        {"message": "Otakmu secepat prosesor i9, sayang sinyal wifi-mu sekelas warnet tahun 2005.", "lucky_item": "Kabel LAN yang digigit tikus"}
    ],
    "kerbau": [
        {"message": "Kerja keras boleh, tipes jangan. Kurangin lembur tanpa bayaran tambahan itu.", "lucky_item": "Obat maag di laci meja kerja"},
        {"message": "Tolong ya, dunia nggak bakal hancur kalau kamu sesekali bolos kerja.", "lucky_item": "Surat izin sakit buatan sendiri"},
        {"message": "Saking kakunya kamu sama rutinitas, robot aja minder lihat jadwal harianmu.", "lucky_item": "Buku agenda tahun 2018 yang masih kosong"},
        {"message": "Keras kepala itu nama tengahmu. Kalau dibilangin, pasti masuk telinga kiri keluar di telinga kiri lagi.", "lucky_item": "Helm SNI tapi belum diklik"},
        {"message": "Bosan itu relatif, tapi ngelihat gaya hidupmu, kayaknya bosan itu absolut.", "lucky_item": "Kopi sachet kadaluarsa"},
        {"message": "Jangan lupa bernapas. Iya tahu kamu lagi fokus ngetik, tapi napas woy!", "lucky_item": "Kipas angin kecil nempel di laptop"},
        {"message": "Berhenti ngerasa dunia berpusat pada deadline-mu. Kasihan temanmu yang ngajak nongkrong di-reject terus.", "lucky_item": "Kursi plastik warmindo"},
        {"message": "Keteguhan hatimu patut diacungi jempol, sayang jempolnya udah kram ngetik laporan.", "lucky_item": "Salep pegal linu aroma sereh"},
        {"message": "Santai sedikit nggak bikin gaji dipotong. Eh, atau dipotong ya? Ya udah kerja lagi sana.", "lucky_item": "Slip gaji dengan potongan bpjs"},
        {"message": "Ubah rutinitasmu hari ini. Coba minum kopi pakai tangan kiri sambil kayang.", "lucky_item": "Gelas mug tulisan 'World's Best Employee'"},
        {"message": "Kamu adalah pilar perusahaan, tapi ingat, pilar juga bisa lumutan kalau nggak dirawat.", "lucky_item": "Sikat WC yang jarang dipakai"},
        {"message": "Sifat old-school-mu bikin kamu kayak fosil di tengah kumpulan Gen Z. Coba install TikTok.", "lucky_item": "Nokia 3310 yang batrenya gembung"},
        {"message": "Terkadang, 'aku nggak tahu' adalah jawaban yang jauh lebih baik daripada ngeyel.", "lucky_item": "Kunci gembok yang karat"},
        {"message": "Lambat asal selamat, tapi kalau lambat banget, gebetanmu keburu nikah sama orang lain.", "lucky_item": "Undangan pernikahan mantan"},
        {"message": "Kamu bisa diandalkan, terlalu bisa diandalkan sampai orang lain jadi parasit.", "lucky_item": "Payung hitam yang gagangnya patah"},
        {"message": "Jangan bawa masalah kerjaan ke mimpi. Cukup bosmu aja yang hantui kamu di grup WA.", "lucky_item": "Bantal bau iler"},
        {"message": "Coba pakai baju warna terang hari ini, biar nggak dikira patung di pojok kantor.", "lucky_item": "Kemeja flanel kotak-kotak pudar"},
        {"message": "Kemampuanmu nyimpan dendam melebihi memori hardisk 2TB. Maafin napa, berat tuh hidup.", "lucky_item": "Hardisk eksternal yang minta diformat"},
        {"message": "Kamu kuat menghadapi masalah, tapi lemah pas ditanya 'kapan nikah?'.", "lucky_item": "Brosur KPR rumah subsidi"},
        {"message": "Sesekali berontaklah, hidup ini terlalu singkat untuk jadi anak emas bos terus.", "lucky_item": "Dasi yang kepanjangan"}
    ],
    "macan": [
        {"message": "Halo main character, jangan lupa hari ini bukan cuma tentang kamu doang ya.", "lucky_item": "Cermin seukuran telapak tangan"},
        {"message": "Impulsif beli barang di olshop gara-gara packaging-nya lucu? Welcome to the club.", "lucky_item": "Kardus paket isi bubble wrap doang"},
        {"message": "Nggak semua orang harus nurut sama kamu, baginda raja. Turunin dikit egonya.", "lucky_item": "Mahkota kertas ulang tahun fast food"},
        {"message": "Drama apa lagi yang mau kamu sutradarai hari ini? Tolong bayar figuran dong.", "lucky_item": "Kacamata hitam di dalam ruangan"},
        {"message": "Keberanianmu luar biasa, sampai berani ngechat 'P' ke atasan jam 11 malam.", "lucky_item": "HP yang di-airplane mode karena takut balesan"},
        {"message": "Auramu memang mengintimidasi, tapi dompetmu pas akhir bulan mengintimidasi kamu balik.", "lucky_item": "Saldo ATM 45 ribu"},
        {"message": "Berhenti bertindak gegabah, apalagi mutusin pacar cuma karena zodiaknya nggak cocok.", "lucky_item": "Buku ramalan bintang edisi 2012"},
        {"message": "Kamu terlahir sebagai pemimpin, sayang anak buahmu pura-pura nggak dengar intruksimu.", "lucky_item": "Toa toa toa toa (rusak)"},
        {"message": "Marah-marah nggak menyelesaikan masalah, tapi bikin tekanan darah naik. Minum air putih sana.", "lucky_item": "Tumbler merk mahal yang isinya air keran"},
        {"message": "Energi hari ini: Siap menerkam tantangan hidup. Realita: Ketiduran di sofa depan TV.", "lucky_item": "Remote TV yang baterainya harus dipukul dulu"},
        {"message": "Gaya selangit, duit sulit. Coba kurang-kurangin eksis di cafe hits.", "lucky_item": "Bon kopi harga 80 ribu"},
        {"message": "Orang-orang segan sama kamu, bukan karena respect, tapi takut kena amuk.", "lucky_item": "Tanda 'Awas Anjing Galak' yang dicoret jadi 'Macan Galak'"},
        {"message": "Reckless decision of the day: Potong poni sendiri pakai gunting dapur.", "lucky_item": "Gunting yang lengket kena selotip"},
        {"message": "Kamu butuh liburan, tapi liburan butuh uang. Balik kerja sana, rawr!", "lucky_item": "Wallpaper pantai di laptop"},
        {"message": "Jangan terlalu kompetitif, ini cuma main ludo, bukan rebutan tahta kerajaan.", "lucky_item": "Bidak ludo warna merah"},
        {"message": "Semua mata tertuju padamu, sayangnya karena kamu pakai baju terbalik.", "lucky_item": "Kaos yang labelnya di leher depan"},
        {"message": "Bossy-mu bikin orang muak, coba belajar pakai kata 'tolong' dan 'terima kasih'.", "lucky_item": "Kamus Bahasa Indonesia untuk pemula"},
        {"message": "Insting predator-mu tajam pas nyari diskonan 9.9, salut!", "lucky_item": "Sinyal 5G di pojok kamar"},
        {"message": "Hati-hati dengan kata-katamu, tajamnya melebihi silet. Kasihan yang baper.", "lucky_item": "Plaster luka gambar Hello Kitty"},
        {"message": "Berhenti main-main dengan api, nanti rumahmu kebakaran. Maksudnya, jangan nge-flirt pacar orang.", "lucky_item": "Korek gas yang apinya kegedean"}
    ],
    "kelinci": [
        {"message": "Berhentilah bilang 'aku nggak apa-apa' sambil banting pintu lemari.", "lucky_item": "Gagang pintu lemari yang copot"},
        {"message": "Passive-aggressive mu itu lho, lebih menusuk daripada jarum suntik dokter gigi.", "lucky_item": "Status WA yang di-hide dari semua orang kecuali satu orang"},
        {"message": "People pleaser sejati, sampai rela makan bubur diaduk demi ngikutin kata teman.", "lucky_item": "Sendok plastik bekas bubur ayam"},
        {"message": "Aesthetics over everything, biarpun dompet menangis melihat harga cafe yang instagramable itu.", "lucky_item": "Tanaman plastik monstera berdebu"},
        {"message": "Terlalu baik sampai gampang ditipu. Hati-hati sama teman yang mau pinjam 100.", "lucky_item": "Bukti transfer m-banking yang udah kedaluwarsa"},
        {"message": "Dibalik wajah manismu, tersimpan rencana pembunuhan... nyamuk yang dari tadi di telinga.", "lucky_item": "Rakit nyamuk listrik baterai soak"},
        {"message": "Fake nice-mu level dewa. Pura-pura senyum padahal di dalem hati udah ngabsen isi kebun binatang.", "lucky_item": "Masker kain dua lapis buat nutupin bibir manyun"},
        {"message": "Saking penakutnya, nonton film horor aja kamu tutup mata dari opening sampai credit title.", "lucky_item": "Selimut tebal bau kapur barus"},
        {"message": "Belajar bilang 'TIDAK' dong, masa disuruh piket terus tiap hari padahal bukan jadwalmu.", "lucky_item": "Sapu ijuk yang gagangnya bengkok"},
        {"message": "Ekspektasimu soal cinta kayak drakor, pantesan realitanya jomblo melulu.", "lucky_item": "Bantal guling yang keseringan dipeluk"},
        {"message": "Suka menghindari konflik, ujung-ujungnya konflik itu ngendap jadi penyakit lambung.", "lucky_item": "Antasida sirup rasa mint"},
        {"message": "Outfit hari ini: pastel aesthetic cottagecore. Mood hari ini: ingin resign dari bumi.", "lucky_item": "Jepit rambut pita warna krem"},
        {"message": "Kamu imut sih, tapi kalau lagi ngambek seremnya ngalahin debt collector.", "lucky_item": "Pesan WA ditarik 5 kali"},
        {"message": "Terlalu banyak mikirin omongan orang, coba mikirin cicilan motor sesekali.", "lucky_item": "Buku garansi motor di bawah jok"},
        {"message": "Seni ngode lewat Spotify playlist-mu gagal total, gebetanmu dengerinnya dangdut koplo.", "lucky_item": "Headset kabel yang sebelah kanan mati"},
        {"message": "Diam-diam menghanyutkan. Kelihatannya polos, padahal tahu gosip terupdate sedivisi.", "lucky_item": "Screenshot chat grup gibah rahasia"},
        {"message": "Kamu butuh lebih banyak kalsium biar tulangmu kuat nahan beban hidup sebagai orang gak enakan.", "lucky_item": "Kotak susu UHT ukuran 125ml"},
        {"message": "Kelembutan hatimu sering dimanfaatin. Coba agak ngegas dikit, pelan aja 'gas'.", "lucky_item": "Klakson motor matic yang suaranya cempreng"},
        {"message": "Banyak yang suka sama kamu, sayang kamu terlalu sibuk nyari kekurangan diri sendiri.", "lucky_item": "Kaca wastafel yang buram kena uap air"},
        {"message": "Kelihatan lemah, tapi kalau di jalan raya bawa motor matic, nyalimu lebih besar dari truk fuso.", "lucky_item": "Lampu sein kiri tapi belok kanan"}
    ],
    "naga": [
        {"message": "Naga memang makhluk mitologi, pantesan kesempurnaanmu cuma fiktif belaka.", "lucky_item": "Buku dongeng anak-anak sobek"},
        {"message": "Egomu lebih tinggi dari gedung Burj Khalifa. Coba deh sesekali turun ke bumi.", "lucky_item": "Tiket lift rusak"},
        {"message": "Main character syndrome-mu lagi kumat ya? Ingat, nggak semua orang lagi nontonin kamu.", "lucky_item": "Kamera CCTV palsu di sudut ruang"},
        {"message": "Selalu merasa paling benar, padahal kemarin nyasar pake Google Maps padahal rutenya cuma lurus.", "lucky_item": "Tanda panah jalan yang dicoret-coret"},
        {"message": "Kharisma luar biasa, tapi napas nagamu kalau pagi tolong dikondisikan.", "lucky_item": "Obat kumur rasa pepermint kuat"},
        {"message": "Kamu suka merintah orang, sayangnya kamu bukan bos di sini. Turunkan telunjukmu.", "lucky_item": "Stempel 'Rejected'"},
        {"message": "Percaya diri itu bagus, narsis itu penyakit. Kamu ada di perbatasan keduanya.", "lucky_item": "Cermin rias dengan lampu LED super terang"},
        {"message": "Semua orang tahu kamu hebat, nggak usah diulang-ulang ceritanya tiap kumpul.", "lucky_item": "Kaset pita rusak karena kusut"},
        {"message": "Kamu dilahirkan untuk memimpin... memimpin antrean seblak di depan perumahan.", "lucky_item": "Nomor antrean 99"},
        {"message": "Terkadang, pura-pura salah itu bisa bikin kamu punya teman lho.", "lucky_item": "Penghapus karet warna hitam"},
        {"message": "Ambisi setinggi langit, realita: cuma sanggup rebahan sambil mikirin plan A sampai Z.", "lucky_item": "Kasur lantai yang tipis"},
        {"message": "Bakat terpendammu adalah ngasih saran yang bagus, tapi nggak pernah dipraktekin sendiri.", "lucky_item": "Buku self-help halaman pertama doang yang dibaca"},
        {"message": "Berhentilah flexing prestasi masa lalu, itu piala lomba RT waktu kamu umur 5 tahun, bro.", "lucky_item": "Piala plastik warna emas ngelupas"},
        {"message": "Gengsi kegedean bikin kamu nahan lapar cuma karena malu bawa bekal kotak makan pink.", "lucky_item": "Tupperware mamah yang dilarang hilang"},
        {"message": "Aura nagamu lagi redup, mungkin kurang makan gorengan abang-abang pinggir jalan.", "lucky_item": "Bungkus kertas koran bekas gorengan"},
        {"message": "Nggak usah caper, diam aja orang udah notice kamu kok saking berisiknya auramu.", "lucky_item": "Toa masjid yang lagi feedback suara"},
        {"message": "Berdebat sama kamu itu kayak ngomong sama tembok. Tembok yang bisa nyembur api.", "lucky_item": "Bata merah yang belum disemen"},
        {"message": "Jangan terlalu keras sama diri sendiri, nanti cepet tua. Egomu butuh istirahat.", "lucky_item": "Krim anti-aging harga murah"},
        {"message": "Kamu nggak perlu persetujuan semua orang, cukup persetujuan dari saldo rekeningmu.", "lucky_item": "Notifikasi m-banking 'Saldo Tidak Cukup'"},
        {"message": "Kurangin sifat bossy-nya, nanti ditinggalin circle baru nangis dipojokan.", "lucky_item": "Tisu toilet gulung setengah basah"}
    ],
    "ular": [
        {"message": "Misterius banget kayak password wifi tetangga. Buka dikit dong hatinya.", "lucky_item": "Router wifi tanpa antena"},
        {"message": "Kamu bukan detektif, berhentilah stalking mantan dari akun fake.", "lucky_item": "Akun bodong IG foto profil telur"},
        {"message": "Terlalu pinter manipulasi, sampai bingung sendiri sebenarnya kamu lagi sedih apa pura-pura sedih.", "lucky_item": "Bawang merah utuh"},
        {"message": "Secretive itu keren, tapi kalau alamat kosan aja nggak mau ngasih tau temen, itu aneh.", "lucky_item": "Gembok koper angka 000"},
        {"message": "Trust issues-mu udah level dewa, sampai sama diri sendiri aja curiga.", "lucky_item": "Kaca spion retak seribu"},
        {"message": "Materialistis itu nggak salah, yang salah kalau nggak ada modalnya.", "lucky_item": "Dompet kosong banyak resletingnya"},
        {"message": "Tatapanmu dingin dan tajam, persis tatapan dosen penguji pas sidang skripsi.", "lucky_item": "Laser pointer presentasi mati"},
        {"message": "Hati-hati, ntar kepatuk omongan sendiri. Kemarin bilang nggak suka, eh sekarang nempel.", "lucky_item": "Lem super glue yang nempel di tangan"},
        {"message": "Jago nyimpen rahasia orang, tapi ember banget kalau udah ngomongin musuh bebuyutan.", "lucky_item": "Ember bocor ditambal lakban"},
        {"message": "Kamu punya indra keenam ya? Pintar banget nyium gelagat red flag orang dari jarak 10 km.", "lucky_item": "Bendera merah sobek-sobek"},
        {"message": "Cantik/ganteng sih, tapi racun. Alias toxic kalau lagi cemburu.", "lucky_item": "Botol obat nyamuk semprot"},
        {"message": "Sering dituduh licik padahal kamu cuma pinter nyari jalan pintas biar cepet kelar.", "lucky_item": "Jalan pintas ke toilet yang dikunci"},
        {"message": "Jangan terlalu tertutup, ntar jamuran lho di dalem situ sendirian.", "lucky_item": "Kapur barus yang mengecil"},
        {"message": "Bakat acting-mu patut dapet piala Oscar, apalagi pas pura-pura lupa bayar patungan makanan.", "lucky_item": "Kalkulator di HP yang aplikasinya disembunyikan"},
        {"message": "Pendendam banget, dicubit dikit balasnya banting meja. Chill dikit napa.", "lucky_item": "Buku catatan daftar musuh (Death Note KW)"},
        {"message": "Kamu selalu punya hidden agenda. Bahkan pas ngajak nongkrong doang ternyata ada udang di balik batu.", "lucky_item": "Batu kali lumutan"},
        {"message": "Pesona ular emang mematikan. Sekali lirik, orang langsung serasa digendam buat nraktir kamu.", "lucky_item": "Kacamata hipnotis mainan"},
        {"message": "Kurangin sifat suudzonnya, nggak semua orang mau nikam kamu dari belakang kok.", "lucky_item": "Gunting kuku yang tumpul"},
        {"message": "Elegan dan berkelas di luar, tapi di kamar dengerinnya DJ remix jedag-jedug.", "lucky_item": "Speaker bluetooth kelap-kelip lampu RGB"},
        {"message": "Sikap dinginmu itu mekanisme pertahanan atau emang dari sononya nggak punya hati?", "lucky_item": "Es batu yang udah mencair di gelas"}
    ],
    "kuda": [
        {"message": "Berhenti lari dari tanggung jawab, kakimu pasti capek biarpun kamu kuda.", "lucky_item": "Sepatu lari solnya bolong"},
        {"message": "FOMO banget jadi orang, ada event dikit wajib dateng, padahal di sana cuma main HP.", "lucky_item": "Baterai powerbank sisa 1 strip"},
        {"message": "Sabar dikit kenapa sih? Mie instan aja butuh 3 menit buat matang, apalagi kesuksesan.", "lucky_item": "Mie instan yang direbus kelamaan jadi lembek"},
        {"message": "Gak sabaran, commitment phobic, dan bosenan. Combo maut yang bikin kamu jomblo terus.", "lucky_item": "Cincin plastik hadiah ciki"},
        {"message": "Energi lo berlebih banget, mending disalurin buat ngepel lantai rumah sana.", "lucky_item": "Kain pel dekil yang baunya apek"},
        {"message": "Tukang petualang, tapi tiap minggu rutenya cuma kasur-kamar mandi-dapur.", "lucky_item": "Peta kota yang jadul"},
        {"message": "Cepat tanggap kalau diajak jalan, lemot banget kalau disuruh ngerjain laporan bos.", "lucky_item": "Kunci motor yang gantungannya copot"},
        {"message": "Selalu butuh kebebasan, sampai lupa kalau kebebasan tanpa uang itu namanya gelandangan.", "lucky_item": "Dompet kosong yang dipake kipasan"},
        {"message": "Gampang bosen sama pacar, coba deh pacaran sama roller coaster biar adrenalinmu terjaga.", "lucky_item": "Tiket wahana pasar malam kucel"},
        {"message": "Kamu pikir kamu kuda liar, padahal kamu cuma kuda lumping yang butuh sesajen indomie.", "lucky_item": "Pecahan beling dari piring tetangga"},
        {"message": "Berani ambil resiko tinggi, padahal asuransi kesehatan aja nunggak 3 bulan.", "lucky_item": "Kartu BPJS yang patah"},
        {"message": "Suka nyerobot antrean, untung wajahmu cukup kasihan untuk dimaafkan.", "lucky_item": "Tanda 'Harap Antre' yang bengkok"},
        {"message": "Jangan kebanyakan janji kalau nggak bisa nepatin. Besok-besok janjinya dipakein meterai.", "lucky_item": "Meterai 10.000 yang udah dicoret"},
        {"message": "Saking cepatnya ngomong, orang ngira kamu lagi ngerap padahal lagi presentasi.", "lucky_item": "Mic karaoke bluetooth yang suaranya kresek-kresek"},
        {"message": "Terlalu independen sampai lupa gimana caranya minta tolong pas ban motor bocor.", "lucky_item": "Pompa ban manual yang berat ditarik"},
        {"message": "Kamu nggak bisa diam di satu tempat, pantesan posisi tidurmu muter 180 derajat tiap malam.", "lucky_item": "Sprei kasur yang selalu lepas ujungnya"},
        {"message": "Niatnya pengen keliling dunia, realitanya keliling nyari promo GrabFood doang.", "lucky_item": "Aplikasi ojol yang minta update"},
        {"message": "Kuda emang kuat lari, tapi hatimu rapuh banget pas dicuekin gebetan seharian.", "lucky_item": "Notifikasi 'Last seen today at 09.00'"},
        {"message": "Spontanitas itu asik, tapi jangan spontan resign pas lagi gak punya tabungan dong.", "lucky_item": "Kardus indomie buat nyimpen barang kantor"},
        {"message": "Kurang-kurangin kebiasaan ninggalin teman pas lagi susah, karma tuh ntar nendang balik.", "lucky_item": "Sepatu kuda yang karetnya lepas"}
    ],
    "kambing": [
        {"message": "Manja boleh, tapi jangan nyusahin orang dong. Minta suapin sekalian?", "lucky_item": "Bib alas makan bayi motif beruang"},
        {"message": "Overthinking tiap malam mikirin chat 'Wkwk' dari crush, padahal dia cuma basa-basi.", "lucky_item": "Bantal yang basah karena air mata buaya"},
        {"message": "Victim mentality-mu luar biasa, selalu ngerasa dunia jahat padahal kamu yang males.", "lucky_item": "Skenario sinetron azab"},
        {"message": "Baperan level akut, ditegur bos suruh benerin font malah nangis di toilet.", "lucky_item": "Tisu gulung toilet yang abis"},
        {"message": "Artistik dan punya selera tinggi, sayangnya gaji masih standar UMR pas-pasan.", "lucky_item": "Palet lukis bekas yang catnya mengering"},
        {"message": "Indecisive banget, milih menu Gofood aja butuh 2 jam, keburu tokonya tutup.", "lucky_item": "Menu warteg yang lecek"},
        {"message": "Suka berimajinasi hidup indah, tapi males mandi pagi. Mimpi doang dipupuk.", "lucky_item": "Gayung bolong di kamar mandi"},
        {"message": "Minta pendapat ke 10 teman, ujung-ujungnya ngikutin keputusan awal yang jelek itu.", "lucky_item": "Coin 500 perak buat lempar undian"},
        {"message": "Terlalu pemaaf sampai sering digoblok-goblokin mantan. Move on woy!", "lucky_item": "Kacamata kuda buat nutupin kenyataan"},
        {"message": "Lebih suka hidup damai, tapi diem-diem ngumpulin gosip buat bahan julid pas lagi ngopi.", "lucky_item": "Gelas kopi setengah sisa"},
        {"message": "Sensitif banget, awan mendung dikit aja kamu udah mikir alam semesta lagi berduka.", "lucky_item": "Payung motif bunga yang rusak rangkanya"},
        {"message": "Bergantung sama orang lain itu keahlianmu. Belajar mandiri dikit, setidaknya potong kuku sendiri.", "lucky_item": "Gunting kuku tumpul"},
        {"message": "Kebaikan hatimu sering dimanfaatkan tukang utang. Belajar nagih dong sesekali.", "lucky_item": "Catatan utang di buku kas kecil"},
        {"message": "Kamu suka hal-hal berbau alam, tapi pas diajak naik gunung malah sambat capek di pos pertama.", "lucky_item": "Sandal jepit gunung tali putus"},
        {"message": "Kambing emang suka makan rumput, tapi jangan gampang termakan omongan manis buaya darat dong.", "lucky_item": "Rumput sintetis sisa dekor"},
        {"message": "Pesimismu nular, temenmu yang lagi semangat bisa langsung lemes abis denger keluhanmu.", "lucky_item": "Radio rusak yang nyiarnya statis doang"},
        {"message": "Suka ngeluh kurang diperhatiin, pas dikasih perhatian malah kabur karena takut komitmen.", "lucky_item": "Tali layangan putus"},
        {"message": "Daya tahan fisikmu lemah banget, kena AC angin-anginan dikit langsung masuk angin.", "lucky_item": "Koin receh buat kerokan"},
        {"message": "Kamu sangat setia kawan, mau aja nemenin temen patah hati padahal kamu sendiri jomblo ngenes.", "lucky_item": "Kaos partai yang dipake tidur"},
        {"message": "Gampang stres kalau rencananya berantakan. Tarik napas, hembuskan, minum teh anget.", "lucky_item": "Kantong teh celup bekas seduhan ke-3"}
    ],
    "monyet": [
        {"message": "Tukang tipu ulung, jago banget ngeles kalau disuruh traktir pas ulang tahun.", "lucky_item": "Dompet tebal isi struk belanja semua"},
        {"message": "Gak bisa serius 5 menit aja? Bahkan di acara pemakaman kamu sempat-sempatnya bikin jokes bapak-bapak.", "lucky_item": "Topeng badut hidung merah"},
        {"message": "Social butterfly sejati, di semua tongkrongan kamu ada, tapi di daftar absensi kelas kamu gaib.", "lucky_item": "ID card event yang udah kelar tahun lalu"},
        {"message": "Clown of the group, selalu ketawa paling kenceng padahal dalem hati nangis karena cicilan.", "lucky_item": "Air mata palsu di botol tetes mata"},
        {"message": "Suka pamer barang baru, padahal itu juga hasil pinjem dari temen kos sebelah.", "lucky_item": "Jaket branded KW super"},
        {"message": "Otakmu penuh ide cemerlang, sayang implementasinya selalu nol besar alias mager.", "lucky_item": "Buku catatan penuh coretan abstrak"},
        {"message": "Kamu bisa temenan sama siapa aja, saking friendly-nya tukang parkir indomaret hafal namamu.", "lucky_item": "Karcis parkir lecek"},
        {"message": "Suka iseng ngerjain orang, awas kualat ntar nyemplung got pas lagi ketawa-ketawa.", "lucky_item": "Kulit pisang hitam di pinggir jalan"},
        {"message": "Pintar manfaatin situasi. Ada musibah banjir, kamu malah buka jasa angkut motor.", "lucky_item": "Ban dalam bekas buat pelampung"},
        {"message": "Selalu punya cara buat kabur dari masalah. Licin banget kayak belut, bukan monyet.", "lucky_item": "Sabun cuci piring rasa jeruk nipis"},
        {"message": "Perhatianmu gampang teralihkan, ngerjain tugas semenit, scroll Tiktok-nya 3 jam.", "lucky_item": "Timer tomat (Pomodoro) yang gak pernah dipencet"},
        {"message": "Caper banget jadi orang, kalau nggak dapet attention sehari aja langsung meriang.", "lucky_item": "Ring light kecil yang batrenya abis"},
        {"message": "Jago gombal, sayangnya jaring asmaramu terlalu luas sampai gebetan saling kenal.", "lucky_item": "Daftar kontak HP bernama 'Sayang 1', 'Sayang 2'"},
        {"message": "Nggak pernah kehabisan topik obrolan, saking bawelnya supir ojol aja sampai capek nanggepin.", "lucky_item": "Helm ojol bau matahari"},
        {"message": "Terkadang saking pinternya kamu ngerasa paling tahu segalanya. Sok asik lu.", "lucky_item": "Kacamata bolong tanpa kaca"},
        {"message": "Paling jago ngeles dari tanggung jawab kelompok. Pas giliran presentasi tiba-tiba sakit perut.", "lucky_item": "Obat diare isi dua tablet"},
        {"message": "Suka pamer pencapaian, walaupun cuma berhasil bangun pagi sebelum jam 9.", "lucky_item": "Alarm jam beker yang dipukul mati"},
        {"message": "Kamu bisa bertahan hidup di mana aja, asal ada wifi gratis dan colokan.", "lucky_item": "Kabel charger panjangnya 2 meter tapi ngelupas"},
        {"message": "Jangan terlalu sering bohong putih, ntar kebiasaan nipu diri sendiri kalau hidupmu baik-baik aja.", "lucky_item": "Cermin retak"},
        {"message": "Kelakuanmu absurd, kadang ngelakuin hal bodoh cuma biar ada cerita lucu pas nongkrong.", "lucky_item": "Foto aib yang di-print jadi stiker WA"}
    ],
    "ayam": [
        {"message": "Pagi-pagi udah berisik banget, kalah tuh toa masjid sama suaramu yang ngomel soal receh.", "lucky_item": "Jam weker berisik tanpa tombol off"},
        {"message": "Perfeksionis banget, benerin letak buku di meja aja butuh pakai penggaris siku.", "lucky_item": "Penggaris besi yang pinggirannya tajam"},
        {"message": "Control freak abis, semua harus sesuai maumu. Kalau nggak, kamu bakal ngambek 3 hari 3 malam.", "lucky_item": "Remote control yang batrenya di-lakban"},
        {"message": "Sombongnya selangit kalau lagi ngerasa bener, padahal mah sering salah juga.", "lucky_item": "Medali plastik juara lomba makan kerupuk"},
        {"message": "Tukang kritik nomor satu. Apa aja dikomentarin, dari outfit orang sampai rasa air mineral.", "lucky_item": "Kaca pembesar gagang kayu"},
        {"message": "Suka ceramah ngasih petuah bijak, padahal idup sendiri masih berantakan kayak kapal pecah.", "lucky_item": "Buku kutipan Mario Teguh edisi lama"},
        {"message": "Tampilan luar selalu rapi dan on point, tapi kamar kosmu dalemnya kayak sarang penyamun.", "lucky_item": "Sisir yang giginya rontok separuh"},
        {"message": "Paling nggak bisa nerima kritik. Dikasih saran dikit langsung defensif kayak lagi disidang.", "lucky_item": "Tameng mainan plastik Captain America"},
        {"message": "Kerja kerasmu patut dipuji, tapi nggak usah pamer ngeluh lelah di semua platform sosmed juga kali.", "lucky_item": "Status Facebook alay tahun 2011"},
        {"message": "Kamu pikir kamu ayam jago yang ditakuti, padahal orang ngeliat kamu kayak ayam sayur yang berisik.", "lucky_item": "Bumbu kaldu rasa ayam bawang"},
        {"message": "Selalu pengen jadi pusat perhatian. Kalau ada yang cerita sedih, kamu pasti nimpalin 'itu mah mending, aku dong...'.", "lucky_item": "Mic yang suaranya paling kenceng di KTV"},
        {"message": "Standarmu terlalu tinggi, makanya nyari jodoh susahnya ngalahin nyari jarum di tumpukan jerami.", "lucky_item": "Jarum pentul bengkok"},
        {"message": "Kamu rajin bangun pagi, sayangnya cuma buat ngecek siapa yang nge-view IG Story-mu.", "lucky_item": "HP layar retak karena ketiduran"},
        {"message": "Jago debat, nggak peduli topiknya apa pokoknya harus menang, walau ngotot pake argumen ngawur.", "lucky_item": "Palu hakim mainan ketok-ketok"},
        {"message": "Terlalu jujur sampai sering nyakitin hati orang. Filter dikit mulutnya, saringan teh aja punya filter.", "lucky_item": "Saringan teh bolong"},
        {"message": "Suka banget ngatur jadwal orang lain, lu pikir lu asisten pribadi mereka?", "lucky_item": "Kalender meja banyak coretan spidol merah"},
        {"message": "Ketelitianmu tingkat dewa, bisa nemu typo di dokumen 100 halaman dalam 5 menit.", "lucky_item": "Stabilo warna kuning terang nyala"},
        {"message": "Jangan terlalu pelit ngasih pujian ke orang lain, lidahmu nggak bakal kram kok kalau bilang 'keren'.", "lucky_item": "Permen pelega tenggorokan"},
        {"message": "Penampilan itu penting, tapi kalau telat meeting sejam gara-gara nyatok rambut doang mah kebangetan.", "lucky_item": "Catokan rambut yang kabelnya konslet"},
        {"message": "Kepercayaan dirimu tinggi banget, sayangnya kadang nggak didukung sama skill yang mumpuni.", "lucky_item": "Buku 'How to Fake it Until You Make it'"}
    ],
    "anjing": [
        {"message": "Loyal sih, tapi clingy-nya kelewatan. Gebetan balas lama dikit udah mikir dia selingkuh.", "lucky_item": "Tali rantai gantungan kunci"},
        {"message": "Anxiety is your middle name. Mikirin masa depan mulu, padahal besok pagi aja belum tentu bangun gasik.", "lucky_item": "Kantong kertas buat niup nafas pas panik"},
        {"message": "Paranoid banget jadi orang, denger suara kresek malem-malem langsung mikir ada maling atau setan.", "lucky_item": "Senter hp yang batrenya sisa 5%"},
        {"message": "Overprotective sama temen. Temenmu jalan sama orang baru, kamu langsung nge-background check orangnya.", "lucky_item": "Topi detektif bulu-bulu"},
        {"message": "Guilt-tripper sejati. Kalau marah nggak teriak, tapi masang muka melas yang bikin orang merasa jadi penjahat.", "lucky_item": "Foto anak anjing sedih di HP"},
        {"message": "Kamu terlalu baik, rela berkorban buat orang yang bahkan nggak inget hari ulang tahunmu.", "lucky_item": "Kue tart lilinnya patah"},
        {"message": "Setia banget sama mantan, padahal mantannya udah nikah dan punya anak dua. Move on anjir!", "lucky_item": "Surat cinta bau apek di laci"},
        {"message": "Suka gigit balik kalau ngerasa terancam. Galak bener kalau ada yang nyenggol keluargamu.", "lucky_item": "Pelindung gigi petinju"},
        {"message": "Khawatiran mulu, ngecek kunci pintu sampai 5 kali sebelum tidur. Padahal gak ada barang berharga juga di rumah.", "lucky_item": "Gembok sepedah yang karatan"},
        {"message": "Punya radar kebohongan yang kuat. Kamu tahu temenmu bohong, tapi pura-pura percaya biar dia seneng.", "lucky_item": "Mesin detektor kebohongan mainan"},
        {"message": "Kalau udah sayang sama orang, bodohnya nggak ketulungan. Logika ditinggal di stasiun.", "lucky_item": "Tiket kereta hangus"},
        {"message": "Butuh validasi terus-menerus. Dibilang 'Good boy/girl' aja udah senengnya minta ampun.", "lucky_item": "Stiker bintang senyum dari guru TK"},
        {"message": "Nggak bisa nyembunyiin perasaan. Kalau nggak suka sama orang, mukamu langsung berubah kecut kayak mangga muda.", "lucky_item": "Garam buat makan mangga muda"},
        {"message": "Kamu pendengar yang baik, saking baiknya sampai dijadiin tempat pembuangan sampah emosi temen-temenmu.", "lucky_item": "Tempat sampah plastik injak"},
        {"message": "Suka nyari masalah sama sesuatu yang nggak perlu dikhawatirin. Kurang-kurangin overthinking napa.", "lucky_item": "Benang kusut yang susah diurai"},
        {"message": "Kamu rela nemenin temenmu begadang ngerjain tugas, ujung-ujungnya kamu yang ngerjain semuanya.", "lucky_item": "Kopi hitam pahit dingin"},
        {"message": "Gampang ngerasa bersalah kalau nolak permintaan tolong, padahal kamu sendiri lagi repot.", "lucky_item": "Post-it note tulisannya 'Maaf ya'"},
        {"message": "Sering curigaan tanpa alasan. Pas pacar ngasih surprise, malah dituduh abis ngelakuin kesalahan.", "lucky_item": "Kaca pembesar plastik"},
        {"message": "Suka menggonggong hal-hal yang nggak penting di medsos, padahal di real life pendiam banget.", "lucky_item": "Keyboard yang tombol capslock-nya nyangkut"},
        {"message": "Sangat peduli sama orang lain, tapi lupa cara peduli sama diri sendiri. Self-care woy!", "lucky_item": "Masker wajah yang udah kadaluarsa"}
    ],
    "babi": [
        {"message": "Hedonist sejati. Habis gajian langsung makan enak, tengah bulan makan promag.", "lucky_item": "Struk All You Can Eat harga 200rb"},
        {"message": "Mager adalah jalan ninjamu. Kalau bisa berbaring, kenapa harus duduk? Apalagi berdiri.", "lucky_item": "Bantal leher travel bau iler"},
        {"message": "Foodie abis, isi galerimu 90% foto makanan, 10% meme garing.", "lucky_item": "Sendok bebek plastik sisa mie ayam"},
        {"message": "Terlalu baik dan lugu, gampang banget dimanfaatin temen buat bayarin parkir atau gofood.", "lucky_item": "Uang 2 ribu lecek buat tukang parkir"},
        {"message": "Self-indulgent pol. 'Aku pantes dapet self-reward ini' alasanmu tiap kali belanja barang nggak penting.", "lucky_item": "Barang random dari TikTok Shop yang gak kepake"},
        {"message": "Gak suka konflik, milih diam dan ngunyah camilan pas temen-temen lagi berantem.", "lucky_item": "Bungkus ciki rasa jagung bakar"},
        {"message": "Memaafkan itu mudah buatmu, apalagi kalau yang minta maaf bawain martabak manis martabak telor.", "lucky_item": "Karet gelang merah bungkus martabak"},
        {"message": "Punya hati selembut kapas, tapi kalau soal makanan, kamu berubah jadi monster buas yang nggak mau bagi.", "lucky_item": "Garpu somay yang udah bengkok"},
        {"message": "Sering dibilang pemalas, padahal kamu sedang dalam fase 'menghemat energi' untuk hal-hal yang nggak penting.", "lucky_item": "Baterai AA sisa daya 10%"},
        {"message": "Paling jago nikmati hidup. Meskipun uang mepet, tetap bisa ngerasa jadi sultan dengan cara ngopi sachet di teras.", "lucky_item": "Gelas plastik bekas kopi janji jiwa"},
        {"message": "Mudah ditipu sama janji-janji manis, baik janji politikus maupun janji mantan yang minta balikan.", "lucky_item": "Permen karet manis di awal doang"},
        {"message": "Berhenti beli barang lucu yang ujung-ujungnya cuma numpuk debu di pojok kamar.", "lucky_item": "Boneka babi warna pink dekil"},
        {"message": "Kamu selalu ngasih kesempatan kedua, ketiga, keempat... sampai orang bosan bikin salah ke kamu.", "lucky_item": "Penghapus yang udah mengecil banget"},
        {"message": "Suka ngeluh berat badan naik, tapi pas diajak jogging milih narik selimut lagi.", "lucky_item": "Timbangan badan digital baterainya abis"},
        {"message": "Nggak tegaan lihat orang kesusahan, saking nggak tegaannya, kadang rela kelaparan demi kasih makan kucing jalanan.", "lucky_item": "Plastik kresek isi makanan kering kucing"},
        {"message": "Bahagiamu sederhana banget: AC dingin, WiFi kenceng, dan setoples camilan micin.", "lucky_item": "Remote AC nyangkut di suhu 16 derajat"},
        {"message": "Sering overbudget pas belanja bulanan karena tergiur tulisan 'Buy 1 Get 1' padahal gak butuh.", "lucky_item": "Deterjen promo kemasan jumbo"},
        {"message": "Tidurnya nyenyak banget, gempa bumi aja kayaknya dikira cuma getaran kasur biasa.", "lucky_item": "Penyumbat telinga warna oranye"},
        {"message": "Nggak peduli omongan orang. 'Haters gonna hate, potatoes gonna potate' adalah motomu.", "lucky_item": "Kentang goreng dingin pinggiran piring"},
        {"message": "Kebaikan hatimu bakal dibalas dengan hal baik, asal jangan kasih pinjem duit ke teman yang 'lupa' bayar.", "lucky_item": "Celengan ayam dari tanah liat pecah"}
    ]
}
