SHIO_FORTUNE_COOKIE_BANK = {
    "tikus": [
        {"message": "Kamu jago baca peluang, cuma belum jago baca isi chat gebetan. Hari ini balas apa adanya, itu sudah cukup.", "lucky_item": "Screenshot promo expired", "tone": "good"},
        {"message": "Tabungan aman, tapi circle pertemananmu butuh investasi. Keluar rumah dong!", "lucky_item": "Uang koin 200 perak di bawah sofa", "tone": "good"},
        {"message": "Hari ini cocok bikin rencana cadangan nomor 14. Tapi jalanin dulu yang nomor satu, siapa tahu sisanya nggak kepakai.", "lucky_item": "Flashdisk isi tugas makalah 2015", "tone": "good"},
        {"message": "Ada peluang emas hari ini, sayangnya kamu kesiangan karena scroll FYP sampai jam 3 pagi.", "lucky_item": "Alarm jam 6.00 yang di-snooze sampai jam 9.00", "tone": "bad"},
        {"message": "Networking itu bagus, tapi nggak usah SKSD sama kasir minimarket juga kali.", "lucky_item": "Kartu member gym yang nggak pernah dipakai", "tone": "neutral"},
        {"message": "Kesuksesanmu sedekat cicilan PayLater bulan depan. Semangat kerja keras bagai quda (tapi kamu tikus).", "lucky_item": "Struk belanja yang tulisannya udah pudar", "tone": "neutral"},
        {"message": "Banyak yang iri sama kepintaranmu ngeles pas ditagih utang. Bakat terpendam!", "lucky_item": "Kalkulator dengan layar pecah", "tone": "neutral"},
        {"message": "Pikiranmu terlalu kalkulatif, sampai lupa ngitung kapan terakhir kali mandi.", "lucky_item": "Sabun batang yang tinggal seiprit", "tone": "neutral"},
        {"message": "Nggak usah mikirin omongan orang, mereka aja belum tentu mikirin kamu.", "lucky_item": "Spion motor kanan yang kendor", "tone": "good"},
        {"message": "Hidup itu kayak main saham, kadang hijau kadang merah. Kamu? Selalu nungguin dividen turun.", "lucky_item": "Lemari pendingin yang cuma ada es batu", "tone": "neutral"},
        {"message": "Semua orang butuh kamu... buat ngerjain tugas kelompok. Kurang-kurangin jadi tumbal proyek.", "lucky_item": "Grup WA yang cuma di-read", "tone": "bad"},
        {"message": "Berhenti cari gratisan wifi cafe tanpa beli minum. Karma itu nyata.", "lucky_item": "Gelas bekas kopi yang ditinggal di meja", "tone": "bad"},
        {"message": "Keberuntunganmu hari ini: nemu duit 50 ribu di celana cucian. Sayangnya udah hancur kena mesin cuci.", "lucky_item": "Kertas lecek bau deterjen", "tone": "neutral"},
        {"message": "Jangan terlalu perhitungan soal perasaan, nanti gebetanmu di-checkout orang lain.", "lucky_item": "Keranjang oren yang isinya 99+ barang", "tone": "bad"},
        {"message": "Hati-hati ngomongin orang dari belakang, ada yang lagi record dari depan.", "lucky_item": "Earphone sebelah kiri yang mati", "tone": "bad"},
        {"message": "Cinta itu buta, tapi kamu lebih suka pura-pura buta pas diajak jalan biar gak keluar ongkos.", "lucky_item": "Kacamata dengan frame isolasi", "tone": "neutral"},
        {"message": "Rahasia umur panjangmu adalah selalu punya alasan buat kabur dari tanggung jawab.", "lucky_item": "Tombol escape di keyboard yang jebol", "tone": "neutral"},
        {"message": "Ada yang diam-diam memperhatikanmu. Tapi itu cuma admin pinjol.", "lucky_item": "Nomor tak dikenal di riwayat panggilan", "tone": "neutral"},
        {"message": "Coba deh sekali-kali traktir temanmu, biar mereka yakin kamu belum bangkrut.", "lucky_item": "Dompet kulit sintesis yang ngelotok", "tone": "good"},
        {"message": "Otakmu secepat prosesor i9, sayang sinyal wifi-mu sekelas warnet tahun 2005.", "lucky_item": "Kabel LAN yang digigit tikus", "tone": "neutral"},
        {"message": "Insting hematmu lagi selaras sama peluang. Hari ini angka yang kamu hitung semalam ternyata masuk akal.", "lucky_item": "Nota tulis tangan yang masih rapi", "tone": "good"},
        {"message": "Ada orang yang mau bantu tanpa kamu minta duluan. Terima aja, nggak semua bantuan ada tagihannya.", "lucky_item": "Payung lipat pinjaman yang belum balik", "tone": "good"},
        {"message": "Rencana yang kamu simpan diam-diam boleh dikeluarkan hari ini. Timing-nya lagi bagus.", "lucky_item": "Catatan di Notes berjudul 'RAHASIA'", "tone": "good"},
        {"message": "Jaringanmu lebih luas dari yang kamu kira. Coba chat satu nama lama, ada pintu yang kebuka.", "lucky_item": "Kontak HP bernama 'Bapak Kos Lama'", "tone": "good"},
        {"message": "Uang yang kamu tahan-tahan akhirnya ketemu tempat yang benar. Keluarkan tanpa nyesel.", "lucky_item": "Amplop putih yang disimpan di buku", "tone": "good"},
        {"message": "Hari ini gampang kepancing hitung-hitungan yang bikin hubungan renggang. Tahan dulu kalkulatornya.", "lucky_item": "Kalkulator HP yang layarnya buram", "tone": "bad"},
        {"message": "Ada tawaran yang kelihatan untung banget. Justru itu yang perlu kamu baca dua kali.", "lucky_item": "Brosur investasi dari grup WA", "tone": "bad"},
        {"message": "Jangan simpan informasi penting sendirian hari ini. Yang kamu kira aman malah jadi beban.", "lucky_item": "Kunci loker yang lupa nomornya", "tone": "bad"},
        {"message": "Kecepatanmu ambil keputusan lagi nggak sinkron sama keadaan. Pelan sehari nggak bikin rugi.", "lucky_item": "Sandal jepit yang talinya mau putus", "tone": "bad"},
        {"message": "Ada yang ngitung balik kebaikanmu hari ini. Siapkan jawaban, jangan siapkan pembelaan.", "lucky_item": "Struk ATM yang saldonya disensor jari", "tone": "bad"},
    ],
    "kerbau": [
        {"message": "Kerja keras boleh, tipes jangan. Kurangin lembur tanpa bayaran tambahan itu.", "lucky_item": "Obat maag di laci meja kerja", "tone": "bad"},
        {"message": "Tolong ya, dunia nggak bakal hancur kalau kamu sesekali bolos kerja.", "lucky_item": "Surat izin sakit buatan sendiri", "tone": "good"},
        {"message": "Saking kakunya kamu sama rutinitas, robot aja minder lihat jadwal harianmu.", "lucky_item": "Buku agenda tahun 2018 yang masih kosong", "tone": "neutral"},
        {"message": "Keras kepala itu nama tengahmu. Kalau dibilangin, pasti masuk telinga kiri keluar di telinga kiri lagi.", "lucky_item": "Helm SNI tapi belum diklik", "tone": "neutral"},
        {"message": "Bosan itu relatif, tapi ngelihat gaya hidupmu, kayaknya bosan itu absolut.", "lucky_item": "Kopi sachet kadaluarsa", "tone": "neutral"},
        {"message": "Jangan lupa bernapas. Iya tahu kamu lagi fokus ngetik, tapi napas woy!", "lucky_item": "Kipas angin kecil nempel di laptop", "tone": "bad"},
        {"message": "Berhenti ngerasa dunia berpusat pada deadline-mu. Kasihan temanmu yang ngajak nongkrong di-reject terus.", "lucky_item": "Kursi plastik warmindo", "tone": "bad"},
        {"message": "Keteguhan hatimu patut diacungi jempol, sayang jempolnya udah kram ngetik laporan.", "lucky_item": "Salep pegal linu aroma sereh", "tone": "neutral"},
        {"message": "Santai sedikit nggak bikin gaji dipotong. Eh, atau dipotong ya? Ya udah kerja lagi sana.", "lucky_item": "Slip gaji dengan potongan bpjs", "tone": "good"},
        {"message": "Ubah rutinitasmu hari ini. Coba minum kopi pakai tangan kiri sambil kayang.", "lucky_item": "Gelas mug tulisan 'World's Best Employee'", "tone": "good"},
        {"message": "Kamu adalah pilar perusahaan, tapi ingat, pilar juga bisa lumutan kalau nggak dirawat.", "lucky_item": "Sikat WC yang jarang dipakai", "tone": "bad"},
        {"message": "Sifat old-school-mu bikin kamu kayak fosil di tengah kumpulan Gen Z. Coba install TikTok.", "lucky_item": "Nokia 3310 yang batrenya gembung", "tone": "good"},
        {"message": "Terkadang, 'aku nggak tahu' adalah jawaban yang jauh lebih baik daripada ngeyel.", "lucky_item": "Kunci gembok yang karat", "tone": "good"},
        {"message": "Lambat asal selamat, tapi kalau lambat banget, gebetanmu keburu nikah sama orang lain.", "lucky_item": "Undangan pernikahan mantan", "tone": "neutral"},
        {"message": "Kamu bisa diandalkan, terlalu bisa diandalkan sampai orang lain jadi parasit.", "lucky_item": "Payung hitam yang gagangnya patah", "tone": "bad"},
        {"message": "Jangan bawa masalah kerjaan ke mimpi. Cukup bosmu aja yang hantui kamu di grup WA.", "lucky_item": "Bantal bau iler", "tone": "bad"},
        {"message": "Coba pakai baju warna terang hari ini, biar nggak dikira patung di pojok kantor.", "lucky_item": "Kemeja flanel kotak-kotak pudar", "tone": "good"},
        {"message": "Kemampuanmu nyimpan dendam melebihi memori hardisk 2TB. Maafin napa, berat tuh hidup.", "lucky_item": "Hardisk eksternal yang minta diformat", "tone": "bad"},
        {"message": "Kamu kuat menghadapi masalah, tapi lemah pas ditanya 'kapan nikah?'.", "lucky_item": "Brosur KPR rumah subsidi", "tone": "neutral"},
        {"message": "Sesekali berontaklah, hidup ini terlalu singkat untuk jadi anak emas bos terus.", "lucky_item": "Dasi yang kepanjangan", "tone": "good"},
        {"message": "Kerja pelanmu hari ini kebetulan pas sama ritme sekitar. Yang kamu cicil lama mulai kelihatan bentuknya.", "lucky_item": "Mug kopi yang gagangnya sudah retak", "tone": "good"},
        {"message": "Ada yang akhirnya ngeh sama porsi kerjamu. Terima pujiannya tanpa buru-buru bilang 'biasa aja'.", "lucky_item": "Lanyard kantor yang warnanya pudar", "tone": "good"},
        {"message": "Hari yang enak buat mulai kebiasaan baru. Yang berat cuma hari pertama, sisanya kamu jago.", "lucky_item": "Botol minum 2 liter bertanda garis", "tone": "good"},
        {"message": "Rutinitasmu bakal digeser orang lain hari ini. Marah boleh, tapi jangan sampai seharian.", "lucky_item": "Jadwal tempel yang sudah dicoret-coret", "tone": "bad"},
        {"message": "Hari ini gampang ngotot soal hal yang sebenarnya nggak penting. Pilih satu yang beneran layak dibela.", "lucky_item": "Pulpen yang tintanya macet sebelah", "tone": "bad"},
        {"message": "Bebanmu lagi lebih berat dari yang kamu akui. Bilang ke satu orang sebelum badanmu yang bilang duluan.", "lucky_item": "Koyo panas yang tinggal selembar", "tone": "bad"},
    ],
    "macan": [
        {"message": "Halo main character, jangan lupa hari ini bukan cuma tentang kamu doang ya.", "lucky_item": "Cermin seukuran telapak tangan", "tone": "bad"},
        {"message": "Impulsif beli barang di olshop gara-gara packaging-nya lucu? Welcome to the club.", "lucky_item": "Kardus paket isi bubble wrap doang", "tone": "neutral"},
        {"message": "Nggak semua orang harus nurut sama kamu, baginda raja. Turunin dikit egonya.", "lucky_item": "Mahkota kertas ulang tahun fast food", "tone": "bad"},
        {"message": "Hari ini ada satu panggung yang menunggu kamu isi. Tampil boleh, asal kru di belakangmu ikut kebagian.", "lucky_item": "Kacamata hitam di dalam ruangan", "tone": "good"},
        {"message": "Keberanianmu luar biasa, sampai berani ngechat 'P' ke atasan jam 11 malam.", "lucky_item": "HP yang di-airplane mode karena takut balesan", "tone": "neutral"},
        {"message": "Auramu memang mengintimidasi, tapi dompetmu pas akhir bulan mengintimidasi kamu balik.", "lucky_item": "Saldo ATM 45 ribu", "tone": "neutral"},
        {"message": "Berhenti bertindak gegabah, apalagi mutusin pacar cuma karena zodiaknya nggak cocok.", "lucky_item": "Buku ramalan bintang edisi 2012", "tone": "bad"},
        {"message": "Kamu terlahir sebagai pemimpin, sayang anak buahmu pura-pura nggak dengar intruksimu.", "lucky_item": "Toa toa toa toa (rusak)", "tone": "neutral"},
        {"message": "Marah-marah nggak menyelesaikan masalah, tapi bikin tekanan darah naik. Minum air putih sana.", "lucky_item": "Tumbler merk mahal yang isinya air keran", "tone": "bad"},
        {"message": "Energi hari ini: Siap menerkam tantangan hidup. Realita: Ketiduran di sofa depan TV.", "lucky_item": "Remote TV yang baterainya harus dipukul dulu", "tone": "neutral"},
        {"message": "Gaya selangit, duit sulit. Coba kurang-kurangin eksis di cafe hits.", "lucky_item": "Bon kopi harga 80 ribu", "tone": "neutral"},
        {"message": "Orang-orang segan sama kamu, bukan karena respect, tapi takut kena amuk.", "lucky_item": "Tanda 'Awas Anjing Galak' yang dicoret jadi 'Macan Galak'", "tone": "bad"},
        {"message": "Reckless decision of the day: Potong poni sendiri pakai gunting dapur.", "lucky_item": "Gunting yang lengket kena selotip", "tone": "neutral"},
        {"message": "Kamu butuh liburan, tapi liburan butuh uang. Balik kerja sana, rawr!", "lucky_item": "Wallpaper pantai di laptop", "tone": "neutral"},
        {"message": "Jangan terlalu kompetitif, ini cuma main ludo, bukan rebutan tahta kerajaan.", "lucky_item": "Bidak ludo warna merah", "tone": "bad"},
        {"message": "Semua mata tertuju padamu, sayangnya karena kamu pakai baju terbalik.", "lucky_item": "Kaos yang labelnya di leher depan", "tone": "neutral"},
        {"message": "Gaya komandomu efektif, cuma kurang dua kata: 'tolong' dan 'terima kasih'. Pakai hari ini, lihat bedanya.", "lucky_item": "Kamus Bahasa Indonesia untuk pemula", "tone": "good"},
        {"message": "Insting predator-mu tajam pas nyari diskonan 9.9, salut!", "lucky_item": "Sinyal 5G di pojok kamar", "tone": "good"},
        {"message": "Kata-katamu tajam dan itu kekuatanmu. Hari ini pilih satu kalimat yang kamu tahan, hasilnya bakal lebih jauh.", "lucky_item": "Plaster luka gambar Hello Kitty", "tone": "good"},
        {"message": "Berhenti main-main dengan api, nanti rumahmu kebakaran. Maksudnya, jangan nge-flirt pacar orang.", "lucky_item": "Korek gas yang apinya kegedean", "tone": "bad"},
        {"message": "Keberanianmu hari ini ketemu momen yang tepat. Ambil langkah yang kemarin kamu tunda.", "lucky_item": "Sepatu lari yang solnya masih bagus", "tone": "good"},
        {"message": "Orang lagi gampang ikut arahanmu. Pakai buat hal yang bermanfaat, bukan buat menang argumen.", "lucky_item": "Peluit plastik dari acara 17-an", "tone": "good"},
        {"message": "Ada panggung kecil yang jatuh ke tanganmu hari ini. Nggak perlu besar buat jadi berkesan.", "lucky_item": "Mikrofon karaoke yang kabelnya kusut", "tone": "good"},
        {"message": "Energimu lagi penuh dan terarah. Habiskan di satu hal, bukan dibagi ke lima.", "lucky_item": "Power bank yang baru dicharge penuh", "tone": "good"},
        {"message": "Keputusan cepatmu hari ini kemungkinan besar benar. Jalan aja, jangan diulang-ulang mikirnya.", "lucky_item": "Koin logam buat suit", "tone": "good"},
        {"message": "Ada yang diam-diam menghormati caramu bekerja. Hari ini mereka bakal bilang langsung.", "lucky_item": "Sertifikat lomba yang belum dibingkai", "tone": "good"},
        {"message": "Nada suaramu hari ini lebih keras dari yang kamu niatkan. Kirim pesannya besok saja.", "lucky_item": "Headset yang sebelah mati", "tone": "bad"},
        {"message": "Ada yang menantangmu cuma buat lihat reaksimu. Jangan dikasih tontonan.", "lucky_item": "Kaus tim yang nomornya sudah mengelupas", "tone": "bad"},
        {"message": "Hari ini gampang ambil risiko yang bukan porsimu. Cek dulu siapa yang ikut kena kalau meleset.", "lucky_item": "Helm yang busanya sudah tipis", "tone": "bad"},
    ],
    "kelinci": [
        {"message": "Berhentilah bilang 'aku nggak apa-apa' sambil banting pintu lemari.", "lucky_item": "Gagang pintu lemari yang copot", "tone": "bad"},
        {"message": "Passive-aggressive mu itu lho, lebih menusuk daripada jarum suntik dokter gigi.", "lucky_item": "Status WA yang di-hide dari semua orang kecuali satu orang", "tone": "bad"},
        {"message": "People pleaser sejati, sampai rela makan bubur diaduk demi ngikutin kata teman.", "lucky_item": "Sendok plastik bekas bubur ayam", "tone": "neutral"},
        {"message": "Aesthetics over everything, biarpun dompet menangis melihat harga cafe yang instagramable itu.", "lucky_item": "Tanaman plastik monstera berdebu", "tone": "neutral"},
        {"message": "Terlalu baik sampai gampang ditipu. Hati-hati sama teman yang mau pinjam 100.", "lucky_item": "Bukti transfer m-banking yang udah kedaluwarsa", "tone": "bad"},
        {"message": "Dibalik wajah manismu, tersimpan rencana pembunuhan... nyamuk yang dari tadi di telinga.", "lucky_item": "Rakit nyamuk listrik baterai soak", "tone": "neutral"},
        {"message": "Fake nice-mu level dewa. Pura-pura senyum padahal di dalem hati udah ngabsen isi kebun binatang.", "lucky_item": "Masker kain dua lapis buat nutupin bibir manyun", "tone": "neutral"},
        {"message": "Saking penakutnya, nonton film horor aja kamu tutup mata dari opening sampai credit title.", "lucky_item": "Selimut tebal bau kapur barus", "tone": "neutral"},
        {"message": "Belajar bilang 'TIDAK' dong, masa disuruh piket terus tiap hari padahal bukan jadwalmu.", "lucky_item": "Sapu ijuk yang gagangnya bengkok", "tone": "bad"},
        {"message": "Ekspektasimu soal cinta kayak drakor, pantesan realitanya jomblo melulu.", "lucky_item": "Bantal guling yang keseringan dipeluk", "tone": "neutral"},
        {"message": "Suka menghindari konflik, ujung-ujungnya konflik itu ngendap jadi penyakit lambung.", "lucky_item": "Antasida sirup rasa mint", "tone": "bad"},
        {"message": "Outfit hari ini: pastel aesthetic cottagecore. Mood hari ini: ingin resign dari bumi.", "lucky_item": "Jepit rambut pita warna krem", "tone": "neutral"},
        {"message": "Kamu imut sih, tapi kalau lagi ngambek seremnya ngalahin debt collector.", "lucky_item": "Pesan WA ditarik 5 kali", "tone": "neutral"},
        {"message": "Terlalu banyak mikirin omongan orang, coba mikirin cicilan motor sesekali.", "lucky_item": "Buku garansi motor di bawah jok", "tone": "bad"},
        {"message": "Seni ngode lewat playlist-mu belum nyampe, gebetanmu ternyata tim dangdut koplo. Bilang langsung aja hari ini.", "lucky_item": "Headset kabel yang sebelah kanan mati", "tone": "good"},
        {"message": "Kamu tahu lebih banyak dari yang kamu tunjukkan. Hari ini pakai itu buat nolong satu orang, bukan buat bahan obrolan.", "lucky_item": "Screenshot chat grup gibah rahasia", "tone": "good"},
        {"message": "Kamu butuh lebih banyak kalsium biar tulangmu kuat nahan beban hidup sebagai orang gak enakan.", "lucky_item": "Kotak susu UHT ukuran 125ml", "tone": "neutral"},
        {"message": "Kelembutan hatimu sering dimanfaatin. Coba agak ngegas dikit, pelan aja 'gas'.", "lucky_item": "Klakson motor matic yang suaranya cempreng", "tone": "good"},
        {"message": "Banyak yang suka sama kamu, sayang kamu terlalu sibuk nyari kekurangan diri sendiri.", "lucky_item": "Kaca wastafel yang buram kena uap air", "tone": "good"},
        {"message": "Kelihatan lemah, tapi kalau di jalan raya bawa motor matic, nyalimu lebih besar dari truk fuso.", "lucky_item": "Lampu sein kiri tapi belok kanan", "tone": "good"},
        {"message": "Kehalusanmu lagi jadi kelebihan, bukan kelemahan. Ada situasi runyam yang cuma kamu yang bisa cairkan.", "lucky_item": "Lilin aromaterapi yang tinggal separuh", "tone": "good"},
        {"message": "Hari yang enak buat ngomong jujur. Orangnya lagi siap dengerin, beneran.", "lucky_item": "Kartu ucapan yang belum sempat dikasih", "tone": "good"},
        {"message": "Selera baikmu kepakai hari ini. Ada yang minta pendapatmu dan beneran mau nurut.", "lucky_item": "Swatch cat tembok warna sage", "tone": "good"},
        {"message": "Kesabaranmu kemarin mulai ada hasilnya. Nggak perlu diumumkan, kamu tahu sendiri.", "lucky_item": "Tanaman kecil yang akhirnya tumbuh tunas", "tone": "good"},
        {"message": "Ada orang yang hadir buat kamu hari ini tanpa diminta. Nikmati, jangan buru-buru cari balasannya.", "lucky_item": "Termos kecil isi teh hangat", "tone": "good"},
        {"message": "Hari ini gampang bilang iya padahal berat. Latihan nolak satu, cukup satu.", "lucky_item": "Sticky note bertulisan 'NANTI DULU'", "tone": "bad"},
        {"message": "Ada yang bakal mancing kamu biar ngalah lagi. Kali ini nggak usah.", "lucky_item": "Karet gelang yang sudah keras", "tone": "bad"},
        {"message": "Perasaanmu lagi tipis, dan itu wajar. Jangan ambil keputusan besar sambil kesel.", "lucky_item": "Bantal sofa yang bentuknya penyok", "tone": "bad"},
        {"message": "Suasana lagi gampang salah paham. Tulis maksudmu, jangan andalkan isyarat.", "lucky_item": "Pensil yang ujungnya patah", "tone": "bad"},
    ],
    "naga": [
        {"message": "Naga memang makhluk mitologi, pantesan kesempurnaanmu cuma fiktif belaka.", "lucky_item": "Buku dongeng anak-anak sobek", "tone": "bad"},
        {"message": "Egomu lebih tinggi dari gedung Burj Khalifa. Coba deh sesekali turun ke bumi.", "lucky_item": "Tiket lift rusak", "tone": "bad"},
        {"message": "Main character syndrome-mu lagi kumat ya? Ingat, nggak semua orang lagi nontonin kamu.", "lucky_item": "Kamera CCTV palsu di sudut ruang", "tone": "bad"},
        {"message": "Selalu merasa paling benar, padahal kemarin nyasar pake Google Maps padahal rutenya cuma lurus.", "lucky_item": "Tanda panah jalan yang dicoret-coret", "tone": "neutral"},
        {"message": "Kharisma luar biasa, tapi napas nagamu kalau pagi tolong dikondisikan.", "lucky_item": "Obat kumur rasa pepermint kuat", "tone": "neutral"},
        {"message": "Kamu suka merintah orang, sayangnya kamu bukan bos di sini. Turunkan telunjukmu.", "lucky_item": "Stempel 'Rejected'", "tone": "bad"},
        {"message": "Percaya diri itu bagus, narsis itu penyakit. Kamu ada di perbatasan keduanya.", "lucky_item": "Cermin rias dengan lampu LED super terang", "tone": "bad"},
        {"message": "Semua orang tahu kamu hebat, nggak usah diulang-ulang ceritanya tiap kumpul.", "lucky_item": "Kaset pita rusak karena kusut", "tone": "bad"},
        {"message": "Kamu dilahirkan untuk memimpin... memimpin antrean seblak di depan perumahan.", "lucky_item": "Nomor antrean 99", "tone": "neutral"},
        {"message": "Terkadang, pura-pura salah itu bisa bikin kamu punya teman lho.", "lucky_item": "Penghapus karet warna hitam", "tone": "good"},
        {"message": "Ambisi setinggi langit, realita: cuma sanggup rebahan sambil mikirin plan A sampai Z.", "lucky_item": "Kasur lantai yang tipis", "tone": "neutral"},
        {"message": "Bakat terpendammu adalah ngasih saran yang bagus, tapi nggak pernah dipraktekin sendiri.", "lucky_item": "Buku self-help halaman pertama doang yang dibaca", "tone": "neutral"},
        {"message": "Berhentilah flexing prestasi masa lalu, itu piala lomba RT waktu kamu umur 5 tahun, bro.", "lucky_item": "Piala plastik warna emas ngelupas", "tone": "bad"},
        {"message": "Gengsi kegedean bikin kamu nahan lapar cuma karena malu bawa bekal kotak makan pink.", "lucky_item": "Tupperware mamah yang dilarang hilang", "tone": "neutral"},
        {"message": "Aura nagamu lagi redup, mungkin kurang makan gorengan abang-abang pinggir jalan.", "lucky_item": "Bungkus kertas koran bekas gorengan", "tone": "neutral"},
        {"message": "Auramu sudah kelihatan tanpa perlu diperjelas. Hari ini diam sebentar, lihat siapa yang mendekat sendiri.", "lucky_item": "Toa masjid yang lagi feedback suara", "tone": "good"},
        {"message": "Berdebat sama kamu itu kayak ngomong sama tembok. Tembok yang bisa nyembur api.", "lucky_item": "Bata merah yang belum disemen", "tone": "neutral"},
        {"message": "Jangan terlalu keras sama diri sendiri, nanti cepet tua. Egomu butuh istirahat.", "lucky_item": "Krim anti-aging harga murah", "tone": "good"},
        {"message": "Kamu nggak perlu persetujuan semua orang, cukup persetujuan dari saldo rekeningmu.", "lucky_item": "Notifikasi m-banking 'Saldo Tidak Cukup'", "tone": "good"},
        {"message": "Kamu terbiasa memimpin, tapi hari ini coba jadi yang nanya duluan. Lingkaranmu bakal lebih betah.", "lucky_item": "Tisu toilet gulung setengah basah", "tone": "good"},
        {"message": "Auramu lagi bekerja tanpa perlu diusahakan. Hari ini cocok buat presentasi atau minta sesuatu.", "lucky_item": "Jas yang kancingnya masih lengkap", "tone": "good"},
        {"message": "Ada kesempatan yang datang karena reputasimu, bukan karena kamu ngejar. Ambil.", "lucky_item": "Kartu nama yang sudah lecek di dompet", "tone": "good"},
        {"message": "Hari yang bagus buat mendelegasikan. Orang lagi mau kerja buat kamu tanpa disuruh dua kali.", "lucky_item": "Papan tulis kecil dan spidol kering", "tone": "good"},
        {"message": "Visi besarmu hari ini kedengarannya masuk akal buat orang lain. Ceritakan sekali lagi.", "lucky_item": "Sketsa rencana di kertas HVS bekas", "tone": "good"},
        {"message": "Ada yang berterima kasih ke kamu hari ini atas hal yang kamu sendiri sudah lupa.", "lucky_item": "Foto lama di galeri yang tiba-tiba muncul", "tone": "good"},
        {"message": "Hari ini gengsimu bakal diuji sama hal kecil. Menang di situ nggak ada hadiahnya.", "lucky_item": "Kacamata hitam yang engselnya goyang", "tone": "bad"},
        {"message": "Ada yang bakal mengoreksimu di depan orang. Jawab besok, bukan sekarang.", "lucky_item": "Map plastik yang sudutnya sobek", "tone": "bad"},
        {"message": "Rencanamu lagi lebih besar dari tenaga yang tersedia. Potong jadi tiga, kerjakan yang pertama.", "lucky_item": "Notebook tebal yang baru terisi dua halaman", "tone": "bad"},
    ],
    "ular": [
        {"message": "Misterius banget kayak password wifi tetangga. Buka dikit dong hatinya.", "lucky_item": "Router wifi tanpa antena", "tone": "bad"},
        {"message": "Kamu bukan detektif, berhentilah stalking mantan dari akun fake.", "lucky_item": "Akun bodong IG foto profil telur", "tone": "bad"},
        {"message": "Terlalu pinter manipulasi, sampai bingung sendiri sebenarnya kamu lagi sedih apa pura-pura sedih.", "lucky_item": "Bawang merah utuh", "tone": "bad"},
        {"message": "Secretive itu keren, tapi kalau alamat kosan aja nggak mau ngasih tau temen, itu aneh.", "lucky_item": "Gembok koper angka 000", "tone": "neutral"},
        {"message": "Kamu terlatih curiga sampai ke diri sendiri. Hari ini pilih satu orang, lalu percaya satu hal kecil dulu.", "lucky_item": "Kaca spion retak seribu", "tone": "good"},
        {"message": "Materialistis itu nggak salah, yang salah kalau nggak ada modalnya.", "lucky_item": "Dompet kosong banyak resletingnya", "tone": "neutral"},
        {"message": "Tatapanmu dingin dan tajam, persis tatapan dosen penguji pas sidang skripsi.", "lucky_item": "Laser pointer presentasi mati", "tone": "neutral"},
        {"message": "Hati-hati, ntar kepatuk omongan sendiri. Kemarin bilang nggak suka, eh sekarang nempel.", "lucky_item": "Lem super glue yang nempel di tangan", "tone": "bad"},
        {"message": "Jago nyimpen rahasia orang, tapi ember banget kalau udah ngomongin musuh bebuyutan.", "lucky_item": "Ember bocor ditambal lakban", "tone": "neutral"},
        {"message": "Kamu punya indra keenam ya? Pintar banget nyium gelagat red flag orang dari jarak 10 km.", "lucky_item": "Bendera merah sobek-sobek", "tone": "good"},
        {"message": "Pesonamu kuat, cuma suaranya berubah tajam pas cemburu. Hari ini tanya dulu sebelum menyimpulkan.", "lucky_item": "Botol obat nyamuk semprot", "tone": "good"},
        {"message": "Orang sering salah baca caramu, padahal kamu cuma efisien. Hari ini jelaskan prosesnya, tuduhannya hilang sendiri.", "lucky_item": "Jalan pintas ke toilet yang dikunci", "tone": "good"},
        {"message": "Jangan terlalu tertutup, ntar jamuran lho di dalem situ sendirian.", "lucky_item": "Kapur barus yang mengecil", "tone": "bad"},
        {"message": "Bakat acting-mu patut dapet piala Oscar, apalagi pas pura-pura lupa bayar patungan makanan.", "lucky_item": "Kalkulator di HP yang aplikasinya disembunyikan", "tone": "neutral"},
        {"message": "Pendendam banget, dicubit dikit balasnya banting meja. Chill dikit napa.", "lucky_item": "Buku catatan daftar musuh (Death Note KW)", "tone": "bad"},
        {"message": "Kamu selalu punya hidden agenda. Bahkan pas ngajak nongkrong doang ternyata ada udang di balik batu.", "lucky_item": "Batu kali lumutan", "tone": "neutral"},
        {"message": "Pesona ular emang mematikan. Sekali lirik, orang langsung serasa digendam buat nraktir kamu.", "lucky_item": "Kacamata hipnotis mainan", "tone": "good"},
        {"message": "Kurangin sifat suudzonnya, nggak semua orang mau nikam kamu dari belakang kok.", "lucky_item": "Gunting kuku yang tumpul", "tone": "bad"},
        {"message": "Elegan dan berkelas di luar, tapi di kamar dengerinnya DJ remix jedag-jedug.", "lucky_item": "Speaker bluetooth kelap-kelip lampu RGB", "tone": "neutral"},
        {"message": "Sikap dinginmu itu mekanisme pertahanan atau emang dari sononya nggak punya hati?", "lucky_item": "Es batu yang udah mencair di gelas", "tone": "bad"},
        {"message": "Bacaanmu soal orang lagi tajam dan tepat. Pakai buat nolong, bukan buat jaga jarak.", "lucky_item": "Kacamata baca yang lensanya bersih", "tone": "good"},
        {"message": "Hari yang enak buat menutup kesepakatan. Kamu lebih siap dari lawan bicaramu.", "lucky_item": "Pulpen hitam yang tintanya masih penuh", "tone": "good"},
        {"message": "Kesabaranmu nunggu akhirnya kebayar hari ini. Momen yang kamu tunggu akhirnya datang.", "lucky_item": "Jam tangan yang baterainya baru diganti", "tone": "good"},
        {"message": "Ada yang membuka diri ke kamu duluan. Balas dengan porsi yang sama, jangan cuma nyimak.", "lucky_item": "Buku catatan bersampul kulit imitasi", "tone": "good"},
        {"message": "Strategi yang kamu susun diam-diam hari ini tinggal dijalankan. Nggak perlu diumumkan.", "lucky_item": "Peta lipat yang sudah usang", "tone": "good"},
        {"message": "Hari ini gampang menyimpulkan sendiri dari potongan informasi. Tanya dulu, hemat tenaga.", "lucky_item": "Kartu memori yang datanya korup", "tone": "bad"},
        {"message": "Ada yang menyinggungmu tanpa sadar. Bahas sekarang sebelum kamu simpan setahun.", "lucky_item": "Gembok kecil yang kuncinya hilang", "tone": "bad"},
    ],
    "kuda": [
        {"message": "Berhenti lari dari tanggung jawab, kakimu pasti capek biarpun kamu kuda.", "lucky_item": "Sepatu lari solnya bolong", "tone": "bad"},
        {"message": "FOMO banget jadi orang, ada event dikit wajib dateng, padahal di sana cuma main HP.", "lucky_item": "Baterai powerbank sisa 1 strip", "tone": "neutral"},
        {"message": "Sabar dikit kenapa sih? Mie instan aja butuh 3 menit buat matang, apalagi kesuksesan.", "lucky_item": "Mie instan yang direbus kelamaan jadi lembek", "tone": "bad"},
        {"message": "Gak sabaran, commitment phobic, dan bosenan. Combo maut yang bikin kamu jomblo terus.", "lucky_item": "Cincin plastik hadiah ciki", "tone": "bad"},
        {"message": "Energi kamu berlebih banget, mending disalurin buat ngepel lantai rumah sana.", "lucky_item": "Kain pel dekil yang baunya apek", "tone": "neutral"},
        {"message": "Tukang petualang, tapi tiap minggu rutenya cuma kasur-kamar mandi-dapur.", "lucky_item": "Peta kota yang jadul", "tone": "neutral"},
        {"message": "Diajak jalan responsnya sepersekian detik, disuruh bikin laporan tiba-tiba sinyal hilang. Kerjain 20 menit dulu, habis itu bebas.", "lucky_item": "Kunci motor yang gantungannya copot", "tone": "good"},
        {"message": "Selalu butuh kebebasan, sampai lupa kalau kebebasan tanpa uang itu namanya gelandangan.", "lucky_item": "Dompet kosong yang dipake kipasan", "tone": "bad"},
        {"message": "Gampang bosen sama pacar, coba deh pacaran sama roller coaster biar adrenalinmu terjaga.", "lucky_item": "Tiket wahana pasar malam kucel", "tone": "bad"},
        {"message": "Kamu pikir kamu kuda liar, padahal kamu cuma kuda lumping yang butuh sesajen indomie.", "lucky_item": "Pecahan beling dari piring tetangga", "tone": "neutral"},
        {"message": "Berani ambil resiko tinggi, padahal asuransi kesehatan aja nunggak 3 bulan.", "lucky_item": "Kartu BPJS yang patah", "tone": "bad"},
        {"message": "Suka nyerobot antrean, untung wajahmu cukup kasihan untuk dimaafkan.", "lucky_item": "Tanda 'Harap Antre' yang bengkok", "tone": "bad"},
        {"message": "Jangan kebanyakan janji kalau nggak bisa nepatin. Besok-besok janjinya dipakein meterai.", "lucky_item": "Meterai 10.000 yang udah dicoret", "tone": "bad"},
        {"message": "Saking cepatnya ngomong, orang ngira kamu lagi ngerap padahal lagi presentasi.", "lucky_item": "Mic karaoke bluetooth yang suaranya kresek-kresek", "tone": "neutral"},
        {"message": "Terlalu independen sampai lupa gimana caranya minta tolong pas ban motor bocor.", "lucky_item": "Pompa ban manual yang berat ditarik", "tone": "bad"},
        {"message": "Kamu nggak bisa diam di satu tempat, pantesan posisi tidurmu muter 180 derajat tiap malam.", "lucky_item": "Sprei kasur yang selalu lepas ujungnya", "tone": "neutral"},
        {"message": "Niatnya pengen keliling dunia, realitanya keliling nyari promo GrabFood doang.", "lucky_item": "Aplikasi ojol yang minta update", "tone": "neutral"},
        {"message": "Kuda emang kuat lari, tapi hatimu rapuh banget pas dicuekin gebetan seharian.", "lucky_item": "Notifikasi 'Last seen today at 09.00'", "tone": "neutral"},
        {"message": "Spontanitas itu asik, tapi jangan spontan resign pas lagi gak punya tabungan dong.", "lucky_item": "Kardus indomie buat nyimpen barang kantor", "tone": "bad"},
        {"message": "Kurang-kurangin kebiasaan ninggalin teman pas lagi susah, karma tuh ntar nendang balik.", "lucky_item": "Sepatu kuda yang karetnya lepas", "tone": "bad"},
        {"message": "Energimu hari ini sinkron sama yang dibutuhkan sekitar. Yang kamu mulai kemungkinan besar jalan.", "lucky_item": "Tali sepatu yang baru diganti", "tone": "good"},
        {"message": "Ajakan yang datang hari ini layak kamu terima. Bukan buang waktu, itu pintu.", "lucky_item": "Tiket konser lama yang masih disimpan", "tone": "good"},
        {"message": "Hari yang bagus buat menutup satu hal yang menggantung. Rasanya bakal jauh lebih lega dari dugaanmu.", "lucky_item": "Kunci motor dengan gantungan baru", "tone": "good"},
        {"message": "Kecepatanmu lagi jadi kelebihan. Ada yang butuh diselesaikan hari ini juga, dan itu kamu.", "lucky_item": "Botol air 600ml yang tinggal separuh", "tone": "good"},
        {"message": "Ada kabar dari jauh yang bikin harimu ringan. Balas hari ini juga.", "lucky_item": "Kartu pos yang belum ditempel perangko", "tone": "good"},
        {"message": "Rasa bosanmu hari ini malah nunjukin arah yang tepat. Ikuti, tapi rapikan yang lama dulu.", "lucky_item": "Ransel yang resletingnya baru diperbaiki", "tone": "good"},
        {"message": "Orang lagi gampang percaya sama semangatmu. Pakai buat ngajak, bukan buat janji.", "lucky_item": "Kaos lari yang warnanya mencolok", "tone": "good"},
        {"message": "Hari yang enak buat olahraga atau jalan jauh. Badanmu lagi mau diajak kerja sama.", "lucky_item": "Handuk kecil yang selalu di tas", "tone": "good"},
        {"message": "Yang kamu tunda seminggu ternyata cuma butuh dua puluh menit. Buktikan hari ini.", "lucky_item": "Timer dapur berbentuk telur", "tone": "good"},
    ],
    "kambing": [
        {"message": "Manja boleh, tapi jangan nyusahin orang dong. Minta suapin sekalian?", "lucky_item": "Bib alas makan bayi motif beruang", "tone": "bad"},
        {"message": "Chat 'Wkwk' dari crush kamu bedah semalaman, padahal itu cuma basa-basi. Tidur dulu, besok kirim pertanyaan yang jelas.", "lucky_item": "Bantal yang basah karena air mata buaya", "tone": "good"},
        {"message": "Hari ini gampang terasa semesta lagi nggak berpihak. Kerjakan satu hal kecil dulu, biasanya perasaannya ikut berubah.", "lucky_item": "Skenario sinetron azab", "tone": "good"},
        {"message": "Ditegur soal hal kecil rasanya nyesek sampai ke toilet. Tarik napas, benerin font-nya, lalu lanjut.", "lucky_item": "Tisu gulung toilet yang abis", "tone": "good"},
        {"message": "Artistik dan punya selera tinggi, sayangnya gaji masih standar UMR pas-pasan.", "lucky_item": "Palet lukis bekas yang catnya mengering", "tone": "neutral"},
        {"message": "Indecisive banget, milih menu Gofood aja butuh 2 jam, keburu tokonya tutup.", "lucky_item": "Menu warteg yang lecek", "tone": "bad"},
        {"message": "Bayanganmu soal hidup indah detail banget, tinggal satu langkah kecil pagi ini yang belum dikerjain.", "lucky_item": "Gayung bolong di kamar mandi", "tone": "good"},
        {"message": "Nanya ke sepuluh teman, ujungnya balik ke pilihan pertamamu juga. Mungkin nalurimu memang sudah benar dari awal.", "lucky_item": "Coin 500 perak buat lempar undian", "tone": "good"},
        {"message": "Pemaafmu luas, dan ada yang terbiasa memanfaatkannya. Hari ini pakai maaf itu buat dirimu sendiri dulu.", "lucky_item": "Kacamata kuda buat nutupin kenyataan", "tone": "good"},
        {"message": "Kamu hafal cerita banyak orang. Hari ini simpan satu yang paling seru, itu bentuk kesetiaan yang jarang dilihat.", "lucky_item": "Gelas kopi setengah sisa", "tone": "good"},
        {"message": "Sensitif banget, awan mendung dikit aja kamu udah mikir alam semesta lagi berduka.", "lucky_item": "Payung motif bunga yang rusak rangkanya", "tone": "neutral"},
        {"message": "Bergantung sama orang lain itu keahlianmu. Belajar mandiri dikit, setidaknya potong kuku sendiri.", "lucky_item": "Gunting kuku tumpul", "tone": "bad"},
        {"message": "Kebaikan hatimu sering dimanfaatkan tukang utang. Belajar nagih dong sesekali.", "lucky_item": "Catatan utang di buku kas kecil", "tone": "bad"},
        {"message": "Kamu suka hal-hal berbau alam, tapi pas diajak naik gunung malah sambat capek di pos pertama.", "lucky_item": "Sandal jepit gunung tali putus", "tone": "neutral"},
        {"message": "Kambing emang suka makan rumput, tapi jangan gampang termakan omongan manis buaya darat dong.", "lucky_item": "Rumput sintetis sisa dekor", "tone": "bad"},
        {"message": "Pesimismu nular, temenmu yang lagi semangat bisa langsung lemes abis denger keluhanmu.", "lucky_item": "Radio rusak yang nyiarnya statis doang", "tone": "bad"},
        {"message": "Suka ngeluh kurang diperhatiin, pas dikasih perhatian malah kabur karena takut komitmen.", "lucky_item": "Tali layangan putus", "tone": "neutral"},
        {"message": "Daya tahan fisikmu lemah banget, kena AC angin-anginan dikit langsung masuk angin.", "lucky_item": "Koin receh buat kerokan", "tone": "neutral"},
        {"message": "Kamu sangat setia kawan, mau aja nemenin temen patah hati padahal kamu sendiri jomblo ngenes.", "lucky_item": "Kaos partai yang dipake tidur", "tone": "good"},
        {"message": "Rencana berantakan bikin dadamu sesak duluan. Tarik napas, minum teh anget, susun ulang satu per satu.", "lucky_item": "Kantong teh celup bekas seduhan ke-3", "tone": "good"},
        {"message": "Kepekaanmu hari ini kepakai buat hal yang benar. Ada yang butuh didengar dan kamu orangnya.", "lucky_item": "Selimut tipis yang selalu dibawa", "tone": "good"},
        {"message": "Hari ini gampang ngerasa dilupakan padahal nggak. Tanya langsung sebelum baper berkembang.", "lucky_item": "Gantungan kunci yang catnya mengelupas", "tone": "bad"},
        {"message": "Ada keputusan yang nggak bisa kamu lempar ke orang lain hari ini. Ambil, sekecil apa pun.", "lucky_item": "Koin buat suit yang selalu kalah", "tone": "bad"},
        {"message": "Suasana hatimu lagi gampang dibawa cuaca. Jangan kirim pesan panjang malam ini.", "lucky_item": "Payung transparan yang gagangnya bengkok", "tone": "bad"},
        {"message": "Ada yang minta tolong lagi hari ini. Boleh bantu, asal kamu sebut batasnya di awal.", "lucky_item": "Kalender meja yang belum dibalik", "tone": "bad"},
    ],
    "monyet": [
        {"message": "Tukang tipu ulung, jago banget ngeles kalau disuruh traktir pas ulang tahun.", "lucky_item": "Dompet tebal isi struk belanja semua", "tone": "bad"},
        {"message": "Gak bisa serius 5 menit aja? Bahkan di acara pemakaman kamu sempat-sempatnya bikin jokes bapak-bapak.", "lucky_item": "Topeng badut hidung merah", "tone": "bad"},
        {"message": "Social butterfly sejati, di semua tongkrongan kamu ada, tapi di daftar absensi kelas kamu gaib.", "lucky_item": "ID card event yang udah kelar tahun lalu", "tone": "neutral"},
        {"message": "Clown of the group, selalu ketawa paling kenceng padahal dalem hati nangis karena cicilan.", "lucky_item": "Air mata palsu di botol tetes mata", "tone": "neutral"},
        {"message": "Suka pamer barang baru, padahal itu juga hasil pinjem dari temen kos sebelah.", "lucky_item": "Jaket branded KW super", "tone": "bad"},
        {"message": "Otakmu penuh ide cemerlang, sayang implementasinya selalu nol besar alias mager.", "lucky_item": "Buku catatan penuh coretan abstrak", "tone": "bad"},
        {"message": "Kamu bisa temenan sama siapa aja, saking friendly-nya tukang parkir indomaret hafal namamu.", "lucky_item": "Karcis parkir lecek", "tone": "good"},
        {"message": "Suka iseng ngerjain orang, awas kualat ntar nyemplung got pas lagi ketawa-ketawa.", "lucky_item": "Kulit pisang hitam di pinggir jalan", "tone": "bad"},
        {"message": "Pintar manfaatin situasi. Ada musibah banjir, kamu malah buka jasa angkut motor.", "lucky_item": "Ban dalam bekas buat pelampung", "tone": "neutral"},
        {"message": "Selalu punya cara buat kabur dari masalah. Licin banget kayak belut, bukan monyet.", "lucky_item": "Sabun cuci piring rasa jeruk nipis", "tone": "neutral"},
        {"message": "Perhatianmu gampang teralihkan, ngerjain tugas semenit, scroll Tiktok-nya 3 jam.", "lucky_item": "Timer tomat (Pomodoro) yang gak pernah dipencet", "tone": "bad"},
        {"message": "Perhatian orang bikin harimu hidup, dan itu wajar. Hari ini kasih perhatian duluan, balasannya lebih awet.", "lucky_item": "Ring light kecil yang batrenya abis", "tone": "good"},
        {"message": "Jago gombal, sayangnya jaring asmaramu terlalu luas sampai gebetan saling kenal.", "lucky_item": "Daftar kontak HP bernama 'Sayang 1', 'Sayang 2'", "tone": "neutral"},
        {"message": "Nggak pernah kehabisan topik obrolan, saking bawelnya supir ojol aja sampai capek nanggepin.", "lucky_item": "Helm ojol bau matahari", "tone": "good"},
        {"message": "Kamu cepat nangkap, sampai sering nyelesaiin kalimat orang. Hari ini tahan dulu, dengerin sampai habis.", "lucky_item": "Kacamata bolong tanpa kaca", "tone": "good"},
        {"message": "Paling jago ngeles dari tanggung jawab kelompok. Pas giliran presentasi tiba-tiba sakit perut.", "lucky_item": "Obat diare isi dua tablet", "tone": "bad"},
        {"message": "Suka pamer pencapaian, walaupun cuma berhasil bangun pagi sebelum jam 9.", "lucky_item": "Alarm jam beker yang dipukul mati", "tone": "neutral"},
        {"message": "Kamu bisa bertahan hidup di mana aja, asal ada wifi gratis dan colokan.", "lucky_item": "Kabel charger panjangnya 2 meter tapi ngelupas", "tone": "good"},
        {"message": "Kamu pandai memoles cerita biar enak didengar. Hari ini ceritakan satu hal apa adanya, ternyata tetap menarik.", "lucky_item": "Cermin retak", "tone": "good"},
        {"message": "Kamu rela ngelakuin hal absurd demi satu cerita lucu pas nongkrong. Simpan satu buat hari ini, pasti kepakai.", "lucky_item": "Foto aib yang di-print jadi stiker WA", "tone": "good"},
        {"message": "Akalmu hari ini nemu jalan yang orang lain nggak lihat. Bagikan, jangan disimpan buat pamer.", "lucky_item": "Obeng mini dari toko serba lima ribu", "tone": "good"},
        {"message": "Hari yang enak buat ketemu orang baru. Satu kenalan hari ini bakal kepakai bulan depan.", "lucky_item": "Stiker laptop yang sudutnya mulai lepas", "tone": "good"},
        {"message": "Yang kamu anggap iseng ternyata dihargai orang. Lanjutkan, itu bukan sekadar lucu-lucuan.", "lucky_item": "Gitar ukulele yang senarnya kurang satu", "tone": "good"},
        {"message": "Hari ini gampang menganggap semua bisa diakali. Ada satu yang memang harus dijalani lurus.", "lucky_item": "Kabel charger yang sudah dililit isolasi", "tone": "bad"},
        {"message": "Candaan yang biasanya aman hari ini bisa salah sasaran. Baca ruangan dulu.", "lucky_item": "Kacamata badut dari kado ulang tahun", "tone": "bad"},
        {"message": "Ada janji lama yang ditagih hari ini. Jawab jujur, alasan kreatifmu sudah ketahuan polanya.", "lucky_item": "Buku agenda yang halamannya kosong semua", "tone": "bad"},
    ],
    "ayam": [
        {"message": "Pagi-pagi udah berisik banget, kalah tuh toa masjid sama suaramu yang ngomel soal receh.", "lucky_item": "Jam weker berisik tanpa tombol off", "tone": "neutral"},
        {"message": "Perfeksionis banget, benerin letak buku di meja aja butuh pakai penggaris siku.", "lucky_item": "Penggaris besi yang pinggirannya tajam", "tone": "neutral"},
        {"message": "Control freak abis, semua harus sesuai maumu. Kalau nggak, kamu bakal ngambek 3 hari 3 malam.", "lucky_item": "Remote control yang batrenya di-lakban", "tone": "bad"},
        {"message": "Kamu yakin banget pas merasa benar, dan sering memang benar. Hari ini sisakan ruang buat kemungkinan meleset.", "lucky_item": "Medali plastik juara lomba makan kerupuk", "tone": "good"},
        {"message": "Tukang kritik nomor satu. Apa aja dikomentarin, dari outfit orang sampai rasa air mineral.", "lucky_item": "Kaca pembesar gagang kayu", "tone": "bad"},
        {"message": "Suka ceramah ngasih petuah bijak, padahal idup sendiri masih berantakan kayak kapal pecah.", "lucky_item": "Buku kutipan Mario Teguh edisi lama", "tone": "bad"},
        {"message": "Tampilan luar selalu rapi dan on point, tapi kamar kosmu dalemnya kayak sarang penyamun.", "lucky_item": "Sisir yang giginya rontok separuh", "tone": "neutral"},
        {"message": "Paling nggak bisa nerima kritik. Dikasih saran dikit langsung defensif kayak lagi disidang.", "lucky_item": "Tameng mainan plastik Captain America", "tone": "bad"},
        {"message": "Kerja kerasmu patut dipuji, tapi nggak usah pamer ngeluh lelah di semua platform sosmed juga kali.", "lucky_item": "Status Facebook alay tahun 2011", "tone": "bad"},
        {"message": "Kamu pikir kamu ayam jago yang ditakuti, padahal orang ngeliat kamu kayak ayam sayur yang berisik.", "lucky_item": "Bumbu kaldu rasa ayam bawang", "tone": "bad"},
        {"message": "Selalu pengen jadi pusat perhatian. Kalau ada yang cerita sedih, kamu pasti nimpalin 'itu mah mending, aku dong...'.", "lucky_item": "Mic yang suaranya paling kenceng di KTV", "tone": "bad"},
        {"message": "Standarmu terlalu tinggi, makanya nyari jodoh susahnya ngalahin nyari jarum di tumpukan jerami.", "lucky_item": "Jarum pentul bengkok", "tone": "neutral"},
        {"message": "Kamu rajin bangun pagi, sayangnya cuma buat ngecek siapa yang nge-view IG Story-mu.", "lucky_item": "HP layar retak karena ketiduran", "tone": "neutral"},
        {"message": "Jago debat, nggak peduli topiknya apa pokoknya harus menang, walau ngotot pake argumen ngawur.", "lucky_item": "Palu hakim mainan ketok-ketok", "tone": "bad"},
        {"message": "Terlalu jujur sampai sering nyakitin hati orang. Filter dikit mulutnya, saringan teh aja punya filter.", "lucky_item": "Saringan teh bolong", "tone": "bad"},
        {"message": "Suka banget ngatur jadwal orang lain, kamu pikir kamu asisten pribadi mereka?", "lucky_item": "Kalender meja banyak coretan spidol merah", "tone": "bad"},
        {"message": "Ketelitianmu tingkat dewa, bisa nemu typo di dokumen 100 halaman dalam 5 menit.", "lucky_item": "Stabilo warna kuning terang nyala", "tone": "good"},
        {"message": "Pujian bukan barang langka yang harus dihemat. Hari ini ucapkan 'keren' ke satu orang, lidahmu aman.", "lucky_item": "Permen pelega tenggorokan", "tone": "good"},
        {"message": "Penampilan itu penting, tapi kalau telat meeting sejam gara-gara nyatok rambut doang mah kebangetan.", "lucky_item": "Catokan rambut yang kabelnya konslet", "tone": "neutral"},
        {"message": "Kepercayaan dirimu tinggi banget, sayangnya kadang nggak didukung sama skill yang mumpuni.", "lucky_item": "Buku 'How to Fake it Until You Make it'", "tone": "bad"},
        {"message": "Ketelitianmu hari ini menyelamatkan sesuatu yang besar. Orang mungkin nggak tahu, tapi kamu tahu.", "lucky_item": "Penggaris besi 30 sentimeter", "tone": "good"},
        {"message": "Hari yang bagus buat merapikan hal yang lama kamu tunda. Hasilnya bakal enak dilihat.", "lucky_item": "Label printer yang tintanya masih ada", "tone": "good"},
        {"message": "Pendapatmu diminta hari ini, dan beneran didengar. Sampaikan yang paling penting duluan.", "lucky_item": "Clipboard plastik warna biru", "tone": "good"},
        {"message": "Standarmu hari ini ketemu orang yang standarnya sama. Nikmati, itu jarang terjadi.", "lucky_item": "Setrika uap yang baru dibersihkan", "tone": "good"},
        {"message": "Kerjamu kelihatan hari ini tanpa perlu kamu sebut. Biarkan orang yang bilang duluan.", "lucky_item": "Name tag yang tulisannya masih jelas", "tone": "good"},
        {"message": "Hari yang enak buat memulai sistem baru. Yang kamu susun sekarang bakal kepakai lama.", "lucky_item": "Binder bekas yang ringnya masih kencang", "tone": "good"},
        {"message": "Ada yang minta maaf ke kamu hari ini. Terima tanpa menambahkan catatan koreksi.", "lucky_item": "Kotak tisu yang tinggal tiga lembar", "tone": "good"},
    ],
    "anjing": [
        {"message": "Loyal sih, tapi clingy-nya kelewatan. Gebetan balas lama dikit udah mikir dia selingkuh.", "lucky_item": "Tali rantai gantungan kunci", "tone": "bad"},
        {"message": "Kepalamu sudah sampai tahun depan padahal besok pagi belum kelihatan. Tarik balik ke hari ini, satu urusan saja.", "lucky_item": "Kantong kertas buat niup nafas pas panik", "tone": "good"},
        {"message": "Suara kresek tengah malam langsung kamu jadikan cerita horor lengkap. Cek sekali, terus tidur beneran.", "lucky_item": "Senter hp yang batrenya sisa 5%", "tone": "good"},
        {"message": "Overprotective sama temen. Temenmu jalan sama orang baru, kamu langsung nge-background check orangnya.", "lucky_item": "Topi detektif bulu-bulu", "tone": "bad"},
        {"message": "Guilt-tripper sejati. Kalau marah nggak teriak, tapi masang muka melas yang bikin orang merasa jadi penjahat.", "lucky_item": "Foto anak anjing sedih di HP", "tone": "bad"},
        {"message": "Kamu terlalu baik, rela berkorban buat orang yang bahkan nggak inget hari ulang tahunmu.", "lucky_item": "Kue tart lilinnya patah", "tone": "bad"},
        {"message": "Setia banget sama mantan, padahal mantannya udah nikah dan punya anak dua. Move on anjir!", "lucky_item": "Surat cinta bau apek di laci", "tone": "bad"},
        {"message": "Suka gigit balik kalau ngerasa terancam. Galak bener kalau ada yang nyenggol keluargamu.", "lucky_item": "Pelindung gigi petinju", "tone": "neutral"},
        {"message": "Khawatiran mulu, ngecek kunci pintu sampai 5 kali sebelum tidur. Padahal gak ada barang berharga juga di rumah.", "lucky_item": "Gembok sepedah yang karatan", "tone": "bad"},
        {"message": "Radar kebohonganmu tajam, tapi kamu pilih diam biar temanmu nyaman. Hari ini tanya baik-baik, bukan didiamkan.", "lucky_item": "Mesin detektor kebohongan mainan", "tone": "good"},
        {"message": "Kalau sudah sayang, logikamu kamu tinggal di stasiun. Nggak apa-apa, asal tiket pulangnya masih kamu pegang.", "lucky_item": "Tiket kereta hangus", "tone": "good"},
        {"message": "Butuh validasi terus-menerus. Dibilang 'Good boy/girl' aja udah senengnya minta ampun.", "lucky_item": "Stiker bintang senyum dari guru TK", "tone": "neutral"},
        {"message": "Nggak bisa nyembunyiin perasaan. Kalau nggak suka sama orang, mukamu langsung berubah kecut kayak mangga muda.", "lucky_item": "Garam buat makan mangga muda", "tone": "neutral"},
        {"message": "Kamu pendengar yang baik, saking baiknya sampai dijadiin tempat pembuangan sampah emosi temen-temenmu.", "lucky_item": "Tempat sampah plastik injak", "tone": "neutral"},
        {"message": "Kamu cemasin hal yang belum tentu kejadian. Tulis kekhawatirannya, besok cek mana yang beneran datang.", "lucky_item": "Benang kusut yang susah diurai", "tone": "good"},
        {"message": "Kamu rela nemenin temenmu begadang ngerjain tugas, ujung-ujungnya kamu yang ngerjain semuanya.", "lucky_item": "Kopi hitam pahit dingin", "tone": "bad"},
        {"message": "Gampang ngerasa bersalah kalau nolak permintaan tolong, padahal kamu sendiri lagi repot.", "lucky_item": "Post-it note tulisannya 'Maaf ya'", "tone": "bad"},
        {"message": "Pacarmu ngasih kejutan dan kepalamu langsung cari motifnya. Hari ini terima dulu, tanya nanti.", "lucky_item": "Kaca pembesar plastik", "tone": "good"},
        {"message": "Suka menggonggong hal-hal yang nggak penting di medsos, padahal di real life pendiam banget.", "lucky_item": "Keyboard yang tombol capslock-nya nyangkut", "tone": "neutral"},
        {"message": "Sangat peduli sama orang lain, tapi lupa cara peduli sama diri sendiri. Self-care woy!", "lucky_item": "Masker wajah yang udah kadaluarsa", "tone": "good"},
        {"message": "Kesetiaanmu hari ini dibalas orang yang tepat. Jarang, jadi nikmati.", "lucky_item": "Kalung kunci rumah yang sudah berkarat", "tone": "good"},
        {"message": "Firasatmu hari ini benar, dan kali ini kabarnya bagus. Percaya aja.", "lucky_item": "Senter kecil yang baterainya masih hidup", "tone": "good"},
        {"message": "Hari yang enak buat memperbaiki hubungan yang renggang. Orangnya juga lagi kepikiran kamu.", "lucky_item": "Foto lama yang terselip di dompet", "tone": "good"},
        {"message": "Hari ini gampang ngitung siapa yang nggak balas kebaikanmu. Berhenti di hitungan pertama.", "lucky_item": "Buku tabungan yang sudah tidak dipakai", "tone": "bad"},
        {"message": "Ada yang nggak balas chat hari ini dan itu bukan tentang kamu. Serius, bukan.", "lucky_item": "Charger HP yang colokannya longgar", "tone": "bad"},
    ],
    "babi": [
        {"message": "Hedonist sejati. Habis gajian langsung makan enak, tengah bulan makan promag.", "lucky_item": "Struk All You Can Eat harga 200rb", "tone": "neutral"},
        {"message": "Mager adalah jalan ninjamu. Kalau bisa berbaring, kenapa harus duduk? Apalagi berdiri.", "lucky_item": "Bantal leher travel bau iler", "tone": "neutral"},
        {"message": "Foodie abis, isi galerimu 90% foto makanan, 10% meme garing.", "lucky_item": "Sendok bebek plastik sisa mie ayam", "tone": "neutral"},
        {"message": "Terlalu baik dan lugu, gampang banget dimanfaatin temen buat bayarin parkir atau gofood.", "lucky_item": "Uang 2 ribu lecek buat tukang parkir", "tone": "bad"},
        {"message": "Self-indulgent pol. 'Aku pantes dapet self-reward ini' alasanmu tiap kali belanja barang nggak penting.", "lucky_item": "Barang random dari TikTok Shop yang gak kepake", "tone": "bad"},
        {"message": "Gak suka konflik, milih diam dan ngunyah camilan pas temen-temen lagi berantem.", "lucky_item": "Bungkus ciki rasa jagung bakar", "tone": "neutral"},
        {"message": "Memaafkan itu mudah buatmu, apalagi kalau yang minta maaf bawain martabak manis martabak telor.", "lucky_item": "Karet gelang merah bungkus martabak", "tone": "good"},
        {"message": "Punya hati selembut kapas, tapi kalau soal makanan, kamu berubah jadi monster buas yang nggak mau bagi.", "lucky_item": "Garpu somay yang udah bengkok", "tone": "neutral"},
        {"message": "Sering dibilang pemalas, padahal kamu sedang dalam fase 'menghemat energi' untuk hal-hal yang nggak penting.", "lucky_item": "Baterai AA sisa daya 10%", "tone": "neutral"},
        {"message": "Paling jago nikmati hidup. Meskipun uang mepet, tetap bisa ngerasa jadi sultan dengan cara ngopi sachet di teras.", "lucky_item": "Gelas plastik bekas kopi janji jiwa", "tone": "good"},
        {"message": "Mudah ditipu sama janji-janji manis, baik janji politikus maupun janji mantan yang minta balikan.", "lucky_item": "Permen karet manis di awal doang", "tone": "bad"},
        {"message": "Berhenti beli barang lucu yang ujung-ujungnya cuma numpuk debu di pojok kamar.", "lucky_item": "Boneka babi warna pink dekil", "tone": "bad"},
        {"message": "Kamu selalu ngasih kesempatan kedua, ketiga, keempat... sampai orang bosan bikin salah ke kamu.", "lucky_item": "Penghapus yang udah mengecil banget", "tone": "bad"},
        {"message": "Suka ngeluh berat badan naik, tapi pas diajak jogging milih narik selimut lagi.", "lucky_item": "Timbangan badan digital baterainya abis", "tone": "neutral"},
        {"message": "Nggak tegaan lihat orang kesusahan, saking nggak tegaannya, kadang rela kelaparan demi kasih makan kucing jalanan.", "lucky_item": "Plastik kresek isi makanan kering kucing", "tone": "good"},
        {"message": "Bahagiamu sederhana banget: AC dingin, WiFi kenceng, dan setoples camilan micin.", "lucky_item": "Remote AC nyangkut di suhu 16 derajat", "tone": "good"},
        {"message": "Sering overbudget pas belanja bulanan karena tergiur tulisan 'Buy 1 Get 1' padahal gak butuh.", "lucky_item": "Deterjen promo kemasan jumbo", "tone": "bad"},
        {"message": "Tidurnya nyenyak banget, gempa bumi aja kayaknya dikira cuma getaran kasur biasa.", "lucky_item": "Penyumbat telinga warna oranye", "tone": "neutral"},
        {"message": "Nggak peduli omongan orang. 'Haters gonna hate, potatoes gonna potate' adalah motomu.", "lucky_item": "Kentang goreng dingin pinggiran piring", "tone": "good"},
        {"message": "Kebaikan hatimu bakal dibalas dengan hal baik, asal jangan kasih pinjem duit ke teman yang 'lupa' bayar.", "lucky_item": "Celengan ayam dari tanah liat pecah", "tone": "good"},
        {"message": "Kebaikanmu hari ini balik lewat jalan yang nggak kamu duga. Terima aja tanpa nanya-nanya.", "lucky_item": "Toples kue yang isinya tinggal remah", "tone": "good"},
        {"message": "Hari yang enak buat makan enak tanpa rasa bersalah. Beneran, hari ini boleh.", "lucky_item": "Sendok kayu yang gagangnya sudah gelap", "tone": "good"},
        {"message": "Ada yang menghargai kelapanganmu hari ini dan bilang langsung. Simpan baik-baik.", "lucky_item": "Kartu ucapan terima kasih dari tetangga", "tone": "good"},
        {"message": "Rezekimu hari ini datang dari orang yang pernah kamu bantu diam-diam.", "lucky_item": "Dompet kain yang resletingnya seret", "tone": "good"},
        {"message": "Hari ini ada yang minta tolong dengan cerita yang meyakinkan. Cek dulu sebelum iya.", "lucky_item": "Kwitansi kosong yang belum diisi", "tone": "bad"},
        {"message": "Pengeluaran kecil hari ini gampang menumpuk tanpa terasa. Catat, jangan diingat-ingat saja.", "lucky_item": "Keranjang belanja online yang penuh", "tone": "bad"},
        {"message": "Ada yang menunda urusanmu dan kamu bakal maklum lagi. Kali ini tanya kapan pastinya.", "lucky_item": "Jam dinding yang telat lima menit", "tone": "bad"},
        {"message": "Hari ini gampang menghindari obrolan yang nggak enak. Justru itu yang paling perlu diselesaikan.", "lucky_item": "Kunci laci yang sengaja disembunyikan", "tone": "bad"},
    ],
}
