DAILY_CHONG_MESSAGES = [
    "Hari ini energi kosmik berbenturan denganmu. Hindari mengambil keputusan finansial besar atau menandatangani kontrak.",
    "Energi bertentangan sedang melingkupimu. Lebih baik tunda rapat penting atau negosiasi besar jika memungkinkan.",
    "Hari yang penuh drama potensial. Tarik napas dalam-dalam sebelum membalas chat yang bikin kesel.",
    "Kosmik lagi gak berpihak nih. Jangan mulai debat sama siapapun hari ini — kamu bakal kalah bukan karena salah, tapi karena energinya emang lagi sial.",
    "Hari Ciong aktif! Simpan kartu kreditmu jauh-jauh, jangan checkout apapun yang harganya lebih dari harga makan siang.",
    "Energi bentrokan bikin emosi gampang meledak. Kalau ada yang bikin kesel, tahan dulu — besok kamu bakal bersyukur gak nge-chat hal yang kamu sesali.",
    "Bintang-bintang lagi bertengkar di atas sana, dan kamu kena imbasnya. Hari yang tepat untuk rebahan dan menghindari konfrontasi.",
    "Hati-hati di jalan dan dalam berkomunikasi. Energi Ciong bisa bikin salah paham kecil jadi masalah besar.",
    "Hari ini bukan waktunya jadi pahlawan. Diam itu emas — terutama saat energi kosmik lagi nge-test kesabaranmu.",
    "Gelombang negatif Ciong sedang kuat. Kelilingi dirimu dengan warna merah atau emas untuk menetralkan energi buruk.",
    "Kosmos memperingatkan: jangan pinjamkan uang hari ini, dan jangan juga meminjam. Urusan finansial rawan bermasalah.",
    "Hari yang cocok untuk 'low profile mode'. Jangan cari perhatian, jangan cari ribut, fokus aja selesaikan yang perlu.",
    "Bentrokan kosmik hari ini bisa bikin kamu salah baca situasi. Double-check semua email dan pesan sebelum kirim!",
    "Energi Ciong bikin kamu rentan terpengaruh mood orang lain. Pasang headset, dengerin musik tenang, dan lindungi energimu.",
    "Hari ini seperti berjalan di atas es tipis — pelan-pelan aja. Jangan ambil risiko yang gak perlu.",
    "Bintang pelindungmu lagi istirahat hari ini. Andalkan logika, bukan emosi, dalam setiap keputusan.",
    "Ciong alert! Kalau bisa WFH atau diam di rumah, itu pilihan paling bijak hari ini.",
    "Jangan tergoda untuk membalas provokasi. Energi Ciong bikin lawan debatmu 2x lebih menyebalkan dari biasanya.",
    "Ini bukan hari terbaikmu, dan itu tidak apa-apa. Istirahat juga bagian dari strategi kosmik.",
    "Peringatan kosmik: hindari memulai proyek baru, hubungan baru, atau kebiasaan baru hari ini. Tunda sampai energi membaik.",
    "Tahan jarimu sebelum menekan tombol kirim. Satu pesan yang ditulis saat panas bisa butuh seminggu untuk diperbaiki.",
    "Kalau ada tugas yang bisa dikerjakan besok tanpa rugi, kerjakan besok. Hari ini energimu lebih baik dipakai bertahan.",
    "Rencana pindahan, renovasi, atau pembelian barang mahal sebaiknya ditunda. Hari bentrokan jarang memberi harga terbaik.",
    "Orang yang biasanya sabar padamu bisa mendadak ketus hari ini. Jangan dibawa perasaan, mereka juga kena imbas energinya.",
    "Hari ini kamu lebih gampang salah dengar. Ulangi instruksi penting dengan kalimatmu sendiri sebelum mulai mengerjakan.",
    "Jaga jarak dari perdebatan di grup chat. Diam di sana hari ini jauh lebih menghemat tenaga daripada menang argumen.",
    "Tubuhmu mungkin terasa lebih tegang dari biasanya. Peregangan lima menit di sela kerja bisa menurunkan tensi yang tidak kamu sadari.",
    "Ada godaan untuk membuktikan dirimu benar. Hari ini, membiarkan orang lain merasa menang justru langkah paling cerdas.",
    "Keluarga bisa jadi sumber gesekan hari ini. Pilih topik ringan saat makan bersama, simpan urusan berat untuk minggu depan.",
    "Jangan tanda tangani perjanjian sewa, cicilan, atau kerja sama hari ini. Baca ulang besok dengan kepala lebih dingin.",
    "Hari yang cocok untuk menyelesaikan pekerjaan sendirian. Kolaborasi hari ini lebih rawan tabrakan daripada biasanya.",
    "Kalau rencanamu dibatalkan orang lain, terima saja. Memaksa jalan hari ini cuma menambah daftar hal yang harus dibereskan.",
    "Hindari berkendara saat terburu-buru. Berangkat lebih awal sepuluh menit jauh lebih murah daripada menanggung kelalaian kecil.",
    "Tidak semua kritik harus dijawab hari ini. Catat, simpan, dan tanggapi setelah energinya reda.",
    "Uang yang keluar karena emosi biasanya yang paling disesali. Kalau ingin belanja untuk menghibur diri, tunggu sampai besok.",
    "Hari bentrokan bukan hari untuk mengambil keputusan tentang hubungan. Rasa ingin menyerah hari ini belum tentu jujur.",
    "Kamu mungkin merasa disalahpahami. Daripada menjelaskan panjang, cukup katakan kamu butuh waktu dan bahas lagi nanti.",
    "Makan tepat waktu hari ini. Lapar ditambah energi bentrokan adalah kombinasi paling cepat untuk meledak.",
    "Selesaikan satu pekerjaan kecil sampai tuntas. Rasa beres yang sederhana cukup untuk menahan hari yang terasa berantakan.",
    "Hari ini lebih baik jadi pendengar di rapat. Pendapatmu tetap penting, hanya waktunya yang kurang tepat.",
    "Kalau ada yang memancing emosi di media sosial, tutup aplikasinya. Hari ini tidak ada komentar yang layak dibalas.",
    "Jaga barang pinjaman milik orang lain dengan lebih hati-hati. Kerusakan kecil hari ini bisa berubah jadi ketegangan panjang.",
    "Rencanakan malam yang tenang. Menutup hari bentrokan dengan istirahat cukup membuat besok terasa jauh lebih ringan.",
    "Hari ini kamu tidak wajib menyenangkan semua orang. Menjaga dirimu tetap tenang sudah pencapaian yang cukup.",
    "Bentrokan tidak selalu datang dari luar. Kalau dua keinginanmu sendiri saling tarik, pilih yang paling sedikit risikonya.",
]
DAILY_SAN_HE_MESSAGES = [
    "Energi kosmik sangat bersinergi denganmu hari ini! Peluang besar menantimu di karir dan asmara.",
    "San He aktif! Ini hari yang sempurna untuk memulai proyek baru, pitching ide, atau menyatakan perasaan.",
    "Tiga Harmoni memberkatimu hari ini. Keputusan yang kamu buat sekarang punya potensi mengubah hidupmu ke arah lebih baik.",
    "Rezeki datang dari arah yang tidak terduga! Tetap buka mata dan telinga — peluang bisa muncul dari obrolan santai.",
    "Energi San He bikin aura leadershipmu bersinar. Orang-orang akan secara natural mengikuti arahanmu hari ini.",
    "Hari yang luar biasa untuk networking! Setiap orang yang kamu temui hari ini berpotensi menjadi koneksi penting di masa depan.",
    "Kreativitasmu sedang di puncak berkat sinergi San He. Ide-ide brilian akan mengalir deras — catat semuanya!",
    "Keberuntungan finansial sedang memihakmu. Kalau ada investasi yang sudah lama kamu pertimbangkan, ini momennya.",
    "San He memberikan keberanian ekstra. Hal-hal yang biasanya kamu takuti, hari ini terasa lebih ringan dan bisa diatasi.",
    "Hari yang sempurna untuk menyelesaikan konflik lama. Energi harmoni membuatmu lebih bijak dalam memilih kata.",
    "Kosmos mendukung langkah besarmu! Wawancara kerja, ujian, atau presentasi — semuanya punya bintang terang hari ini.",
    "Energi positif San He menular ke orang-orang di sekitarmu. Kamu jadi pembawa keberuntungan bagi timmu hari ini.",
    "Intuisi kosmikmu sangat tajam. Percaya pada firasat pertamamu — dia jarang salah di hari San He.",
    "Hari untuk berani bermimpi besar! San He membuka pintu-pintu yang biasanya tertutup rapat.",
    "Peluang promosi atau kenaikan jabatan sangat cerah. Tunjukkan hasil kerjamu dengan percaya diri.",
    "Cinta dan keharmonisan menyelimuti hubunganmu. Momen romantis akan tercipta secara natural hari ini.",
    "Hari yang cocok untuk belajar hal baru. Otakmu menyerap informasi 3x lebih cepat berkat energi San He.",
    "Keberanian dan kebijaksanaan berjalan beriringan hari ini. Ambil langkah yang sudah lama kamu tunda!",
    "San He membawa keberuntungan berlipat! Apapun yang kamu mulai hari ini punya fondasi kosmik yang kuat.",
    "Bintang-bintang bersekutu untukmu. Nikmati hari ini dengan penuh syukur — momen seperti ini tidak datang setiap hari.",
    "Kirim pesan ke orang yang sudah lama ingin kamu hubungi. Hari ini sambutannya kemungkinan jauh lebih hangat dari dugaanmu.",
    "Ajukan pertanyaan yang biasanya kamu tahan. Jawaban yang kamu dapat hari ini bisa membuka jalan yang selama ini tertutup.",
    "Kerja kelompok terasa lancar hari ini. Bagikan tugas yang tadinya kamu pikul sendiri, hasilnya justru lebih baik.",
    "Hari yang bagus untuk memperbarui portofolio atau CV. Cara kamu menjelaskan pencapaianmu sedang tepat sasaran.",
    "Rezeki kecil yang berulang lebih mungkin datang hari ini. Perhatikan tawaran kecil, jangan cuma menunggu yang besar.",
    "Kalau ada ide usaha sampingan, tulis rencana kasarnya hari ini. Energinya mendukung langkah pertama, bukan cuma angan.",
    "Orang-orang di sekitarmu lebih mudah diajak sepakat. Manfaatkan untuk membereskan keputusan bersama yang tertunda.",
    "Hari ini kamu gampang menangkap pola. Masalah yang kemarin terasa rumit bisa tiba-tiba kelihatan jalan keluarnya.",
    "Belajar keterampilan baru terasa lebih mudah hari ini. Mulai dari bagian yang paling kamu hindari selama ini.",
    "Hubungan dengan atasan atau dosen sedang cair. Waktu yang pas untuk minta masukan atau mengajukan usulan.",
    "Kalau sedang mencari tempat tinggal atau kerja baru, hari ini informasinya lebih gampang mengalir ke arahmu.",
    "Energimu cukup untuk dua hal sekaligus hari ini. Tetap prioritaskan yang paling penting agar semangatnya tidak terpecah.",
    "Hari yang baik untuk membayar utang lama atau menagih yang tertunda. Pembicaraan soal uang terasa lebih ringan.",
    "Teman lama bisa membawa kabar baik hari ini. Balas pesan dari orang yang sudah lama tidak menyapamu.",
    "Kamu sedang mudah dipercaya. Gunakan kepercayaan itu untuk hal yang benar-benar kamu sanggupi, jangan berjanji berlebihan.",
    "Hari ini semangat olahraga lebih mudah muncul. Bangun kebiasaan kecil yang bisa kamu teruskan minggu depan.",
    "Tulis tiga hal yang ingin kamu capai tahun ini. Hari San He membuat target yang ditulis lebih mudah terasa nyata.",
    "Tawaran kolaborasi yang datang hari ini layak dipertimbangkan serius. Orangnya kemungkinan sejalan denganmu.",
    "Kalau ada hubungan yang ingin kamu perbaiki, hari ini kata-katamu lebih mudah diterima dengan baik.",
    "Keputusan belanja besar yang sudah dipikirkan lama bisa dieksekusi hari ini. Pastikan tetap membandingkan harga dulu.",
    "Hari yang pas untuk merapikan rencana keuangan bulanan. Angka-angkanya terasa lebih jernih untuk kamu baca.",
    "Energi harmoni membuat presentasi mengalir. Latihan sekali lagi sebelum tampil, dan biarkan sisanya berjalan alami.",
    "Kamu bisa jadi penghubung antara dua orang yang saling butuh hari ini. Kenalkan mereka, manfaatnya berbalik padamu.",
    "Rasa percaya dirimu stabil hari ini. Waktu yang bagus untuk mengambil peran yang biasanya kamu serahkan ke orang lain.",
    "Hari ini cocok untuk merayakan hal kecil bersama orang terdekat. Kebahagiaan yang dibagi terasa berlipat.",
]
DAILY_LIU_HE_MESSAGES = [
    "Hari yang luar biasa harmonis! Akan ada penolong misterius atau kelancaran dalam segala urusan.",
    "Liu He aktif — ini level keberuntungan tertinggi! Segala yang kamu sentuh hari ini berpotensi jadi emas.",
    "Harmoni Keenam membuka pintu rezeki tersembunyi. Jangan tolak undangan atau ajakan apapun hari ini!",
    "Hari ini kamu dikelilingi oleh energi pelindung kosmik. Rasanya seperti punya guardian angel yang kerja lembur.",
    "Liu He bikin karisma kamu meledak! Orang-orang akan tertarik padamu secara natural — gunakan untuk hal positif.",
    "Keberuntungan langka sedang berpihak padamu. Beli lotre? Mungkin. Tapi lebih baik investasikan energi ini untuk keputusan hidup yang bermakna.",
    "Hari di mana 'kebetulan' sebenarnya adalah takdir. Perhatikan tanda-tanda kecil dari semesta hari ini.",
    "Energi Liu He membuat masalah yang rumit tiba-tiba menemukan solusinya. Hari untuk menyelesaikan urusan yang menumpuk!",
    "Seseorang akan menawarkan bantuan yang sangat kamu butuhkan tanpa diminta. Terima dengan tangan terbuka!",
    "Aura positifmu hari ini bisa menyembuhkan hubungan yang retak. Waktu terbaik untuk minta maaf atau memaafkan.",
    "Liu He memberikan kejelasan pikiran yang luar biasa. Keputusan yang kamu buat hari ini akan kamu syukuri bertahun-tahun kemudian.",
    "Hari ini kamu adalah magnet keberuntungan. Bahkan hal-hal kecil — antrian pendek, diskon tak terduga — semuanya berpihak padamu.",
    "Kombinasi kosmik terbaik sedang aktif! Ini hari untuk negosiasi, melamar kerja, atau bahkan melamar pasangan.",
    "Energi harmoni Liu He sangat langka dan sakral. Gunakan hari ini untuk menanam benih kebaikan — hasilnya akan berlipat ganda.",
    "Hari yang sempurna untuk memulai tradisi baru, kebiasaan sehat, atau babak baru dalam hidupmu.",
    "Kosmos memberikanmu 'golden ticket' hari ini. Jangan sia-siakan dengan rebahan — keluar dan buat sesuatu terjadi!",
    "Liu He membawa keselarasan antara pikiran, hati, dan tindakan. Kamu akan merasa utuh dan damai hari ini.",
    "Penolong datang dari arah yang paling tidak kamu sangka. Bisa jadi teman lama, stranger, atau bahkan mantan yang tiba-tiba helpful.",
    "Hari yang diberkati penuh! Energi Liu He ini hanya datang beberapa kali sebulan — manfaatkan sebaik mungkin.",
    "Semesta sedang tersenyum padamu. Apapun yang membuatmu cemas belakangan ini, hari ini kamu akan mendapat jawaban yang melegakan.",
    "Seseorang sedang memikirkanmu dengan baik hari ini. Kabar yang datang kemungkinan lebih manis dari yang kamu kira.",
    "Urusan administrasi yang biasanya berbelit bisa selesai cepat hari ini. Kerjakan yang paling lama kamu tunda.",
    "Hari ini orang lebih mudah memberi kesempatan kedua. Kalau ada yang ingin kamu coba ulang, sekarang waktunya.",
    "Pencarian barang yang hilang lebih mungkin berhasil hari ini. Cek tempat yang paling tidak masuk akal.",
    "Rekomendasi dari orang lain punya bobot besar hari ini. Minta tolong teman untuk menyebut namamu di tempat yang tepat.",
    "Kalau kamu sedang menunggu jawaban, hari ini kemungkinan kabarnya datang. Siapkan langkah lanjutanmu.",
    "Hubungan asmara terasa hangat tanpa perlu banyak usaha. Nikmati kebersamaan sederhana tanpa merencanakan terlalu jauh.",
    "Hari ini kamu sulit ditolak. Ajukan permintaan yang wajar dengan jelas, peluangnya bagus.",
    "Energi pelindung membuat perjalanan hari ini lebih lancar. Kalau harus bepergian, hari ini pilihan yang baik.",
    "Tawaran diskon atau kemudahan kecil lebih sering mampir hari ini. Terima dengan wajar, jangan tergoda membeli yang tidak perlu.",
    "Kamu bisa menjembatani konflik orang lain dengan mudah hari ini. Kata-katamu terdengar netral dan menenangkan.",
    "Waktu yang bagus untuk memperkenalkan pasangan atau teman baru ke lingkaranmu. Suasananya mendukung kesan pertama yang baik.",
    "Hari ini ide-idemu lebih mudah didukung orang. Sampaikan usulan yang selama ini kamu simpan.",
    "Kesehatanmu terasa lebih bugar. Manfaatkan untuk aktivitas yang biasanya membuatmu cepat lelah.",
    "Seseorang yang lebih berpengalaman bisa membukakan jalan untukmu hari ini. Jangan malu bertanya dan meminta arahan.",
    "Hari ini transaksi jual beli cenderung menguntungkan dua pihak. Waktu yang bagus untuk menjual barang yang tidak terpakai.",
    "Kamu sedang dikelilingi orang yang tulus. Terima bantuan mereka tanpa merasa berutang berlebihan.",
    "Energi Liu He membuat kesalahan kecil lebih mudah dimaafkan. Kalau ada yang ingin kamu akui, hari ini aman.",
    "Hari ini kamu bisa memulai percakapan sulit dengan hasil yang lebih lembut dari perkiraanmu.",
    "Jadwal yang padat pun terasa bisa dijalani hari ini. Susun urutannya, dan satu per satu akan beres.",
    "Kalau kamu sedang menabung untuk sesuatu, hari ini ada peluang kecil mempercepatnya. Perhatikan pemasukan tak terduga.",
    "Hari yang pas untuk menyatakan terima kasih pada orang yang pernah menolongmu. Kebaikan itu akan kembali dengan cara lain.",
    "Kamu mudah menemukan orang yang sepikiran hari ini. Obrolan panjang bisa berujung jadi rencana nyata.",
    "Energi keberuntungan ini paling terasa kalau kamu bergerak. Jangan habiskan hari yang langka ini hanya menunggu.",
    "Hari ini kebaikan kecil yang kamu lakukan berbalik lebih cepat. Mulai dari menolong satu orang tanpa diminta.",
]
DAILY_XIANG_XING_MESSAGES = [
    "Ada sedikit friksi energi hari ini. Berhati-hatilah dalam berkomunikasi agar tidak memicu konflik.",
    "Gelombang ketegangan terasa samar tapi nyata. Pilih kata-katamu dengan hati-hati, terutama saat chatting.",
    "Energi hari ini membawa gesekan kecil yang bisa membesar kalau tidak diantisipasi. Stay cool!",
    "Friksi kosmik sedang menguji kesabaranmu. Jangan terpancing emosi oleh hal-hal sepele.",
    "Hari yang sedikit 'gerah' secara energi. Hindari gosip dan drama — fokus pada urusanmu sendiri.",
    "Ada potensi miscommunication hari ini. Kalau pesan pentingnya panjang, mending telpon langsung daripada chat.",
    "Ketegangan batin mungkin muncul tanpa alasan jelas. Itu efek friksi kosmik — bukan karena ada yang salah denganmu.",
    "Hari yang butuh ekstra kesabaran. Orang-orang di sekitarmu mungkin lebih sensitif dari biasanya.",
    "Energi gesekan bikin kamu gampang kesal sama hal kecil. Sebelum marah, tanya: 'Ini penting gak sih setahun lagi?'",
    "Hati-hati dengan nada bicara hari ini. Apa yang kamu maksud bercanda bisa ditangkap serius oleh orang lain.",
    "Friksi ringan di aspek keuangan. Cek dua kali sebelum transfer atau bayar sesuatu — pastikan nominalnya benar.",
    "Hari ini bukan waktu yang tepat untuk mengkritik orang lain, meski niatmu membangun. Simpan feedbacknya untuk besok.",
    "Energi ketegangan bisa dinetralisir dengan aktivitas fisik. Olahraga ringan atau jalan kaki bisa bantu reset moodmu.",
    "Rekan kerja atau teman mungkin tanpa sadar menyinggungmu. Berikan benefit of the doubt sebelum bereaksi.",
    "Gesekan kosmik hari ini ibarat cuaca mendung — tidak hujan, tapi juga tidak cerah. Bawa 'payung' kesabaran.",
    "Hari untuk mendengarkan lebih banyak dan berbicara lebih sedikit. Kebijaksanaan ada di keheningan.",
    "Jangan buat keputusan besar saat emosi sedang tidak stabil. Tidur dulu, besok pagi pikiran lebih jernih.",
    "Friksi hari ini bisa jadi sinyal bahwa ada sesuatu yang perlu kamu evaluasi ulang dalam hidupmu.",
    "Energi gesekan membuat hubungan asmara sedikit rawan baper. Jangan over-analyze chat gebetan hari ini.",
    "Ketegangan kecil ini akan berlalu. Hari ini cukup bertahan dan menjaga ketenangan — besok energinya jauh lebih baik.",
    "Hari ini kamu mungkin merasa dikoreksi terus. Terima yang masuk akal, lewatkan yang cuma soal selera.",
    "Pekerjaan yang sama bisa perlu diulang dua kali hari ini. Simpan cadangan dan catat langkahnya supaya tidak mulai dari nol.",
    "Ada ketegangan antara yang kamu mau dan yang diharapkan orang. Cari titik tengah, jangan memaksakan salah satunya.",
    "Janji temu hari ini rawan molor. Siapkan kegiatan cadangan supaya waktu tunggumu tidak terbuang sia-sia.",
    "Hindari bercanda soal hal sensitif hari ini. Batas yang biasanya longgar sedang lebih tipis dari biasanya.",
    "Hari ini aturan terasa lebih kaku. Ikuti prosedur dengan sabar, jalan pintas justru bisa memperpanjang urusan.",
    "Orang tua atau keluarga bisa lebih rewel hari ini. Dengarkan dulu, sering kali yang mereka butuhkan cuma diperhatikan.",
    "Tugas kecil yang disepelekan bisa jadi masalah hari ini. Selesaikan yang remeh sebelum yang besar.",
    "Hari ini kamu lebih peka terhadap kritik. Beri jeda sebelum menanggapi, supaya yang keluar tanggapan, bukan reaksi.",
    "Gesekan di tempat kerja bisa muncul karena pembagian tugas yang kurang jelas. Perjelas siapa mengerjakan apa sejak pagi.",
    "Jangan paksakan diri menyelesaikan semuanya hari ini. Pilih dua hal penting, sisanya pindahkan ke besok.",
    "Kebiasaan lama yang ingin kamu tinggalkan bisa menggoda lagi hari ini. Jauhkan pemicunya dari jangkauan.",
    "Hari ini pesan singkat lebih mudah disalahartikan. Tambahkan konteks satu kalimat supaya niatmu terbaca jelas.",
    "Rasa jenuh bisa muncul di tengah hari. Ganti suasana sebentar, bekerja di tempat lain bisa menyegarkan fokusmu.",
    "Ada pelajaran yang terasa berulang hari ini. Perhatikan polanya, di situ jawabannya biasanya tersembunyi.",
    "Hari ini lebih aman membayar tagihan tepat waktu. Denda kecil hari ini lebih menjengkelkan dari biasanya.",
    "Kamu bisa merasa kurang dihargai hari ini. Ingatkan dirimu pada pencapaian kecil yang sudah kamu kumpulkan.",
    "Diskusi soal aturan rumah atau pembagian tugas bisa memanas. Tulis kesepakatannya supaya tidak diperdebatkan lagi.",
    "Hari ini cocok untuk merapikan hal yang mengganjal secara diam-diam. Tidak perlu diumumkan, cukup dibereskan.",
    "Tubuhmu memberi tanda kelelahan lebih cepat. Minum cukup air dan jangan melewatkan jam tidur malam ini.",
    "Pendapatmu bisa berbenturan dengan orang yang keras kepala. Sampaikan sekali dengan tenang, lalu biarkan.",
    "Hari ini lebih baik menunda obrolan soal uang dengan teman. Nada yang salah bisa membuat urusan kecil jadi panjang.",
    "Tekanan hari ini membentuk, bukan menghancurkan. Selesaikan yang bisa, dan berikan dirimu kredit untuk itu.",
    "Kalau ada yang menagih janji, akui dengan jujur kalau belum bisa. Alasan panjang malah menambah gesekan.",
    "Hari ini lebih baik mengalah pada hal kecil supaya tenaga tersimpan untuk hal yang benar-benar penting.",
]
DAILY_PO_MESSAGES = [
    "Energi Po merusak rencana yang sudah tersusun rapi. Siapkan rencana cadangan sebelum melangkah keluar rumah.",
    "Ada yang retak diam-diam hari ini — bisa janji, bisa barang. Jangan menaruh harapan besar pada satu rencana saja.",
    "Kesepakatan yang tadinya mulus bisa berubah mendadak. Konfirmasi ulang sebelum kamu berangkat menemui siapa pun.",
    "Energi hari ini melemahkan fondasi. Tunda menandatangani apa pun yang sifatnya mengikat untuk jangka panjang.",
    "Po membawa pembatalan tak terduga. Kalau acaramu batal hari ini, itu bukan salahmu — energinya memang begitu.",
    "Barangmu lebih rawan rusak atau tertinggal hari ini. Cek dompet, kunci, dan ponsel setiap kali berpindah tempat.",
    "Hari ini kamu boros tanpa sadar. Uang keluar untuk hal-hal kecil yang kalau ditotal justru bikin kaget.",
    "Po menggerus kerja sama. Proyek bareng orang lain rawan berantakan — perjelas pembagian tugas sejak awal.",
    "Sesuatu yang lama kamu bangun terasa goyah hari ini. Tenang, ini fase yang lewat, bukan keruntuhan.",
    "Hindari memulai hal baru hari ini. Energinya lebih cocok untuk merapikan yang lama daripada membangun yang baru.",
    "Komitmen yang dibuat hari ini rawan berubah lagi besok. Kalau masih bisa ditunda, sebaiknya ditunda.",
    "Po mengganggu urusan teknis: sinyal buruk, berkas rusak, atau jadwal bentrok. Simpan pekerjaanmu lebih sering.",
    "Hari ini rencana A sampai C bisa gagal bersamaan. Fleksibilitas jauh lebih berguna daripada keras kepala.",
    "Energi perusakan menyentuh hubungan. Kata yang terlanjur keluar hari ini akan sulit ditarik kembali.",
    "Ada kebocoran halus dalam keuanganmu. Periksa langganan atau tagihan yang mungkin sudah lama terlupakan.",
    "Hari yang kurang bersahabat untuk transaksi besar. Tawaran yang terdengar sempurna perlu diperiksa dua kali.",
    "Po membuat fokusmu mudah pecah. Tuntaskan satu hal dulu sebelum berpindah ke pekerjaan berikutnya.",
    "Perjalanan hari ini rawan hambatan kecil — macet, telat, atau salah jalur. Berangkatlah lebih awal dari biasanya.",
    "Yang retak hari ini belum tentu harus dibuang. Perbaiki pelan-pelan, jangan memutuskan saat sedang kesal.",
    "Energi Po akan berlalu. Hari ini cukup jaga apa yang sudah ada, tidak perlu menambah beban yang baru.",
    "Simpan salinan dokumen penting hari ini. Berkas yang hilang atau rusak lebih merepotkan dari biasanya.",
    "Janji yang dibuat dengan terburu-buru hari ini rawan tidak terpenuhi. Lebih baik berjanji sedikit tapi pasti.",
    "Kalau rencana liburan sedang disusun, tunda pembayaran tiket sampai jadwalnya benar-benar pasti.",
    "Hari ini perangkat elektronikmu lebih rawan bermasalah. Isi daya penuh dan simpan data penting di dua tempat.",
    "Kerja sama yang belum jelas pembagian hasilnya sebaiknya diperjelas hari ini sebelum dilanjutkan.",
    "Ada yang bisa membatalkan janji denganmu mendadak. Siapkan rencana cadangan untuk waktumu yang kosong.",
    "Hari ini lebih bijak memperbaiki yang rusak daripada membeli yang baru. Uangmu lebih baik ditahan dulu.",
    "Pesan lama bisa disalahpahami ulang hari ini. Kalau ada yang bertanya soal masa lalu, jawab singkat dan jujur.",
    "Kesepakatan lisan hari ini mudah terlupakan. Ringkas hasil obrolan penting dalam pesan tertulis.",
    "Kebiasaan baik yang sedang kamu bangun bisa terputus hari ini. Tidak apa-apa, lanjutkan lagi besok tanpa menyalahkan diri.",
    "Hari ini lebih rawan kehilangan barang kecil di jalan. Periksa tas sebelum meninggalkan tempat mana pun.",
    "Kalau ada yang menawarkan jalan pintas soal uang, tolak dengan sopan. Hari ini yang terlalu mudah biasanya bermasalah.",
    "Rencana kelompok bisa berantakan karena satu orang mundur. Siapkan pembagian tugas yang bisa dialihkan.",
    "Hari ini cocok untuk mengecek ulang langganan otomatis dan cicilan. Ada pengeluaran yang mungkin sudah tidak kamu butuhkan.",
    "Jangan membuat perubahan besar pada rutinitas kerja hari ini. Pola lama lebih aman sampai energinya membaik.",
    "Hubungan yang sedang renggang bisa makin retak kalau dipaksa bicara hari ini. Beri ruang dulu, lanjutkan saat suasana tenang.",
    "Hari ini makanan dan minuman yang terlalu lama disimpan sebaiknya dihindari. Perutmu lebih sensitif dari biasanya.",
    "Jadwal yang terlalu mepet rawan berantakan. Sisakan jeda di antara kegiatan supaya satu keterlambatan tidak merembet.",
    "Hari ini lebih baik tidak meminjamkan barang berharga. Kerusakan kecil bisa jadi alasan salah paham panjang.",
    "Kalau ada proyek yang terasa tidak berjalan, jangan buru-buru membubarkannya. Evaluasi dulu bagian mana yang benar-benar rusak.",
    "Uang tunai lebih rawan hilang hari ini. Bawa secukupnya dan simpan sisanya di tempat aman.",
    "Hari ini pengumuman besar sebaiknya ditunda. Kabar yang disampaikan terlalu cepat mudah ditarik kembali.",
    "Kalau sedang merenovasi atau memperbaiki sesuatu di rumah, periksa ulang ukurannya. Kesalahan kecil hari ini mahal.",
    "Energi Po mengajarkan melepas yang sudah tidak berfungsi. Relakan satu hal kecil yang selama ini kamu pertahankan tanpa alasan.",
    "Hari ini lebih baik merawat apa yang sudah kamu punya. Stabil untuk sementara jauh lebih berharga daripada bertambah.",
]
DAILY_HAI_MESSAGES = [
    "Energi Hai membawa bahaya yang tak terlihat. Yang tersenyum padamu hari ini belum tentu berpihak padamu.",
    "Hati-hati dengan niat baik yang berlebihan hari ini. Ada yang menolong sambil menyimpan maksud lain.",
    "Hari ini rawan salah paham yang sengaja dipelihara. Luruskan segera, jangan biarkan mengendap berhari-hari.",
    "Jaga rahasiamu hari ini. Cerita yang kamu bagikan berpotensi berpindah ke telinga yang keliru.",
    "Hai melemahkan daya tahan tubuh. Jangan abaikan sinyal lelah — istirahat bukan kemewahan hari ini.",
    "Ada yang memanfaatkan kebaikanmu diam-diam. Menolong itu baik, asal kamu tidak ikut jadi korban.",
    "Gosip lebih mudah menempel hari ini. Jangan ikut menyebarkan, dan jangan panik kalau kamu yang kena.",
    "Waspadai tawaran yang terlalu manis. Yang mudah didapat biasanya menyimpan harga yang belum kelihatan.",
    "Hai membawa gesekan dari orang terdekat, bukan dari orang jauh. Justru di situ kamu perlu lebih peka.",
    "Periksa detail kecil dalam dokumen hari ini. Yang merugikan biasanya disembunyikan di bagian paling bawah.",
    "Energi hari ini bikin kamu mudah dipengaruhi saat lelah. Tunda keputusan penting sampai pikiranmu segar.",
    "Ada yang menahan informasi darimu hari ini. Bertanya langsung jauh lebih aman daripada menebak-nebak sendiri.",
    "Hai menyentuh urusan kesehatan. Makan teratur, dan jangan menunda periksa kalau ada yang terasa mengganjal.",
    "Hari ini jarak adalah bentuk perlindungan. Tidak semua undangan dan ajakan perlu kamu iyakan.",
    "Berilah kebaikan tanpa mengharap balasan hari ini, supaya kecewa tidak sempat berubah menjadi luka.",
    "Energi Hai berpotensi membuka kembali konflik lama. Jangan memancing, dan jangan mau terpancing.",
    "Ada yang membanding-bandingkanmu dengan orang lain hari ini. Itu urusan mereka, bukan ukuran nilaimu.",
    "Simpan barang berharga lebih rapi hari ini. Kelalaian kecil bisa berubah menjadi kerugian yang nyata.",
    "Hari ini intuisimu lebih tajam daripada logikamu. Kalau ada yang terasa janggal, biasanya memang janggal.",
    "Bahaya hari ini sifatnya halus, bukan dramatis. Cukup waspada secukupnya — tidak perlu sampai paranoid.",
    "Hari ini lebih aman menahan cerita soal rencana besarmu. Wujudkan dulu, ceritakan belakangan.",
    "Ada orang yang ramah di depan tapi mengeluh di belakang. Tidak perlu dikonfrontasi, cukup batasi informasi yang kamu bagi.",
    "Waspadai rasa tidak enak yang muncul tanpa alasan jelas. Tubuhmu sering menangkap sinyal lebih dulu dari pikiranmu.",
    "Tawaran kerja sama yang terburu-buru sebaiknya dipelajari ulang. Minta waktu, orang yang tulus akan mau menunggu.",
    "Hari ini hindari meminjamkan kata sandi atau akses akun, bahkan ke orang dekat.",
    "Cek ulang tagihan dan saldo rekeningmu hari ini. Kesalahan kecil lebih mudah lolos tanpa terlihat.",
    "Hubungan pertemanan bisa terasa dingin tanpa alasan. Jangan menebak-nebak, tanyakan langsung dengan nada santai.",
    "Hari ini kurangi makanan yang terlalu pedas atau berminyak. Pencernaanmu lebih rentan dari biasanya.",
    "Orang yang meminta bantuan berulang kali mungkin mulai memanfaatkanmu. Menolak sekali tidak membuatmu jahat.",
    "Tanda tangani sesuatu hanya setelah kamu membaca seluruhnya. Bagian yang merugikan biasanya ada di lampiran.",
    "Hari ini jaga nada bicara dengan rekan kerja. Kalimat santai bisa dicatat dan dipakai di kemudian hari.",
    "Kalau ada rahasia orang lain yang kamu pegang, jaga baik-baik. Hari ini cerita lebih mudah bocor.",
    "Luka lama bisa terasa lagi hari ini. Itu bukan kemunduran, cukup akui perasaannya lalu lanjutkan harimu.",
    "Hari ini lebih baik tidak membuat komitmen jangka panjang dengan orang yang baru kamu kenal.",
    "Ada yang mungkin iri dengan pencapaianmu. Rayakan dengan lingkaran kecil yang benar-benar mendukungmu.",
    "Istirahat lebih awal malam ini. Energi Hai bekerja pelan dan menumpuk di tubuh yang kurang tidur.",
    "Hindari ikut campur dalam masalah rumah tangga orang lain hari ini. Niat baik mudah disalahpahami.",
    "Kalau ada tawaran investasi dari kenalan baru, abaikan dulu. Hari ini yang terlalu menjanjikan patut dicurigai.",
    "Hari ini kamu bisa merasa dimanfaatkan. Tulis apa yang sudah kamu berikan, lalu putuskan batasnya dengan tenang.",
    "Jaga kebersihan dan kesehatan kecil hari ini, seperti cuci tangan dan minum cukup. Hal remeh sedang berpengaruh besar.",
    "Kalimat pujian yang berlebihan hari ini perlu disaring. Tidak semua sanjungan datang tanpa maksud.",
    "Hari ini lebih aman berbelanja di tempat yang sudah kamu percaya. Penjual baru lebih rawan mengecewakan.",
    "Energi Hai melemahkan fokus saat malam. Selesaikan pekerjaan penting sebelum sore.",
    "Kalau ada yang menceritakan keburukan orang lain padamu, ingat dia juga bisa menceritakanmu di tempat lain.",
    "Bahaya kecil yang diantisipasi tidak akan jadi besar. Cukup hati-hati hari ini, besok energinya berganti.",
]
DAILY_ZI_XING_MESSAGES = [
    "Hari Zi Xing: lawan terberatmu hari ini adalah pikiranmu sendiri. Kurangi overthinking, perbanyak bernapas.",
    "Energi berbalik ke dalam hari ini. Kamu cenderung menghukum diri atas hal yang orang lain sudah lama lupakan.",
    "Zi Xing membuat standarmu pada diri sendiri jadi tidak masuk akal. Hari ini, cukup baik sudah sangat cukup.",
    "Kamu rawan menyabotase rencanamu sendiri hari ini. Sadari saat kamu mulai menunda tanpa alasan yang jelas.",
    "Energi hukuman-diri sedang aktif. Kalau hari ini terasa berat, besar kemungkinan kamu yang memberatkannya.",
    "Zi Xing membuatmu mencari kesalahan di tempat yang tidak ada salahnya. Berhenti mengulang percakapan di kepala.",
    "Suara kritik dari dalam terdengar lebih keras dari kenyataan hari ini. Jangan telan semuanya mentah-mentah.",
    "Energi berputar di dalam tanpa penyaluran. Gerakkan badanmu — jalan kaki sebentar saja sudah cukup membantu.",
    "Hari Zi Xing cocok untuk menyendiri sejenak, tapi jangan sampai tenggelam. Beri batas waktu untuk dirimu.",
    "Kamu cenderung memikul beban yang bukan tanggung jawabmu. Letakkan sebagian hari ini, itu bukan kegagalan.",
    "Zi Xing memunculkan keraguan di saat paling tidak tepat. Percayai keputusan yang sudah kamu timbang matang.",
    "Hari ini perfeksionismu bekerja melawanmu. Selesai jauh lebih berguna daripada sempurna tapi tak pernah jadi.",
    "Energi hari ini memantulkan sifatmu kembali kepadamu, termasuk sisi yang selama ini kamu hindari.",
    "Berhenti membandingkan dirimu hari ini dengan versi terbaikmu. Keduanya tetap orang yang sama.",
    "Kamu mungkin memilih diam padahal sedang butuh bicara. Satu pesan jujur bisa meringankan banyak hal.",
    "Energi hukuman-diri membuat istirahat terasa seperti kemalasan. Padahal justru itu yang paling kamu butuhkan.",
    "Zi Xing menajamkan introspeksi sekaligus memperbesar rasa bersalah. Ambil pelajarannya, tinggalkan hukumannya.",
    "Jangan ambil keputusan besar tentang dirimu sendiri hari ini. Penilaianmu sedang tidak adil kepadamu.",
    "Kalau hari ini kamu merasa tidak cukup, ingat: itu suara energi Zi Xing, bukan gambaran kenyataan.",
    "Energi ini mereda besok. Hari ini, perlakukan dirimu seperti kamu memperlakukan sahabat baikmu sendiri.",
    "Hari ini kamu mungkin merasa tertinggal dari teman sebaya. Ingat, kamu cuma melihat hasil mereka, bukan proses dan ragunya.",
    "Satu kesalahan kecil tidak menghapus semua usahamu. Catat pelajarannya, lalu lepaskan rasa bersalahnya.",
    "Hari ini kamu cenderung menunda karena takut hasilnya jelek. Mulai saja dengan versi kasar, perbaikan bisa menyusul.",
    "Jangan menilai dirimu dari satu percakapan canggung. Orang lain kemungkinan sudah melupakannya.",
    "Energi Zi Xing membuatmu sulit menerima pujian. Coba ucapkan terima kasih saja tanpa membantahnya.",
    "Hari ini kamu bisa terlalu keras soal pola makan atau olahraga. Konsisten lebih penting daripada sempurna.",
    "Rasa bersalah karena beristirahat sedang tinggi. Padahal tubuh yang cukup istirahat bekerja jauh lebih baik besok.",
    "Kalau pikiranmu berputar di satu masalah, tulis di kertas. Masalah yang dituliskan terasa jauh lebih kecil.",
    "Hari ini bandingkan dirimu dengan dirimu bulan lalu saja. Di situ kemajuanmu lebih jelas terlihat.",
    "Kamu mungkin menolak bantuan karena merasa harus mandiri. Menerima bantuan juga bentuk kekuatan.",
    "Hari ini jangan menghapus karya atau tulisan lama hanya karena malu. Itu bukti kamu pernah berani mencoba.",
    "Standar yang kamu pasang untuk dirimu hari ini mungkin lebih tinggi dari yang kamu pasang untuk orang lain. Samakan.",
    "Kalau merasa tidak berguna hari ini, lakukan satu hal kecil untuk orang lain. Rasa berarti sering datang dari situ.",
    "Hari ini hindari membaca ulang pesan lama yang membuatmu malu. Masa lalu tidak perlu diputar ulang terus.",
    "Energi hukuman diri membuatmu sulit memutuskan. Pilih yang cukup baik, jangan menunggu pilihan yang sempurna.",
    "Kamu boleh tidak produktif hari ini. Satu hari pelan tidak menentukan arah hidupmu.",
    "Hari ini perhatikan cara kamu bicara pada dirimu sendiri. Kalau kalimat itu tidak pantas untuk sahabat, jangan pakai untukmu.",
    "Rasa gagal hari ini sering berasal dari target yang terlalu banyak. Kurangi daftarmu, lalu rayakan yang selesai.",
    "Jangan menarik diri dari orang terdekat hari ini. Satu obrolan ringan bisa memutus lingkaran pikiran berat.",
    "Hari ini kamu bisa terlalu serius menanggapi komentar kecil. Saring mana yang berguna dan mana yang cukup dilupakan.",
    "Energi Zi Xing membuat kebiasaan buruk terasa lebih memalukan. Perbaiki satu langkah kecil, bukan semuanya sekaligus.",
    "Hari ini tidak perlu membuktikan apa pun ke siapa pun. Bekerja dengan tenang sudah cukup.",
    "Kalau kamu mulai membatalkan rencana karena merasa tidak siap, coba jalani separuhnya dulu.",
    "Kamu layak diperlakukan dengan sabar, termasuk oleh dirimu sendiri. Hari ini latih kesabaran itu ke dalam.",
    "Energi ini mengajarkan menerima diri apa adanya. Kekurangan yang kamu lihat hari ini tidak membatalkan nilaimu.",
]
DAILY_BEN_MING_MESSAGES = [
    "Hari ini dikuasai oleh Shio milikmu. Energi sangat kuat namun bisa fluktuatif, tetaplah membumi.",
    "Ini hari cermin kosmikmu! Energi menguat tapi juga mengamplifikasi sisi negatifmu. Sadar diri adalah kuncinya.",
    "Hari Zhi Ri — kekuatanmu di puncak, tapi begitu juga kelemahanmu. Seimbangkan keduanya.",
    "Hari Shio-mu sendiri! Seperti ultah kosmik mini. Energinya intens — bisa sangat bagus atau sangat chaos, tergantung pilihanmu.",
    "Energi Ben Ming membuat intuisimu sangat tajam, tapi juga bikin kamu lebih emosional. Jaga keseimbangan.",
    "Hari di mana sifat dominanmu terasa 2x lebih kuat. Kalau dominanmu positif, hari ini luar biasa. Kalau negatif... ya berhati-hatilah.",
    "Zhi Ri aktif — kamu seperti baterai yang di-overcharge. Energi melimpah tapi perlu disalurkan dengan bijak.",
    "Ini hari refleksi diri yang sempurna. Apa yang kamu rasakan hari ini adalah cerminan jujur dari kondisi batinmu.",
    "Energi kembar bikin orang-orang dengan Shio yang sama denganmu juga sedang intens hari ini. Komunitas kosmikmu sedang sinkron!",
    "Hari Ben Ming cocok untuk ritual self-care atau meditasi. Energimu yang kuat perlu di-grounding agar tidak berlebihan.",
    "Sifat terbaikmu bersinar terang hari ini — tapi awas, sifat terburukmu juga ikut muncul di permukaan.",
    "Hari yang powerful untuk manifestasi. Tulis keinginanmu, visualisasikan, dan lepaskan ke semesta.",
    "Zhi Ri membawa kesadaran penuh tentang siapa dirimu sebenarnya. Terima semua sisimu — yang baik dan yang masih perlu diperbaiki.",
    "Energi hari ini ibarat pedang bermata dua. Gunakan untuk memotong hambatan, bukan untuk melukai orang lain.",
    "Hari kembar kosmik! Kamu akan merasa lebih 'dirimu sendiri' dari biasanya — embrace it.",
    "Ben Ming bikin kreativitasmu meledak, tapi juga bikin kamu mudah bosan. Fokuskan energi pada satu hal penting.",
    "Ini hari di mana keputusan kecil bisa berdampak besar. Pilih dengan sadar, bukan impulsif.",
    "Energi Zhi Ri mengamplifikasi segalanya. Cinta terasa lebih dalam, kemarahan terasa lebih panas. Kendalikan volumenya.",
    "Hari yang tepat untuk mengevaluasi goals dan arah hidupmu. Energi kosmik sedang menyorot 'panggung' pribadimu.",
    "Ben Ming mengingatkan: kamu lebih kuat dari yang kamu kira, tapi juga lebih rentan dari yang kamu akui. Jaga dirimu.",
    "Hari ini orang lebih mudah mengenali sifat aslimu. Tampilkan sisi terbaikmu tanpa berpura-pura jadi orang lain.",
    "Kebiasaan yang biasa kamu lakukan terasa lebih kuat hari ini, baik yang bagus maupun yang buruk. Pilih dengan sadar.",
    "Kalau sedang menimbang pilihan hidup, hari ini suara hatimu lebih jernih. Dengarkan sebelum meminta pendapat orang.",
    "Energimu tinggi di pagi hari dan bisa anjlok di sore hari. Selesaikan yang berat lebih dulu.",
    "Hari ini kamu bisa bertemu orang yang sangat mirip denganmu. Hubungan itu bisa jadi cermin yang berguna.",
    "Rasa percaya dirimu naik, tapi pastikan tidak berubah jadi keras kepala. Tetap buka ruang untuk masukan.",
    "Hari yang bagus untuk menulis jurnal. Hal yang kamu sadari hari ini bisa jadi pegangan untuk bulan-bulan ke depan.",
    "Hari ini emosimu lebih cepat naik turun. Beri jeda sebelum merespons kabar yang mengejutkan.",
    "Kamu mungkin merasa ingin mengulang cara lama yang sudah terbukti. Tidak apa-apa, asal kamu tahu alasannya.",
    "Hari ini kamu cocok mengambil peran yang sesuai sifat alamimu. Jangan memaksa jadi sosok yang bukan dirimu.",
    "Energi kembar membuat kelebihan dan kekuranganmu sama-sama terlihat. Terima keduanya tanpa perlu malu.",
    "Hari ini cocok untuk merawat tubuh. Pijat, tidur cukup, atau makan masakan rumah bisa memulihkan energi.",
    "Kalau ada keputusan tentang identitas atau jalan hidup, hari ini kamu lebih jujur pada dirimu sendiri.",
    "Hari ini orang dekat bisa memberi masukan yang tepat sasaran. Dengarkan walaupun rasanya menusuk.",
    "Energimu mudah meluap hari ini. Salurkan ke olahraga atau hobi yang membuatmu bergerak.",
    "Hari ini cocok untuk merapikan barang pribadi. Menata ruang sendiri membantu menata pikiran.",
    "Kamu mungkin lebih sensitif terhadap kritik tentang kepribadianmu. Ambil yang membangun, abaikan yang cuma menghakimi.",
    "Hari ini kamu bisa merasa sangat yakin sekaligus ragu. Keduanya wajar, ambil langkah kecil yang paling aman.",
    "Hari ini cocok untuk menyusun ulang prioritas pribadimu. Apa yang dulu penting bisa jadi sudah berubah.",
    "Energi Ben Ming membuat nostalgia lebih kuat. Kenang yang baik, tapi jangan terjebak di sana.",
    "Hari ini lebih baik tidak membuat janji besar. Energi yang melonjak bisa membuatmu menjanjikan lebih dari sanggupmu.",
    "Kalau ada yang memuji keunikanmu, terima dengan hangat. Hari ini keunikan itu adalah kekuatanmu.",
    "Hari ini kamu lebih mudah fokus pada tujuan pribadi. Gunakan untuk satu langkah konkret, sekecil apa pun.",
    "Energi yang kuat ini perlu penyeimbang. Luangkan waktu tanpa layar sebelum tidur malam ini.",
    "Hari kembar mengingatkan kamu pada titik awalmu. Lihat sejauh apa kamu sudah melangkah, dan beri dirimu apresiasi.",
]
DAILY_PING_MESSAGES = [
    "Energi kosmik hari ini cukup seimbang. Lakukan aktivitas rutinitasmu dengan pikiran tenang.",
    "Hari yang damai dan stabil. Tidak ada kejutan besar — nikmati ketenangan ini untuk recharge energimu.",
    "Energi netral berarti kamu punya kendali penuh atas harimu. Mau produktif atau santai, semua terserahmu.",
    "Hari yang cocok untuk menyelesaikan pekerjaan yang tertunda. Tidak ada gangguan kosmik yang berarti.",
    "Keseimbangan energi hari ini mendukung aktivitas sehari-hari. Fokus, selesaikan, dan nikmati prosesnya.",
    "Hari biasa yang bisa kamu ubah jadi luar biasa dengan sikap positif. Energi kosmik mendukung niat baikmu.",
    "Tidak ada badai, tidak ada pelangi ganda — tapi ada kedamaian yang cukup untuk menyelesaikan banyak hal.",
    "Energi hari ini seperti air tenang: jernih dan menenangkan. Bagus untuk berpikir jernih dan membuat rencana.",
    "Hari yang netral adalah kanvas kosong. Kamu yang menentukan warnanya — mau diisi produktivitas atau quality time.",
    "Kosmik lagi dalam mode 'standby'. Manfaatkan untuk mengejar tugas-tugas kecil yang sering kamu tunda.",
    "Hari yang tenang untuk memulihkan energi dari hari-hari sebelumnya yang mungkin intens. Self-care time!",
    "Tidak ada urgensi kosmik hari ini. Nikmati secangkir teh, baca buku, atau sekadar menikmati momen.",
    "Energi stabil cocok untuk belajar hal baru atau mengasah skill. Otakmu siap menyerap informasi dengan baik.",
    "Hari yang bagus untuk bonding dengan keluarga atau teman dekat. Energi hangat dan nyaman menyelimuti interaksimu.",
    "Kosmik memberikan jeda hari ini. Gunakan untuk merencanakan langkah besar yang akan kamu ambil di hari-hari mendatang.",
    "Hari netral adalah hadiah tersembunyi — tidak semua orang bisa menikmati ketenangan di tengah hiruk-pikuk kehidupan.",
    "Energi hari ini mendukung konsistensi. Kalau kamu punya rutinitas bagus, hari ini hasilnya terasa lebih nyata.",
    "Tidak ada friksi, tidak ada drama. Hari yang sempurna untuk menata ulang kamar, meja kerja, atau bahkan pikiranmu.",
    "Hari yang damai untuk introspeksi ringan. Coba tanya pada dirimu: 'Apa satu hal yang bisa aku syukuri hari ini?'",
    "Energi seimbang membuat semua aspek hidupmu berjalan smooth. Karir aman, asmara tenang, keuangan stabil. Nikmati!",
    "Hari ini cocok untuk menyelesaikan pekerjaan rumah yang tertunda. Hasilnya kecil, tapi rasa leganya besar.",
    "Energi yang tenang mendukung kebiasaan membaca. Lima belas menit saja sudah cukup untuk memulai lagi.",
    "Hari yang bagus untuk mengecek kesehatan rutin atau membuat janji dokter yang sudah lama ditunda.",
    "Tidak ada gangguan besar hari ini. Gunakan untuk mengatur ulang jadwal minggu depan dengan lebih realistis.",
    "Hari ini cocok untuk memasak sendiri. Kegiatan sederhana bisa jadi cara menenangkan pikiran.",
    "Energi netral memudahkan kamu berpikir jangka panjang. Tulis satu rencana untuk tiga bulan ke depan.",
    "Hari ini cocok untuk merapikan galeri foto dan berkas di ponsel. Ruang digital yang lega ikut melegakan kepala.",
    "Tidak ada yang mendesak hari ini. Beri kabar pada satu orang yang sudah lama tidak kamu sapa.",
    "Hari ini cocok untuk latihan keterampilan yang butuh pengulangan. Kemajuan kecil terasa lebih konsisten.",
    "Energi yang stabil membuat hari ini cocok untuk membereskan administrasi dan dokumen pribadi.",
    "Hari ini kamu bisa bekerja dengan ritme sendiri. Manfaatkan untuk tugas yang butuh konsentrasi panjang.",
    "Tidak ada badai hari ini, jadi coba satu hal baru yang kecil. Rute baru ke kantor pun cukup.",
    "Hari yang tenang untuk mengevaluasi pengeluaran bulan ini. Tidak ada tekanan, jadi angkanya bisa dibaca jujur.",
    "Hari ini cocok untuk berolahraga ringan tanpa target. Bergerak demi merasa enak, bukan demi angka.",
    "Energi netral bagus untuk mendengarkan. Tanyakan kabar teman dan dengarkan sampai selesai.",
    "Hari ini cocok untuk memperbaiki barang kecil yang rusak. Beres sedikit demi sedikit terasa memuaskan.",
    "Tidak ada kejutan besar hari ini. Nikmati rutinitasmu, kadang yang biasa justru paling menenangkan.",
    "Hari ini cocok untuk menyusun daftar belanja dan menu seminggu. Hemat tenaga dan uang untuk hari-hari berikutnya.",
    "Energi seimbang membuat hari ini cocok untuk belajar hal teoritis. Otakmu sedang siap menyerap penjelasan panjang.",
    "Hari ini cocok untuk merawat tanaman atau hewan peliharaan. Merawat yang lain ikut merawat dirimu.",
    "Tidak ada tekanan hari ini, jadi cobalah tidur lebih awal. Tabungan istirahat berguna untuk hari yang lebih sibuk.",
    "Hari ini cocok untuk menata ulang meja kerja. Lingkungan yang rapi membantu fokusmu bertahan lebih lama.",
    "Energi netral memberi ruang untuk berpikir tanpa terburu-buru. Timbang ulang satu keputusan yang kemarin kamu ambil cepat.",
    "Hari ini cocok untuk menulis catatan syukur. Hal kecil yang berjalan baik sering terlewat kalau tidak ditulis.",
    "Hari yang datar bukan hari yang sia-sia. Kemajuan yang tenang tetap kemajuan.",
]
SHIO_DAILY_TIPS = {
    "tikus": [
        "Tips Tikus: Insting bisnismu tajam hari ini. Kalau ada firasat soal peluang, jangan diabaikan!",
        "Tips Tikus: Jangan terlalu banyak mikir. Kadang overthinking adalah musuh terbesar orang secerdik kamu.",
        "Tips Tikus: Hari yang bagus untuk networking. Sapa orang baru — kamu gak pernah tahu siapa yang jadi koneksi penting.",
        "Tips Tikus: Sifat adaptifmu adalah superpower. Kalau ada perubahan mendadak, kamu yang paling siap menghadapinya.",
        "Tips Tikus: Hati-hati sama kecenderunganmu untuk mengontrol segalanya. Lepaskan sedikit, biarkan alam bekerja.",
        "Tips Tikus: Coba kurangi multitasking hari ini. Fokus satu hal dan selesaikan sampai tuntas.",
        "Tips Tikus: Kreativitasmu sedang tinggi! Tulis ide-ide yang muncul — salah satunya bisa jadi game changer.",
        "Tips Tikus: Jangan lupa makan teratur. Kamu sering terlalu fokus kerja sampai lupa isi perut.",
        "Tips Tikus: Hari yang cocok untuk menabung atau review keuangan. Sisi cermatmu lagi kuat!",
        "Tips Tikus: Sesekali tunjukkan sisi vulnerablemu ke orang terdekat. Gak harus selalu keliatan kuat.",
        "Tips Tikus: Sebelum mengambil peluang, tanyakan siapa yang ikut untung selain kamu. Kesepakatan yang adil lebih awet.",
        "Tips Tikus: Bayar satu utang kecil hari ini tanpa ditagih. Nama baikmu lebih berharga dari uang yang tertahan.",
        "Tips Tikus: Kamu cepat membaca situasi, tapi jangan langsung menyimpulkan niat orang. Tanya dulu sebelum menilai.",
        "Tips Tikus: Hari ini cocok untuk membatalkan satu langganan yang sudah tidak kamu pakai. Hemat kecil yang pasti.",
        "Tips Tikus: Kalau ada yang minta tolong, bantu dulu tanpa menghitung balasannya. Rezeki sering datang dari arah itu.",
        "Tips Tikus: Coba cerita soal rencanamu ke satu orang yang kamu percaya. Masukan mereka bisa menambal celah yang tidak kamu lihat.",
        "Tips Tikus: Tidak semua informasi perlu kamu simpan untuk nanti. Lepaskan yang tidak ada hubungannya dengan hidupmu.",
        "Tips Tikus: Hari ini lebih baik menyelesaikan satu proyek daripada memulai tiga rencana baru.",
        "Tips Tikus: Istirahat cukup malam ini. Otak yang terus menghitung juga butuh waktu tidak menghitung apa pun.",
        "Tips Tikus: Traktir orang yang sering membantumu. Terima kasih yang nyata terasa lebih dari ucapan.",
        "Tips Tikus: Kalau ragu soal keputusan uang, tunda satu malam. Pagi hari biasanya membawa angka yang lebih jujur.",
        "Tips Tikus: Jangan bandingkan penghasilanmu dengan orang lain hari ini. Setiap orang membayar harga yang tidak terlihat.",
        "Tips Tikus: Kamu pandai mencari jalan keluar. Hari ini, gunakan untuk membantu teman yang sedang buntu.",
        "Tips Tikus: Kurangi mengecek harga dan saldo berulang kali. Kekhawatiran tidak menambah isi rekening.",
        "Tips Tikus: Hari ini cocok untuk belajar investasi dari sumber yang jelas, bukan dari rumor di grup.",
        "Tips Tikus: Akui kalau kamu salah hitung. Mengaku lebih cepat membuat orang tetap percaya padamu.",
        "Tips Tikus: Beri dirimu hadiah kecil tanpa rasa bersalah. Kerja kerasmu layak dirayakan sesekali.",
        "Tips Tikus: Jaga ucapanmu soal orang yang tidak ada di ruangan. Cerita itu bisa berbalik padamu.",
        "Tips Tikus: Hari ini, dengarkan lebih lama sebelum menawarkan solusi. Kadang orang cuma butuh didengar.",
        "Tips Tikus: Tulis tiga hal yang sudah kamu capai bulan ini. Kamu lebih maju dari yang kamu rasakan.",
    ],
    "kerbau": [
        "Tips Kerbau: Konsistensimu adalah kekuatan terbesar. Terus jalan di jalurmu meski orang lain berbelok.",
        "Tips Kerbau: Coba sedikit lebih fleksibel hari ini. Rencana yang berubah bukan berarti bencana.",
        "Tips Kerbau: Hari yang bagus untuk menyelesaikan proyek jangka panjang. Stamina kosmimu sedang prima.",
        "Tips Kerbau: Jangan simpan perasaan terlalu dalam. Curhat ke satu orang terpercaya bisa sangat meringankan.",
        "Tips Kerbau: Sisi perfeksionismu mungkin muncul kuat hari ini. Ingat: done is better than perfect.",
        "Tips Kerbau: Istirahat itu bukan kelemahan. Kamu sudah bekerja sangat keras — beri dirimu jeda.",
        "Tips Kerbau: Coba masakan baru atau restoran baru hari ini. Keluar dari zona nyaman dimulai dari hal kecil.",
        "Tips Kerbau: Jangan biarkan keras kepalamu merusak hubungan. Kadang mengalah bukan berarti kalah.",
        "Tips Kerbau: Fokusmu pada detail sangat diapresiasi orang lain. Kamu mungkin gak sadar betapa diandalkannya kamu.",
        "Tips Kerbau: Hari yang cocok untuk olahraga berat. Energi fisikmu sedang melimpah!",
        "Tips Kerbau: Kalau ada cara kerja baru yang lebih cepat, coba sekali. Tidak cocok pun kamu tetap belajar sesuatu.",
        "Tips Kerbau: Sampaikan keberatanmu hari ini juga. Menunggu terlalu lama membuat masalah kecil ikut membatu.",
        "Tips Kerbau: Terima bantuan yang ditawarkan tanpa merasa kalah. Kamu tetap orang yang paling bisa diandalkan.",
        "Tips Kerbau: Hari ini jadwalkan waktu santai sungguhan. Istirahat juga pekerjaan yang harus kamu jalankan dengan serius.",
        "Tips Kerbau: Tanyakan pendapat orang yang lebih muda darimu. Sudut pandang mereka bisa memperbarui caramu.",
        "Tips Kerbau: Ucapkan terima kasih secara langsung pada orang yang membantumu. Kerja diam-diam juga perlu disebut.",
        "Tips Kerbau: Periksa kesehatan punggung dan bahumu. Kerja keras bertahun-tahun sering menumpuk di sana.",
        "Tips Kerbau: Hari ini cocok untuk menyelesaikan satu tugas panjang dalam satu duduk. Fokusmu sedang tahan lama.",
        "Tips Kerbau: Jangan menunggu diminta untuk bicara soal gaji atau hakmu. Diam bukan jaminan dihargai.",
        "Tips Kerbau: Coba ubah satu hal kecil di rutinitasmu. Perubahan kecil melatih kamu untuk perubahan besar.",
        "Tips Kerbau: Kalau lelah, bilang lelah. Orang di sekitarmu tidak bisa membantu hal yang tidak kamu ceritakan.",
        "Tips Kerbau: Hari ini jangan mengambil pekerjaan tambahan. Porsi yang sekarang sudah cukup berat.",
        "Tips Kerbau: Sabarmu adalah kekuatan, tapi jangan dipakai untuk menahan hal yang sebenarnya tidak adil.",
        "Tips Kerbau: Rencanakan liburan kecil, walau cuma satu hari. Kamu butuh jeda yang direncanakan, bukan kebetulan.",
        "Tips Kerbau: Maafkan satu kesalahan orang yang sudah lama kamu simpan. Bebannya lebih berat untukmu daripada untuknya.",
        "Tips Kerbau: Hari ini cocok untuk merapikan keuangan jangka panjang. Tabunganmu bisa bekerja lebih baik.",
        "Tips Kerbau: Beri dirimu izin untuk berubah pikiran. Mengubah keputusan karena fakta baru bukan kelemahan.",
        "Tips Kerbau: Ajak orang terdekat makan bersama tanpa membahas pekerjaan sama sekali.",
        "Tips Kerbau: Kalau ada yang memuji hasil kerjamu, terima saja. Tidak perlu mengecilkannya.",
        "Tips Kerbau: Hari ini lihat seberapa jauh kamu sudah berjalan. Konsistensimu membangun lebih banyak dari yang kamu sadari.",
    ],
    "macan": [
        "Tips Macan: Keberanianmu menginspirasi orang lain. Tapi hari ini, coba dengarkan dulu sebelum bertindak.",
        "Tips Macan: Jangan terlalu kompetitif hari ini. Hidup bukan lomba — kadang jalan santai lebih menikmati pemandangan.",
        "Tips Macan: Energi dominanmu bisa overwhelm orang lain. Sedikit kelembutan akan membuat pesanmu lebih didengar.",
        "Tips Macan: Hari yang cocok untuk petualangan kecil. Jelajahi tempat baru, coba makanan yang belum pernah kamu coba.",
        "Tips Macan: Intuisi Macan lagi tajam. Kalau ada sesuatu yang 'gak beres', kemungkinan besar firasatmu benar.",
        "Tips Macan: Channel energi agresifmu ke olahraga atau hobi kreatif. Jangan ke drama medsos.",
        "Tips Macan: Kamu natural born leader, tapi hari ini cobalah jadi follower yang supportive. Tim butuh itu.",
        "Tips Macan: Jangan abaikan sinyal tubuhmu. Kamu sering push diri terlalu keras sampai burnout.",
        "Tips Macan: Hari yang bagus untuk mengambil risiko yang sudah kamu perhitungkan matang.",
        "Tips Macan: Sisi unpredictable-mu kadang bikin orang bingung. Coba konsisten di satu hal hari ini.",
        "Tips Macan: Sebelum memutuskan hal besar, tunggu satu jam. Keberanianmu lebih tajam kalau didampingi jeda.",
        "Tips Macan: Beri pujian tulus pada satu orang di timmu hari ini. Pemimpin yang hebat membuat orang lain ikut bersinar.",
        "Tips Macan: Kalau ada yang tidak setuju, tanya alasannya sebelum membantah. Kamu bisa menemukan sudut yang terlewat.",
        "Tips Macan: Hari ini cocok untuk menuntaskan satu janji lama. Kata-katamu lebih berharga kalau selalu ditepati.",
        "Tips Macan: Turunkan intensitas saat bicara dengan orang yang lebih pendiam. Mereka butuh ruang untuk menjawab.",
        "Tips Macan: Minta maaf lebih dulu kalau kemarin kamu terlalu keras. Itu tidak mengurangi wibawamu.",
        "Tips Macan: Salurkan emosi panas ke olahraga intens. Tubuh yang lelah membuat kepala lebih dingin.",
        "Tips Macan: Hari ini jangan mengambil alih pekerjaan orang lain. Percayai mereka menyelesaikan bagiannya.",
        "Tips Macan: Rencanakan langkah kedua sebelum mengambil langkah pertama. Keberanian yang terencana lebih sering menang.",
        "Tips Macan: Istirahat sebelum benar-benar kehabisan tenaga. Kamu sering baru berhenti saat sudah terlambat.",
        "Tips Macan: Tunjukkan sisi lembutmu ke orang terdekat. Mereka ingin mengenal lebih dari sisi kuatmu.",
        "Tips Macan: Hari ini cocok untuk membimbing orang yang baru belajar. Kesabaranmu akan terlatih di situ.",
        "Tips Macan: Jangan membalas komentar pedas dengan yang lebih pedas. Diam yang tenang lebih membuat lawan berpikir.",
        "Tips Macan: Periksa lagi keuangan sebelum mengikuti tantangan atau taruhan dengan teman.",
        "Tips Macan: Kalau kamu salah arah, putar balik dengan cepat. Bertahan demi gengsi lebih mahal.",
        "Tips Macan: Hari ini tanyakan pada dirimu, apa yang sedang kamu buktikan dan untuk siapa.",
        "Tips Macan: Dengarkan cerita orang sampai selesai tanpa menyambungkannya ke pengalamanmu.",
        "Tips Macan: Coba selesaikan konflik lama dengan satu percakapan jujur. Kamu cukup berani untuk memulainya.",
        "Tips Macan: Pilih satu target dan kejar sampai tuntas bulan ini. Energi yang terpusat jauh lebih kuat.",
        "Tips Macan: Beri dirimu penghargaan atas keberanian yang kemarin tidak kelihatan oleh siapa pun.",
    ],
    "kelinci": [
        "Tips Kelinci: Elegansi dan kelembutan adalah kekuatanmu. Jangan pernah anggap itu kelemahan.",
        "Tips Kelinci: Hari ini cocok untuk aktivitas kreatif — melukis, menulis, memasak, atau mendekorasi.",
        "Tips Kelinci: Jangan terlalu menghindari konflik. Kadang menyuarakan pendapat itu penting untuk dirimu sendiri.",
        "Tips Kelinci: Waspada terhadap energi orang lain yang terlalu negatif. Lindungi batinmu yang sensitif.",
        "Tips Kelinci: Ketenangan batinmu hari ini bisa jadi jangkar bagi orang-orang di sekitarmu yang sedang kacau.",
        "Tips Kelinci: Coba tantang dirimu untuk keluar dari comfort zone — meski cuma sedikit. Kamu lebih kuat dari yang kamu kira.",
        "Tips Kelinci: Hari yang bagus untuk merawat tanaman, menata rumah, atau melakukan sesuatu yang nurturing.",
        "Tips Kelinci: Jangan ragu bilang 'tidak' kalau memang kamu merasa sudah kewalahan. Itu bukan egois, itu self-respect.",
        "Tips Kelinci: Sisi diplomatismu sangat dibutuhkan hari ini. Kamu bisa jadi mediator alami untuk konflik orang lain.",
        "Tips Kelinci: Luangkan waktu untuk dirimu sendiri. Me-time bukan kemewahan — itu kebutuhan esensial Kelinci.",
        "Tips Kelinci: Sampaikan satu pendapat yang biasanya kamu simpan. Suaramu penting walau pelan.",
        "Tips Kelinci: Hari ini cocok untuk menolak satu permintaan yang memberatkan. Batasmu layak dihormati.",
        "Tips Kelinci: Kalau ada yang mengganjal, tulis dulu kalimatnya. Membaca ulang membantu kamu berani menyampaikannya.",
        "Tips Kelinci: Jangan jadi penengah untuk konflik yang bukan urusanmu. Biarkan mereka menyelesaikannya sendiri.",
        "Tips Kelinci: Kamu pandai membuat suasana nyaman. Hari ini, buat juga suasana nyaman untuk dirimu sendiri.",
        "Tips Kelinci: Coba ambil satu keputusan kecil tanpa bertanya pada siapa pun. Percayai penilaianmu.",
        "Tips Kelinci: Hari ini cocok untuk menata ruang tidurmu. Tempat yang tenang membuat istirahatmu lebih dalam.",
        "Tips Kelinci: Kalau kamu kecewa, sebut saja kecewanya. Diam tidak membuat perasaannya hilang.",
        "Tips Kelinci: Batasi waktu mendengarkan keluhan orang lain. Energimu juga perlu diisi ulang.",
        "Tips Kelinci: Terima pujian tanpa langsung membalasnya dengan merendah. Kamu memang pantas dipuji.",
        "Tips Kelinci: Hari ini cocok untuk kegiatan yang melatih keberanian kecil, seperti menyapa orang baru.",
        "Tips Kelinci: Periksa lagi janji yang kamu iyakan karena tidak enak. Lepaskan yang sebenarnya tidak sanggup kamu penuhi.",
        "Tips Kelinci: Kalau ada konflik, hadapi dengan tenang daripada menghindar. Kamu lebih kuat dari rasa takutmu.",
        "Tips Kelinci: Luangkan waktu untuk hobi yang menenangkan. Itu cara terbaikmu memulihkan tenaga.",
        "Tips Kelinci: Jangan menebak perasaan orang dari nada chat. Tanyakan langsung kalau ragu.",
        "Tips Kelinci: Hari ini cocok untuk meminta hal yang kamu butuhkan dengan kalimat yang jelas.",
        "Tips Kelinci: Kamu tidak harus menyenangkan semua orang. Cukup jujur dan sopan.",
        "Tips Kelinci: Rapikan jadwalmu supaya ada jeda di antara pertemuan. Kamu butuh waktu menyendiri untuk pulih.",
        "Tips Kelinci: Coba sampaikan keinginanmu tanpa minta maaf lebih dulu.",
        "Tips Kelinci: Hargai dirimu hari ini karena sudah menjaga kedamaian banyak orang. Sekarang giliran menjaga dirimu.",
    ],
    "naga": [
        "Tips Naga: Percaya dirimu menular ke orang lain. Gunakan energi itu untuk memotivasi timmu.",
        "Tips Naga: Hari ini jangan terlalu dominan dalam diskusi. Beri ruang orang lain untuk bersinar juga.",
        "Tips Naga: Antusiasme Naga bisa jadi bumerang kalau gak diimbangi perencanaan. Mikir dulu, baru terbang!",
        "Tips Naga: Hari yang cocok untuk menyusun visi besar. Kamu Naga — impianmu memang seharusnya besar!",
        "Tips Naga: Sisi perfeksionis dan dominanmu kadang bikin orang lain merasa kurang. Puji orang lain hari ini.",
        "Tips Naga: Energi leadershipmu sedang kuat. Kalau ada masalah tim, kamu yang paling bisa menyelesaikannya.",
        "Tips Naga: Jangan takut menunjukkan sisi vulnerablemu. Kekuatan Naga sejati terletak pada keberanian untuk jujur.",
        "Tips Naga: Hari yang bagus untuk belajar hal baru. Otak Naga haus pengetahuan dan hari ini penyerapannya maksimal.",
        "Tips Naga: Hati-hati dengan ego. Kadang pendapat orang lain juga bisa lebih baik dari idemu.",
        "Tips Naga: Kamu ditakdirkan untuk hal-hal besar. Tapi jangan lupa, hal-hal kecil juga punya makna.",
        "Tips Naga: Pecah rencana besarmu jadi tiga langkah kecil. Kerjakan langkah pertama hari ini juga.",
        "Tips Naga: Beri kredit pada orang yang membantu di belakang layar. Kesuksesanmu dibangun bersama mereka.",
        "Tips Naga: Dengarkan kritik hari ini tanpa langsung membela diri. Ambil satu poin yang masuk akal.",
        "Tips Naga: Kalau sedang lelah, akui saja. Kamu tidak harus selalu tampil kuat di depan semua orang.",
        "Tips Naga: Hari ini cocok untuk menyelesaikan pekerjaan detail yang biasanya kamu serahkan ke orang lain.",
        "Tips Naga: Tanyakan pendapat orang yang paling pendiam di timmu. Ide terbaik sering datang dari sana.",
        "Tips Naga: Jangan mengumumkan rencana sebelum ada langkah nyata. Bukti lebih meyakinkan daripada janji.",
        "Tips Naga: Periksa lagi anggaran sebelum membeli sesuatu demi penampilan. Nilaimu tidak ditentukan oleh barangmu.",
        "Tips Naga: Beri ruang orang lain memimpin sesekali. Kepemimpinanmu tetap terlihat dari caramu mendukung.",
        "Tips Naga: Hari ini cocok untuk merawat hubungan lama yang mulai renggang karena kesibukanmu.",
        "Tips Naga: Kalau rencanamu gagal, cari pelajarannya dulu sebelum mencari yang salah.",
        "Tips Naga: Nikmati pencapaian kecil tanpa langsung memasang target berikutnya.",
        "Tips Naga: Jangan ambil semua tanggung jawab sendirian. Delegasikan dengan kepercayaan penuh.",
        "Tips Naga: Hari ini coba jadi murid dalam hal yang belum kamu kuasai. Rasa ingin tahu membuatmu tetap tumbuh.",
        "Tips Naga: Jaga nada bicara saat memberi arahan. Arahan yang lembut lebih cepat dijalankan.",
        "Tips Naga: Istirahatkan dirimu dari layar dan pujian online sejenak. Kepala yang tenang membuat visimu lebih jernih.",
        "Tips Naga: Rayakan keberhasilan orang lain dengan tulus. Itu tidak mengurangi cahayamu.",
        "Tips Naga: Hari ini tulis ulang tujuan jangka panjangmu. Pastikan itu masih sesuatu yang benar-benar kamu inginkan.",
        "Tips Naga: Tepati janji kecil sama seriusnya dengan janji besar.",
        "Tips Naga: Ingat, kamu tidak harus sempurna untuk dihargai. Kamu sudah cukup berharga apa adanya.",
    ],
    "ular": [
        "Tips Ular: Kebijaksanaanmu adalah aset paling berharga. Hari ini, gunakan untuk menasihati orang yang membutuhkan.",
        "Tips Ular: Jangan terlalu misterius. Kadang keterbukaan justru menarik orang lebih dekat padamu.",
        "Tips Ular: Intuisi Ular sedang sangat tajam hari ini. Firasat pertamamu hampir pasti benar.",
        "Tips Ular: Kamu tipe yang menyimpan dendam lama. Hari ini, coba lepaskan satu hal yang sudah membebanmu.",
        "Tips Ular: Hari yang bagus untuk riset, analisis, atau memecahkan masalah yang rumit. Otakmu sedang sharp!",
        "Tips Ular: Sisi materialistismu mungkin muncul hari ini. Ingatkan dirimu: hal-hal terbaik dalam hidup itu gratis.",
        "Tips Ular: Kamu punya aura magnetik alami. Gunakan untuk menarik peluang, bukan untuk memanipulasi.",
        "Tips Ular: Hari yang cocok untuk meditasi atau mindfulness. Kedalaman batinmu perlu diisi ulang secara rutin.",
        "Tips Ular: Jangan over-analyze hubunganmu hari ini. Kadang cinta itu sederhana — tidak perlu dibedah.",
        "Tips Ular: Sisi bijaksanamu sangat dibutuhkan di situasi yang sedang kacau. Jadi penengah hari ini.",
        "Tips Ular: Ceritakan satu hal tentang dirimu ke orang yang kamu percaya. Keterbukaan kecil memperdalam hubungan.",
        "Tips Ular: Hari ini jangan mengumpulkan bukti untuk keputusan yang sudah kamu ambil. Pertimbangkan dari awal.",
        "Tips Ular: Kalau ada yang mengecewakan, sampaikan langsung. Menyimpan dan menunggu hanya memperpanjang lukanya.",
        "Tips Ular: Kemampuan analisismu tajam. Gunakan untuk membantu orang lain, bukan untuk menilai mereka.",
        "Tips Ular: Hari ini cocok untuk menyelesaikan tugas yang butuh ketelitian tinggi. Fokusmu sedang dalam.",
        "Tips Ular: Beri orang kesempatan kedua yang sungguh-sungguh. Tidak semua kesalahan berasal dari niat buruk.",
        "Tips Ular: Kalau ada tawaran yang bagus, jangan curigai berlebihan. Kadang hal baik memang datang tanpa jebakan.",
        "Tips Ular: Luangkan waktu tanpa menganalisis apa pun. Pikiranmu juga butuh diam sebentar.",
        "Tips Ular: Hari ini coba minta pendapat orang lain sebelum memutuskan sendirian.",
        "Tips Ular: Lepaskan satu dendam kecil. Energi yang tersimpan di sana bisa dipakai untuk hal lain.",
        "Tips Ular: Sampaikan terima kasih secara terbuka. Orang ingin tahu bahwa kamu menghargai mereka.",
        "Tips Ular: Hari ini cocok untuk merapikan rencana keuangan jangka panjang dengan kepala dingin.",
        "Tips Ular: Jangan menguji kesetiaan orang lewat sikap dingin. Tanyakan langsung apa yang kamu ingin tahu.",
        "Tips Ular: Kamu pengamat yang hebat. Hari ini, biarkan juga dirimu diamati dan dikenal.",
        "Tips Ular: Kurangi mengecek ulang hal yang sudah jelas. Kepercayaan juga perlu dilatih.",
        "Tips Ular: Hari ini cocok untuk membaca atau belajar hal yang mendalam. Otakmu sedang menikmati kerumitan.",
        "Tips Ular: Kalau merasa kesepian, hubungi satu orang. Kamu tidak harus menunggu mereka yang memulai.",
        "Tips Ular: Tunjukkan emosimu sesekali. Orang lebih mudah dekat dengan yang terasa manusiawi.",
        "Tips Ular: Jangan menyimpan rencana keluar di hubungan yang masih ingin kamu pertahankan.",
        "Tips Ular: Hari ini beri dirimu kelonggaran. Tidak semua hal perlu kamu kendalikan.",
    ],
    "kuda": [
        "Tips Kuda: Energimu sedang meledak-ledak! Salurkan ke aktivitas produktif sebelum jadi gelisah tanpa arah.",
        "Tips Kuda: Coba sabar sedikit. Gak semua hal perlu diselesaikan hari ini — beberapa butuh waktu.",
        "Tips Kuda: Hari yang bagus untuk olahraga, travelling, atau aktivitas outdoor. Kuda butuh ruang untuk berlari!",
        "Tips Kuda: Sifat humorismu bisa mencairkan situasi tegang. Gunakan superpower ini dengan bijak.",
        "Tips Kuda: Jangan buat keputusan impulsif soal keuangan. Tidur dulu sebelum checkout barang mahal.",
        "Tips Kuda: Kamu mudah bosan — itu wajar. Tapi coba tantang dirimu untuk menyelesaikan satu hal sampai tuntas hari ini.",
        "Tips Kuda: Energi sosialmu sedang tinggi. Hari yang sempurna untuk hangout, reunian, atau kencan!",
        "Tips Kuda: Jangan tinggalkan proyek setengah jadi. Disiplin menyelesaikan adalah pelajaran terbesar untuk Kuda.",
        "Tips Kuda: Kamu adalah sumber semangat bagi orang di sekitarmu. Jangan underestimate dampak positifmu!",
        "Tips Kuda: Hari ini hindari debat panjang — kamu mudah terpancing dan bilang hal yang kamu sesali.",
        "Tips Kuda: Selesaikan satu tugas lama sebelum memulai yang baru hari ini.",
        "Tips Kuda: Kalau ingin membatalkan janji, kabari secepatnya. Menghilang lebih menyakitkan daripada bilang tidak bisa.",
        "Tips Kuda: Hari ini cocok untuk olahraga di luar ruangan. Tubuhmu butuh ruang untuk bergerak bebas.",
        "Tips Kuda: Tulis semua rencana yang sedang kamu jalankan. Lihat mana yang bisa dilepas dengan tenang.",
        "Tips Kuda: Jangan membeli tiket atau barang secara mendadak hari ini. Tunggu sampai jadwalmu pasti.",
        "Tips Kuda: Dengarkan orang yang lebih lambat darimu. Mereka sering melihat hal yang kamu lewati.",
        "Tips Kuda: Hari ini coba bertahan di satu tempat lebih lama dari biasanya. Kesabaran juga bisa dilatih.",
        "Tips Kuda: Kalau bosan, jangan langsung pergi. Cari hal baru di tempat yang sama.",
        "Tips Kuda: Beri kabar pada orang yang menunggu jawabanmu. Kepastian lebih berharga dari janji manis.",
        "Tips Kuda: Periksa lagi pengeluaran untuk hiburan bulan ini. Kesenangan spontan cepat menumpuk.",
        "Tips Kuda: Hari ini cocok untuk mengajak teman melakukan kegiatan fisik bersama.",
        "Tips Kuda: Kalau ada yang mengkritik kebiasaanmu berpindah-pindah, dengarkan dulu. Mungkin ada benarnya.",
        "Tips Kuda: Tidur cukup malam ini. Energimu yang besar tetap butuh diisi ulang.",
        "Tips Kuda: Jangan berkomitmen ke terlalu banyak hal sekaligus. Pilih yang benar-benar kamu mau.",
        "Tips Kuda: Hari ini coba rencanakan akhir pekan sejak awal, bukan dadakan di hari itu.",
        "Tips Kuda: Minta maaf secara langsung kalau kemarin kamu meninggalkan seseorang tanpa kabar.",
        "Tips Kuda: Kejujuranmu menyegarkan, tapi pilih waktu yang tepat untuk menyampaikannya.",
        "Tips Kuda: Hari ini cocok untuk menata dokumen penting yang sering kamu abaikan.",
        "Tips Kuda: Rayakan satu hal yang berhasil kamu tuntaskan. Itu bukti kamu bisa konsisten.",
        "Tips Kuda: Kebebasan paling terasa saat kamu tidak meninggalkan urusan yang menggantung.",
    ],
    "kambing": [
        "Tips Kambing: Kepekaan emosionalmu adalah hadiah, bukan beban. Hari ini, gunakan untuk memahami orang lain.",
        "Tips Kambing: Jangan terlalu bergantung pada validasi orang lain. Kamu sudah cukup baik apa adanya.",
        "Tips Kambing: Hari yang cocok untuk kegiatan artistik — musik, puisi, fashion, atau apapun yang melibatkan estetika.",
        "Tips Kambing: Sisi pemalumu mungkin muncul kuat hari ini. Tapi ingat, di balik ketenanganmu ada kekuatan yang luar biasa.",
        "Tips Kambing: Kelilingi dirimu dengan orang-orang positif. Energi negatif orang lain sangat mudah memengaruhi Kambing.",
        "Tips Kambing: Hari yang bagus untuk merapikan rumah atau workspace. Kambing butuh lingkungan yang tenang dan indah.",
        "Tips Kambing: Jangan overthinking soal masa depan. Fokus pada hari ini — masa depan akan mengikuti langkahmu.",
        "Tips Kambing: Sisi simpatikmu sangat diapresiasi. Tapi jangan sampai kamu mengorbankan dirimu sendiri untuk orang lain terus.",
        "Tips Kambing: Coba berjemur di bawah matahari pagi 10 menit. Energi alam sangat membantu recharge batin Kambing.",
        "Tips Kambing: Kamu lebih tangguh dari yang kamu kira. Hari ini, buktikan itu pada dirimu sendiri.",
        "Tips Kambing: Pilih satu hal hari ini dan pertahankan tanpa meminta pendapat ulang.",
        "Tips Kambing: Kalau butuh ditemani, bilang langsung. Orang terdekatmu senang diminta.",
        "Tips Kambing: Hari ini batasi waktu memikirkan kemungkinan terburuk. Beri dirimu waktu lima belas menit, lalu berhenti.",
        "Tips Kambing: Tulis perasaanmu sebelum menceritakannya ke orang lain. Kamu jadi lebih paham apa yang sebenarnya kamu butuhkan.",
        "Tips Kambing: Jangan membaca ulang chat lama untuk mencari tanda bahwa kamu tidak disukai.",
        "Tips Kambing: Hari ini cocok untuk kegiatan kreatif yang tidak perlu dinilai siapa pun.",
        "Tips Kambing: Terima satu solusi yang ditawarkan orang, walau rasanya belum sempurna.",
        "Tips Kambing: Kamu layak mendapat hal baik tanpa harus membuktikan apa pun lebih dulu.",
        "Tips Kambing: Kurangi membandingkan hidupmu dengan unggahan orang lain hari ini.",
        "Tips Kambing: Hari ini coba selesaikan satu tugas kecil yang sering kamu tunda karena takut salah.",
        "Tips Kambing: Kalau capek memberi, berhenti sejenak. Itu bukan egois, itu merawat diri.",
        "Tips Kambing: Sampaikan kekecewaan dengan kalimat pendek dan jelas. Tidak perlu lewat sindiran.",
        "Tips Kambing: Hari ini cocok untuk jalan kaki santai. Gerak pelan membantu menenangkan pikiran.",
        "Tips Kambing: Jangan menunggu diyakinkan terus untuk percaya bahwa kamu disayang.",
        "Tips Kambing: Tanyakan langsung kalau kamu ragu dengan niat seseorang. Menebak hanya menambah cemas.",
        "Tips Kambing: Hari ini rapikan satu sudut kecil di kamarmu. Lingkungan yang teratur menenangkan hatimu.",
        "Tips Kambing: Beri kesempatan pada dirimu untuk salah dan belajar dari situ.",
        "Tips Kambing: Kalau ada yang memuji, terima dan simpan. Baca lagi saat kamu merasa tidak cukup.",
        "Tips Kambing: Hari ini coba minta bantuan tanpa merasa merepotkan. Orang yang peduli justru senang membantu.",
        "Tips Kambing: Ingat, perasaanmu penting, tapi tidak selalu menggambarkan kenyataan. Beri ruang untuk fakta.",
    ],
    "monyet": [
        "Tips Monyet: Kecerdasanmu sedang bersinar hari ini. Gunakan untuk problem-solving, bukan untuk iseng nge-troll orang.",
        "Tips Monyet: Jangan spread too thin. Pilih 1–2 prioritas dan fokus — kamu bisa multitask, tapi hasilnya lebih bagus kalau fokus.",
        "Tips Monyet: Hari yang bagus untuk brainstorming dan inovasi. Ide-ide gila dari Monyet sering jadi hal revolusioner!",
        "Tips Monyet: Sisi egoismu mungkin muncul hari ini. Coba lakukan satu tindakan selfless tanpa mengharapkan apapun.",
        "Tips Monyet: Social butterfly mode: ON. Hari ini energimu cocok untuk bertemu banyak orang dan bikin suasana rame.",
        "Tips Monyet: Jangan terlalu sering menertawakan masalah serius. Kadang orang butuh kamu untuk serius dan empati.",
        "Tips Monyet: Kreativitasmu lagi overflow. Tuangkan ke proyek nyata sebelum hilang — ide Monyet datang dan pergi secepat kilat.",
        "Tips Monyet: Hari yang cocok untuk belajar skill baru. Kamu tipe yang cepat menguasai sesuatu — manfaatkan itu!",
        "Tips Monyet: Hindari bergosip hari ini. Mulut Monyet yang terlalu ramai bisa bikin masalah yang gak perlu.",
        "Tips Monyet: Kamu adalah jiwa pesta di setiap kelompok. Tapi jangan lupa, kadang teman-temanmu butuh Monyet yang serius dan suportif.",
        "Tips Monyet: Jawab satu pertanyaan serius hari ini dengan serius, tanpa lelucon.",
        "Tips Monyet: Pilih satu ide dan jalankan sampai ada hasilnya sebelum melompat ke ide berikutnya.",
        "Tips Monyet: Kalau kamu kelewatan bercanda, minta maaf tanpa menambahkan kata cuma bercanda.",
        "Tips Monyet: Hari ini cocok untuk belajar keterampilan yang butuh latihan panjang. Tantang kecepatanmu dengan kedalaman.",
        "Tips Monyet: Jaga cerita yang dipercayakan padamu. Rahasia orang bukan bahan obrolan.",
        "Tips Monyet: Tunjukkan saat kamu sedang tidak baik-baik saja. Orang terdekatmu ingin tahu.",
        "Tips Monyet: Hari ini jangan mencari celah di aturan. Jalan lurus kadang lebih cepat.",
        "Tips Monyet: Selesaikan satu tugas yang membosankan sampai tuntas. Kamu akan terkejut dengan rasa puasnya.",
        "Tips Monyet: Dengarkan orang sampai selesai sebelum menyela dengan ide.",
        "Tips Monyet: Kurangi berpindah aplikasi dan tugas. Fokus panjang membuat hasil kerjamu lebih kuat.",
        "Tips Monyet: Hari ini coba tanyakan kabar seseorang dan dengarkan jawabannya dengan sungguh-sungguh.",
        "Tips Monyet: Kalau ada yang menagih janji, akui dengan jujur. Mengelak membuat kepercayaan menurun.",
        "Tips Monyet: Hari ini cocok untuk merapikan proyek yang setengah jadi. Pilih satu untuk diselesaikan.",
        "Tips Monyet: Jangan uji kesabaran orang untuk melihat reaksinya.",
        "Tips Monyet: Tulis tiga hal yang benar-benar ingin kamu kuasai tahun ini. Fokus ke sana.",
        "Tips Monyet: Hari ini coba jadi yang paling sedikit bicara di ruangan. Kamu akan menangkap banyak hal.",
        "Tips Monyet: Kalau lelah jadi yang paling lucu, beristirahat saja. Kamu tetap disukai walau diam.",
        "Tips Monyet: Periksa pengeluaran untuk ide dadakan bulan ini. Kreativitas tidak harus mahal.",
        "Tips Monyet: Hari ini cocok untuk membantu teman memecahkan masalah yang rumit. Otakmu sedang cemerlang.",
        "Tips Monyet: Ingat, kepercayaan orang dibangun dari konsistensi, bukan dari kepintaran.",
    ],
    "ayam": [
        "Tips Ayam: Observasi tajammu hari ini bisa menangkap detail yang dilewatkan semua orang. Kamu detective kosmik!",
        "Tips Ayam: Jangan terlalu keras mengkritik dirimu sendiri. Standar tinggimu kadang jadi beban yang tidak perlu.",
        "Tips Ayam: Hari yang cocok untuk organizing — file digital, lemari pakaian, atau jadwal mingguanmu.",
        "Tips Ayam: Keberanianmu bicara jujur itu langka. Tapi hari ini, coba bungkus kejujuranmu dengan sedikit kelembutan.",
        "Tips Ayam: Sisi perfeksionismu bisa bikin orang lain insecure. Pujilah effort orang lain, bukan cuma hasilnya.",
        "Tips Ayam: Kamu pekerja keras yang sering gak diapresiasi. Hari ini, apresiasi dirimu sendiri — kamu pantas mendapatkannya.",
        "Tips Ayam: Jangan terlalu sombong soal pencapaianmu. Biarkan hasilnya yang berbicara — orang akan notice sendiri.",
        "Tips Ayam: Hari yang bagus untuk financial planning. Ketelitianmu cocok untuk bikin budget atau review investasi.",
        "Tips Ayam: Bangun lebih pagi hari ini dan nikmati ketenangan sebelum dunia ramai. Itu me-time terbaik untuk Ayam.",
        "Tips Ayam: Kamu adalah pilar kekuatan yang sering gak disadari. Hari ini, akui bahwa kamu juga boleh lemah sesekali.",
        "Tips Ayam: Sebut dulu hal yang sudah benar sebelum memberi koreksi hari ini.",
        "Tips Ayam: Biarkan satu hal kecil tidak sempurna hari ini. Dunia tetap berjalan baik.",
        "Tips Ayam: Kalau ingin memberi masukan, tanya dulu apakah orangnya sedang mau mendengarnya.",
        "Tips Ayam: Hari ini cocok untuk merapikan rencana keuangan. Ketelitianmu sedang sangat berguna.",
        "Tips Ayam: Beri dirimu pujian atas hal yang sudah kamu selesaikan, bukan hanya catatan kekurangannya.",
        "Tips Ayam: Jangan mengerjakan ulang tugas orang lain diam-diam. Ajari mereka supaya bisa sendiri.",
        "Tips Ayam: Hari ini coba istirahat tanpa merasa bersalah. Tubuhmu juga bagian dari pekerjaanmu.",
        "Tips Ayam: Turunkan standar untuk hal yang memang tidak penting. Simpan energimu untuk yang berarti.",
        "Tips Ayam: Kalau cemas, tulis daftar hal yang bisa kamu kendalikan. Fokus di situ saja.",
        "Tips Ayam: Hari ini cocok untuk menyelesaikan administrasi yang rumit. Kamu paling tahan dengan detail.",
        "Tips Ayam: Dengarkan alasan orang sebelum menilai caranya salah. Bisa jadi mereka punya pertimbangan lain.",
        "Tips Ayam: Ucapkan terima kasih atas usaha orang lain, bukan hanya hasilnya.",
        "Tips Ayam: Kurangi mengecek ulang pekerjaan yang sudah selesai. Percayai hasil kerjamu.",
        "Tips Ayam: Hari ini beri ruang untuk spontanitas kecil. Tidak semua hal harus direncanakan.",
        "Tips Ayam: Kalau kamu salah, akui dengan sederhana tanpa penjelasan panjang.",
        "Tips Ayam: Tawarkan diri merapikan jadwal teman yang berantakan. Bakat menatamu bisa jadi hadiah untuk orang lain.",
        "Tips Ayam: Jangan menilai orang dari seberapa rapi penampilan atau pekerjaannya.",
        "Tips Ayam: Luangkan waktu untuk hal yang kamu nikmati tanpa tujuan produktif.",
        "Tips Ayam: Hari ini coba sampaikan kritik dengan nada yang sama seperti kamu ingin dikritik.",
        "Tips Ayam: Ingat, kamu tidak harus memperbaiki semua hal. Beberapa hal cukup diterima.",
    ],
    "anjing": [
        "Tips Anjing: Loyalitasmu sangat dihargai oleh orang-orang terpercaya. Hari ini, biarkan mereka membalas kebaikanmu.",
        "Tips Anjing: Jangan terlalu curiga. Tidak semua orang punya niat buruk — beri kesempatan pada orang baru.",
        "Tips Anjing: Hari yang cocok untuk volunteer atau membantu orang yang membutuhkan. Hatimu akan terasa sangat puas.",
        "Tips Anjing: Sisi kehati-hatianmu kadang berlebihan. Coba ambil satu risiko kecil hari ini — hasilnya mungkin mengejutkan.",
        "Tips Anjing: Kejujuranmu adalah harta karun. Tapi hari ini, sampaikan kebenaran dengan kasih sayang, bukan blak-blakan.",
        "Tips Anjing: Kamu sering menanggung beban emosional orang lain. Hari ini, izinkan dirimu untuk melepas dan istirahat.",
        "Tips Anjing: Hari yang bagus untuk quality time dengan orang yang paling kamu percaya. Kamu butuh safe space.",
        "Tips Anjing: Jangan simpan kecemasan sendirian. Bicarakan dengan seseorang — kamu gak harus selalu jadi yang kuat.",
        "Tips Anjing: Sisi protektifmu kadang bikin orang merasa terkekang. Beri mereka ruang untuk bertumbuh sendiri.",
        "Tips Anjing: Kamu adalah definisi 'teman sejati'. Hari ini, jangan lupa jadi teman terbaik untuk dirimu sendiri.",
        "Tips Anjing: Tanya langsung kalau ada perubahan sikap yang membuatmu cemas.",
        "Tips Anjing: Hari ini bantu satu orang tanpa mencatat bantuannya di kepala.",
        "Tips Anjing: Kalau lelah menjaga semua orang, beristirahat saja. Mereka akan tetap baik-baik saja.",
        "Tips Anjing: Jangan menarik kesimpulan dari satu pesan yang dibalas singkat.",
        "Tips Anjing: Hari ini cocok untuk menghabiskan waktu dengan orang yang membuatmu merasa aman.",
        "Tips Anjing: Beri kepercayaan kecil pada orang baru. Tidak semua orang akan mengecewakanmu.",
        "Tips Anjing: Sampaikan kecemasanmu dengan tenang, bukan lewat sikap dingin.",
        "Tips Anjing: Hari ini coba ambil satu keputusan kecil yang sedikit berisiko. Kamu akan baik-baik saja.",
        "Tips Anjing: Kalau merasa kurang dihargai, katakan dengan jujur. Orang tidak bisa menebak.",
        "Tips Anjing: Batasi waktu memikirkan skenario terburuk. Gantikan dengan satu tindakan nyata.",
        "Tips Anjing: Hari ini cocok untuk membela orang yang sedang diperlakukan tidak adil. Keberanianmu berarti.",
        "Tips Anjing: Jangan menanggung masalah keluarga sendirian. Bagi bebannya dengan anggota lain.",
        "Tips Anjing: Kesetiaanmu berharga. Pastikan kamu memberikannya pada orang yang juga setia padamu.",
        "Tips Anjing: Hari ini beri orang dekat ruang untuk punya urusan sendiri tanpa kamu awasi.",
        "Tips Anjing: Kalau sudah memaafkan, jangan ungkit lagi di pertengkaran berikutnya.",
        "Tips Anjing: Periksa kesehatanmu. Kamu sering mengurus orang lain sampai lupa merawat diri.",
        "Tips Anjing: Hari ini cocok untuk mengirim pesan dukungan pada teman yang sedang berjuang.",
        "Tips Anjing: Jangan mengukur kasih sayang orang dari seberapa cepat mereka membalas.",
        "Tips Anjing: Terima bantuan tanpa merasa berutang seumur hidup.",
        "Tips Anjing: Ingat, kamu juga layak dijaga. Biarkan orang lain menjagamu sesekali.",
    ],
    "babi": [
        "Tips Babi: Kemurahan hatimu sangat mulia. Tapi hari ini, pastikan kamu juga murah hati kepada dirimu sendiri.",
        "Tips Babi: Jangan terlalu memanjakan diri sampai lupa tanggung jawab. Satu jam produktif dulu, baru reward!",
        "Tips Babi: Hari yang cocok untuk memasak sesuatu yang lezat untuk orang-orang tersayang. Food is your love language!",
        "Tips Babi: Sisi materialistismu mungkin muncul — pengen belanja ini itu. Tanya dulu: butuh atau cuma mau?",
        "Tips Babi: Kamu tipe yang diam-diam sangat rajin. Hari ini hasilnya mulai terlihat — terima pujiannya dengan bangga!",
        "Tips Babi: Jangan biarkan orang memanfaatkan kebaikanmu. Belajar bilang 'tidak' itu bukan kejahatan.",
        "Tips Babi: Hari yang bagus untuk menikmati alam — taman, pantai, atau sekadar duduk di balkon menikmati angin.",
        "Tips Babi: Welaskasihmu adalah kekuatan langka di dunia yang keras ini. Jangan pernah kehilangan sisi itu.",
        "Tips Babi: Coba evaluasi pengeluaran minggu ini. Babi yang cermat keuangannya akan menjadi Babi yang kaya raya.",
        "Tips Babi: Kamu adalah 'comfort person' bagi banyak orang. Pastikan kamu juga punya comfort person untuk dirimu sendiri.",
        "Tips Babi: Periksa dulu sebelum percaya pada cerita yang terlalu mulus. Itu bukan berarti kamu curiga berlebihan.",
        "Tips Babi: Tentukan batas berapa yang boleh kamu pinjamkan bulan ini, lalu patuhi.",
        "Tips Babi: Hari ini selesaikan satu tugas penting sebelum bersantai. Istirahatnya jadi lebih nikmat.",
        "Tips Babi: Kalau ada yang merugikanmu dua kali, beri jarak. Kebaikanmu tidak wajib tanpa batas.",
        "Tips Babi: Hari ini cocok untuk menyusun rencana sederhana untuk bulan depan.",
        "Tips Babi: Jangan menunda tagihan yang bisa kamu bayar hari ini. Denda kecil menumpuk.",
        "Tips Babi: Sampaikan kecewamu hari itu juga. Ikhlas yang dipaksakan akan terasa berat nanti.",
        "Tips Babi: Hari ini coba tolak satu ajakan yang sebenarnya tidak kamu inginkan.",
        "Tips Babi: Kurangi jajan karena bosan. Catat berapa yang keluar minggu ini.",
        "Tips Babi: Kamu pantas mendapat perlakuan baik yang sama seperti yang kamu berikan.",
        "Tips Babi: Hari ini cocok untuk bergerak sedikit lebih banyak. Jalan sore bisa menyegarkan tubuh dan pikiran.",
        "Tips Babi: Jangan membela orang yang jelas-jelas salah hanya karena kamu tidak tega.",
        "Tips Babi: Mulai satu kebiasaan kecil hari ini, misalnya menabung sedikit setiap hari.",
        "Tips Babi: Kalau ada tawaran menggiurkan dari kenalan baru, tanyakan pendapat orang yang kamu percaya dulu.",
        "Tips Babi: Hari ini beri dirimu waktu untuk memikirkan apa yang sebenarnya kamu inginkan.",
        "Tips Babi: Jangan menunggu keadaan membaik sendiri. Ambil satu langkah kecil untuk mengubahnya.",
        "Tips Babi: Nikmati hal-hal enak tanpa berlebihan. Seimbang membuat kesenangannya bertahan lama.",
        "Tips Babi: Hari ini cocok untuk merapikan barang yang menumpuk. Ruang lega membuat hati lega.",
        "Tips Babi: Minta hakmu dengan sopan tapi tegas. Kamu tidak perlu merasa bersalah.",
        "Tips Babi: Ingat, menjaga dirimu bukan berarti berhenti baik pada orang lain.",
    ],
}
