DAY_OFFICER_BANK = [
    {
        "key": "jian",
        "name": "Jian (Membangun)",
        "hanzi": "建",
        "code": "neutral",
        "meaning": "Energi hari ini condong ke awal mula. Cocok memulai, kurang cocok membongkar.",
        "yi": ["Memulai rencana baru", "Perjalanan dan keberangkatan", "Melamar kerja atau wawancara", "Memohon restu"],
        "ji": ["Menggali atau membongkar", "Pindah rumah", "Membuka simpanan besar"],
    },
    {
        "key": "chu",
        "name": "Chu (Membersihkan)",
        "hanzi": "除",
        "code": "good",
        "meaning": "Hari untuk menyingkirkan yang lama supaya ruang baru terbuka.",
        "yi": ["Bersih-bersih dan merapikan", "Berobat", "Mengakhiri yang sudah usang", "Melunasi utang"],
        "ji": ["Perjalanan jauh", "Menikah", "Menyimpan barang berharga"],
    },
    {
        "key": "man",
        "name": "Man (Penuh)",
        "hanzi": "滿",
        "code": "neutral",
        "meaning": "Energi meluap penuh. Baik untuk merayakan, rawan untuk yang butuh ketelitian.",
        "yi": ["Doa dan syukuran", "Membuka usaha", "Menjamu tamu", "Menandatangani kerja sama"],
        "ji": ["Mulai minum obat", "Mengambil keputusan medis", "Pemakaman"],
    },
    {
        "key": "ping",
        "name": "Ping (Merata)",
        "hanzi": "平",
        "code": "neutral",
        "meaning": "Hari serba datar. Tidak menonjol, tapi aman untuk hal rutin.",
        "yi": ["Pekerjaan rutin", "Perbaikan dan perawatan", "Berdamai atau mediasi", "Meratakan tanah"],
        "ji": ["Menikah", "Membuka usaha", "Menanam investasi baru"],
    },
    {
        "key": "ding",
        "name": "Ding (Menetapkan)",
        "hanzi": "定",
        "code": "good",
        "meaning": "Energi mengunci dan memantapkan. Apa pun yang diputuskan hari ini cenderung bertahan.",
        "yi": ["Menandatangani kontrak", "Bertunangan atau berjanji", "Mendaftar sekolah", "Menetapkan target"],
        "ji": ["Berperkara di pengadilan", "Perjalanan jauh", "Mengubah rencana besar"],
    },
    {
        "key": "zhi",
        "name": "Zhi (Menggenggam)",
        "hanzi": "執",
        "code": "neutral",
        "meaning": "Hari untuk memegang erat dan menuntaskan, bukan melepas.",
        "yi": ["Menagih piutang", "Menyelesaikan yang tertunda", "Membangun dan mendirikan", "Menjaga komitmen"],
        "ji": ["Membuka usaha baru", "Pindah tempat", "Melepas aset"],
    },
    {
        "key": "po",
        "name": "Po (Merusak)",
        "hanzi": "破",
        "code": "bad",
        "meaning": "Hari paling rawan dalam siklus. Energi memecah, bukan menyatukan.",
        "yi": ["Membongkar bangunan lama", "Mengobati penyakit menahun", "Memutus hubungan toksik"],
        "ji": ["Menikah", "Membuka usaha", "Menandatangani apa pun", "Memulai hal penting"],
    },
    {
        "key": "wei",
        "name": "Wei (Bahaya)",
        "hanzi": "危",
        "code": "bad",
        "meaning": "Energi rawan tergelincir. Hari untuk berhati-hati, bukan menantang.",
        "yi": ["Ritual dan meditasi", "Beristirahat penuh", "Introspeksi"],
        "ji": ["Naik ke tempat tinggi", "Perjalanan air atau udara", "Olahraga ekstrem", "Mengambil risiko besar"],
    },
    {
        "key": "cheng",
        "name": "Cheng (Berhasil)",
        "hanzi": "成",
        "code": "good",
        "meaning": "Hari terbaik dalam siklus. Hampir semua urusan didukung energinya.",
        "yi": ["Membuka usaha", "Menikah", "Mendaftar sekolah", "Membuat perjanjian", "Memulai apa pun"],
        "ji": ["Berperkara", "Bertengkar atau mengadu"],
    },
    {
        "key": "shou",
        "name": "Shou (Memanen)",
        "hanzi": "收",
        "code": "neutral",
        "meaning": "Energi menarik masuk. Baik untuk menerima, kurang baik untuk melepas.",
        "yi": ["Menerima pembayaran", "Menabung dan menyimpan", "Merekrut orang", "Mengumpulkan data"],
        "ji": ["Perjalanan jauh", "Membuka simpanan", "Memberi pinjaman"],
    },
    {
        "key": "kai",
        "name": "Kai (Membuka)",
        "hanzi": "開",
        "code": "good",
        "meaning": "Pintu-pintu terbuka. Energi mengalir keluar dan menyambut yang baru.",
        "yi": ["Membuka usaha", "Mulai belajar hal baru", "Berobat", "Memulai proyek", "Bertemu orang baru"],
        "ji": ["Pemakaman", "Menutup atau mengakhiri sesuatu"],
    },
    {
        "key": "bi",
        "name": "Bi (Menutup)",
        "hanzi": "閉",
        "code": "bad",
        "meaning": "Energi menutup rapat. Cocok menambal dan menyimpan, buruk untuk memulai.",
        "yi": ["Menambal dan memperbaiki", "Menutup rekening lama", "Menyimpan rapat-rapat"],
        "ji": ["Membuka usaha", "Perjalanan jauh", "Operasi atau tindakan medis", "Memulai hal baru"],
    },
]

ELEMENT_RELATION_BANK = {
    "sheng_wo": {
        "name": "Xiang Sheng (Dihidupi)",
        "code": "good",
        "symbol": "→",
        "desc": "Elemen hari ini menghidupi elemenmu. Energimu terisi dari luar — ini hari yang murah hati padamu.",
        "advice": "Manfaatkan dukungan yang datang. Minta bantuan hari ini lebih mudah dikabulkan.",
    },
    "wo_sheng": {
        "name": "Xie Qi (Menguras)",
        "code": "neutral",
        "symbol": "←",
        "desc": "Elemenmu justru menghidupi elemen hari ini. Kamu produktif, tapi energimu terpakai keluar.",
        "advice": "Berkaryalah, tapi jangan lupa mengisi ulang. Hari ini kamu memberi lebih banyak dari menerima.",
    },
    "ke_wo": {
        "name": "Xiang Ke (Ditekan)",
        "code": "bad",
        "symbol": "⊗",
        "desc": "Elemen hari ini mengekang elemenmu. Ada tekanan dari luar yang terasa mengganjal.",
        "advice": "Jangan melawan arus hari ini. Menunduk sebentar lebih hemat tenaga daripada mendobrak.",
    },
    "wo_ke": {
        "name": "De Cai (Menguasai)",
        "code": "good",
        "symbol": "⊕",
        "desc": "Elemenmu mengekang elemen hari ini. Kamu memegang kendali — ini energi rezeki dan penaklukan.",
        "advice": "Hari yang tepat untuk mengambil inisiatif, bernegosiasi, dan mengejar apa yang kamu incar.",
    },
    "bi_he": {
        "name": "Bi He (Sejalan)",
        "code": "neutral",
        "symbol": "=",
        "desc": "Elemen hari ini sama dengan elemenmu. Energinya menguat, tapi tanpa penyeimbang.",
        "advice": "Kamu merasa paling 'diri sendiri' hari ini. Bagus untuk fokus, rawan untuk keras kepala.",
    },
}


DAILY_RANK_STATUS_WEIGHT = {
    "liu_he": 4,
    "san_he": 3,
    "ben_ming": 0,
    "netral": 1,
    "liu_po": -1,
    "zi_xing": -2,
    "liu_hai": -2,
    "xiang_xing": -3,
    "chong": -4,
}

DAILY_RANK_ELEMENT_WEIGHT = {
    "sheng_wo": 3,
    "bi_he": 2,
    "wo_ke": 1,
    "wo_sheng": 0,
    "ke_wo": -2,
}

DAILY_RANK_TIERS = [
    {
        "key": "puncak",
        "label": "Papan Atas",
        "code": "good",
        "note": "Energi hari ini berpihak. Kalau ada yang mau dimulai atau diminta, hari ini giliranmu maju duluan.",
    },
    {
        "key": "tengah",
        "label": "Papan Tengah",
        "code": "neutral",
        "note": "Tidak didorong, tidak dihambat. Hasil hari ini ditentukan usahamu sendiri, bukan cuaca kosmiknya.",
    },
    {
        "key": "dasar",
        "label": "Papan Bawah",
        "code": "bad",
        "note": "Arus hari ini melawanmu. Bukan berarti sial, tapi hemat tenaga dan tunda yang bisa ditunda.",
    },
]

DAILY_RANK_NOTE = (
    "Peringkat ini menimbang relasi cabang shio terhadap cabang hari, lalu "
    "interaksi elemennya. Bobotnya penafsiran, bukan kaidah baku — anggap "
    "hiburan harian, bukan vonis."
)


NAYIN_BANK = {
    0: {"hanzi": "海中金", "name": "Emas dalam Laut", "element": "logam"},
    1: {"hanzi": "爐中火", "name": "Api dalam Tungku", "element": "api"},
    2: {"hanzi": "大林木", "name": "Kayu Hutan Besar", "element": "kayu"},
    3: {"hanzi": "路旁土", "name": "Tanah Tepi Jalan", "element": "tanah"},
    4: {"hanzi": "劍鋒金", "name": "Emas Mata Pedang", "element": "logam"},
    5: {"hanzi": "山頭火", "name": "Api Puncak Gunung", "element": "api"},
    6: {"hanzi": "澗下水", "name": "Air Jurang", "element": "air"},
    7: {"hanzi": "城頭土", "name": "Tanah Benteng Kota", "element": "tanah"},
    8: {"hanzi": "白蠟金", "name": "Emas Lilin Putih", "element": "logam"},
    9: {"hanzi": "楊柳木", "name": "Kayu Dedalu", "element": "kayu"},
    10: {"hanzi": "泉中水", "name": "Air Mata Air", "element": "air"},
    11: {"hanzi": "屋上土", "name": "Tanah Atap Rumah", "element": "tanah"},
    12: {"hanzi": "霹靂火", "name": "Api Petir", "element": "api"},
    13: {"hanzi": "松柏木", "name": "Kayu Pinus dan Cemara", "element": "kayu"},
    14: {"hanzi": "長流水", "name": "Air Sungai Panjang", "element": "air"},
    15: {"hanzi": "沙中金", "name": "Emas dalam Pasir", "element": "logam"},
    16: {"hanzi": "山下火", "name": "Api Kaki Gunung", "element": "api"},
    17: {"hanzi": "平地木", "name": "Kayu Dataran", "element": "kayu"},
    18: {"hanzi": "壁上土", "name": "Tanah Dinding", "element": "tanah"},
    19: {"hanzi": "金箔金", "name": "Emas Lembaran", "element": "logam"},
    20: {"hanzi": "覆燈火", "name": "Api Lampu Bertudung", "element": "api"},
    21: {"hanzi": "天河水", "name": "Air Sungai Langit", "element": "air"},
    22: {"hanzi": "大驛土", "name": "Tanah Jalan Raya", "element": "tanah"},
    23: {"hanzi": "釵釧金", "name": "Emas Perhiasan", "element": "logam"},
    24: {"hanzi": "桑柘木", "name": "Kayu Murbei", "element": "kayu"},
    25: {"hanzi": "大溪水", "name": "Air Sungai Besar", "element": "air"},
    26: {"hanzi": "沙中土", "name": "Tanah dalam Pasir", "element": "tanah"},
    27: {"hanzi": "天上火", "name": "Api Langit", "element": "api"},
    28: {"hanzi": "石榴木", "name": "Kayu Delima", "element": "kayu"},
    29: {"hanzi": "大海水", "name": "Air Samudra", "element": "air"},
}

STEM_RELATION_BANK = {
    (0, 5): {
        "kind": "he",
        "hanzi": "甲己合",
        "label": "Berpadu jadi Tanah",
        "text": "Batang tahun Jia (甲) dan Ji (己) berpadu jadi Tanah. Yang berprinsip bertemu yang telaten, dan kesepakatan kalian cenderung tahan lama.",
    },
    (1, 6): {
        "kind": "he",
        "hanzi": "乙庚合",
        "label": "Berpadu jadi Logam",
        "text": "Batang tahun Yi (乙) dan Geng (庚) berpadu jadi Logam. Kelenturan bertemu ketegasan, dan dari situ keputusan yang jelas biasanya lahir.",
    },
    (2, 7): {
        "kind": "he",
        "hanzi": "丙辛合",
        "label": "Berpadu jadi Air",
        "text": "Batang tahun Bing (丙) dan Xin (辛) berpadu jadi Air. Keterbukaan bertemu ketelitian, dan kalian saling melembutkan cara masing-masing.",
    },
    (3, 8): {
        "kind": "he",
        "hanzi": "丁壬合",
        "label": "Berpadu jadi Kayu",
        "text": "Batang tahun Ding (丁) dan Ren (壬) berpadu jadi Kayu. Kedalaman bertemu keluwesan — hubungan yang hangat sekaligus rumit.",
    },
    (4, 9): {
        "kind": "he",
        "hanzi": "戊癸合",
        "label": "Berpadu jadi Api",
        "text": "Batang tahun Wu (戊) dan Gui (癸) berpadu jadi Api. Ketenangan bertemu kepekaan; beda cara pandang sering terasa, tapi justru itu yang merekatkan.",
    },
    (0, 6): {
        "kind": "chong",
        "hanzi": "甲庚冲",
        "label": "Berbenturan",
        "text": "Batang tahun Jia (甲) dan Geng (庚) berbenturan. Dua kehendak keras yang sama-sama tidak mau membelok lebih dulu.",
    },
    (1, 7): {
        "kind": "chong",
        "hanzi": "乙辛冲",
        "label": "Berbenturan",
        "text": "Batang tahun Yi (乙) dan Xin (辛) berbenturan. Yang satu menyesuaikan, yang satu menuntut standar; gesekannya halus tapi terus-menerus.",
    },
    (2, 8): {
        "kind": "chong",
        "hanzi": "丙壬冲",
        "label": "Berbenturan",
        "text": "Batang tahun Bing (丙) dan Ren (壬) berbenturan. Yang satu terbuka terang-terangan, yang satu menyimpan, dan keduanya merasa tidak terbaca.",
    },
    (3, 9): {
        "kind": "chong",
        "hanzi": "丁癸冲",
        "label": "Berbenturan",
        "text": "Batang tahun Ding (丁) dan Gui (癸) berbenturan. Sama-sama peka dan sama-sama memendam, jadi salah pahamnya dalam dan lama.",
    },
}

STEM_NEUTRAL = {
    "kind": "netral",
    "hanzi": "干無合冲",
    "label": "Netral",
    "text": "Batang tahun kalian tidak berpadu maupun berbenturan. Lapisan langitnya diam, jadi yang menentukan tetap relasi cabang dan elemennya.",
}

NAYIN_RELATION_BANK = {
    "setara": "Nayin kalian sama-sama {element}. Cara kalian memandang rezeki dan rasa aman mirip, termasuk titik butanya.",
    "memberi": "Nayin {self_name} menghidupi {other_name}. Dalam urusan jangka panjang, kamu lebih sering jadi pihak yang menopang.",
    "menerima": "Nayin {other_name} menghidupi {self_name}. Dalam urusan jangka panjang, kamu lebih sering jadi pihak yang ditopang.",
    "menekan": "Nayin {self_name} mengekang {other_name}. Kamu cenderung jadi penentu arah saat keputusan besar diambil.",
    "ditekan": "Nayin {other_name} mengekang {self_name}. Kamu cenderung mengalah saat keputusan besar diambil.",
}


TIME_ZONE_MERIDIANS = {
    "WIB": 105.0,
    "WITA": 120.0,
    "WIT": 135.0,
}

DEFAULT_CITY = "jakarta"

CITY_ALIASES = {
    "banjar": "banjar_jawa_barat",
    "depok": "depok_jawa_barat",
    "martapura": "martapura_kalimantan_selatan",
    "tanjung": "tanjung_kalimantan_selatan",
}

BIRTH_CITIES = {
    "abepura": ("Abepura", 140.63, "WIT", "Papua"),
    "adiwerna": ("Adiwerna", 109.13, "WIB", "Jawa Tengah"),
    "aek_kanopan": ("Aek Kanopan", 99.65, "WIB", "Sumatera Utara"),
    "agats": ("Agats", 138.14, "WIT", "Papua Selatan"),
    "aimas": ("Aimas", 131.34, "WIT", "Papua Barat Daya"),
    "airmadidi": ("Airmadidi", 124.98, "WITA", "Sulawesi Utara"),
    "amahai": ("Amahai", 128.92, "WIT", "Maluku"),
    "ambarawa": ("Ambarawa", 110.4, "WIB", "Jawa Tengah"),
    "ambon": ("Ambon", 128.18, "WIT", "Maluku"),
    "amlapura": ("Amlapura", 115.62, "WITA", "Bali"),
    "ampana": ("Ampana", 121.58, "WITA", "Sulawesi Tengah"),
    "amuntai": ("Amuntai", 115.25, "WITA", "Kalimantan Selatan"),
    "andoolo": ("Andoolo", 122.25, "WITA", "Sulawesi Tenggara"),
    "argamakmur": ("Argamakmur", 102.19, "WIB", "Bengkulu"),
    "arjawinangun": ("Arjawinangun", 108.41, "WIB", "Jawa Barat"),
    "arosuka": ("Arosuka", 100.62, "WIB", "Sumatera Barat"),
    "asera": ("Asera", 122.07, "WITA", "Sulawesi Tenggara"),
    "astanajapura": ("Astanajapura", 108.63, "WIB", "Jawa Barat"),
    "atambua": ("Atambua", 124.89, "WITA", "Nusa Tenggara Timur"),
    "baa": ("Baa", 123.05, "WITA", "Nusa Tenggara Timur"),
    "baekrajan": ("Baekrajan", 110.85, "WIB", "Jawa Tengah"),
    "bagan_si_api_api": ("Bagan Si Api-api", 100.81, "WIB", "Riau"),
    "bajawa": ("Bajawa", 120.97, "WITA", "Nusa Tenggara Timur"),
    "baki": ("Baki", 110.78, "WIB", "Jawa Tengah"),
    "balai_pungut": ("Balai Pungut", 101.29, "WIB", "Riau"),
    "balige": ("Balige", 99.07, "WIB", "Sumatera Utara"),
    "balikpapan": ("Balikpapan", 116.83, "WITA", "Kalimantan Timur"),
    "banda_aceh": ("Banda Aceh", 95.33, "WIB", "Aceh"),
    "bandar_lampung": ("Bandar Lampung", 105.26, "WIB", "Lampung"),
    "bandar_seri_bentan": ("Bandar Seri Bentan", 104.48, "WIB", "Kepulauan Riau"),
    "bandung": ("Bandung", 107.61, "WIB", "Jawa Barat"),
    "banggai": ("Banggai", 123.5, "WITA", "Sulawesi Tengah"),
    "bangil": ("Bangil", 112.82, "WIB", "Jawa Timur"),
    "bangkalan": ("Bangkalan", 112.74, "WIB", "Jawa Timur"),
    "bangkinang": ("Bangkinang", 101.02, "WIB", "Riau"),
    "bangko": ("Bangko", 102.26, "WIB", "Jambi"),
    "bangli": ("Bangli", 115.35, "WITA", "Bali"),
    "banjar_bali": ("Banjar, Bali", 114.97, "WITA", "Bali"),
    "banjar_jawa_barat": ("Banjar, Jawa Barat", 107.43, "WIB", "Jawa Barat"),
    "banjaran": ("Banjaran", 107.59, "WIB", "Jawa Barat"),
    "banjarbaru": ("Banjarbaru", 114.84, "WITA", "Kalimantan Selatan"),
    "banjarmasin": ("Banjarmasin", 114.59, "WITA", "Kalimantan Selatan"),
    "banjarnegara": ("Banjarnegara", 109.7, "WIB", "Jawa Tengah"),
    "bantaeng": ("Bantaeng", 119.95, "WITA", "Sulawesi Selatan"),
    "bantul": ("Bantul", 110.33, "WIB", "DI Yogyakarta"),
    "banyuwangi": ("Banyuwangi", 114.36, "WIB", "Jawa Timur"),
    "barabai": ("Barabai", 115.38, "WITA", "Kalimantan Selatan"),
    "barru": ("Barru", 119.62, "WITA", "Sulawesi Selatan"),
    "batam": ("Batam", 104.02, "WIB", "Riau"),
    "batang": ("Batang", 110.71, "WIB", "Jawa Tengah"),
    "batauga": ("Batauga", 122.6, "WITA", "Sulawesi Tenggara"),
    "batu": ("Batu", 112.53, "WIB", "Jawa Timur"),
    "batulicin": ("Batulicin", 116.01, "WITA", "Kalimantan Selatan"),
    "baturaja": ("Baturaja", 104.17, "WIB", "Sumatera Selatan"),
    "batusangkar": ("Batusangkar", 100.61, "WIB", "Sumatera Barat"),
    "baubau": ("Baubau", 122.6, "WITA", "Sulawesi Tenggara"),
    "bekasi": ("Bekasi", 106.99, "WIB", "Jawa Barat"),
    "belawan": ("Belawan", 98.68, "WIB", "Sumatera Utara"),
    "belopa": ("Belopa", 120.37, "WITA", "Sulawesi Selatan"),
    "bengkalis": ("Bengkalis", 102.13, "WIB", "Riau"),
    "bengkayang": ("Bengkayang", 109.44, "WIB", "Kalimantan Barat"),
    "bengkulu": ("Bengkulu", 102.27, "WIB", "Bengkulu"),
    "benteng": ("Benteng", 120.46, "WITA", "Sulawesi Selatan"),
    "besuki": ("Besuki", 113.7, "WIB", "Jawa Timur"),
    "betun": ("Betun", 124.91, "WITA", "Nusa Tenggara Timur"),
    "biak": ("Biak", 136.08, "WIT", "Papua"),
    "bima": ("Bima", 118.73, "WITA", "Nusa Tenggara Barat"),
    "binjai": ("Binjai", 98.49, "WIB", "Sumatera Utara"),
    "bintuhan": ("Bintuhan", 103.35, "WIB", "Bengkulu"),
    "bintuni": ("Bintuni", 133.52, "WIT", "Papua Barat"),
    "bitung": ("Bitung", 125.13, "WITA", "Sulawesi Utara"),
    "blambangan_umpu": ("Blambangan Umpu", 104.52, "WIB", "Lampung"),
    "blangkejeren": ("Blangkejeren", 97.34, "WIB", "Aceh"),
    "blangpidie": ("Blangpidie", 96.84, "WIB", "Aceh"),
    "blitar": ("Blitar", 112.17, "WIB", "Jawa Timur"),
    "blora": ("Blora", 111.42, "WIB", "Jawa Tengah"),
    "bobong": ("Bobong", 124.38, "WIT", "Maluku Utara"),
    "bogor": ("Bogor", 106.79, "WIB", "Jawa Barat"),
    "bojonegoro": ("Bojonegoro", 111.88, "WIB", "Jawa Timur"),
    "bondowoso": ("Bondowoso", 113.82, "WIB", "Jawa Timur"),
    "bontang": ("Bontang", 117.49, "WITA", "Kalimantan Timur"),
    "boroko": ("Boroko", 123.27, "WITA", "Sulawesi Utara"),
    "borong": ("Borong", 120.61, "WITA", "Nusa Tenggara Timur"),
    "botawa": ("Botawa", 136.45, "WIT", "Papua"),
    "boyolali": ("Boyolali", 110.6, "WIB", "Jawa Tengah"),
    "brebes": ("Brebes", 109.04, "WIB", "Jawa Tengah"),
    "bukittinggi": ("Bukittinggi", 100.37, "WIB", "Sumatera Barat"),
    "bula": ("Bula", 130.5, "WIT", "Maluku"),
    "bulukumba": ("Bulukumba", 120.18, "WITA", "Sulawesi Selatan"),
    "bungku": ("Bungku", 121.97, "WITA", "Sulawesi Tengah"),
    "buntok": ("Buntok", 114.84, "WIB", "Kalimantan Tengah"),
    "buol": ("Buol", 121.44, "WITA", "Sulawesi Tengah"),
    "buranga": ("Buranga", 122.98, "WITA", "Sulawesi Tenggara"),
    "burmeso": ("Burmeso", 138.04, "WIT", "Papua"),
    "calang": ("Calang", 95.58, "WIB", "Aceh"),
    "caringin": ("Caringin", 106.82, "WIB", "Jawa Barat"),
    "caruban": ("Caruban", 111.66, "WIB", "Jawa Timur"),
    "cepu": ("Cepu", 111.59, "WIB", "Jawa Tengah"),
    "ciamis": ("Ciamis", 108.35, "WIB", "Jawa Barat"),
    "ciampea": ("Ciampea", 106.7, "WIB", "Jawa Barat"),
    "cianjur": ("Cianjur", 107.14, "WIB", "Jawa Barat"),
    "cibinong": ("Cibinong", 106.85, "WIB", "Jawa Barat"),
    "cicurug": ("Cicurug", 106.78, "WIB", "Jawa Barat"),
    "cikampek": ("Cikampek", 107.46, "WIB", "Jawa Barat"),
    "cikarang": ("Cikarang", 107.15, "WIB", "Jawa Barat"),
    "cikupa": ("Cikupa", 106.51, "WIB", "Jawa Barat"),
    "cilacap": ("Cilacap", 109.01, "WIB", "Jawa Tengah"),
    "cilegon": ("Cilegon", 106.05, "WIB", "Banten"),
    "cileungsir": ("Cileungsir", 106.96, "WIB", "Jawa Barat"),
    "cileunyi": ("Cileunyi", 107.75, "WIB", "Jawa Barat"),
    "cimahi": ("Cimahi", 107.54, "WIB", "Jawa Barat"),
    "ciputat": ("Ciputat", 106.7, "WIB", "Jawa Barat"),
    "ciranjang_hilir": ("Ciranjang-hilir", 107.26, "WIB", "Jawa Barat"),
    "cirebon": ("Cirebon", 108.56, "WIB", "Jawa Barat"),
    "ciruas": ("Ciruas", 106.23, "WIB", "Banten"),
    "citeureup": ("Citeureup", 106.88, "WIB", "Jawa Barat"),
    "comal": ("Comal", 109.53, "WIB", "Jawa Tengah"),
    "curug": ("Curug", 106.56, "WIB", "Banten"),
    "curup": ("Curup", 102.52, "WIB", "Bengkulu"),
    "daik_lingga": ("Daik Lingga", 104.62, "WIB", "Kepulauan Riau"),
    "daruba": ("Daruba", 128.29, "WIT", "Maluku Utara"),
    "demak": ("Demak", 110.64, "WIB", "Jawa Tengah"),
    "denpasar": ("Denpasar", 115.22, "WITA", "Bali"),
    "depok_di_yogyakarta": ("Depok, DI Yogyakarta", 110.43, "WIB", "DI Yogyakarta"),
    "depok_jawa_barat": ("Depok, Jawa Barat", 106.82, "WIB", "Jawa Barat"),
    "dobo": ("Dobo", 134.23, "WIT", "Maluku"),
    "dolok_sanggul": ("Dolok Sanggul", 98.75, "WIB", "Sumatera Utara"),
    "dompu": ("Dompu", 118.46, "WITA", "Nusa Tenggara Barat"),
    "donggala": ("Donggala", 119.74, "WITA", "Sulawesi Tengah"),
    "dukuhturi": ("Dukuhturi", 109.08, "WIB", "Jawa Tengah"),
    "dumai": ("Dumai", 101.44, "WIB", "Riau"),
    "elelim": ("Elelim", 139.71, "WIT", "Papua Pegunungan"),
    "ende": ("Ende", 121.66, "WITA", "Nusa Tenggara Timur"),
    "enrekang": ("Enrekang", 119.77, "WITA", "Sulawesi Selatan"),
    "fakfak": ("Fakfak", 132.3, "WIT", "Papua"),
    "fef": ("Fef", 132.43, "WIT", "Papua Barat Daya"),
    "galesong": ("Galesong", 119.37, "WITA", "Sulawesi Selatan"),
    "gamping_lor": ("Gamping Lor", 110.33, "WIB", "DI Yogyakarta"),
    "garut": ("Garut", 107.92, "WIB", "Jawa Barat"),
    "gedangan": ("Gedangan", 112.73, "WIB", "Jawa Timur"),
    "gedong_tataan": ("Gedong Tataan", 105.1, "WIB", "Lampung"),
    "genteng": ("Genteng", 114.15, "WIB", "Jawa Timur"),
    "gerung": ("Gerung", 116.13, "WITA", "Nusa Tenggara Barat"),
    "gianyar": ("Gianyar", 115.33, "WITA", "Bali"),
    "godean": ("Godean", 110.29, "WIB", "DI Yogyakarta"),
    "godo": ("Godo", 118.67, "WITA", "Nusa Tenggara Barat"),
    "gombong": ("Gombong", 109.51, "WIB", "Jawa Tengah"),
    "gorontalo": ("Gorontalo", 123.06, "WITA", "Gorontalo"),
    "gresik": ("Gresik", 112.66, "WIB", "Jawa Timur"),
    "grogol": ("Grogol", 110.82, "WIB", "Jawa Tengah"),
    "gunung_sugih": ("Gunung Sugih", 105.21, "WIB", "Lampung"),
    "gunung_tua": ("Gunung Tua", 99.63, "WIB", "Sumatera Utara"),
    "gunungsitoli": ("Gunungsitoli", 97.61, "WIB", "Sumatera Utara"),
    "idi_rayeuk": ("Idi Rayeuk", 97.77, "WIB", "Aceh"),
    "ilaga": ("Ilaga", 137.4, "WIT", "Papua Tengah"),
    "indralaya": ("Indralaya", 104.68, "WIB", "Sumatera Selatan"),
    "indramayu": ("Indramayu", 108.32, "WIB", "Jawa Barat"),
    "jailolo": ("Jailolo", 127.47, "WIT", "Maluku Utara"),
    "jakarta": ("Jakarta", 106.85, "WIB", "DKI Jakarta"),
    "jambi_city": ("Jambi City", 103.62, "WIB", "Jambi"),
    "jampang_tengah": ("Jampang Tengah", 106.8, "WIB", "Jawa Barat"),
    "jatibarang": ("Jatibarang", 108.32, "WIB", "Jawa Barat"),
    "jatiroto": ("Jatiroto", 111.12, "WIB", "Jawa Tengah"),
    "jatiwangi": ("Jatiwangi", 108.26, "WIB", "Jawa Barat"),
    "jayapura": ("Jayapura", 140.72, "WIT", "Papua"),
    "jember": ("Jember", 113.7, "WIB", "Jawa Timur"),
    "jeneponto": ("Jeneponto", 119.75, "WITA", "Sulawesi Selatan"),
    "jepara": ("Jepara", 110.67, "WIB", "Jawa Tengah"),
    "jombang": ("Jombang", 112.23, "WIB", "Jawa Timur"),
    "kabanjahe": ("Kabanjahe", 98.49, "WIB", "Sumatera Utara"),
    "kajen": ("Kajen", 109.58, "WIB", "Jawa Tengah"),
    "kalabahi": ("Kalabahi", 124.55, "WITA", "Nusa Tenggara Timur"),
    "kalianda": ("Kalianda", 105.59, "WIB", "Lampung"),
    "kandangan": ("Kandangan", 115.28, "WITA", "Kalimantan Selatan"),
    "karang_tinggi": ("Karang Tinggi", 102.42, "WIB", "Bengkulu"),
    "karanganyar": ("Karanganyar", 110.94, "WIB", "Jawa Tengah"),
    "karangbaru": ("Karangbaru", 98.03, "WIB", "Aceh"),
    "karangsembung": ("Karangsembung", 108.64, "WIB", "Jawa Barat"),
    "karawang": ("Karawang", 107.32, "WIB", "Jawa Barat"),
    "kartasura": ("Kartasura", 110.74, "WIB", "Jawa Tengah"),
    "karubaga": ("Karubaga", 138.46, "WIT", "Papua Pegunungan"),
    "kasihan": ("Kasihan", 110.33, "WIB", "DI Yogyakarta"),
    "kawalu": ("Kawalu", 108.21, "WIB", "Jawa Barat"),
    "kayu_agung": ("Kayu Agung", 104.83, "WIB", "Sumatera Selatan"),
    "kebomas": ("Kebomas", 112.63, "WIB", "Jawa Timur"),
    "kebumen": ("Kebumen", 109.65, "WIB", "Jawa Tengah"),
    "kediri": ("Kediri", 112.02, "WIB", "Jawa Timur"),
    "kedungwaru": ("Kedungwaru", 111.92, "WIB", "Jawa Timur"),
    "kedungwuni": ("Kedungwuni", 109.65, "WIB", "Jawa Tengah"),
    "kefamenanu": ("Kefamenanu", 124.48, "WITA", "Nusa Tenggara Timur"),
    "kendal": ("Kendal", 110.2, "WIB", "Jawa Tengah"),
    "kendari": ("Kendari", 122.52, "WITA", "Sulawesi Tenggara"),
    "kenyam": ("Kenyam", 138.38, "WIT", "Papua Pegunungan"),
    "kepahiang": ("Kepahiang", 102.57, "WIB", "Bengkulu"),
    "kepanjen": ("Kepanjen", 112.57, "WIB", "Jawa Timur"),
    "kepi": ("Kepi", 139.32, "WIT", "Papua Selatan"),
    "kertosono": ("Kertosono", 112.1, "WIB", "Jawa Timur"),
    "ketapang": ("Ketapang", 109.98, "WIB", "Kalimantan Barat"),
    "kigamani": ("Kigamani", 135.94, "WIT", "Papua Tengah"),
    "kisaran": ("Kisaran", 99.62, "WIB", "Sumatera Utara"),
    "klangenan": ("Klangenan", 108.44, "WIB", "Jawa Barat"),
    "klaten": ("Klaten", 110.61, "WIB", "Jawa Tengah"),
    "klungkung": ("Klungkung", 115.4, "WITA", "Bali"),
    "koba": ("Koba", 106.41, "WIB", "Kepulauan Bangka Belitung"),
    "kobakma": ("Kobakma", 139.06, "WIT", "Papua Pegunungan"),
    "kolaka": ("Kolaka", 121.61, "WITA", "Sulawesi Tenggara"),
    "kolonodale": ("Kolonodale", 121.34, "WITA", "Sulawesi Tengah"),
    "kota_agung": ("Kota Agung", 104.65, "WIB", "Lampung"),
    "kota_pinang": ("Kota Pinang", 100.09, "WIB", "Sumatera Utara"),
    "kota_ternate": ("Kota Ternate", 127.37, "WIT", "Maluku"),
    "kotabaru_hilir": ("Kotabaru Hilir", 116.23, "WITA", "Kalimantan Selatan"),
    "kotabumi": ("Kotabumi", 104.88, "WIB", "Lampung"),
    "kotamobagu": ("Kotamobagu", 124.31, "WITA", "Sulawesi Utara"),
    "kresek": ("Kresek", 106.38, "WIB", "Jawa Barat"),
    "krui": ("Krui", 103.93, "WIB", "Lampung"),
    "kuala_pembuang": ("Kuala Pembuang", 112.55, "WIB", "Kalimantan Tengah"),
    "kuala_tungkal": ("Kuala Tungkal", 103.46, "WIB", "Jambi"),
    "kudus": ("Kudus", 110.84, "WIB", "Jawa Tengah"),
    "kumurkek": ("Kumurkek", 132.5, "WIT", "Papua Barat Daya"),
    "kuningan": ("Kuningan", 108.48, "WIB", "Jawa Barat"),
    "kupang": ("Kupang", 123.61, "WITA", "Nusa Tenggara Timur"),
    "kwandang": ("Kwandang", 122.92, "WITA", "Gorontalo"),
    "labuan_bajo": ("Labuan Bajo", 119.89, "WITA", "Nusa Tenggara Timur"),
    "labuha": ("Labuha", 127.48, "WIT", "Maluku Utara"),
    "labungkari": ("Labungkari", 122.55, "WITA", "Sulawesi Tenggara"),
    "lahat": ("Lahat", 103.54, "WIB", "Sumatera Selatan"),
    "lamongan": ("Lamongan", 112.42, "WIB", "Jawa Timur"),
    "langara": ("Langara", 122.99, "WITA", "Sulawesi Tenggara"),
    "langgur": ("Langgur", 132.74, "WIT", "Maluku"),
    "langsa": ("Langsa", 97.97, "WIB", "Aceh"),
    "larantuka": ("Larantuka", 122.98, "WITA", "Nusa Tenggara Timur"),
    "lasusua": ("Lasusua", 120.88, "WITA", "Sulawesi Tenggara"),
    "lawang": ("Lawang", 112.69, "WIB", "Jawa Timur"),
    "laworo": ("Laworo", 122.52, "WITA", "Sulawesi Tenggara"),
    "lembang": ("Lembang", 107.62, "WIB", "Jawa Barat"),
    "lewoleba": ("Lewoleba", 123.42, "WITA", "Nusa Tenggara Timur"),
    "lhokseumawe": ("Lhokseumawe", 97.15, "WIB", "Aceh"),
    "limapuluh": ("Limapuluh", 99.42, "WIB", "Sumatera Utara"),
    "limboto": ("Limboto", 122.98, "WITA", "Gorontalo"),
    "liwa": ("Liwa", 104.08, "WIB", "Lampung"),
    "loa_janan": ("Loa Janan", 117.1, "WITA", "Kalimantan Timur"),
    "lolak": ("Lolak", 124.01, "WITA", "Sulawesi Utara"),
    "lotu": ("Lotu", 97.35, "WIB", "Sumatera Utara"),
    "lubuk_basung": ("Lubuk Basung", 100.06, "WIB", "Sumatera Barat"),
    "lubuk_pakam": ("Lubuk Pakam", 98.87, "WIB", "Sumatera Utara"),
    "lubuk_sikaping": ("Lubuk Sikaping", 100.17, "WIB", "Sumatera Barat"),
    "lubuklinggau": ("Lubuklinggau", 102.86, "WIB", "Sumatera Selatan"),
    "lumajang": ("Lumajang", 113.22, "WIB", "Jawa Timur"),
    "luwuk": ("Luwuk", 122.79, "WITA", "Sulawesi Tengah"),
    "maba": ("Maba", 128.29, "WIT", "Maluku Utara"),
    "madiun": ("Madiun", 111.52, "WIB", "Jawa Timur"),
    "magelang": ("Magelang", 110.22, "WIB", "Jawa Tengah"),
    "magetan": ("Magetan", 111.33, "WIB", "Jawa Timur"),
    "majalengka": ("Majalengka", 108.23, "WIB", "Jawa Barat"),
    "majene": ("Majene", 118.97, "WITA", "Sulawesi Barat"),
    "makale": ("Makale", 119.85, "WITA", "Sulawesi Selatan"),
    "makassar": ("Makassar", 119.43, "WITA", "Sulawesi Selatan"),
    "malang": ("Malang", 112.63, "WIB", "Jawa Timur"),
    "malili": ("Malili", 121.09, "WITA", "Sulawesi Selatan"),
    "malinau": ("Malinau", 116.62, "WITA", "Kalimantan Utara"),
    "mamasa": ("Mamasa", 119.38, "WITA", "Sulawesi Barat"),
    "mamuju": ("Mamuju", 118.89, "WITA", "Sulawesi Barat"),
    "manado": ("Manado", 124.85, "WITA", "Sulawesi Utara"),
    "manggar": ("Manggar", 108.27, "WIB", "Kepulauan Bangka Belitung"),
    "mangupura": ("Mangupura", 115.17, "WITA", "Bali"),
    "manna": ("Manna", 102.9, "WIB", "Bengkulu"),
    "manokwari": ("Manokwari", 134.06, "WIT", "Papua Barat"),
    "marabahan": ("Marabahan", 114.77, "WITA", "Kalimantan Selatan"),
    "margahayukencana": ("Margahayukencana", 107.57, "WIB", "Jawa Barat"),
    "marisa": ("Marisa", 121.94, "WITA", "Gorontalo"),
    "maros": ("Maros", 119.57, "WITA", "Sulawesi Selatan"),
    "martapura_kalimantan_selatan": ("Martapura, Kalimantan Selatan", 114.86, "WITA", "Kalimantan Selatan"),
    "martapura_sumatera_selatan": ("Martapura, Sumatera Selatan", 104.35, "WIB", "Sumatera Selatan"),
    "masamba": ("Masamba", 120.33, "WITA", "Sulawesi Selatan"),
    "masohi": ("Masohi", 128.97, "WIT", "Maluku"),
    "mataram": ("Mataram", 116.12, "WITA", "Nusa Tenggara Barat"),
    "maumere": ("Maumere", 122.21, "WITA", "Nusa Tenggara Timur"),
    "mbay": ("Mbay", 121.27, "WITA", "Nusa Tenggara Timur"),
    "medan": ("Medan", 98.67, "WIB", "Sumatera Utara"),
    "melati": ("Melati", 110.37, "WIB", "DI Yogyakarta"),
    "mempawah": ("Mempawah", 108.97, "WIB", "Kalimantan Barat"),
    "mendaha": ("Mendaha", 103.59, "WIB", "Jambi"),
    "menggala": ("Menggala", 105.25, "WIB", "Lampung"),
    "merauke": ("Merauke", 140.41, "WIT", "Papua Selatan"),
    "mertoyudan": ("Mertoyudan", 110.23, "WIB", "Jawa Tengah"),
    "metro": ("Metro", 105.31, "WIB", "Lampung"),
    "meulaboh": ("Meulaboh", 96.13, "WIB", "Aceh"),
    "mojokerto": ("Mojokerto", 112.43, "WIB", "Jawa Timur"),
    "mojosari": ("Mojosari", 112.56, "WIB", "Jawa Timur"),
    "molibagu": ("Molibagu", 123.98, "WITA", "Sulawesi Utara"),
    "muara_beliti": ("Muara Beliti", 103.03, "WIB", "Sumatera Selatan"),
    "muara_bungo": ("Muara Bungo", 102.11, "WIB", "Jambi"),
    "muara_enim": ("Muara Enim", 103.77, "WIB", "Sumatera Selatan"),
    "muara_sabak": ("Muara Sabak", 103.85, "WIB", "Jambi"),
    "muara_tebo": ("Muara Tebo", 102.44, "WIB", "Jambi"),
    "muara_teweh": ("Muara Teweh", 114.9, "WIB", "Kalimantan Tengah"),
    "muaro": ("Muaro", 100.96, "WIB", "Sumatera Barat"),
    "mukomuko": ("Mukomuko", 101.11, "WIB", "Bengkulu"),
    "mulia": ("Mulia", 137.99, "WIT", "Papua Tengah"),
    "muncar": ("Muncar", 114.33, "WIB", "Jawa Timur"),
    "mungkid": ("Mungkid", 110.22, "WIB", "Jawa Tengah"),
    "muntilan": ("Muntilan", 110.29, "WIB", "Jawa Tengah"),
    "muntok": ("Muntok", 105.16, "WIB", "Kepulauan Bangka Belitung"),
    "nabire": ("Nabire", 135.5, "WIT", "Papua Tengah"),
    "namlea": ("Namlea", 127.09, "WIT", "Maluku"),
    "namrole": ("Namrole", 126.73, "WIT", "Maluku"),
    "nanga_bulik": ("Nanga Bulik", 111.49, "WIB", "Kalimantan Tengah"),
    "nangah_pinoh": ("Nangah Pinoh", 111.73, "WIB", "Kalimantan Barat"),
    "negara": ("Negara", 114.62, "WITA", "Bali"),
    "ngabang": ("Ngabang", 109.95, "WIB", "Kalimantan Barat"),
    "ngamprah": ("Ngamprah", 107.28, "WIB", "Jawa Barat"),
    "nganjuk": ("Nganjuk", 111.9, "WIB", "Jawa Timur"),
    "nunukan": ("Nunukan", 117.65, "WITA", "Kalimantan Utara"),
    "nusantara": ("Nusantara", 116.71, "WITA", "Kalimantan Timur"),
    "oelamasi": ("Oelamasi", 123.88, "WITA", "Nusa Tenggara Timur"),
    "oksibil": ("Oksibil", 140.63, "WIT", "Papua Pegunungan"),
    "ondong_siau": ("Ondong Siau", 125.36, "WITA", "Sulawesi Utara"),
    "onolimbu": ("Onolimbu", 97.5, "WIB", "Sumatera Utara"),
    "pacitan": ("Pacitan", 111.1, "WIB", "Jawa Timur"),
    "padalarang": ("Padalarang", 107.47, "WIB", "Jawa Barat"),
    "padang": ("Padang", 100.35, "WIB", "Sumatera Barat"),
    "padang_aro": ("Padang Aro", 101.26, "WIB", "Sumatera Barat"),
    "padangpanjang": ("Padangpanjang", 100.41, "WIB", "Sumatera Barat"),
    "padangsidempuan": ("Padangsidempuan", 99.27, "WIB", "Sumatera Utara"),
    "pagar_alam": ("Pagar Alam", 103.25, "WIB", "Sumatera Selatan"),
    "painan": ("Painan", 100.57, "WIB", "Sumatera Barat"),
    "palangkaraya": ("Palangkaraya", 113.92, "WIB", "Kalimantan Tengah"),
    "palembang": ("Palembang", 104.75, "WIB", "Sumatera Selatan"),
    "palimanan": ("Palimanan", 108.42, "WIB", "Jawa Barat"),
    "palopo": ("Palopo", 120.2, "WITA", "Sulawesi Selatan"),
    "palu": ("Palu", 119.87, "WITA", "Sulawesi Tengah"),
    "pamanukan": ("Pamanukan", 107.81, "WIB", "Jawa Barat"),
    "pamekasan": ("Pamekasan", 113.47, "WIB", "Jawa Timur"),
    "pamulang": ("Pamulang", 106.74, "WIB", "Jawa Barat"),
    "panaragan": ("Panaragan", 105.08, "WIB", "Lampung"),
    "pandak": ("Pandak", 110.29, "WIB", "DI Yogyakarta"),
    "pandan": ("Pandan", 98.82, "WIB", "Sumatera Utara"),
    "pandeglang": ("Pandeglang", 106.11, "WIB", "Banten"),
    "pangkajene": ("Pangkajene", 119.55, "WITA", "Sulawesi Selatan"),
    "pangkalan_balai": ("Pangkalan Balai", 104.39, "WIB", "Sumatera Selatan"),
    "pangkalan_kerinci": ("Pangkalan Kerinci", 101.86, "WIB", "Riau"),
    "pangkalanbuun": ("Pangkalanbuun", 111.63, "WIB", "Kalimantan Tengah"),
    "pangkalpinang": ("Pangkalpinang", 106.11, "WIB", "Kepulauan Bangka Belitung"),
    "pangururan": ("Pangururan", 98.7, "WIB", "Sumatera Utara"),
    "pare": ("Pare", 112.2, "WIB", "Jawa Timur"),
    "parepare": ("Parepare", 119.63, "WITA", "Sulawesi Selatan"),
    "pariaman": ("Pariaman", 100.12, "WIB", "Sumatera Barat"),
    "parigi_jawa_barat": ("Parigi, Jawa Barat", 108.5, "WIB", "Jawa Barat"),
    "parigi_sulawesi_tengah": ("Parigi, Sulawesi Tengah", 120.18, "WITA", "Sulawesi Tengah"),
    "paringin": ("Paringin", 115.47, "WITA", "Kalimantan Selatan"),
    "parit_malintang": ("Parit Malintang", 100.28, "WIB", "Sumatera Barat"),
    "parung": ("Parung", 106.73, "WIB", "Jawa Barat"),
    "pasar_wajo": ("Pasar Wajo", 122.84, "WITA", "Sulawesi Tenggara"),
    "pasarkemis": ("Pasarkemis", 106.53, "WIB", "Jawa Barat"),
    "paseh": ("Paseh", 107.79, "WIB", "Jawa Barat"),
    "pasir_pengaraian": ("Pasir Pengaraian", 100.3, "WIB", "Riau"),
    "pasuruan": ("Pasuruan", 112.91, "WIB", "Jawa Timur"),
    "pati": ("Pati", 111.04, "WIB", "Jawa Tengah"),
    "payakumbuh": ("Payakumbuh", 100.63, "WIB", "Sumatera Barat"),
    "pecangaan": ("Pecangaan", 110.71, "WIB", "Jawa Tengah"),
    "pekalongan": ("Pekalongan", 109.68, "WIB", "Jawa Tengah"),
    "pekanbaru": ("Pekanbaru", 101.44, "WIB", "Riau"),
    "pelabuhanratu": ("Pelabuhanratu", 106.55, "WIB", "Jawa Barat"),
    "pelaihari": ("Pelaihari", 114.78, "WITA", "Kalimantan Selatan"),
    "pemalang": ("Pemalang", 109.38, "WIB", "Jawa Tengah"),
    "pemangkat": ("Pemangkat", 108.97, "WIB", "Kalimantan Barat"),
    "pematang_raya": ("Pematang Raya", 98.85, "WIB", "Sumatera Utara"),
    "pematangsiantar": ("Pematangsiantar", 99.07, "WIB", "Sumatera Utara"),
    "penajam": ("Penajam", 116.77, "WITA", "Kalimantan Timur"),
    "perbaungan": ("Perbaungan", 98.96, "WIB", "Sumatera Utara"),
    "percut": ("Percut", 98.86, "WIB", "Sumatera Utara"),
    "pinrang": ("Pinrang", 119.65, "WITA", "Sulawesi Selatan"),
    "piru": ("Piru", 128.19, "WIT", "Maluku"),
    "plumbon": ("Plumbon", 108.47, "WIB", "Jawa Barat"),
    "polewali": ("Polewali", 119.34, "WITA", "Sulawesi Barat"),
    "ponorogo": ("Ponorogo", 111.46, "WIB", "Jawa Timur"),
    "pontianak": ("Pontianak", 109.33, "WIB", "Kalimantan Barat"),
    "poso": ("Poso", 120.75, "WITA", "Sulawesi Tengah"),
    "prabumulih": ("Prabumulih", 104.23, "WIB", "Sumatera Selatan"),
    "pringsewu": ("Pringsewu", 104.97, "WIB", "Lampung"),
    "probolinggo": ("Probolinggo", 113.22, "WIB", "Jawa Timur"),
    "pulang_pisau": ("Pulang Pisau", 114.24, "WIB", "Kalimantan Tengah"),
    "pulau_pramuka": ("Pulau Pramuka", 106.61, "WIB", "DKI Jakarta"),
    "pulau_punjung": ("Pulau Punjung", 101.5, "WIB", "Sumatera Barat"),
    "purbalingga": ("Purbalingga", 109.36, "WIB", "Jawa Tengah"),
    "puruk_cahu": ("Puruk Cahu", 114.58, "WIB", "Kalimantan Tengah"),
    "purwakarta": ("Purwakarta", 107.44, "WIB", "Jawa Barat"),
    "purwodadi": ("Purwodadi", 110.92, "WIB", "Jawa Tengah"),
    "purwokerto": ("Purwokerto", 109.23, "WIB", "Jawa Tengah"),
    "purworejo": ("Purworejo", 110.01, "WIB", "Jawa Tengah"),
    "putussibau": ("Putussibau", 112.93, "WIB", "Kalimantan Barat"),
    "raha": ("Raha", 122.72, "WITA", "Sulawesi Tenggara"),
    "ranai": ("Ranai", 108.38, "WIB", "Kepulauan Riau"),
    "rangkasbitung": ("Rangkasbitung", 106.25, "WIB", "Banten"),
    "ransiki": ("Ransiki", 134.17, "WIT", "Papua Barat"),
    "rantau": ("Rantau", 115.16, "WITA", "Kalimantan Selatan"),
    "rantau_prapat": ("Rantau Prapat", 100.05, "WIB", "Sumatera Utara"),
    "rantauprapat": ("Rantauprapat", 99.83, "WIB", "Sumatera Utara"),
    "rantepao": ("Rantepao", 119.9, "WITA", "Sulawesi Selatan"),
    "rasiei": ("Rasiei", 134.53, "WIT", "Papua Barat"),
    "ratahan": ("Ratahan", 124.8, "WITA", "Sulawesi Utara"),
    "rembang": ("Rembang", 111.35, "WIB", "Jawa Tengah"),
    "rengasdengklok": ("Rengasdengklok", 107.3, "WIB", "Jawa Barat"),
    "rumbia": ("Rumbia", 122.0, "WITA", "Sulawesi Tenggara"),
    "ruteng": ("Ruteng", 120.46, "WITA", "Nusa Tenggara Timur"),
    "salak": ("Salak", 98.32, "WIB", "Sumatera Utara"),
    "salakan": ("Salakan", 123.29, "WITA", "Sulawesi Tengah"),
    "salatiga": ("Salatiga", 110.49, "WIB", "Jawa Tengah"),
    "samarinda": ("Samarinda", 117.15, "WITA", "Kalimantan Timur"),
    "sambas": ("Sambas", 109.25, "WIB", "Kalimantan Barat"),
    "sampang": ("Sampang", 113.24, "WIB", "Jawa Timur"),
    "sampit": ("Sampit", 112.95, "WIB", "Kalimantan Tengah"),
    "sanana": ("Sanana", 125.98, "WIT", "Maluku Utara"),
    "sangatta": ("Sangatta", 117.53, "WITA", "Kalimantan Timur"),
    "sanggau": ("Sanggau", 110.6, "WIB", "Kalimantan Barat"),
    "sangkapura": ("Sangkapura", 112.65, "WIB", "Jawa Timur"),
    "sarilamak": ("Sarilamak", 100.66, "WIB", "Sumatera Barat"),
    "sarolangun": ("Sarolangun", 102.73, "WIB", "Jambi"),
    "sawangan": ("Sawangan", 106.77, "WIB", "Jawa Barat"),
    "seba": ("Seba", 121.84, "WITA", "Nusa Tenggara Timur"),
    "sei_rampah": ("Sei Rampah", 99.14, "WIB", "Sumatera Utara"),
    "sekadau": ("Sekadau", 110.9, "WIB", "Kalimantan Barat"),
    "sekayu": ("Sekayu", 103.83, "WIB", "Sumatera Selatan"),
    "selat_panjang": ("Selat Panjang", 102.71, "WIB", "Riau"),
    "selong": ("Selong", 116.53, "WITA", "Nusa Tenggara Barat"),
    "semarang": ("Semarang", 110.42, "WIB", "Jawa Tengah"),
    "semarapura": ("Semarapura", 115.4, "WITA", "Bali"),
    "sendawar": ("Sendawar", 115.69, "WITA", "Kalimantan Timur"),
    "sengeti": ("Sengeti", 103.51, "WIB", "Jambi"),
    "sengkang": ("Sengkang", 120.03, "WITA", "Sulawesi Selatan"),
    "sentani": ("Sentani", 140.51, "WIT", "Papua"),
    "sepatan": ("Sepatan", 106.58, "WIB", "Jawa Barat"),
    "serang": ("Serang", 106.15, "WIB", "Banten"),
    "serpong": ("Serpong", 106.66, "WIB", "Jawa Barat"),
    "serui": ("Serui", 136.24, "WIT", "Papua"),
    "sewon": ("Sewon", 110.36, "WIB", "DI Yogyakarta"),
    "siak_sri_indrapura": ("Siak Sri Indrapura", 102.05, "WIB", "Riau"),
    "sibolga": ("Sibolga", 98.78, "WIB", "Sumatera Utara"),
    "sibuhuan": ("Sibuhuan", 99.73, "WIB", "Sumatera Utara"),
    "sidenreng": ("Sidenreng", 119.8, "WITA", "Sulawesi Selatan"),
    "sidikalang": ("Sidikalang", 98.31, "WIB", "Sumatera Utara"),
    "sidoarjo": ("Sidoarjo", 112.72, "WIB", "Jawa Timur"),
    "sigi_biromaru": ("Sigi Biromaru", 119.92, "WITA", "Sulawesi Tengah"),
    "sigli": ("Sigli", 95.96, "WIB", "Aceh"),
    "simpang_empat": ("Simpang Empat", 99.82, "WIB", "Sumatera Barat"),
    "simpang_tiga_redelong": ("Simpang Tiga Redelong", 96.87, "WIB", "Aceh"),
    "sinabang": ("Sinabang", 96.38, "WIB", "Aceh"),
    "singaparna": ("Singaparna", 108.11, "WIB", "Jawa Barat"),
    "singaraja": ("Singaraja", 115.09, "WITA", "Bali"),
    "singkawang": ("Singkawang", 108.98, "WIB", "Kalimantan Barat"),
    "singkil": ("Singkil", 97.79, "WIB", "Aceh"),
    "singosari": ("Singosari", 112.67, "WIB", "Jawa Timur"),
    "sinjai": ("Sinjai", 120.25, "WITA", "Sulawesi Selatan"),
    "sintang": ("Sintang", 111.5, "WIB", "Kalimantan Barat"),
    "sipirok": ("Sipirok", 99.27, "WIB", "Sumatera Utara"),
    "situbondo": ("Situbondo", 114.01, "WIB", "Jawa Timur"),
    "siulak": ("Siulak", 101.33, "WIB", "Jambi"),
    "slawi": ("Slawi", 109.14, "WIB", "Jawa Tengah"),
    "sleman": ("Sleman", 110.36, "WIB", "DI Yogyakarta"),
    "sofifi": ("Sofifi", 127.56, "WIT", "Maluku Utara"),
    "sokaraja": ("Sokaraja", 109.29, "WIB", "Jawa Tengah"),
    "solok": ("Solok", 100.66, "WIB", "Sumatera Barat"),
    "soreang": ("Soreang", 107.52, "WIB", "Jawa Barat"),
    "sorendiweri": ("Sorendiweri", 135.74, "WIT", "Papua"),
    "sorong": ("Sorong", 131.26, "WIT", "Papua Barat Daya"),
    "south_tangerang": ("South Tangerang", 106.72, "WIB", "Banten"),
    "sragen": ("Sragen", 111.02, "WIB", "Jawa Tengah"),
    "subang": ("Subang", 107.76, "WIB", "Jawa Barat"),
    "subulussalam": ("Subulussalam", 97.88, "WIB", "Aceh"),
    "sugapa": ("Sugapa", 137.05, "WIT", "Papua Tengah"),
    "suka_makmue": ("Suka Makmue", 96.62, "WIB", "Aceh"),
    "sukabumi": ("Sukabumi", 106.93, "WIB", "Jawa Barat"),
    "sukadana_kalimantan_barat": ("Sukadana, Kalimantan Barat", 109.95, "WIB", "Kalimantan Barat"),
    "sukadana_lampung": ("Sukadana, Lampung", 105.55, "WIB", "Lampung"),
    "sukawati": ("Sukawati", 115.05, "WITA", "Bali"),
    "sukoharjo": ("Sukoharjo", 110.84, "WIB", "Jawa Tengah"),
    "sumbawa_besar": ("Sumbawa Besar", 117.42, "WITA", "Nusa Tenggara Barat"),
    "sumber": ("Sumber", 108.48, "WIB", "Jawa Barat"),
    "sumedang": ("Sumedang", 107.92, "WIB", "Jawa Barat"),
    "sumedang_utara": ("Sumedang Utara", 107.92, "WIB", "Jawa Barat"),
    "sumenep": ("Sumenep", 113.86, "WIB", "Jawa Timur"),
    "sumohai": ("Sumohai", 139.35, "WIT", "Papua Pegunungan"),
    "sungai_penuh": ("Sungai Penuh", 101.39, "WIB", "Jambi"),
    "sungai_raya": ("Sungai Raya", 109.4, "WIB", "Kalimantan Barat"),
    "sungailiat": ("Sungailiat", 106.12, "WIB", "Kepulauan Bangka Belitung"),
    "sunggal": ("Sunggal", 98.62, "WIB", "Sumatera Utara"),
    "sungguminasa": ("Sungguminasa", 119.45, "WITA", "Sulawesi Selatan"),
    "surabaya": ("Surabaya", 112.75, "WIB", "Jawa Timur"),
    "surakarta": ("Surakarta", 110.83, "WIB", "Jawa Tengah"),
    "suwawa": ("Suwawa", 123.15, "WITA", "Gorontalo"),
    "tabanan": ("Tabanan", 115.13, "WITA", "Bali"),
    "tais": ("Tais", 102.58, "WIB", "Bengkulu"),
    "takalar": ("Takalar", 119.44, "WITA", "Sulawesi Selatan"),
    "takengon": ("Takengon", 96.85, "WIB", "Aceh"),
    "talang_ubi": ("Talang Ubi", 103.83, "WIB", "Sumatera Selatan"),
    "taliwang": ("Taliwang", 116.85, "WITA", "Nusa Tenggara Barat"),
    "tambolaka": ("Tambolaka", 119.24, "WITA", "Nusa Tenggara Timur"),
    "tamiang_layang": ("Tamiang Layang", 115.2, "WIB", "Kalimantan Tengah"),
    "tana_paser": ("Tana Paser", 116.19, "WITA", "Kalimantan Timur"),
    "tanah_merah": ("Tanah Merah", 140.31, "WIT", "Papua Selatan"),
    "tangerang": ("Tangerang", 106.63, "WIB", "Banten"),
    "tanjung_pandan": ("Tanjung Pandan", 107.63, "WIB", "Kepulauan Bangka Belitung"),
    "tanjung_pinang": ("Tanjung Pinang", 104.46, "WIB", "Kepulauan Riau"),
    "tanjung_selor": ("Tanjung Selor", 117.37, "WITA", "Kalimantan Utara"),
    "tanjung_kalimantan_selatan": ("Tanjung, Kalimantan Selatan", 115.41, "WITA", "Kalimantan Selatan"),
    "tanjung_nusa_tenggara_barat": ("Tanjung, Nusa Tenggara Barat", 116.16, "WITA", "Nusa Tenggara Barat"),
    "tanjungagung": ("Tanjungagung", 103.8, "WIB", "Sumatera Selatan"),
    "tanjungbalai": ("Tanjungbalai", 99.8, "WIB", "Sumatera Utara"),
    "tarakan": ("Tarakan", 117.59, "WITA", "Kalimantan Utara"),
    "tarempa": ("Tarempa", 106.22, "WIB", "Kepulauan Riau"),
    "tarub": ("Tarub", 109.17, "WIB", "Jawa Tengah"),
    "tasikmalaya": ("Tasikmalaya", 108.22, "WIB", "Jawa Barat"),
    "tebing_tinggi": ("Tebing Tinggi", 103.08, "WIB", "Sumatera Selatan"),
    "tebingtinggi": ("Tebingtinggi", 99.16, "WIB", "Sumatera Utara"),
    "tegal": ("Tegal", 109.14, "WIB", "Jawa Tengah"),
    "teluk_dalam": ("Teluk Dalam", 97.8, "WIB", "Sumatera Utara"),
    "teluk_kuantan": ("Teluk Kuantan", 101.58, "WIB", "Riau"),
    "teluknaga": ("Teluknaga", 106.64, "WIB", "Jawa Barat"),
    "temanggung": ("Temanggung", 110.19, "WIB", "Jawa Tengah"),
    "tembilahan": ("Tembilahan", 103.16, "WIB", "Riau"),
    "teminabuan": ("Teminabuan", 132.01, "WIT", "Papua Barat Daya"),
    "terbanggi_besar": ("Terbanggi Besar", 105.22, "WIB", "Lampung"),
    "ternate": ("Ternate", 127.38, "WIT", "Maluku Utara"),
    "tiakur": ("Tiakur", 127.8, "WIT", "Maluku"),
    "tideng_pale": ("Tideng Pale", 116.91, "WITA", "Kalimantan Utara"),
    "tigaraksa": ("Tigaraksa", 106.51, "WIB", "Banten"),
    "tigi": ("Tigi", 136.27, "WIT", "Papua Tengah"),
    "tilamuta": ("Tilamuta", 122.35, "WITA", "Gorontalo"),
    "timika": ("Timika", 136.68, "WIT", "Papua Tengah"),
    "tiom": ("Tiom", 138.45, "WIT", "Papua Pegunungan"),
    "tobadak": ("Tobadak", 119.35, "WITA", "Sulawesi Barat"),
    "toli_toli": ("Toli-Toli", 120.82, "WITA", "Sulawesi Tengah"),
    "tondano": ("Tondano", 124.91, "WITA", "Sulawesi Utara"),
    "trenggalek": ("Trenggalek", 111.71, "WIB", "Jawa Timur"),
    "tual": ("Tual", 132.75, "WIT", "Maluku"),
    "tuapejat": ("Tuapejat", 99.59, "WIB", "Sumatera Barat"),
    "tuban": ("Tuban", 112.06, "WIB", "Jawa Timur"),
    "tubei": ("Tubei", 102.2, "WIB", "Bengkulu"),
    "tulangan_utara": ("Tulangan Utara", 112.65, "WIB", "Jawa Timur"),
    "tulungagung": ("Tulungagung", 111.9, "WIB", "Jawa Timur"),
    "tutuyan": ("Tutuyan", 124.61, "WITA", "Sulawesi Utara"),
    "ubud": ("Ubud", 115.27, "WITA", "Bali"),
    "ujoh_bilang": ("Ujoh Bilang", 115.25, "WITA", "Kalimantan Timur"),
    "ullong": ("Ullong", 133.91, "WIT", "Papua Barat"),
    "unaaha": ("Unaaha", 122.04, "WITA", "Sulawesi Tenggara"),
    "ungaran": ("Ungaran", 110.41, "WIB", "Jawa Tengah"),
    "waikabubak": ("Waikabubak", 119.39, "WITA", "Nusa Tenggara Timur"),
    "waingapu": ("Waingapu", 120.26, "WITA", "Nusa Tenggara Timur"),
    "waisai": ("Waisai", 130.51, "WIT", "Papua Barat Daya"),
    "wamena": ("Wamena", 138.95, "WIT", "Papua Pegunungan"),
    "wanci": ("Wanci", 123.54, "WITA", "Sulawesi Tenggara"),
    "waris": ("Waris", 140.88, "WIT", "Papua"),
    "watampone": ("Watampone", 120.33, "WITA", "Sulawesi Selatan"),
    "watansoppeng": ("Watansoppeng", 119.88, "WITA", "Sulawesi Selatan"),
    "wates": ("Wates", 110.16, "WIB", "DI Yogyakarta"),
    "weda": ("Weda", 127.87, "WIT", "Maluku Utara"),
    "wedi": ("Wedi", 110.58, "WIB", "Jawa Tengah"),
    "weleri": ("Weleri", 110.07, "WIB", "Jawa Tengah"),
    "weru": ("Weru", 108.5, "WIB", "Jawa Barat"),
    "wiralaga_mulya": ("Wiralaga Mulya", 105.49, "WIB", "Lampung"),
    "wonogiri": ("Wonogiri", 110.92, "WIB", "Jawa Tengah"),
    "wonosari": ("Wonosari", 110.6, "WIB", "DI Yogyakarta"),
    "wonosobo": ("Wonosobo", 109.9, "WIB", "Jawa Tengah"),
    "yogyakarta": ("Yogyakarta", 110.36, "WIB", "DI Yogyakarta"),
}
