SHIO_COMPATIBILITY_BANK = {
    ("anjing", "anjing"): {
        "score": 74,
        "asmara": "Sama-sama Anjing bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Sama-sama bisa dipercaya memegang hal penting, tapi tidak ada yang berani mengambil risiko yang sebenarnya perlu diambil.",
        "drama": "Dua-duanya mencemaskan hal yang sama diam-diam, lalu sama-sama menunggu yang lain bicara duluan.",
        "tips": "Tunjuk satu orang di luar kalian untuk menantang keputusan kalian sesekali.",
    },
    ("anjing", "ayam"): {
        "score": 37,
        "asmara": "Ada aja halangannya, Anjing dan Ayam butuh extra effort buat nyatu.",
        "bisnis": "Salah paham kecil menumpuk diam-diam sampai jadi ketidakpercayaan yang sulit dijelaskan sumbernya.",
        "drama": "Ayam menyindir, Anjing menyimpan, lalu keduanya merasa yang lain yang memulai.",
        "tips": "Buat job desk yang sangat jelas, dan larang saling menyindir lewat pihak ketiga.",
    },
    ("anjing", "babi"): {
        "score": 63,
        "asmara": "Anjing dan Babi? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Anjing menetapkan aturan mainnya, Babi yang bikin orang mau ikut — jalan asal ada yang menagih tenggat.",
        "drama": "Anjing curiga pada orang yang Babi terima begitu saja, dan dua-duanya merasa yang lain tidak realistis.",
        "tips": "Anjing, sebutkan alasan curigamu. Babi, jangan langsung percaya sebelum dicek.",
    },
    ("anjing", "kambing"): {
        "score": 32,
        "asmara": "Kambing butuh dimengerti, Anjing butuh kepastian. Keduanya jarang mendapatkan yang dibutuhkan.",
        "bisnis": "Anjing mau cepat beres, Kambing butuh waktu supaya merasa aman — tanpa pemisahan tugas, kerja sama ini melelahkan keduanya.",
        "drama": "Saling menuduh tidak peduli, padahal dua-duanya sama-sama lelah tapi tidak mengatakannya.",
        "tips": "Pisahkan tanggung jawab sejelas mungkin, dan ucapkan kebutuhanmu langsung tanpa isyarat.",
    },
    ("anjing", "kelinci"): {
        "score": 96,
        "asmara": "Beneran jodoh dari surga! Anjing dan Kelinci itu match banget.",
        "bisnis": "Anjing menjaga standar, Kelinci menjaga hubungan dengan klien — pembagian yang jarang perlu dibicarakan ulang.",
        "drama": "Ributnya cuma waktu Kelinci bilang 'gapapa kok' padahal jelas ada apa-apa, dan Anjing kadung khawatir semalaman.",
        "tips": "Kelinci, sebut keberatanmu di hari kejadian. Anjing, jangan tafsirkan diamnya sebagai masalah besar.",
    },
    ("anjing", "kerbau"): {
        "score": 34,
        "asmara": "Dua-duanya keras dan merasa paling benar, jadi hubungan ini lebih sering jadi ajang adu prinsip.",
        "bisnis": "Anjing dan Kerbau sama-sama yakin caranya paling benar, jadi tenaga habis berdebat soal metode, bukan soal hasil.",
        "drama": "Dua-duanya keras dan sanggup mendiamkan jauh lebih lama dari yang sehat.",
        "tips": "Bagi wewenang secara tegas, dan sepakati bahwa metode berbeda boleh jalan bersamaan.",
    },
    ("anjing", "kuda"): {
        "score": 86,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Anjing dan Kuda.",
        "bisnis": "Kuda menggerakkan, Anjing menjaga supaya tidak ada yang dikorbankan di jalan — laju cepat tapi tidak ceroboh.",
        "drama": "Anjing menganggap Kuda terlalu gampang berjanji, Kuda menganggap Anjing terlalu banyak mencemaskan.",
        "tips": "Kuda, kurangi jumlah janjimu. Anjing, tagih yang penting saja, jangan semuanya.",
    },
    ("anjing", "macan"): {
        "score": 89,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Anjing dan Macan.",
        "bisnis": "Macan berani mengambil keputusan yang tidak enak, Anjing memastikan keputusan itu adil buat semua yang terlibat.",
        "drama": "Macan sudah selesai marah, Anjing masih memutar kejadiannya di kepala berhari-hari.",
        "tips": "Macan, sampaikan bahwa urusannya sudah kelar. Anjing, percaya waktu dia bilang begitu.",
    },
    ("anjing", "monyet"): {
        "score": 58,
        "asmara": "Anjing dan Monyet? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Monyet mencari jalan pintas, Anjing menolak yang tidak lurus — gesekan ini melelahkan tapi menghasilkan kerja yang rapi.",
        "drama": "Anjing menganggap Monyet licin, Monyet menganggap Anjing kaku pada aturan yang tidak penting.",
        "tips": "Tentukan bersama mana aturan yang tidak boleh ditawar dan mana yang boleh diakali.",
    },
    ("anjing", "naga"): {
        "score": 27,
        "asmara": "Waduh, energi kalian gampang bentrok! Anjing sama Naga ibarat api ketemu bensin.",
        "bisnis": "Naga mengejar yang besar, Anjing mengejar yang benar — tanpa wasit, tiap keputusan berubah jadi perdebatan prinsip.",
        "drama": "Naga merasa diragukan, Anjing merasa diabaikan, dan keduanya sama-sama tidak mau mundur.",
        "tips": "Libatkan orang ketiga yang kalian berdua hormati untuk memutus saat buntu.",
    },
    ("anjing", "tikus"): {
        "score": 65,
        "asmara": "Anjing dan Tikus? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Tikus melihat peluang, Anjing memeriksa risikonya — aman asal keputusannya tidak ditunda terus-menerus.",
        "drama": "Dua-duanya waspada, jadi banyak waktu habis untuk saling meyakinkan bahwa tidak ada yang disembunyikan.",
        "tips": "Buka informasi lebih awal dari yang terasa nyaman, di dua arah.",
    },
    ("anjing", "ular"): {
        "score": 65,
        "asmara": "Anjing dan Ular? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Ular menghitung diam-diam, Anjing butuh alasan yang bisa dijelaskan — rapatkan itu dulu sebelum jalan.",
        "drama": "Anjing merasa tidak dilibatkan, Ular merasa tidak semua proses perlu diceritakan.",
        "tips": "Ular, bagikan kesimpulannya meski prosesnya tetap kamu simpan.",
    },
    ("ayam", "ayam"): {
        "score": 44,
        "asmara": "Dua perfeksionis yang saling mengoreksi sampai lupa cara menikmati kebersamaan.",
        "bisnis": "Standar dua-duanya tinggi, jadi mutunya terjamin tapi hampir tidak ada yang pernah dianggap selesai.",
        "drama": "Saling mengoreksi hal kecil sampai keduanya lelah merasa tidak pernah cukup benar.",
        "tips": "Sepakati definisi 'sudah cukup' di awal pekerjaan, lalu hormati definisi itu.",
    },
    ("ayam", "babi"): {
        "score": 65,
        "asmara": "Ayam dan Babi? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Babi membuka hubungan, Ayam merapikan janjinya jadi hitam di atas putih — celahnya di menagih pembayaran.",
        "drama": "Ayam menyebut kekurangan Babi terlalu blak-blakan, Babi tidak melawan tapi jadi menjauh.",
        "tips": "Ayam, ganti nadamu saat mengoreksi. Babi, katakan waktu tersinggung, jangan cuma menghilang.",
    },
    ("ayam", "kambing"): {
        "score": 66,
        "asmara": "Ayam dan Kambing? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Kambing menjaga rasa, Ayam menjaga standar teknisnya — hasilnya bagus kalau keduanya tidak saling merendahkan.",
        "drama": "Ayam mengkritik cara kerja, Kambing membacanya sebagai penolakan pada dirinya.",
        "tips": "Ayam, sebut apa yang sudah benar lebih dulu. Kambing, pisahkan kritik pekerjaan dari penilaian diri.",
    },
    ("ayam", "kelinci"): {
        "score": 28,
        "asmara": "Waduh, energi kalian gampang bentrok! Ayam sama Kelinci ibarat api ketemu bensin.",
        "bisnis": "Ayam menuntut kejelasan, Kelinci menghindari konfrontasi — pekerjaannya jalan tapi hubungannya terkikis.",
        "drama": "Ayam mengejar jawaban, Kelinci mundur, lalu keduanya merasa tidak dihormati.",
        "tips": "Ayam, ajukan satu pertanyaan per waktu. Kelinci, jawab meski jawabannya mengecewakan.",
    },
    ("ayam", "kerbau"): {
        "score": 87,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Ayam dan Kerbau.",
        "bisnis": "Kerbau sanggup menjalani rutinitas panjang, Ayam memastikan tidak ada yang meleset — pekerjaan yang salahnya mahal aman di tangan kalian.",
        "drama": "Ayam menyuarakan kekurangan, Kerbau diam lalu menyimpannya sebagai catatan yang tidak pernah dibahas.",
        "tips": "Kerbau, jawab saat itu juga meski singkat. Ayam, pisahkan mana yang wajib dikoreksi dan mana yang cuma selera.",
    },
    ("ayam", "kuda"): {
        "score": 66,
        "asmara": "Ayam dan Kuda? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Kuda membawa energi dan peluang, Ayam memastikan tidak ada yang bolong di belakang — asal Kuda mau membaca catatannya.",
        "drama": "Kuda menganggap Ayam rewel, Ayam menganggap Kuda ceroboh, dan keduanya sama-sama ada benarnya.",
        "tips": "Kuda, baca ringkasannya sebelum memutuskan. Ayam, kirim ringkasan, bukan seluruh dokumen.",
    },
    ("ayam", "macan"): {
        "score": 66,
        "asmara": "Ayam dan Macan? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Macan mengambil keputusan besar, Ayam menjaga supaya pelaksanaannya tidak berantakan — asal Macan tidak menolak diperiksa.",
        "drama": "Macan tersinggung dikoreksi di depan orang, Ayam tidak paham kenapa fakta bikin marah.",
        "tips": "Ayam, koreksi berdua saja. Macan, jangan balas koreksi dengan menaikkan suara.",
    },
    ("ayam", "monyet"): {
        "score": 61,
        "asmara": "Ayam dan Monyet? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Monyet mencari cara tercepat, Ayam memastikan caranya tetap benar — produktif kalau keduanya berhenti saling menyindir.",
        "drama": "Monyet menghindar dengan bercanda, Ayam mengejar sampai jawabannya jelas.",
        "tips": "Monyet, jawab dulu baru bercanda. Ayam, terima jawaban singkat sebagai jawaban.",
    },
    ("ayam", "naga"): {
        "score": 95,
        "asmara": "Beneran jodoh dari surga! Ayam dan Naga itu match banget.",
        "bisnis": "Naga membawa peluang besar, Ayam memastikan angkanya masuk akal — jarang gagal di tahap eksekusi.",
        "drama": "Naga merasa dikuliahi tiap Ayam mengoreksi detail, padahal Ayam sedang menyelamatkan proyeknya.",
        "tips": "Ayam, sampaikan koreksi berdua saja. Naga, anggap itu bagian dari rencana, bukan serangan ke egomu.",
    },
    ("ayam", "tikus"): {
        "score": 54,
        "asmara": "Bisa dekat dengan cepat, tapi sama cepatnya retak kalau salah satu mulai banyak menuntut.",
        "bisnis": "Rencana kalian bagus di atas kertas tapi sering retak di pelaksanaan karena detailnya diubah sepihak.",
        "drama": "Ayam mengoreksi cara Tikus mengatur uang, Tikus merasa dicurigai padahal sedang berhemat.",
        "tips": "Kunci rencananya tertulis dan sepakati bahwa perubahan harus disetujui berdua.",
    },
    ("ayam", "ular"): {
        "score": 85,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Ayam dan Ular.",
        "bisnis": "Ular membaca situasi sebelum bergerak, Ayam merapikan pelaksanaannya — keputusan kalian jarang perlu diulang.",
        "drama": "Ayam menuntut penjelasan, Ular merasa tidak semua hal perlu diucapkan.",
        "tips": "Ular, berikan versi singkatnya daripada tidak sama sekali. Ayam, jangan bertanya bertubi-tubi di saat yang salah.",
    },
    ("babi", "babi"): {
        "score": 46,
        "asmara": "Nyaman luar biasa, tapi kenyamanan itu sendiri yang perlahan membuat kalian berhenti bertumbuh.",
        "bisnis": "Suasananya paling hangat dari semua pasangan, tapi tidak ada yang mengingatkan waktu uangnya bocor.",
        "drama": "Sama-sama menunda hal yang tidak enak sampai menumpuk jadi masalah yang terlalu besar.",
        "tips": "Tetapkan satu hari tiap bulan khusus membereskan yang selama ini ditunda.",
    },
    ("babi", "kambing"): {
        "score": 88,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Babi dan Kambing.",
        "bisnis": "Babi dan Kambing sama-sama tidak tega, jadi suasana kerjanya enak — tapi kalian butuh satu orang lain yang berani menagih.",
        "drama": "Dua-duanya menunggu yang lain mengambil keputusan sulit, akhirnya tidak ada yang mengambil.",
        "tips": "Tentukan siapa yang memutuskan di urusan apa, tertulis, sebelum kalian membutuhkannya.",
    },
    ("babi", "kelinci"): {
        "score": 88,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Babi dan Kelinci.",
        "bisnis": "Kelinci menjaga hubungan, Babi membuka pintu dengan ketulusan — jaringan kalian tumbuh tanpa terasa diusahakan.",
        "drama": "Dua-duanya menghindari pembicaraan yang tidak enak sampai masalahnya terlalu tua untuk dibahas.",
        "tips": "Pasang jadwal tetap untuk membahas yang mengganjal, supaya tidak menunggu suasana yang pas.",
    },
    ("babi", "kerbau"): {
        "score": 60,
        "asmara": "Babi dan Kerbau? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Kerbau tekun menjalankan, Babi menjaga hubungan dengan orangnya — stabil asal ada yang berani menetapkan target.",
        "drama": "Kerbau merasa menanggung lebih banyak, Babi tidak sadar sedang dibiarkan santai.",
        "tips": "Kerbau, sebutkan bebanmu. Babi, tawarkan bantuan sebelum diminta.",
    },
    ("babi", "kuda"): {
        "score": 59,
        "asmara": "Babi dan Kuda? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Kuda cepat bergerak, Babi membuat orang nyaman bekerja sama — lemahnya di menahan pengeluaran.",
        "drama": "Dua-duanya boros saat suasana hatinya sedang bagus, lalu sama-sama kaget di akhir bulan.",
        "tips": "Pisahkan rekening operasional dari rekening senang-senang, sungguhan beda rekening.",
    },
    ("babi", "macan"): {
        "score": 97,
        "asmara": "Beneran jodoh dari surga! Babi dan Macan itu match banget.",
        "bisnis": "Macan berani mengambil langkah pertama, Babi bikin orang betah bekerja sama — pintu terbuka dan tetap terbuka.",
        "drama": "Macan meledak lima menit, Babi diam saja, lalu dua minggu kemudian baru ketahuan dia sebenarnya terluka.",
        "tips": "Babi, bilang saat itu juga waktu tersinggung. Macan, turunkan volume sebelum menyampaikan isinya.",
    },
    ("babi", "monyet"): {
        "score": 39,
        "asmara": "Ada aja halangannya, Babi dan Monyet butuh extra effort buat nyatu.",
        "bisnis": "Monyet mengakali kesepakatan yang Babi anggap sudah jelas — kerugiannya baru terasa jauh belakangan.",
        "drama": "Babi merasa dimanfaatkan tapi tidak enak menuduh, Monyet merasa tidak melakukan apa pun yang salah.",
        "tips": "Tulis kesepakatannya, termasuk bagian yang kalian anggap tidak perlu ditulis.",
    },
    ("babi", "naga"): {
        "score": 62,
        "asmara": "Babi dan Naga? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Naga membawa ambisi besar, Babi memberi kehangatan yang bikin tim bertahan — asal Babi tidak diambil untung.",
        "drama": "Naga memutuskan sendiri, Babi mengiyakan lalu diam-diam merasa tidak dianggap.",
        "tips": "Babi, sampaikan keberatanmu sebelum keputusan diketok. Naga, tanya dulu.",
    },
    ("babi", "tikus"): {
        "score": 62,
        "asmara": "Babi dan Tikus? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Tikus menjaga hitungan, Babi menjaga relasi — aman asal Tikus tidak menganggap Babi naif.",
        "drama": "Tikus kesal karena Babi terlalu gampang memberi, Babi kesal karena Tikus terlalu menghitung.",
        "tips": "Tetapkan pagu bantuan bersama, supaya tidak ada yang merasa dihakimi.",
    },
    ("babi", "ular"): {
        "score": 23,
        "asmara": "Waduh, energi kalian gampang bentrok! Babi sama Ular ibarat api ketemu bensin.",
        "bisnis": "Babi terbuka apa adanya, Ular menyimpan hampir semuanya — kepercayaan sulit tumbuh meski hasil kerjanya bagus.",
        "drama": "Babi merasa tidak pernah benar-benar dikenal, Ular merasa terus-menerus diinterogasi.",
        "tips": "Ular, bagikan satu hal tanpa diminta. Babi, berhenti menuntut kedekatan dalam tempo cepat.",
    },
    ("kambing", "kambing"): {
        "score": 77,
        "asmara": "Sama-sama Kambing bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Suasana kerjanya paling nyaman, tapi tenggat gampang bergeser karena tidak ada yang tega menagih.",
        "drama": "Sama-sama memendam sampai yang satu menangis dan yang lain kaget kenapa tiba-tiba.",
        "tips": "Pasang tenggat dari luar, dan latih mengatakan 'aku keberatan' tanpa minta maaf lebih dulu.",
    },
    ("kambing", "kelinci"): {
        "score": 86,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Kambing dan Kelinci.",
        "bisnis": "Kambing dan Kelinci sama-sama peka pada rasa dan detail, cocok di bidang yang dinilai dari mutu — lemahnya di urusan menagih bayaran.",
        "drama": "Saling menunggu ditebak, lalu sama-sama kecewa karena tebakannya meleset.",
        "tips": "Ucapkan yang kamu mau dengan kalimat lurus, bukan lewat isyarat.",
    },
    ("kambing", "kerbau"): {
        "score": 29,
        "asmara": "Waduh, energi kalian gampang bentrok! Kambing sama Kerbau ibarat api ketemu bensin.",
        "bisnis": "Kerbau mendorong target, Kambing butuh ruang untuk merasa aman — tekanan yang satu jadi kelumpuhan yang lain.",
        "drama": "Kerbau menganggap Kambing tidak tahan banting, Kambing menganggap Kerbau tidak punya hati.",
        "tips": "Kerbau, sampaikan target tanpa nada menghakimi. Kambing, sebutkan bantuan yang kamu butuhkan.",
    },
    ("kambing", "kuda"): {
        "score": 97,
        "asmara": "Beneran jodoh dari surga! Kambing dan Kuda itu match banget.",
        "bisnis": "Kuda membuka jalan dan mencari orang, Kambing merawat mutu dan detailnya — arus masuk dan mutu keluar sama-sama terjaga.",
        "drama": "Kuda sudah pindah ke rencana berikutnya sementara Kambing masih memikirkan yang kemarin belum tuntas.",
        "tips": "Kuda, tuntaskan satu hal sebelum mengumumkan yang baru. Kambing, jangan pendam kalau merasa ditinggal.",
    },
    ("kambing", "macan"): {
        "score": 67,
        "asmara": "Kambing dan Macan? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Macan berani menembus, Kambing merawat mutunya — jalan asal Macan tidak memaksakan kecepatannya.",
        "drama": "Macan tidak sabar, Kambing jadi kehilangan percaya diri dan malah makin lambat.",
        "tips": "Macan, turunkan tempo saat memberi arahan. Kambing, bilang butuh waktu berapa lama.",
    },
    ("kambing", "monyet"): {
        "score": 67,
        "asmara": "Kambing dan Monyet? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Monyet mencari peluang, Kambing menggarapnya dengan telaten — pas asal Monyet tidak berpindah minat di tengah jalan.",
        "drama": "Monyet menganggap Kambing terlalu baper, Kambing menganggap Monyet tidak serius.",
        "tips": "Monyet, selesaikan yang sudah dimulai. Kambing, jangan menyimpulkan dari nada bercandanya.",
    },
    ("kambing", "naga"): {
        "score": 59,
        "asmara": "Kambing dan Naga? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Naga menetapkan target, Kambing mengeksekusi detail — timpang kalau Naga tidak menghargai kerja yang tidak terlihat.",
        "drama": "Kambing merasa jasanya tidak diakui, Naga tidak sadar ada yang perlu diakui.",
        "tips": "Naga, sebutkan kontribusinya dengan nama. Kambing, tunjukkan hasilmu, jangan menunggu ditemukan.",
    },
    ("kambing", "tikus"): {
        "score": 43,
        "asmara": "Ada aja halangannya, Kambing dan Tikus butuh extra effort buat nyatu.",
        "bisnis": "Tikus berhitung ketat, Kambing tidak tega — keputusan uang jadi tempat keduanya diam-diam saling kecewa.",
        "drama": "Kambing merasa dianggap boros, Tikus merasa dianggap pelit, dan tidak ada yang mengatakannya.",
        "tips": "Pisahkan pos yang boleh dipakai bebas dari pos yang harus disetujui berdua.",
    },
    ("kambing", "ular"): {
        "score": 61,
        "asmara": "Kambing dan Ular? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Ular menyusun rencana, Kambing merawat pelaksanaannya — tenang tapi bisa terlalu lama berputar di tahap persiapan.",
        "drama": "Dua-duanya memendam, jadi tidak ada yang tahu ada masalah sampai salah satunya menyerah.",
        "tips": "Tetapkan satu waktu tetap untuk saling menyebut apa yang sedang mengganjal.",
    },
    ("kelinci", "kelinci"): {
        "score": 75,
        "asmara": "Sama-sama Kelinci bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Rapi, sopan, dan enak dilihat klien — yang jarang terjadi adalah keputusan sulit diambil tepat waktu.",
        "drama": "Tidak ada yang mau memulai, jadi masalahnya mengendap sambil dua-duanya berpura-pura baik-baik saja.",
        "tips": "Sepakati bahwa mengangkat masalah bukan bentuk menyerang, supaya ada yang berani memulai.",
    },
    ("kelinci", "kerbau"): {
        "score": 67,
        "asmara": "Kelinci dan Kerbau? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Kerbau menahan bebannya, Kelinci menjaga suasananya — kuat asal Kelinci berani menyampaikan yang tidak enak.",
        "drama": "Kerbau merasa dia yang mengerjakan semuanya, Kelinci merasa tidak pernah ditanya pendapatnya.",
        "tips": "Kerbau, tanya sebelum memutuskan. Kelinci, jawab jujur waktu ditanya.",
    },
    ("kelinci", "kuda"): {
        "score": 57,
        "asmara": "Kuda bergerak cepat, Kelinci butuh rasa aman. Yang dibangun pelan sering rusak oleh keputusan mendadak.",
        "bisnis": "Awalnya semangat, lalu Kuda pindah fokus dan Kelinci tidak enak menagih — proyeknya mengambang tanpa pernah diumumkan.",
        "drama": "Kuda membatalkan rencana mendadak, Kelinci bilang tidak apa-apa padahal kecewa.",
        "tips": "Kelinci, tagih di hari yang sama. Kuda, umumkan pembatalan sebelum orang terlanjur menyiapkan.",
    },
    ("kelinci", "macan"): {
        "score": 64,
        "asmara": "Kelinci dan Macan? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Macan menerjang, Kelinci melunakkan — cocok menghadapi klien sulit, asal Macan tidak memotong di tengah.",
        "drama": "Macan meninggikan suara, Kelinci langsung menutup diri dan obrolannya selesai sepihak.",
        "tips": "Macan, pelankan. Kelinci, jangan pergi dari ruangan sebelum bilang kamu butuh jeda.",
    },
    ("kelinci", "monyet"): {
        "score": 58,
        "asmara": "Kelinci dan Monyet? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Monyet mencari celah, Kelinci menghaluskan cara menyampaikannya — mulus asal kesepakatannya dicatat.",
        "drama": "Kelinci merasa dipermainkan, Monyet merasa Kelinci terlalu serius menanggapi.",
        "tips": "Catat kesepakatan sekecil apa pun, supaya tidak ada yang bergantung pada ingatan.",
    },
    ("kelinci", "naga"): {
        "score": 41,
        "asmara": "Ada aja halangannya, Kelinci dan Naga butuh extra effort buat nyatu.",
        "bisnis": "Naga mendorong terus, Kelinci mengiyakan lalu kewalahan tanpa memberi tahu — hasilnya meleset di menit terakhir.",
        "drama": "Kelinci menyerap tekanan sampai habis, Naga baru tahu setelah semuanya terlambat.",
        "tips": "Kelinci, katakan kapasitasmu di awal. Naga, tanyakan itu sebelum menambah beban.",
    },
    ("kelinci", "tikus"): {
        "score": 36,
        "asmara": "Awalnya terasa nyaman, tapi lama-lama saling menuntut hal yang diam-diam melukai kalian berdua.",
        "bisnis": "Tikus mendorong, Kelinci mengalah, lalu diam-diam menarik diri dari pekerjaannya sendiri.",
        "drama": "Tikus merasa harus mengurus semuanya, Kelinci merasa tidak pernah diberi ruang.",
        "tips": "Tikus, berhenti mengambil alih. Kelinci, ambil kembali bagianmu dan selesaikan sampai tuntas.",
    },
    ("kelinci", "ular"): {
        "score": 64,
        "asmara": "Kelinci dan Ular? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Ular menimbang dalam-dalam, Kelinci menjaga hubungannya tetap enak — pelan tapi jarang menimbulkan musuh.",
        "drama": "Dua-duanya sopan di permukaan sambil menyimpan penilaian masing-masing.",
        "tips": "Sepakati bahwa jujur tidak akan merusak hubungan kalian, lalu buktikan sekali.",
    },
    ("kerbau", "kerbau"): {
        "score": 72,
        "asmara": "Sama-sama Kerbau bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Kerja keras berlipat, tapi kalau caranya ternyata salah kalian sama-sama terlambat menyadarinya.",
        "drama": "Dua-duanya merasa paling benar dan sama-sama sanggup diam berhari-hari.",
        "tips": "Tetapkan batas waktu untuk mendiamkan: lewat dari itu wajib bicara meski belum reda.",
    },
    ("kerbau", "kuda"): {
        "score": 40,
        "asmara": "Ada aja halangannya, Kerbau dan Kuda butuh extra effort buat nyatu.",
        "bisnis": "Kerbau mengerjakan yang Kuda tinggalkan, dan bebannya menumpuk tanpa pernah dibicarakan.",
        "drama": "Kuda merasa dikekang, Kerbau merasa ditinggal sendirian mengurus sisanya.",
        "tips": "Bagi tugas beserta tenggatnya, lalu tinjau bersama tiap minggu tanpa saling menyalahkan.",
    },
    ("kerbau", "macan"): {
        "score": 59,
        "asmara": "Kerbau dan Macan? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Macan mau cepat, Kerbau mau benar — hasilnya bagus kalau keduanya sepakat soal tenggat sejak awal.",
        "drama": "Macan menganggap Kerbau menghambat, Kerbau menganggap Macan gegabah.",
        "tips": "Sepakati tenggat bersama, lalu Macan berhenti mendesak dan Kerbau berhenti menawar.",
    },
    ("kerbau", "monyet"): {
        "score": 68,
        "asmara": "Kerbau dan Monyet? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Monyet menemukan jalan pintas, Kerbau menolak yang belum teruji — pelan tapi hasilnya tahan lama.",
        "drama": "Monyet bosan dengan cara lama, Kerbau curiga pada cara baru.",
        "tips": "Coba cara Monyet di skala kecil dulu, dengan ukuran keberhasilan yang disepakati Kerbau.",
    },
    ("kerbau", "naga"): {
        "score": 50,
        "asmara": "Dua ego besar yang sama-sama enggan menyesuaikan diri, jadi kemajuan hubungan mudah mundur lagi.",
        "bisnis": "Naga mengubah arah saat Kerbau sudah membangun fondasinya — kerja yang sudah jadi sering terbuang.",
        "drama": "Kerbau merasa usahanya disepelekan, Naga merasa dihambat oleh kekakuan.",
        "tips": "Naga, umumkan perubahan sebelum Kerbau mulai mengerjakan. Kerbau, tanyakan sasaran akhirnya sebelum berangkat.",
    },
    ("kerbau", "tikus"): {
        "score": 98,
        "asmara": "Beneran jodoh dari surga! Kerbau dan Tikus itu match banget.",
        "bisnis": "Tikus mencium peluang dan menghitung risikonya, Kerbau menjalankan sampai tuntas tanpa mengeluh.",
        "drama": "Tikus gelisah karena Kerbau tidak segera bergerak, Kerbau kesal karena rencananya diubah saat sudah jalan.",
        "tips": "Sepakati tenggat di awal. Setelah itu Tikus berhenti mengubah, Kerbau berhenti menunda.",
    },
    ("kerbau", "ular"): {
        "score": 89,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Kerbau dan Ular.",
        "bisnis": "Ular menimbang, Kerbau mengeksekusi tanpa banyak bertanya — pelan tapi hampir tidak pernah salah langkah.",
        "drama": "Dua-duanya irit bicara, jadi salah paham bisa mengendap berbulan-bulan tanpa ada yang menyadari.",
        "tips": "Sepakati satu pertanyaan wajib tiap minggu: ada yang mengganjal atau tidak?",
    },
    ("kuda", "kuda"): {
        "score": 47,
        "asmara": "Seru dan penuh petualangan, tapi tidak ada yang memegang kemudi saat keduanya ingin lari.",
        "bisnis": "Energinya berlipat dan ide berdatangan, tapi tidak ada yang menuntaskan dan semuanya berhenti di tengah.",
        "drama": "Dua-duanya bicara duluan dan berpikir belakangan, jadi luka kecil menumpuk tanpa pernah dibereskan.",
        "tips": "Pilih satu proyek dan larang diri kalian memulai yang baru sebelum yang itu ditutup.",
    },
    ("kuda", "macan"): {
        "score": 87,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Kuda dan Macan.",
        "bisnis": "Kuda dan Macan sama-sama berani dan cepat, cocok merintis — yang kurang orang yang mau mengurus sisa administrasinya.",
        "drama": "Sama-sama bicara duluan dan berpikir belakangan, jadi ributnya cepat panas meski isinya sepele.",
        "tips": "Sepakati aturan jeda: siapa pun boleh menghentikan obrolan satu jam sebelum dilanjutkan.",
    },
    ("kuda", "monyet"): {
        "score": 60,
        "asmara": "Kuda dan Monyet? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Kuda dan Monyet sama-sama cepat dan luwes, peluang datang terus — yang hilang justru orang yang menutup pekerjaannya.",
        "drama": "Sama-sama pindah ke hal baru, jadi janji lama menumpuk tanpa ada yang mengurus.",
        "tips": "Buat daftar yang belum selesai di tempat yang kelihatan, dan larang menambah sebelum ada yang dicoret.",
    },
    ("kuda", "naga"): {
        "score": 68,
        "asmara": "Kuda dan Naga? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Naga memimpikan yang besar, Kuda langsung berangkat — momentumnya luar biasa, ketelitiannya yang perlu dipinjam dari orang lain.",
        "drama": "Dua-duanya gengsi mengaku kewalahan, jadi masalahnya baru kelihatan setelah terlanjur besar.",
        "tips": "Sepakati satu laporan jujur mingguan, isinya khusus apa yang tidak berjalan.",
    },
    ("kuda", "tikus"): {
        "score": 24,
        "asmara": "Waduh, energi kalian gampang bentrok! Kuda sama Tikus ibarat api ketemu bensin.",
        "bisnis": "Kuda ingin berangkat sekarang, Tikus ingin menghitung dulu — tiap keputusan jadi tarik-menarik yang menguras.",
        "drama": "Kuda merasa dikekang, Tikus merasa diseret ke risiko yang tidak dia setujui.",
        "tips": "Pisahkan modal yang boleh dipertaruhkan dari yang tidak, lalu masing-masing bebas di wilayahnya.",
    },
    ("kuda", "ular"): {
        "score": 64,
        "asmara": "Kuda dan Ular? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Ular menghitung sebelum melangkah, Kuda sudah berangkat duluan — jalan asal keduanya sepakat kapan berhenti membahas.",
        "drama": "Kuda merasa ditahan, Ular merasa diseret ke keputusan yang belum matang.",
        "tips": "Tetapkan batas waktu berpikir. Lewat dari itu, jalan dengan keputusan terbaik yang ada.",
    },
    ("macan", "macan"): {
        "score": 75,
        "asmara": "Sama-sama Macan bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Dua-duanya mau memimpin dan tidak ada yang mau mengurus rincian — cepat berangkat, sering tersandung di tengah.",
        "drama": "Ributnya besar dan cepat, lalu sama-sama gengsi menyapa duluan.",
        "tips": "Bagi wilayah wewenang sejak awal, dan gilir siapa yang minta maaf lebih dulu.",
    },
    ("macan", "monyet"): {
        "score": 25,
        "asmara": "Waduh, energi kalian gampang bentrok! Macan sama Monyet ibarat api ketemu bensin.",
        "bisnis": "Macan menerjang langsung, Monyet memutar lewat samping — sama-sama efektif sendiri, saling mengacaukan kalau bareng.",
        "drama": "Macan merasa dipermainkan, Monyet merasa Macan tidak bisa diajak berpikir.",
        "tips": "Kerjakan bagian masing-masing secara terpisah, lalu satukan hasilnya di titik yang disepakati.",
    },
    ("macan", "naga"): {
        "score": 60,
        "asmara": "Macan dan Naga? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Macan dan Naga sama-sama ingin memimpin dan sama-sama berani — hebat di depan klien, berantakan kalau wewenangnya tidak dibagi.",
        "drama": "Berebut siapa yang menentukan arah, padahal arah yang mereka mau sebenarnya sama.",
        "tips": "Bagi wilayah keputusan secara tertulis sebelum proyek dimulai, bukan sesudah bentrok.",
    },
    ("macan", "tikus"): {
        "score": 61,
        "asmara": "Macan dan Tikus? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Tikus menyiapkan bekal, Macan yang berangkat — efektif asal Macan mau mendengar hitungannya.",
        "drama": "Macan menganggap Tikus terlalu hati-hati, Tikus menganggap Macan nekat tanpa rencana.",
        "tips": "Macan, tanya dulu berapa cadangannya. Tikus, sampaikan sebagai batas, bukan sebagai larangan.",
    },
    ("macan", "ular"): {
        "score": 30,
        "asmara": "Tarik-menarik yang intens dan memabukkan, tapi dua-duanya menyimpan senjata untuk saat bertengkar.",
        "bisnis": "Macan bergerak terbuka, Ular menyiapkan diam-diam — keduanya merasa yang lain tidak jujur soal niatnya.",
        "drama": "Macan meledak karena merasa ada yang disembunyikan, Ular makin menutup karena diledaki.",
        "tips": "Sepakati apa yang wajib diberitahukan dan apa yang boleh disimpan, sebelum curiga terbentuk.",
    },
    ("monyet", "monyet"): {
        "score": 73,
        "asmara": "Sama-sama Monyet bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Ide mengalir terus dan solusinya kreatif, tapi tidak ada yang betah menuntaskan bagian yang membosankan.",
        "drama": "Sama-sama mengubah pembicaraan serius jadi lelucon sampai tidak ada yang benar-benar selesai.",
        "tips": "Tetapkan satu jam tanpa bercanda per minggu, khusus untuk hal yang belum kelar.",
    },
    ("monyet", "naga"): {
        "score": 90,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Monyet dan Naga.",
        "bisnis": "Naga menetapkan target besar, Monyet mencari jalan pintas yang sah untuk mencapainya — gerak kalian cepat sekali.",
        "drama": "Monyet mengalihkan pembicaraan serius dengan candaan, Naga menganggap itu tidak menghormati.",
        "tips": "Monyet, selesaikan satu pembicaraan serius tanpa melucu. Naga, jangan baca candaannya sebagai perendahan.",
    },
    ("monyet", "tikus"): {
        "score": 90,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Monyet dan Tikus.",
        "bisnis": "Tikus menghitung, Monyet mencari celah — kalian menemukan peluang yang orang lain tidak lihat.",
        "drama": "Dua-duanya pintar berkelit, jadi pertengkarannya berubah jadi adu argumen yang tidak ada ujungnya.",
        "tips": "Berhenti membuktikan siapa yang lebih benar, mulai menentukan apa yang mau diperbaiki.",
    },
    ("monyet", "ular"): {
        "score": 99,
        "asmara": "Beneran jodoh dari surga! Monyet dan Ular itu match banget.",
        "bisnis": "Ular menyusun strategi dalam diam, Monyet mencari celah pelaksanaannya — jarang ada yang bisa mengimbangi kecepatan ini.",
        "drama": "Dua-duanya menyimpan informasi, jadi masalah baru ketahuan setelah terlanjur membesar.",
        "tips": "Buat satu forum rutin untuk saling membuka kartu, meski terasa tidak perlu.",
    },
    ("naga", "naga"): {
        "score": 49,
        "asmara": "Dua Naga saling mengagumi sampai keduanya sadar tidak ada yang bersedia jadi pendukung.",
        "bisnis": "Ambisi dua-duanya besar, tapi tidak ada yang mau mengerjakan bagian yang tidak kelihatan.",
        "drama": "Sama-sama gengsi mengakui salah, jadi ributnya panjang meski isinya sudah selesai.",
        "tips": "Gilir siapa yang mengambil peran pendukung tiap proyek, tanpa dianggap kalah.",
    },
    ("naga", "tikus"): {
        "score": 85,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Naga dan Tikus.",
        "bisnis": "Naga mengangkat visinya, Tikus memastikan kasnya cukup untuk sampai ke sana — ambisi yang jarang kehabisan bahan bakar.",
        "drama": "Tikus mencemaskan hal yang belum terjadi, Naga menganggapnya menghambat keberanian.",
        "tips": "Naga, dengarkan angka yang dia sebut. Tikus, sampaikan sebagai syarat, bukan sebagai larangan.",
    },
    ("naga", "ular"): {
        "score": 62,
        "asmara": "Naga dan Ular? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Naga tampil di depan, Ular menyiapkan strateginya di belakang — kuat asal Naga tidak mengklaim semuanya.",
        "drama": "Ular merasa jasanya diambil, tapi memilih tidak mengatakannya.",
        "tips": "Naga, sebut namanya di depan orang. Ular, katakan waktu merasa tidak dihargai.",
    },
    ("tikus", "tikus"): {
        "score": 76,
        "asmara": "Sama-sama Tikus bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Dua-duanya hemat dan waspada, jadi jarang rugi — tapi juga jarang mengambil peluang yang perlu keberanian.",
        "drama": "Saling mengecek diam-diam alih-alih bertanya langsung, lalu sama-sama merasa tidak dipercaya.",
        "tips": "Ganti kebiasaan memeriksa jadi kebiasaan bertanya, meski jawabannya mungkin tidak enak.",
    },
    ("tikus", "ular"): {
        "score": 63,
        "asmara": "Tikus dan Ular? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Tikus dan Ular sama-sama menghitung sebelum bergerak, jadi jarang rugi — tapi juga jarang mengambil peluang yang perlu nekat.",
        "drama": "Sama-sama menyimpan informasi, jadi kepercayaannya tumbuh sangat lambat.",
        "tips": "Bergantian membuka satu hal yang biasanya kalian simpan, sampai jadi kebiasaan.",
    },
    ("ular", "ular"): {
        "score": 78,
        "asmara": "Sama-sama Ular bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Analisisnya dalam dan keputusannya matang, tapi bisa terlalu lama menimbang sampai kesempatannya lewat.",
        "drama": "Dua-duanya menyimpan, jadi yang terlihat cuma jarak yang pelan-pelan melebar tanpa penjelasan.",
        "tips": "Tetapkan tanggal keputusan sejak awal, dan biasakan menyebut satu hal yang sedang kamu simpan.",
    },
}


PAIR_ELEMENT_DYNAMIC_BANK = {
    "memberi": {
        "label": "Memberi Energi",
        "arrow": "\u2192",
        "icon": "\U0001f331",
        "summary": "Elemen {self_element} milik {self} menghidupi {other_element} milik {other}. Kamu yang lebih sering menyalurkan tenaga, ide, dan dukungan ke arahnya.",
        "advice": "Peran menumbuhkan itu memang cocok denganmu. Yang perlu dijaga: jangan sampai kamu kehabisan sendiri karena tidak ada yang mengisi balik.",
    },
    "menerima": {
        "label": "Menerima Dukungan",
        "arrow": "\u2190",
        "icon": "\U0001f381",
        "summary": "Elemen {other_element} milik {other} menghidupi {self_element} milik {self}. Kamu yang lebih sering ditopang, dibukakan jalan, dan diberi tenaga.",
        "advice": "Terima dukungannya tanpa merasa berutang, tapi sebutkan terima kasihmu dengan jelas. Hubungan seperti ini retak saat sokongan mulai dianggap wajar.",
    },
    "menekan": {
        "label": "Menekan",
        "arrow": "\u21d2",
        "icon": "\u2699\ufe0f",
        "summary": "Elemen {self_element} milik {self} mengekang {other_element} milik {other}. Kamu yang lebih sering mengatur tempo, menetapkan batas, dan mengoreksi.",
        "advice": "Tekananmu bisa jadi disiplin yang dia butuhkan atau beban yang bikin dia menutup diri. Bedanya ada di nada, bukan di isinya.",
    },
    "ditekan": {
        "label": "Ditekan",
        "arrow": "\u21d0",
        "icon": "\U0001f9ff",
        "summary": "Elemen {other_element} milik {other} mengekang {self_element} milik {self}. Kamu yang lebih sering merasa diatur, dikoreksi, atau harus menyesuaikan diri.",
        "advice": "Tidak semua tekanan itu buruk, sebagian memang menajamkan. Tapi tetapkan batas yang jelas soal mana yang boleh dia atur dan mana yang tidak.",
    },
    "setara": {
        "label": "Setara",
        "arrow": "\u2194",
        "icon": "\u2696\ufe0f",
        "summary": "{self} dan {other} sama-sama berelemen {self_element}, jadi tidak ada yang otomatis memberi atau menekan. Kalian berdiri di posisi yang sama.",
        "advice": "Kekuatannya di saling paham, kelemahannya di titik buta yang sama. Cari orang ketiga berelemen beda untuk menutup yang kalian berdua lewatkan.",
    },
}


PAIR_RELATION_BANK = {
    "liu_he": {
        "label": "Liu He",
        "hanzi": "六合",
        "title": "Pasangan Enam Harmoni",
        "code": "good",
        "note": "Ikatan paling erat di antara dua belas cabang. Dua shio ini saling mengunci — yang satu menutup celah yang satunya, tanpa perlu dibicarakan.",
    },
    "san_he": {
        "label": "San He",
        "hanzi": "三合",
        "title": "Satu Kelompok Tiga Harmoni",
        "code": "good",
        "note": "Kalian berdua anggota trine yang sama, jadi arah hidupnya searah sejak awal. Kerja sama terasa ringan karena tujuannya memang mirip.",
    },
    "ben_ming": {
        "label": "Bi Jian",
        "hanzi": "比肩",
        "title": "Cabang Kembar",
        "code": "neutral",
        "note": "Shio yang sama berarti watak sebaya. Saling paham tanpa dijelaskan, tapi titik butanya juga persis sama — tidak ada yang menutupi kelemahan siapa pun.",
    },
    "zi_xing": {
        "label": "Zi Xing",
        "hanzi": "自刑",
        "title": "Cabang Kembar yang Menghukum Diri",
        "code": "bad",
        "note": "Shio yang sama, tapi cabang ini termasuk yang menghukum dirinya sendiri. Kebiasaan buruk yang sama jadi berlipat dua, bukan saling mengoreksi.",
    },
    "netral": {
        "label": "Ping",
        "hanzi": "平",
        "title": "Tidak Ada Ikatan Khusus",
        "code": "neutral",
        "note": "Tidak ada tarikan maupun benturan bawaan antara kedua cabang. Hubungan ini ditentukan usaha kalian, bukan oleh bawaan shionya.",
    },
    "liu_po": {
        "label": "Liu Po",
        "hanzi": "六破",
        "title": "Pasangan Perusakan",
        "code": "bad",
        "note": "Yang sudah tersusun rapi gampang retak di tangan berdua. Rencana tetap bisa jalan, asal diperiksa ulang lebih sering dari biasanya.",
    },
    "liu_hai": {
        "label": "Liu Hai",
        "hanzi": "六害",
        "title": "Pasangan Saling Menyakiti",
        "code": "bad",
        "note": "Luka yang timbul biasanya halus dan tidak disengaja. Bukan pertengkaran besar, melainkan hal kecil yang menumpuk tanpa pernah dibahas.",
    },
    "xiang_xing": {
        "label": "Xiang Xing",
        "hanzi": "相刑",
        "title": "Pasangan Saling Menghukum",
        "code": "bad",
        "note": "Kedua cabang saling menggerus. Gesekannya pelan tapi terus-menerus, sering muncul lewat urusan aturan, kesepakatan, atau siapa yang berhak memutuskan.",
    },
    "chong": {
        "label": "Chong",
        "hanzi": "六冲",
        "title": "Pasangan Berseberangan",
        "code": "bad",
        "note": "Dua cabang yang berhadapan lurus di lingkaran. Tarik-menarik terus terjadi, dan perubahan di hubungan ini jarang datang pelan-pelan.",
    },
}

DAY_PILLAR_RELATION_BANK = {
    "liu_he": "Cabang hari kalian berpasangan 六合. Di 合婚 ini bacaan paling kuat: istana pasangan kalian saling mengunci, bukan sekadar shionya cocok.",
    "san_he": "Cabang hari kalian satu kelompok 三合. Istana pasangan kalian menarik ke arah yang sama, jadi hidup bersama terasa searah.",
    "ben_ming": "Cabang hari kalian sama. Kalian mengenali diri sendiri di pasangan — nyaman, tapi jarang ada yang menantang.",
    "zi_xing": "Cabang hari kalian sama dan termasuk yang menghukum diri. Pola yang sama berulang di dua orang sekaligus.",
    "netral": "Cabang hari kalian tidak berelasi khusus. Istana pasangan kalian netral: tidak menarik, tidak menolak.",
    "liu_po": "Cabang hari kalian 六破. Kesepakatan rumah tangga gampang berubah bentuk; tulis yang penting, jangan andalkan ingatan.",
    "liu_hai": "Cabang hari kalian 六害. Yang melukai biasanya hal kecil yang dianggap sepele oleh yang melakukannya.",
    "xiang_xing": "Cabang hari kalian 相刑. Istana pasangan saling menggerus — biasanya soal siapa yang mengalah dan seberapa sering.",
    "chong": "Cabang hari kalian 六冲. Ini yang paling diperhatikan di 合婚 klasik: istana pasangan berhadapan langsung, jadi hubungan ini butuh aturan main yang jelas sejak awal.",
}

DAY_STEM_CONTEXT = {
    "he": "Batang hari kalian berpadu ({hanzi}). Watak inti kalian saling melengkapi, bukan sekadar akur di permukaan.",
    "chong": "Batang hari kalian berbenturan ({hanzi}). Dua watak inti yang sama-sama tidak mau membelok lebih dulu.",
    "netral": "Batang hari kalian tidak berpadu maupun berbenturan. Watak inti kalian berjalan sendiri-sendiri tanpa saling menarik.",
}

USEFUL_GOD_MATCH_BANK = {
    "saling_memasok": {
        "title": "Saling Memasok",
        "code": "good",
        "note": "Elemen inti {a} termasuk yang dibutuhkan {b}, dan sebaliknya. Ini hasil terbaik di 合婚 modern — kalian saling menambal kekurangan, bukan cuma cocok di permukaan.",
        "advice": "Hubungan seperti ini biasanya bikin keduanya naik. Jangan sia-siakan dengan menunda hal yang perlu diputuskan bersama.",
    },
    "sepihak": {
        "title": "Satu Arah",
        "code": "neutral",
        "note": "Elemen inti {giver} memasok apa yang dibutuhkan {receiver}, tapi tidak sebaliknya. Yang satu lebih banyak menerima, yang satu lebih banyak memberi.",
        "advice": "Bukan masalah selama disadari. Yang memberi perlu diisi ulang dari tempat lain, bukan dari hubungan ini saja.",
    },
    "timpang": {
        "title": "Timpang",
        "code": "neutral",
        "note": "Satu pihak memasok, satu pihak justru menekan. Hubungan ini terasa hangat sekaligus melelahkan tergantung siapa yang ditanya.",
        "advice": "Bicarakan soal porsi, bukan soal perasaan. Yang timpang di sini bisa dihitung, jadi bisa juga diatur.",
    },
    "saling_menguras": {
        "title": "Saling Menguras",
        "code": "bad",
        "note": "Elemen inti kalian masing-masing justru termasuk yang membebani pasangannya. Secara struktur, kebersamaan ini menuntut tenaga ekstra dari keduanya.",
        "advice": "Bukan berarti tidak bisa. Tapi hubungan ini butuh sumber tenaga dari luar — pekerjaan, lingkaran, atau waktu sendiri yang dijaga.",
    },
    "netral": {
        "title": "Netral",
        "code": "neutral",
        "note": "Elemen inti kalian tidak saling memasok maupun menekan. Tidak ada dorongan struktural ke arah mana pun.",
        "advice": "Yang menentukan hubungan ini bukan bawaan chart, melainkan kebiasaan yang kalian bangun sendiri.",
    },
}

COUPLE_STAR_BANK = {
    "tao_hua_both": {
        "icon": "🌸",
        "title": "Dua-duanya Bawa 桃花",
        "code": "neutral",
        "note": "Kalian berdua punya Bintang Pesona di chart. Mudah saling tertarik, tapi juga sama-sama mudah menarik perhatian dari luar. Batasnya perlu disepakati, bukan diasumsikan.",
    },
    "tao_hua_one": {
        "icon": "🌸",
        "title": "Satu Pihak Bawa 桃花",
        "code": "neutral",
        "note": "Satu dari kalian punya Bintang Pesona. Perhatian dari luar lebih sering datang ke pihak itu — bukan salahnya, tapi perlu dibicarakan sebelum jadi curiga.",
    },
    "solitude_both": {
        "icon": "🌑",
        "title": "Dua-duanya Bawa Bintang Kesendirian",
        "code": "bad",
        "note": "孤辰 atau 寡宿 muncul di kedua chart. Kalian berdua sama-sama butuh ruang sendiri, dan itu bisa terbaca sebagai dingin kalau tidak dijelaskan.",
    },
    "solitude_one": {
        "icon": "🌑",
        "title": "Satu Pihak Bawa Bintang Kesendirian",
        "code": "neutral",
        "note": "Satu dari kalian cenderung menarik diri saat sedang berat. Itu bukan penolakan, dan pasangannya perlu tahu itu sejak awal.",
    },
    "tian_yi": {
        "icon": "⭐",
        "title": "Ada 天乙貴人 di Hubungan Ini",
        "code": "good",
        "note": "Setidaknya satu dari kalian membawa Bintang Penolong Mulia. Saat hubungan ini kesulitan, pertolongan cenderung datang lewat perantara.",
    },
}
