SHIO_COMPATIBILITY_BANK = {
    ("anjing", "anjing"): {
        "score": 74,
        "asmara": "Sama-sama Anjing bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("anjing", "ayam"): {
        "score": 37,
        "asmara": "Ada aja halangannya, Anjing dan Ayam butuh extra effort buat nyatu.",
        "bisnis": "Sering miskom dan curigaan sendiri, mending bikin job desk yang super jelas.",
        "drama": "Drama saling sindir pakai quotes di IG Story sampe temen-temen ikutan bingung.",
        "tips": "Stop saling nyalahin, coba duduk bareng dan ngomong dari hati ke hati.",
    },
    ("anjing", "babi"): {
        "score": 63,
        "asmara": "Anjing dan Babi? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Kerja bareng kalian asyik, satu mikir strategi satu lagi eksekusi.",
        "drama": "Satu mau healing ke gunung, satu mau ke mall, akhirnya malah sama-sama bad mood di rumah.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("anjing", "kambing"): {
        "score": 32,
        "asmara": "Kambing butuh dimengerti, Anjing butuh kepastian. Keduanya jarang mendapatkan yang dibutuhkan.",
        "bisnis": "Beda ritme kerja bikin salah satu merasa ditinggal dan yang lain merasa dikejar-kejar.",
        "drama": "Saling menuduh tidak peduli, padahal dua-duanya sama-sama lelah tapi tidak bilang.",
        "tips": "Ucapkan kebutuhanmu secara langsung. Menebak-tebak isi kepala pasangan cuma memperbesar luka.",
    },
    ("anjing", "kelinci"): {
        "score": 96,
        "asmara": "Beneran jodoh dari surga! Anjing dan Kelinci itu match banget.",
        "bisnis": "Chemistry kalian di dunia kerja itu dewa banget, auto cuan kalau bareng.",
        "drama": "Gak ada drama berat, paling ribut rebutan siapa yang traktir boba duluan.",
        "tips": "Pertahankan vibes positif kalian, you guys are perfect together!",
    },
    ("anjing", "kerbau"): {
        "score": 34,
        "asmara": "Dua-duanya keras dan merasa paling benar, jadi hubungan ini lebih sering jadi ajang adu prinsip.",
        "bisnis": "Sama-sama ngotot soal cara kerja. Tanpa pemisahan wewenang yang tegas, kerja sama ini melelahkan.",
        "drama": "Perang dingin berhari-hari karena tidak ada yang mau mengalah duluan.",
        "tips": "Sepakati satu aturan: siapa yang lebih tenang, dia yang bicara duluan. Bukan siapa yang lebih benar.",
    },
    ("anjing", "kuda"): {
        "score": 86,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Anjing dan Kuda.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("anjing", "macan"): {
        "score": 89,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Anjing dan Macan.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("anjing", "monyet"): {
        "score": 58,
        "asmara": "Anjing dan Monyet? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("anjing", "naga"): {
        "score": 27,
        "asmara": "Waduh, energi kalian gampang bentrok! Anjing sama Naga ibarat api ketemu bensin.",
        "bisnis": "Bakal sering debat meeting, siapin kopi ekstra biar gak gampang emosi.",
        "drama": "Satu ngomong A, satu denger Z. Ujung-ujungnya saling block di Instagram semaleman.",
        "tips": "Harus ada yang ngalah! Jangan dua-duanya keras kepala kalau mau langgeng.",
    },
    ("anjing", "tikus"): {
        "score": 65,
        "asmara": "Anjing dan Tikus? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Jangan rebutan spotlight ya pas meeting, bagi-bagi tugas aja.",
        "drama": "Debat soal film yang mau ditonton berujung perang dingin di chat.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("anjing", "ular"): {
        "score": 65,
        "asmara": "Anjing dan Ular? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("ayam", "ayam"): {
        "score": 44,
        "asmara": "Dua perfeksionis yang saling mengoreksi sampai lupa cara menikmati kebersamaan.",
        "bisnis": "Standar tinggi berlipat ganda. Hasilnya rapi, tapi prosesnya menguras mental kalian berdua.",
        "drama": "Saling menunjuk detail yang salah, padahal yang dibutuhkan cuma satu kalimat apresiasi.",
        "tips": "Sepakati satu hari tanpa saling mengkritik. Biarkan yang tidak sempurna lewat begitu saja.",
    },
    ("ayam", "babi"): {
        "score": 65,
        "asmara": "Ayam dan Babi? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Ribut kecil dari salah paham emoji doang, tapi panjang urusannya wkwk.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("ayam", "kambing"): {
        "score": 66,
        "asmara": "Ayam dan Kambing? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Jangan rebutan spotlight ya pas meeting, bagi-bagi tugas aja.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("ayam", "kelinci"): {
        "score": 28,
        "asmara": "Waduh, energi kalian gampang bentrok! Ayam sama Kelinci ibarat api ketemu bensin.",
        "bisnis": "Bakal sering debat meeting, siapin kopi ekstra biar gak gampang emosi.",
        "drama": "Satu ngomong A, satu denger Z. Ujung-ujungnya saling block di Instagram semaleman.",
        "tips": "Harus ada yang ngalah! Jangan dua-duanya keras kepala kalau mau langgeng.",
    },
    ("ayam", "kerbau"): {
        "score": 87,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Ayam dan Kerbau.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("ayam", "kuda"): {
        "score": 66,
        "asmara": "Ayam dan Kuda? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Kerja bareng kalian asyik, satu mikir strategi satu lagi eksekusi.",
        "drama": "Pas ribut gara-gara milih tempat makan, bisa sampai diem-dieman tiga hari.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("ayam", "macan"): {
        "score": 66,
        "asmara": "Ayam dan Macan? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("ayam", "monyet"): {
        "score": 61,
        "asmara": "Ayam dan Monyet? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("ayam", "naga"): {
        "score": 95,
        "asmara": "Beneran jodoh dari surga! Ayam dan Naga itu match banget.",
        "bisnis": "Chemistry kalian di dunia kerja itu dewa banget, auto cuan kalau bareng.",
        "drama": "Gak ada drama berat, paling ribut rebutan siapa yang traktir boba duluan.",
        "tips": "Pertahankan vibes positif kalian, you guys are perfect together!",
    },
    ("ayam", "tikus"): {
        "score": 54,
        "asmara": "Bisa dekat dengan cepat, tapi sama cepatnya retak kalau salah satu mulai banyak menuntut.",
        "bisnis": "Rencana sering berubah di tengah jalan. Kunci fondasi dulu sebelum menambah target baru.",
        "drama": "Kritik kecil yang dianggap remeh perlahan mengikis rasa hormat di antara kalian.",
        "tips": "Rawat yang sudah ada sebelum mengejar yang baru. Hubungan ini bocor halus, bukan jebol besar.",
    },
    ("ayam", "ular"): {
        "score": 85,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Ayam dan Ular.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("babi", "babi"): {
        "score": 46,
        "asmara": "Nyaman luar biasa, tapi kenyamanan itu sendiri yang perlahan membuat kalian berhenti bertumbuh.",
        "bisnis": "Sama-sama terlalu percaya dan enggan menagih, jadi rawan dimanfaatkan pihak ketiga.",
        "drama": "Tidak ada yang tegas, jadi masalah dibiarkan mengendap sampai meledak tanpa peringatan.",
        "tips": "Tetapkan batas yang jelas, termasuk kepada satu sama lain. Baik hati bukan berarti tanpa aturan.",
    },
    ("babi", "kambing"): {
        "score": 88,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Babi dan Kambing.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("babi", "kelinci"): {
        "score": 88,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Babi dan Kelinci.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("babi", "kerbau"): {
        "score": 60,
        "asmara": "Babi dan Kerbau? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Jangan rebutan spotlight ya pas meeting, bagi-bagi tugas aja.",
        "drama": "Ribut kecil dari salah paham emoji doang, tapi panjang urusannya wkwk.",
        "tips": "Kasih space satu sama lain biar gak gampang bosen.",
    },
    ("babi", "kuda"): {
        "score": 59,
        "asmara": "Babi dan Kuda? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Debat soal film yang mau ditonton berujung perang dingin di chat.",
        "tips": "Kasih space satu sama lain biar gak gampang bosen.",
    },
    ("babi", "macan"): {
        "score": 97,
        "asmara": "Beneran jodoh dari surga! Babi dan Macan itu match banget.",
        "bisnis": "Chemistry kalian di dunia kerja itu dewa banget, auto cuan kalau bareng.",
        "drama": "Gak ada drama berat, paling ribut rebutan siapa yang traktir boba duluan.",
        "tips": "Pertahankan vibes positif kalian, you guys are perfect together!",
    },
    ("babi", "monyet"): {
        "score": 39,
        "asmara": "Ada aja halangannya, Babi dan Monyet butuh extra effort buat nyatu.",
        "bisnis": "Sering miskom dan curigaan sendiri, mending bikin job desk yang super jelas.",
        "drama": "Drama saling sindir pakai quotes di IG Story sampe temen-temen ikutan bingung.",
        "tips": "Stop saling nyalahin, coba duduk bareng dan ngomong dari hati ke hati.",
    },
    ("babi", "naga"): {
        "score": 62,
        "asmara": "Babi dan Naga? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Cuan ngalir lancar kalau udah satu visi misi.",
        "drama": "Ribut kecil dari salah paham emoji doang, tapi panjang urusannya wkwk.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("babi", "tikus"): {
        "score": 62,
        "asmara": "Babi dan Tikus? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Satu mau healing ke gunung, satu mau ke mall, akhirnya malah sama-sama bad mood di rumah.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("babi", "ular"): {
        "score": 23,
        "asmara": "Waduh, energi kalian gampang bentrok! Babi sama Ular ibarat api ketemu bensin.",
        "bisnis": "Bakal sering debat meeting, siapin kopi ekstra biar gak gampang emosi.",
        "drama": "Satu ngomong A, satu denger Z. Ujung-ujungnya saling block di Instagram semaleman.",
        "tips": "Harus ada yang ngalah! Jangan dua-duanya keras kepala kalau mau langgeng.",
    },
    ("kambing", "kambing"): {
        "score": 77,
        "asmara": "Sama-sama Kambing bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("kambing", "kelinci"): {
        "score": 86,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Kambing dan Kelinci.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("kambing", "kerbau"): {
        "score": 29,
        "asmara": "Waduh, energi kalian gampang bentrok! Kambing sama Kerbau ibarat api ketemu bensin.",
        "bisnis": "Bakal sering debat meeting, siapin kopi ekstra biar gak gampang emosi.",
        "drama": "Satu ngomong A, satu denger Z. Ujung-ujungnya saling block di Instagram semaleman.",
        "tips": "Harus ada yang ngalah! Jangan dua-duanya keras kepala kalau mau langgeng.",
    },
    ("kambing", "kuda"): {
        "score": 97,
        "asmara": "Beneran jodoh dari surga! Kambing dan Kuda itu match banget.",
        "bisnis": "Chemistry kalian di dunia kerja itu dewa banget, auto cuan kalau bareng.",
        "drama": "Gak ada drama berat, paling ribut rebutan siapa yang traktir boba duluan.",
        "tips": "Pertahankan vibes positif kalian, you guys are perfect together!",
    },
    ("kambing", "macan"): {
        "score": 67,
        "asmara": "Kambing dan Macan? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Kerja bareng kalian asyik, satu mikir strategi satu lagi eksekusi.",
        "drama": "Pas ribut gara-gara milih tempat makan, bisa sampai diem-dieman tiga hari.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("kambing", "monyet"): {
        "score": 67,
        "asmara": "Kambing dan Monyet? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("kambing", "naga"): {
        "score": 59,
        "asmara": "Kambing dan Naga? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Satu mau healing ke gunung, satu mau ke mall, akhirnya malah sama-sama bad mood di rumah.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("kambing", "tikus"): {
        "score": 43,
        "asmara": "Ada aja halangannya, Kambing dan Tikus butuh extra effort buat nyatu.",
        "bisnis": "Sering miskom dan curigaan sendiri, mending bikin job desk yang super jelas.",
        "drama": "Drama saling sindir pakai quotes di IG Story sampe temen-temen ikutan bingung.",
        "tips": "Stop saling nyalahin, coba duduk bareng dan ngomong dari hati ke hati.",
    },
    ("kambing", "ular"): {
        "score": 61,
        "asmara": "Kambing dan Ular? Boleh banget dicoba, siapa tau malah jadi power couple tak terduga.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Satu mau healing ke gunung, satu mau ke mall, akhirnya malah sama-sama bad mood di rumah.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("kelinci", "kelinci"): {
        "score": 75,
        "asmara": "Sama-sama Kelinci bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("kelinci", "kerbau"): {
        "score": 67,
        "asmara": "Kelinci dan Kerbau? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Cuan ngalir lancar kalau udah satu visi misi.",
        "drama": "Satu mau healing ke gunung, satu mau ke mall, akhirnya malah sama-sama bad mood di rumah.",
        "tips": "Turunin ego dikit, kalian berdua sama-sama berharga kok.",
    },
    ("kelinci", "kuda"): {
        "score": 57,
        "asmara": "Kuda bergerak cepat, Kelinci butuh rasa aman. Yang dibangun pelan sering rusak oleh keputusan mendadak.",
        "bisnis": "Komitmen mudah berubah. Apa pun yang disepakati harus ada tenggat dan bukti tertulis.",
        "drama": "Kelinci merasa ditinggalkan, Kuda merasa dikekang. Dua-duanya benar, dua-duanya kecewa.",
        "tips": "Beri kabar sebelum berubah rencana. Kejutan di hubungan ini lebih sering melukai daripada menyenangkan.",
    },
    ("kelinci", "macan"): {
        "score": 64,
        "asmara": "Kelinci dan Macan? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Debat soal film yang mau ditonton berujung perang dingin di chat.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("kelinci", "monyet"): {
        "score": 58,
        "asmara": "Kelinci dan Monyet? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Beda gaya kerja dikit wajar, yang penting target kecapai.",
        "drama": "Debat soal film yang mau ditonton berujung perang dingin di chat.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("kelinci", "naga"): {
        "score": 41,
        "asmara": "Ada aja halangannya, Kelinci dan Naga butuh extra effort buat nyatu.",
        "bisnis": "Sering miskom dan curigaan sendiri, mending bikin job desk yang super jelas.",
        "drama": "Drama saling sindir pakai quotes di IG Story sampe temen-temen ikutan bingung.",
        "tips": "Stop saling nyalahin, coba duduk bareng dan ngomong dari hati ke hati.",
    },
    ("kelinci", "tikus"): {
        "score": 36,
        "asmara": "Awalnya terasa nyaman, tapi lama-lama saling menuntut hal yang diam-diam melukai kalian berdua.",
        "bisnis": "Rawan saling menyalahkan saat rugi. Perjanjian harus hitam di atas putih sejak hari pertama.",
        "drama": "Bukan ribut besar, tapi sindiran halus yang menumpuk sampai salah satu memilih pergi diam-diam.",
        "tips": "Berhenti menyimpan skor. Katakan keberatanmu saat masih kecil, jangan setelah jadi dendam.",
    },
    ("kelinci", "ular"): {
        "score": 64,
        "asmara": "Kelinci dan Ular? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Cuan ngalir lancar kalau udah satu visi misi.",
        "drama": "Debat soal film yang mau ditonton berujung perang dingin di chat.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("kerbau", "kerbau"): {
        "score": 72,
        "asmara": "Sama-sama Kerbau bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("kerbau", "kuda"): {
        "score": 40,
        "asmara": "Ada aja halangannya, Kerbau dan Kuda butuh extra effort buat nyatu.",
        "bisnis": "Sering miskom dan curigaan sendiri, mending bikin job desk yang super jelas.",
        "drama": "Drama saling sindir pakai quotes di IG Story sampe temen-temen ikutan bingung.",
        "tips": "Stop saling nyalahin, coba duduk bareng dan ngomong dari hati ke hati.",
    },
    ("kerbau", "macan"): {
        "score": 59,
        "asmara": "Kerbau dan Macan? Ada chemistry yang menarik di antara kalian, lumayan smooth.",
        "bisnis": "Jangan rebutan spotlight ya pas meeting, bagi-bagi tugas aja.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("kerbau", "monyet"): {
        "score": 68,
        "asmara": "Kerbau dan Monyet? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Satu mau healing ke gunung, satu mau ke mall, akhirnya malah sama-sama bad mood di rumah.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("kerbau", "naga"): {
        "score": 50,
        "asmara": "Dua ego besar yang sama-sama enggan menyesuaikan diri, jadi kemajuan hubungan mudah mundur lagi.",
        "bisnis": "Visi bisa sejalan, tapi cara mencapainya bertabrakan sampai rencana bubar di tengah jalan.",
        "drama": "Saling menganggap yang satu terlalu lambat dan yang lain terlalu ngawur.",
        "tips": "Putuskan sejak awal siapa pegang kemudi di area mana, supaya tidak saling membongkar kerja pasangan.",
    },
    ("kerbau", "tikus"): {
        "score": 98,
        "asmara": "Beneran jodoh dari surga! Kerbau dan Tikus itu match banget.",
        "bisnis": "Chemistry kalian di dunia kerja itu dewa banget, auto cuan kalau bareng.",
        "drama": "Gak ada drama berat, paling ribut rebutan siapa yang traktir boba duluan.",
        "tips": "Pertahankan vibes positif kalian, you guys are perfect together!",
    },
    ("kerbau", "ular"): {
        "score": 89,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Kerbau dan Ular.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("kuda", "kuda"): {
        "score": 47,
        "asmara": "Seru dan penuh petualangan, tapi tidak ada yang memegang kemudi saat keduanya ingin lari.",
        "bisnis": "Ide melimpah, eksekusi minim. Dua-duanya bosan sebelum satu proyek pun selesai.",
        "drama": "Sama-sama kabur saat pembicaraan mulai serius, jadi masalahnya tidak pernah benar-benar dibahas.",
        "tips": "Tunjuk satu hal yang wajib diselesaikan berdua sampai tuntas, sekecil apa pun.",
    },
    ("kuda", "macan"): {
        "score": 87,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Kuda dan Macan.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("kuda", "monyet"): {
        "score": 60,
        "asmara": "Kuda dan Monyet? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Jangan rebutan spotlight ya pas meeting, bagi-bagi tugas aja.",
        "drama": "Debat soal film yang mau ditonton berujung perang dingin di chat.",
        "tips": "Turunin ego dikit, kalian berdua sama-sama berharga kok.",
    },
    ("kuda", "naga"): {
        "score": 68,
        "asmara": "Kuda dan Naga? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Kerja bareng kalian asyik, satu mikir strategi satu lagi eksekusi.",
        "drama": "Ribut kecil dari salah paham emoji doang, tapi panjang urusannya wkwk.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("kuda", "tikus"): {
        "score": 24,
        "asmara": "Waduh, energi kalian gampang bentrok! Kuda sama Tikus ibarat api ketemu bensin.",
        "bisnis": "Bakal sering debat meeting, siapin kopi ekstra biar gak gampang emosi.",
        "drama": "Satu ngomong A, satu denger Z. Ujung-ujungnya saling block di Instagram semaleman.",
        "tips": "Harus ada yang ngalah! Jangan dua-duanya keras kepala kalau mau langgeng.",
    },
    ("kuda", "ular"): {
        "score": 64,
        "asmara": "Kuda dan Ular? Bisa dibilang cocok, cuma kadang beda frekuensi sedikit aja.",
        "bisnis": "Cuan ngalir lancar kalau udah satu visi misi.",
        "drama": "Pas ribut gara-gara milih tempat makan, bisa sampai diem-dieman tiga hari.",
        "tips": "Kasih space satu sama lain biar gak gampang bosen.",
    },
    ("macan", "macan"): {
        "score": 75,
        "asmara": "Sama-sama Macan bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("macan", "monyet"): {
        "score": 25,
        "asmara": "Waduh, energi kalian gampang bentrok! Macan sama Monyet ibarat api ketemu bensin.",
        "bisnis": "Bakal sering debat meeting, siapin kopi ekstra biar gak gampang emosi.",
        "drama": "Satu ngomong A, satu denger Z. Ujung-ujungnya saling block di Instagram semaleman.",
        "tips": "Harus ada yang ngalah! Jangan dua-duanya keras kepala kalau mau langgeng.",
    },
    ("macan", "naga"): {
        "score": 60,
        "asmara": "Macan dan Naga? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Cuan ngalir lancar kalau udah satu visi misi.",
        "drama": "Masing-masing gengsi minta maaf duluan, endingnya malah sama-sama kangen.",
        "tips": "Banyakin quality time bareng, nonton konser atau jalan-jalan santai.",
    },
    ("macan", "tikus"): {
        "score": 61,
        "asmara": "Macan dan Tikus? Kombinasi unik nih, asal gak sama-sama batu pasti aman.",
        "bisnis": "Cuan ngalir lancar kalau udah satu visi misi.",
        "drama": "Pas ribut gara-gara milih tempat makan, bisa sampai diem-dieman tiga hari.",
        "tips": "Turunin ego dikit, kalian berdua sama-sama berharga kok.",
    },
    ("macan", "ular"): {
        "score": 30,
        "asmara": "Tarik-menarik yang intens dan memabukkan, tapi dua-duanya menyimpan senjata untuk saat bertengkar.",
        "bisnis": "Saling mengagumi sekaligus mencurigai. Transparansi angka adalah syarat mati kerja sama ini.",
        "drama": "Macan meledak di depan, Ular membalas belakangan dengan cara yang jauh lebih dingin.",
        "tips": "Jangan menyimpan kartu untuk dipakai saat marah. Yang begitu tidak menyelesaikan apa pun.",
    },
    ("monyet", "monyet"): {
        "score": 73,
        "asmara": "Sama-sama Monyet bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("monyet", "naga"): {
        "score": 90,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Monyet dan Naga.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("monyet", "tikus"): {
        "score": 90,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Monyet dan Tikus.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("monyet", "ular"): {
        "score": 99,
        "asmara": "Beneran jodoh dari surga! Monyet dan Ular itu match banget.",
        "bisnis": "Chemistry kalian di dunia kerja itu dewa banget, auto cuan kalau bareng.",
        "drama": "Gak ada drama berat, paling ribut rebutan siapa yang traktir boba duluan.",
        "tips": "Pertahankan vibes positif kalian, you guys are perfect together!",
    },
    ("naga", "naga"): {
        "score": 49,
        "asmara": "Dua Naga saling mengagumi sampai keduanya sadar tidak ada yang bersedia jadi pendukung.",
        "bisnis": "Sama-sama ingin memimpin dan sama-sama gengsi mengakui salah, jadi kesalahan dibiarkan membesar.",
        "drama": "Adu gengsi tingkat tinggi. Tidak ada yang minta maaf karena keduanya merasa paling berjasa.",
        "tips": "Bergantian jadi pendengar. Kelemahan terbesar kalian bukan lawan, tapi cermin.",
    },
    ("naga", "tikus"): {
        "score": 85,
        "asmara": "Hubungan yang super chill dan saling melengkapi buat Naga dan Tikus.",
        "bisnis": "Kerja bareng kalian itu smooth banget, kayak air ngalir santai tapi pasti nyampe tujuan.",
        "drama": "Kalau ribut paling soal hal sepele kayak mau dengerin playlist siapa pas road trip.",
        "tips": "Tetep solid dan jangan biarin omongan orang ngerusak mood kalian.",
    },
    ("naga", "ular"): {
        "score": 62,
        "asmara": "Naga dan Ular? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Jangan rebutan spotlight ya pas meeting, bagi-bagi tugas aja.",
        "drama": "Ribut kecil dari salah paham emoji doang, tapi panjang urusannya wkwk.",
        "tips": "Kurangin overthinking dan saling jujur aja tentang perasaan kalian.",
    },
    ("tikus", "tikus"): {
        "score": 76,
        "asmara": "Sama-sama Tikus bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
    ("tikus", "ular"): {
        "score": 63,
        "asmara": "Tikus dan Ular? Kalian berdua bisa nyambung kok, asal mau saling dengerin.",
        "bisnis": "Kalian bisa jadi tim yang solid asal komunikasi dijaga.",
        "drama": "Pas ribut gara-gara milih tempat makan, bisa sampai diem-dieman tiga hari.",
        "tips": "Jangan gengsi buat minta maaf duluan kalau lagi ada masalah.",
    },
    ("ular", "ular"): {
        "score": 78,
        "asmara": "Sama-sama Ular bikin kalian paham luar dalam, tapi kadang ngebosenin.",
        "bisnis": "Bisa ngegas bareng kalau visi sama, tapi kalau mandek malah overthinking berdua.",
        "drama": "Karna sifatnya sama plek ketiplek, kalau ngambek ya sama-sama nunggu disapa duluan.",
        "tips": "Cari hobi baru di luar rutinitas biar hubungan gak terasa hambar.",
    },
}
