DAY_OFFICER_BANK = [
    {
        "key": "jian",
        "name": "Jian (Membangun)",
        "hanzi": "建",
        "code": "neutral",
        "meaning": "Energi hari ini condong ke awal mula. Cocok memulai, kurang cocok membongkar.",
        "yi": ["Memulai rencana baru", "Perjalanan & keberangkatan", "Melamar kerja atau wawancara", "Memohon restu"],
        "ji": ["Menggali atau membongkar", "Pindah rumah", "Membuka simpanan besar"],
    },
    {
        "key": "chu",
        "name": "Chu (Membersihkan)",
        "hanzi": "除",
        "code": "good",
        "meaning": "Hari untuk menyingkirkan yang lama supaya ruang baru terbuka.",
        "yi": ["Bersih-bersih & merapikan", "Berobat", "Mengakhiri yang sudah usang", "Melunasi utang"],
        "ji": ["Perjalanan jauh", "Menikah", "Menyimpan barang berharga"],
    },
    {
        "key": "man",
        "name": "Man (Penuh)",
        "hanzi": "滿",
        "code": "neutral",
        "meaning": "Energi meluap penuh. Baik untuk merayakan, rawan untuk yang butuh ketelitian.",
        "yi": ["Doa & syukuran", "Membuka usaha", "Menjamu tamu", "Menandatangani kerja sama"],
        "ji": ["Mulai minum obat", "Mengambil keputusan medis", "Pemakaman"],
    },
    {
        "key": "ping",
        "name": "Ping (Merata)",
        "hanzi": "平",
        "code": "neutral",
        "meaning": "Hari serba datar. Tidak menonjol, tapi aman untuk hal rutin.",
        "yi": ["Pekerjaan rutin", "Perbaikan & perawatan", "Berdamai atau mediasi", "Meratakan tanah"],
        "ji": ["Menikah", "Membuka usaha", "Menanam investasi baru"],
    },
    {
        "key": "ding",
        "name": "Ding (Menetapkan)",
        "hanzi": "定",
        "code": "good",
        "meaning": "Energi mengunci dan memantapkan. Apa pun yang diputuskan hari ini cenderung bertahan.",
        "yi": ["Menandatangani kontrak", "Bertunangan atau berjanji", "Mendaftar sekolah", "Menetapkan target"],
        "ji": ["Berperkara di pengadilan", "Perjalanan jauh", "Mengubah rencana besar"],
    },
    {
        "key": "zhi",
        "name": "Zhi (Menggenggam)",
        "hanzi": "執",
        "code": "neutral",
        "meaning": "Hari untuk memegang erat dan menuntaskan, bukan melepas.",
        "yi": ["Menagih piutang", "Menyelesaikan yang tertunda", "Membangun & mendirikan", "Menjaga komitmen"],
        "ji": ["Membuka usaha baru", "Pindah tempat", "Melepas aset"],
    },
    {
        "key": "po",
        "name": "Po (Merusak)",
        "hanzi": "破",
        "code": "bad",
        "meaning": "Hari paling rawan dalam siklus. Energi memecah, bukan menyatukan.",
        "yi": ["Membongkar bangunan lama", "Mengobati penyakit menahun", "Memutus hubungan toksik"],
        "ji": ["Menikah", "Membuka usaha", "Menandatangani apa pun", "Memulai hal penting"],
    },
    {
        "key": "wei",
        "name": "Wei (Bahaya)",
        "hanzi": "危",
        "code": "bad",
        "meaning": "Energi rawan tergelincir. Hari untuk berhati-hati, bukan menantang.",
        "yi": ["Ritual & meditasi", "Beristirahat penuh", "Introspeksi"],
        "ji": ["Naik ke tempat tinggi", "Perjalanan air atau udara", "Olahraga ekstrem", "Mengambil risiko besar"],
    },
    {
        "key": "cheng",
        "name": "Cheng (Berhasil)",
        "hanzi": "成",
        "code": "good",
        "meaning": "Hari terbaik dalam siklus. Hampir semua urusan didukung energinya.",
        "yi": ["Membuka usaha", "Menikah", "Mendaftar sekolah", "Membuat perjanjian", "Memulai apa pun"],
        "ji": ["Berperkara", "Bertengkar atau mengadu"],
    },
    {
        "key": "shou",
        "name": "Shou (Memanen)",
        "hanzi": "收",
        "code": "neutral",
        "meaning": "Energi menarik masuk. Baik untuk menerima, kurang baik untuk melepas.",
        "yi": ["Menerima pembayaran", "Menabung & menyimpan", "Merekrut orang", "Mengumpulkan data"],
        "ji": ["Perjalanan jauh", "Membuka simpanan", "Memberi pinjaman"],
    },
    {
        "key": "kai",
        "name": "Kai (Membuka)",
        "hanzi": "開",
        "code": "good",
        "meaning": "Pintu-pintu terbuka. Energi mengalir keluar dan menyambut yang baru.",
        "yi": ["Membuka usaha", "Mulai belajar hal baru", "Berobat", "Memulai proyek", "Bertemu orang baru"],
        "ji": ["Pemakaman", "Menutup atau mengakhiri sesuatu"],
    },
    {
        "key": "bi",
        "name": "Bi (Menutup)",
        "hanzi": "閉",
        "code": "bad",
        "meaning": "Energi menutup rapat. Cocok menambal dan menyimpan, buruk untuk memulai.",
        "yi": ["Menambal & memperbaiki", "Menutup rekening lama", "Menyimpan rapat-rapat"],
        "ji": ["Membuka usaha", "Perjalanan jauh", "Operasi atau tindakan medis", "Memulai hal baru"],
    },
]

ELEMENT_RELATION_BANK = {
    "sheng_wo": {
        "name": "Xiang Sheng (Dihidupi)",
        "code": "good",
        "symbol": "→",
        "desc": "Elemen hari ini menghidupi elemenmu. Energimu terisi dari luar — ini hari yang murah hati padamu.",
        "advice": "Manfaatkan dukungan yang datang. Minta bantuan hari ini lebih mudah dikabulkan.",
    },
    "wo_sheng": {
        "name": "Xie Qi (Menguras)",
        "code": "neutral",
        "symbol": "←",
        "desc": "Elemenmu justru menghidupi elemen hari ini. Kamu produktif, tapi energimu terpakai keluar.",
        "advice": "Berkaryalah, tapi jangan lupa mengisi ulang. Hari ini kamu memberi lebih banyak dari menerima.",
    },
    "ke_wo": {
        "name": "Xiang Ke (Ditekan)",
        "code": "bad",
        "symbol": "⊗",
        "desc": "Elemen hari ini mengekang elemenmu. Ada tekanan dari luar yang terasa mengganjal.",
        "advice": "Jangan melawan arus hari ini. Menunduk sebentar lebih hemat tenaga daripada mendobrak.",
    },
    "wo_ke": {
        "name": "De Cai (Menguasai)",
        "code": "good",
        "symbol": "⊕",
        "desc": "Elemenmu mengekang elemen hari ini. Kamu memegang kendali — ini energi rezeki dan penaklukan.",
        "advice": "Hari yang tepat untuk mengambil inisiatif, bernegosiasi, dan mengejar apa yang kamu incar.",
    },
    "bi_he": {
        "name": "Bi He (Sejalan)",
        "code": "neutral",
        "symbol": "=",
        "desc": "Elemen hari ini sama dengan elemenmu. Energinya menguat, tapi tanpa penyeimbang.",
        "advice": "Kamu merasa paling 'diri sendiri' hari ini. Bagus untuk fokus, rawan untuk keras kepala.",
    },
}
