ROAST_WETON = {
    "minggu_legi": [
        "Kamu tipe yang ditanya 'lagi sibuk nggak?' langsung jawab 'nggak kok', padahal to-do list-mu sepanjang struk belanja bulanan.",
        "Grup keluarga paling aktif gara-gara kamu. Semua stiker ucapan selamat pagi di sana hasil kurasimu sendiri.",
        "Neptu 10 bikin kamu jadi tempat curhat gratis. Masalahnya, kamu sendiri belum pernah curhat balik ke siapa pun.",
        "Kamu gampang akrab sama siapa saja, sampai kasir minimarket langganan tahu rencana liburanmu tahun depan.",
        "Tiap salah langkah kamu jadikan pelajaran hidup. Bagus sih, cuma koleksinya sudah bisa dibukukan tiga jilid.",
        "Kamarmu rapi, lemarimu rapi, tapi tab browser-mu terbuka 47 dan semuanya berlabel 'nanti dibaca'.",
        "Kamu bilang 'santai aja', lalu diam-diam menyusun rencana cadangan A sampai F buat acara kumpul keluarga.",
        "Terlalu sabar sampai orang lupa kamu juga bisa capek. Sesekali bilang 'nggak dulu', dunia nggak bakal runtuh kok.",
    ],
    "minggu_pahing": [
        "Kamu rapi dua kali lipat: rapi karena Minggu, rapi karena Pahing. Sendok di rak piring pun kamu susun sesuai ukuran.",
        "Butuh me-time tapi juga jadi problem solver semua orang. Hasilnya, jam istirahatmu habis buat masalah orang lain.",
        "Kamu bisa beresin konflik grup dalam lima menit, tapi butuh lima hari buat mutusin mau makan siang di mana.",
        "Mandiri banget sampai minta tolong terasa kayak kalah. Padahal nggak semua hal harus kamu angkat sendirian.",
        "Kamu punya folder khusus buat struk, garansi, dan buku manual. Semua orang rumah tahu harus nanya ke siapa.",
        "Supel di luar, butuh sunyi di dalam. Habis nongkrong tiga jam, kamu perlu recharge sehari penuh tanpa notifikasi.",
        "Kamu sayang keluarga, tapi kalau ada yang naruh barang sembarangan di mejamu, sayangnya pending dulu sebentar.",
        "Solusimu selalu masuk akal, cuma cara nyampeinnya kadang kayak dosen lagi presentasi di depan kelas.",
    ],
    "minggu_pon": [
        "Kamu tegas soal prinsip, tapi langsung luluh kalau keluarga yang minta. Prinsipmu punya pengecualian khusus orang rumah.",
        "Rajin sampai bikin teman satu tim merasa bersalah. Kamu sudah submit, mereka baru buka dokumennya.",
        "Pendirianmu kuat banget. Sekali bilang bubur lebih enak nggak diaduk, debat itu nggak akan pernah selesai.",
        "Kamu peduli teman sampai hafal jadwal gajian mereka, jadi tahu kapan waktu yang tepat buat ngajak makan.",
        "Hidupmu cenderung berkecukupan, tapi tetap saja kamu bandingin harga di tiga aplikasi sebelum checkout.",
        "Kamu enak diajak ngobrol, asal topiknya nggak menyentuh hal yang sudah kamu putuskan sebelumnya.",
        "Kamu penurut ke orang yang kamu hormati, tapi keras kepala ke siapa pun yang belum lolos seleksimu.",
        "Tiap Minggu pagi kamu punya ritual beberes. Siapa pun yang ganggu ritual itu otomatis masuk daftar pantauan.",
    ],
    "minggu_wage": [
        "Kamu jarang ngomong, tapi begitu ada yang butuh bantuan, kamu sudah di lokasi sebelum grup selesai diskusi.",
        "Gaya hidupmu sesederhana itu: kaos favorit yang sama, menu makan siang yang sama, dan tetap bahagia.",
        "Kamu terlalu nggak ribet sampai orang lain yang menentukan pilihan buatmu. Sesekali, pilih sendiri.",
        "Tulus banget sampai sering bilang 'terserah', lalu makan dengan pasrah di tempat yang sebenarnya kurang kamu suka.",
        "Diam-diam gesit. Orang baru sadar kamu sudah beresin semuanya waktu lihat centang di checklist bersama.",
        "Kamu nggak mikirin harta, tapi hafal banget promo gratis ongkir tiap tanggal kembar.",
        "Sayang keluarga versi kamu: nggak banyak kata, tapi galon di rumah selalu terisi sebelum habis.",
        "Kamu penurut, tapi kalau sudah diam lama lalu jawab 'oke', itu tandanya kamu sebenarnya nggak oke.",
    ],
    "minggu_kliwon": [
        "Auramu misterius, padahal kamu cuma lagi mikir mau pesan es teh atau es jeruk.",
        "Harga dirimu tinggi, jadi minta maaf duluan terasa seperti mendaki gunung tanpa bekal.",
        "Kamu lembut dan baik hati, tapi jarang bikin story, jadi orang mengira kamu hidup di dimensi lain.",
        "Jiwa petualangmu kuat. Rencana liburan sudah lengkap sampai itinerary, tinggal cuti yang belum di-ACC.",
        "Pendiam di grup besar, tapi begitu ngobrol berdua, ceritamu bisa sampai tiga jam tanpa jeda iklan.",
        "Kamu menarik tanpa berusaha, lalu bingung kenapa orang-orang suka penasaran sama hidupmu.",
        "Kamu rapi dan tulus, tapi kalau harga dirimu tersentil, kamu memilih diam elegan selama tiga hari kerja.",
        "Orang butuh waktu untuk membaca kamu. Kamu sendiri juga kadang butuh waktu buat membaca dirimu.",
    ],
    "senin_legi": [
        "Ringan tangan level kamu: belum diminta, sudah bantu angkat galon, beresin kabel, dan pesan makanan buat semua.",
        "Kamu suka belajar hal baru. Minggu lalu belajar bikin sourdough, minggu ini sudah pindah ke kaligrafi.",
        "Cekatan banget sampai orang lain kelihatan lambat. Pelan-pelan, rekan kerjamu juga butuh waktu napas.",
        "Kamu gampang akrab, jadi di setiap acara selalu ada yang bilang 'eh, kamu kenal dia juga?'.",
        "Suka berbagi sampai bekal makan siangmu jarang habis dimakan sendiri.",
        "Pendiam tapi gesit: kamu nggak banyak ngomong di rapat, tapi action item-nya sudah jalan duluan.",
        "Tiap kesalahan kamu jadikan bahan belajar, termasuk salah kirim stiker ke grup kantor.",
        "Kamu terampil di banyak hal, tapi kalau ditanya keahlian utamamu apa, kamu bingung sendiri milih yang mana.",
    ],
    "senin_pahing": [
        "Kamu cekatan dan mandiri, jadi kalau ada yang mau bantu, kamu bilang 'udah beres kok' padahal belum.",
        "Kamu suka mengatur. Liburan bareng teman? Kamu yang pegang spreadsheet, budget, dan jam kumpul.",
        "Ringan tangan ke semua orang, tapi jangan sentuh barang di mejamu tanpa izin. Itu zona pribadi.",
        "Jiwa petualangmu besar, tapi tetap bawa pouch berisi obat, tisu basah, dan charger cadangan.",
        "Kamu menarik dan lembut, sampai orang nggak sadar kamu sedang mengatur semuanya dari balik layar.",
        "Me-time bagimu wajib. Kalau seharian ketemu orang, malamnya kamu butuh ruang sunyi dan playlist lo-fi.",
        "Kamu bersih-bersih kalau lagi stres, jadi kamar yang super rapi biasanya tanda kamu lagi banyak pikiran.",
        "Terampil banget sampai sering dimintai tolong benerin apa saja, dari printer sampai rencana liburan teman.",
    ],
    "senin_pon": [
        "Kamu tegas soal hal kecil, tapi ragu banget untuk keputusan besar. Pilih warna casing cepat, pilih karier lama.",
        "Berani bicara di rapat, tapi begitu ditanya 'jadi kapan mulai?', kamu minta waktu buat mikir lagi.",
        "Kamu cekatan dan terampil, cuma susah diajak mengubah cara kerja yang sudah kamu anggap paling benar.",
        "Suka berbagi, tapi tetap punya catatan siapa saja yang belum balikin barangmu.",
        "Pendirianmu kuat, jadi kalau kamu bilang 'nggak', orang tahu itu bukan 'nanti dulu'.",
        "Kamu cenderung berkecukupan, tapi hobi bikin anggaran bulanan yang kamu revisi tiap minggu.",
        "Kamu ringan tangan membantu, tapi kalau caranya nggak sesuai standarmu, kamu ulang dari awal diam-diam.",
        "Kamu yakin di awal, galau di tengah, lalu tetap jalan karena terlanjur bilang ke semua orang.",
    ],
    "senin_wage": [
        "Kamu penurut, tapi sekali tersinggung, kejadian lima tahun lalu masih bisa kamu ceritakan lengkap dengan tanggalnya.",
        "Emosimu cepat naik, cepat juga kamu menyesal. Siklus ini biasanya selesai dengan kamu traktir martabak.",
        "Hidupmu sederhana dan nggak ribet, kecuali soal urutan antre. Di situ kamu mendadak jadi penegak keadilan.",
        "Kamu cekatan membantu siapa saja, tapi jangan lupa bilang terima kasih. Kamu mencatatnya dalam hati.",
        "Nggak terlalu mikirin harta, jadi dompet digitalmu sering jadi korban patungan dadakan.",
        "Kamu suka berbagi makanan, tapi gorengan terakhir di piring tetap kamu anggap wilayah sengketa.",
        "Terampil dan ringan tangan, sampai sering jadi 'orang yang bisa diandalkan' tanpa pernah ditanya kabarnya.",
        "Kamu bilang sudah memaafkan. Benar sih, cuma ingatanmu tetap menyimpan versi arsipnya.",
    ],
    "senin_kliwon": [
        "Kamu rajin dan cekatan, tapi pendiam, jadi prestasimu sering baru ketahuan waktu ada yang lihat hasilnya.",
        "Harga dirimu tinggi, jadi kamu lebih memilih begadang sendiri daripada minta bantuan.",
        "Kamu peduli teman dengan cara misterius: tiba-tiba kirim makanan tanpa pesan apa pun.",
        "Orang mengira kamu cuek, padahal kamu ingat ulang tahun semua anggota tim.",
        "Kamu suka berbagi ilmu, asal nggak disuruh presentasi di depan banyak orang.",
        "Diammu bikin orang segan, padahal kamu cuma lagi menghitung ulang pengeluaran bulan ini.",
        "Terampil di banyak hal, tapi jarang pamer. Portofoliomu tersimpan lebih rapat dari password Wi-Fi rumah.",
        "Kamu penurut ke aturan, tapi punya satu prinsip yang nggak bisa ditawar oleh siapa pun.",
    ],
    "selasa_legi": [
        "Kamu usil ke orang yang kamu sayang. Kalau kamu nggak pernah ngerjain seseorang, berarti kalian belum akrab.",
        "Susah ditebak: pagi semangat bikin rencana, sore ganti rencana, malam minta maaf karena berubah pikiran.",
        "Gampang bergaul, tapi emosi cepat naik. Kenalan baru langsung akrab, debat soal bubur juga langsung panas.",
        "Kamu suka belajar hal baru, terutama cara baru ngerjain teman tanpa ketahuan.",
        "Sekali sakit hati, kamu ingat. Bedanya, kamu masih mau senyum sambil menyusun sindiran halus.",
        "Kamu cepat akrab, cepat marah, cepat baikan. Teman-temanmu sudah hafal pola ini dan tetap sayang.",
        "Candaanmu kadang kelewat batas, tapi permintaan maafmu juga niat banget, lengkap dengan jajanan.",
        "Tiap salah langkah kamu ambil hikmahnya, lalu mengulang langkah yang mirip dengan gaya yang beda.",
    ],
    "selasa_pahing": [
        "Kamu usil ke orang lain, tapi jangan coba-coba mengacak barang di mejamu. Itu melanggar konstitusi pribadimu.",
        "Susah ditebak dan mandiri. Orang baru tahu kamu pindah kos waktu kamu sudah upload foto kamar baru.",
        "Rajin dan rapi, tapi butuh waktu sendiri. Jangan ajak ngobrol sebelum kopimu habis setengah.",
        "Kamu suka mengatur, dan jujur saja, hidup teman-temanmu memang lebih rapi karena kamu.",
        "Orang butuh waktu untuk dekat denganmu. Kamu anggap itu proses verifikasi dua langkah.",
        "Kamu peduli teman, tapi caramu ngasih nasihat mirip notifikasi yang nggak bisa di-mute.",
        "Mood-mu susah ditebak, tapi jadwalmu selalu rapi. Kombinasi yang bikin orang bingung sekaligus kagum.",
        "Me-time bagimu bukan pilihan, tapi kebutuhan pokok, setara sama makan dan charger HP.",
    ],
    "selasa_pon": [
        "Kamu sabar dan cerdas, jadi sering dimintai nasihat, lalu nasihatmu diabaikan dan kamu tetap sabar.",
        "Usil tapi tegas. Kamu bisa ngerjain teman seharian, lalu serius banget waktu bahas deadline.",
        "Pendirianmu kuat. Kalau kamu sudah bilang tempat makan itu enak, jangan harap bisa diganti.",
        "Susah ditebak: tampang santai, tapi di kepala sudah ada analisis risiko tiga halaman.",
        "Kamu tempat curhat favorit karena jawabanmu jujur, meski kadang terlalu jujur untuk jam sebelas malam.",
        "Hidupmu cenderung berkecukupan, tapi kamu tetap pilih jalan kaki kalau jaraknya kurang dari satu kilometer.",
        "Orang butuh waktu untuk dekat denganmu, lalu setelah dekat, mereka jadi sasaran usilmu seumur hidup.",
        "Kamu jarang marah, tapi sekali tegas, satu grup langsung rapi tanpa perlu diulang.",
    ],
    "selasa_wage": [
        "Kamu susah diam di satu tempat. Baru duduk lima menit, sudah cek tiket promo ke kota sebelah.",
        "Gaya hidupmu sederhana: ransel kecil, sandal nyaman, dan rasa penasaran yang nggak pernah habis.",
        "Usilmu halus. Orang baru sadar dikerjain kamu setelah tiga hari.",
        "Kamu penurut kalau diajak jalan, apa pun rencananya. Asal jangan disuruh diam di rumah seharian.",
        "Susah ditebak: tadi bilang mager, sejam kemudian kirim foto dari warung kopi di ujung kota.",
        "Kamu nggak terlalu mikirin harta, tapi selalu punya dana darurat khusus buat perjalanan dadakan.",
        "Orang butuh waktu untuk dekat denganmu, karena kamu jarang ada di tempat yang sama dua kali.",
        "Kamu nggak ribet soal makan, tidur, atau penginapan. Yang ribet cuma jadwal pulangmu yang terus mundur.",
    ],
    "selasa_kliwon": [
        "Wetonmu jatuh di Anggara Kasih, tapi rasa sayangmu kamu simpan rapat seperti draft yang nggak pernah dikirim.",
        "Kamu usil dan misterius sekaligus. Orang nggak tahu kamu lagi bercanda atau serius, dan kamu menikmatinya.",
        "Berani di hal kecil, ragu di hal besar. Nekat coba level pedas lima, tapi mikir seminggu buat ganti potongan rambut.",
        "Harga dirimu tinggi, jadi kalau kalah main game, kamu minta rematch sampai menang.",
        "Kamu pendiam, tapi sekali bicara, kalimatmu dikutip teman-teman selama sebulan.",
        "Orang butuh waktu lama untuk dekat denganmu. Yang berhasil biasanya dapat akses ke sisi usilmu.",
        "Kamu susah ditebak, bahkan oleh dirimu sendiri. Rencana weekend baru jelas Sabtu siang.",
        "Kamu menyimpan banyak hal sendiri. Sesekali cerita, orang terdekatmu sebenarnya sudah siap mendengar.",
    ],
    "rabu_legi": [
        "Kamu sering beruntung di saat yang pas, sampai teman-teman minta kamu yang ambil nomor antrean.",
        "Berani dan gampang bergaul. Masuk ruangan penuh orang asing, keluar dengan tiga grup chat baru.",
        "Kamu rajin dan baik hati, jadi otomatis ditunjuk jadi bendahara di setiap kepanitiaan.",
        "Suka belajar dari kesalahan, termasuk kesalahan percaya ramalan cuaca di aplikasi.",
        "Kamu peduli teman sampai ingat alergi makanan mereka waktu pesan katering.",
        "Berani ambil langkah, tapi tetap nurut nasihat ibu. Keputusan besar selalu lewat sidang keluarga dulu.",
        "Keberuntunganmu sering datang mepet deadline, dan kamu mulai menganggap itu strategi.",
        "Kamu gampang akrab dengan siapa pun, sampai driver ojek online langgananmu tahu nama kucingmu.",
    ],
    "rabu_pahing": [
        "Jiwa pemimpinmu kuat, tapi kamu juga suka mengatur. Hasilnya, acara apa pun terasa seperti proyek resmi.",
        "Kamu sopan dan pemaaf, tapi kalau timeline dilanggar, senyummu berubah jadi senyum HRD.",
        "Temanmu banyak, tapi yang boleh masuk kamar dan lihat meja kerjamu cuma segelintir.",
        "Berani ambil keputusan dan rapi eksekusinya. Satu-satunya kelemahan: kamu susah mendelegasikan.",
        "Kamu mandiri sampai lupa bahwa tim dibentuk supaya kamu nggak kerja sendirian.",
        "Keberuntunganmu sering pas timing-nya, tapi kamu tetap siapin rencana B sampai D, jaga-jaga.",
        "Kamu pemaaf, tapi dokumentasi kesalahan orang tetap kamu arsipkan rapi, lengkap dengan tanggal.",
        "Me-time bagimu adalah rapat dengan diri sendiri, lengkap dengan agenda dan notulen.",
    ],
    "rabu_pon": [
        "Kamu jago cari jalan keluar, sampai teman-teman menganggapmu layanan pelanggan pribadi 24 jam.",
        "Berani dan tegas. Kamu satu-satunya yang berani bilang ke grup bahwa rencana liburan itu nggak realistis.",
        "Supel ke semua orang, tapi pendirianmu nggak bisa ditawar, bahkan sama diskon 50 persen.",
        "Kamu beruntung di saat yang pas, lalu menjelaskannya sebagai hasil perhitungan yang matang.",
        "Kamu punya solusi untuk semua masalah, kecuali soal kenapa kamu selalu tidur lewat tengah malam.",
        "Berbudi baik dan cerdas, tapi kalau berdebat, kamu datang membawa data dan tangkapan layar.",
        "Hidupmu cenderung berkecukupan karena kamu tegas pada satu aturan: checkout hanya setelah tidur semalam.",
        "Kamu taat aturan, kecuali aturan yang menurutmu nggak logis. Yang itu kamu ajukan revisi resmi.",
    ],
    "rabu_wage": [
        "Kamu berani nyoba hal baru, tapi kalau ditanya mau makan apa, jawabanmu tetap 'apa aja deh'.",
        "Gaya hidupmu sederhana dan kamu sering beruntung. Orang heran kenapa hidupmu kelihatan santai terus.",
        "Kamu penurut dan baik hati, jadi sering jadi penengah waktu teman-temanmu ribut soal hal remeh.",
        "Berani di risiko kecil, ragu di risiko besar. Nyoba warung baru cepat, ganti kerjaan butuh seribu pertimbangan.",
        "Kamu nggak terlalu mikirin harta, tapi rezekimu sering datang dari arah yang nggak kamu duga.",
        "Kamu gampang bilang 'iya' ke ajakan orang, lalu bingung sendiri kenapa jadwal weekend penuh.",
        "Keputusan besar kamu tanyakan ke banyak orang, lalu tetap memilih opsi yang dari awal kamu suka.",
        "Kamu nggak ribet, tapi teman-temanmu jadi ribet karena kamu terlalu sering bilang 'terserah kamu aja'.",
    ],
    "rabu_kliwon": [
        "Kamu nggak suka diatur, jadi kalau dikasih aturan, kamu baca dulu, lalu bikin versi revisinya sendiri.",
        "Berani, keras kemauan, dan misterius. Kombinasi yang bikin orang segan mau ngajak debat.",
        "Harga dirimu tinggi, jadi kamu lebih memilih nyasar sejam daripada tanya arah ke orang.",
        "Kamu beruntung di saat yang pas, tapi tetap bersikap seolah semuanya sudah kamu rencanakan.",
        "Pendiam di rapat, tapi sekali bicara, keputusannya langsung berubah.",
        "Kemauanmu kuat. Sekali niat diet, kamu disiplin. Sekali niat nggak diet, lebih disiplin lagi.",
        "Kamu baik hati dengan cara yang tidak diumumkan. Orang baru tahu kamu membantu setelah semuanya beres.",
        "Kamu nggak suka diatur-atur, termasuk oleh alarm pagi yang kamu pasang sendiri.",
    ],
    "kamis_legi": [
        "Semangatmu menyala tiap ada ide baru. Sayangnya, ide lama masih antre di notes HP-mu.",
        "Kamu gampang luluh oleh pujian. Bilang saja 'kamu jago banget', kamu bakal bantu sampai selesai.",
        "Gampang bergaul dan suka diapresiasi. Satu like dari orang yang kamu kagumi bisa bikin mood naik seharian.",
        "Jiwa petualangmu besar, apalagi kalau perjalanannya bisa jadi konten yang banjir komentar.",
        "Kamu belajar dari kesalahan, lalu membagikan pelajarannya dalam thread panjang.",
        "Kamu lembut di luar, tapi semangatmu bisa membakar satu tim buat lembur demi ide yang kamu yakini.",
        "Kamu menarik dan hangat, jadi orang yang baru kenal pun langsung mau cerita rahasia ke kamu.",
        "Kamu senang dipuji, tapi pura-pura biasa saja. Padahal pujiannya sudah kamu screenshot.",
    ],
    "kamis_pahing": [
        "Semangatmu menyala, tapi kamu tetap kalem di luar. Orang nggak tahu di kepalamu ada rapat besar.",
        "Kamu rapi dan suka mengatur, jadi grup liburan selalu punya itinerary berwarna lengkap dengan legenda.",
        "Kamu nggak suka ribut, jadi kalau ada konflik, kamu pilih kirim pesan panjang yang tertata rapi.",
        "Mandiri tapi senang diapresiasi. Kamu bisa kerja sendiri, asal hasilnya dilihat dan dihargai.",
        "Kamu luluh oleh pujian soal kerapianmu. Bilang 'mejamu enak dilihat', kamu tersenyum seharian.",
        "Me-time bagimu harus terjadwal, dan jadwalnya juga harus rapi.",
        "Kamu baik hati dan kalem, tapi kalau ada yang merusak sistem label di dapur, kesabaranmu diuji.",
        "Ambisimu besar tapi kamu jalankan diam-diam. Tahu-tahu, targetnya sudah tercapai dan kamu cuma senyum.",
    ],
    "kamis_pon": [
        "Semangatmu seperti api, pendirianmu seperti beton. Kalau sudah yakin, nggak ada yang bisa menghentikanmu.",
        "Kamu nggak suka diatur, tapi suka banget dipuji. Cara terbaik mengarahkanmu adalah memuji idemu dulu.",
        "Tegas dan berkemauan keras. Kamu bisa jadi pemimpin rapat, tapi susah jadi peserta yang cuma mendengar.",
        "Hidupmu cenderung berkecukupan, dan semangatmu memastikan itu berlanjut lewat tiga side hustle.",
        "Kamu gampang luluh oleh pujian, tapi keras kepala kalau dikritik. Tip buat temanmu: pakai sandwich pujian.",
        "Kamu punya pendapat untuk semua hal, dan semuanya kamu sampaikan dengan intonasi presentasi.",
        "Kamu semangat memulai, tegas mengeksekusi, dan kesal kalau ada yang bilang 'pelan-pelan aja'.",
        "Kalau sudah punya target, kamu kejar. Kalau ada yang nyuruh berhenti, kamu kejar lebih cepat.",
    ],
    "kamis_wage": [
        "Semangatmu besar dan gaya hidupmu sederhana. Kamu bisa bahagia cuma karena kopi sachet dan pujian tulus.",
        "Kamu penurut dan senang diapresiasi, jadi rajin banget kalau atasan bilang 'makasih ya'.",
        "Kamu peduli teman, sampai rela antre dua jam demi jajanan yang mereka pengin coba.",
        "Kamu gampang luluh oleh pujian. Hati-hati, orang yang tahu ini bisa menitipkan semua tugasnya ke kamu.",
        "Kamu nggak terlalu mikirin harta, tapi semangat banget kalau ada tantangan menabung 30 hari.",
        "Rajin, cerdas, dan nggak ribet. Kamu tipe orang yang tugasnya selesai sebelum grup sempat panik.",
        "Kamu semangat di awal proyek, lalu diam-diam jadi satu-satunya yang menyelesaikannya.",
        "Semangatmu menyala untuk orang lain. Pastikan masih ada sisa api untuk mimpimu sendiri.",
    ],
    "kamis_kliwon": [
        "Kamu pemimpin yang kalem dan misterius. Tim nggak tahu kamu lagi senang atau kecewa sampai rapat evaluasi.",
        "Semangatmu seperti api, tapi kamu menyalakannya diam-diam. Tahu-tahu proyekmu sudah jadi.",
        "Harga dirimu tinggi, tapi kamu pemaaf. Kamu memaafkan dengan anggun, lalu menjaga jarak dengan elegan.",
        "Temanmu banyak, tapi yang benar-benar tahu isi kepalamu bisa dihitung dengan satu tangan.",
        "Kamu senang diapresiasi, tapi nggak akan pernah minta. Pujian harus datang sendiri, tanpa kode.",
        "Sopan banget, sampai orang nggak sadar kamu sebenarnya lagi menolak permintaan mereka.",
        "Kamu pendiam di keramaian, tapi semua orang tetap menoleh ke kamu waktu butuh keputusan.",
        "Kamu jarang cerita soal diri sendiri, jadi orang-orang mengisi kekosongan itu dengan teori tentangmu.",
    ],
    "jumat_legi": [
        "Tutur katamu halus banget, sampai kritikanmu terdengar seperti pujian dan orang baru sadar besoknya.",
        "Kamu berpengetahuan luas dan gampang bergaul, jadi obrolan tongkrongan sering berubah jadi kelas gratis.",
        "Berani memberi saran ke orang lain, tapi ragu sendiri waktu harus ambil keputusan besar untuk hidupmu.",
        "Kamu dekat dengan keluarga, sampai grup keluarga lebih ramai kalau kamu yang mulai obrolan.",
        "Sabar saat susah, tapi nggak sabar menunggu balasan chat yang sudah centang biru.",
        "Kamu suka belajar, jadi rak bukumu penuh dengan buku yang baru dibaca sampai bab tiga.",
        "Kamu gampang akrab dengan siapa pun, termasuk orang yang baru ketemu di antrean kopi.",
        "Keputusan besar kamu diskusikan dengan lima orang, lalu kamu minta pendapat orang keenam.",
    ],
    "jumat_pahing": [
        "Tutur katamu halus, tapi kemauanmu keras. Kamu menolak dengan sopan, dan tetap menolak.",
        "Kamu mandiri dan nggak suka diatur. Petunjuk arah dari aplikasi pun kadang kamu anggap saran saja.",
        "Rapi dan berpengetahuan, jadi catatan kuliahmu dulu beredar lebih luas daripada materi dari dosen.",
        "Kamu sabar saat susah, tapi nggak sabar kalau ada orang yang kerjanya berantakan.",
        "Me-time bagimu adalah membaca, merapikan, lalu merapikan lagi yang sudah rapi.",
        "Kamu dekat dengan keluarga, tapi tetap butuh pintu kamar yang tertutup rapat untuk isi ulang energi.",
        "Kalau sudah punya rencana, kamu jalankan sendiri. Minta bantuan terasa seperti mengakui kalah.",
        "Kamu kasih saran dengan bahasa halus, lalu kecewa diam-diam waktu sarannya nggak dijalankan.",
    ],
    "jumat_pon": [
        "Tutur katamu lembut tapi pendirianmu tegas. Orang setuju denganmu tanpa sadar sedang dibujuk.",
        "Kamu berpengetahuan luas dan suka petualangan, jadi tiap perjalanan pulang dengan fakta sejarah baru.",
        "Kamu menarik dan baik hati, tapi jangan salah, kamu tetap punya batas yang jelas.",
        "Hidupmu cenderung berkecukupan, dan kamu paling senang membagikannya lewat traktiran kecil.",
        "Sabar saat susah, tegas saat perlu. Kamu tipe orang yang diandalkan waktu semua orang panik.",
        "Jiwa petualangmu kuat, tapi rencananya tetap matang. Spontanitasmu pun terjadwal.",
        "Kamu dekat dengan keluarga dan suka jadi juru bicara keluarga di setiap acara besar.",
        "Kamu punya pendirian, tapi menyampaikannya sehalus itu sampai orang lain merasa itu ide mereka.",
    ],
    "jumat_wage": [
        "Sabarmu dobel, dari Jumat dan dari neptu 10. Orang lain sudah marah, kamu masih bilang 'mungkin dia capek'.",
        "Kamu tempat curhat andalan karena tutur katamu halus dan kamu nggak pernah menghakimi.",
        "Gaya hidupmu sederhana dan kamu bahagia dengan itu. Orang lain sibuk upgrade, kamu sibuk menikmati.",
        "Kamu penurut, tapi jangan salah, pengetahuanmu luas. Kamu cuma memilih kapan mau menunjukkannya.",
        "Kamu dekat dengan keluarga dan jadi orang pertama yang ditelepon kalau ada yang butuh bantuan.",
        "Kamu terlalu sabar, sampai orang lupa kamu juga punya batas. Sesekali, tunjukkan batasnya.",
        "Kamu nggak mikirin harta, tapi diam-diam paling rajin menyisihkan uang untuk keluarga.",
        "Kamu cerdas memberi nasihat, tapi paling susah mengikuti nasihatmu sendiri.",
    ],
    "jumat_kliwon": [
        "Wetonmu jatuh di hari yang dianggap keramat, jadi wajar kalau auramu terasa misterius bahkan di video call.",
        "Kamu berpengetahuan luas tapi pendiam. Orang baru tahu kamu jago waktu ada masalah yang cuma kamu bisa beresin.",
        "Harga dirimu tinggi dan tutur katamu halus. Kamu bisa menolak ajakan tanpa satu pun kata 'nggak'.",
        "Kamu jago mencari jalan keluar, lalu menghilang lagi sebelum orang sempat bilang terima kasih.",
        "Supel kalau perlu, pendiam kalau bisa. Kamu tahu persis kapan harus bicara dan kapan harus menghilang.",
        "Kamu sabar saat susah dan jarang mengeluh. Yang tahu kamu lagi berat cuma playlist-mu.",
        "Kamu dekat dengan keluarga, tapi urusan pribadimu tetap tersimpan dengan sistem keamanan berlapis.",
        "Orang sering bertanya-tanya soal kamu. Kamu menikmati itu, sambil tetap membalas chat seperlunya.",
    ],
    "sabtu_legi": [
        "Kamu pekerja andal dan gampang bergaul, jadi selalu jadi orang pertama yang diajak ke proyek baru.",
        "Energimu seperti angin kencang. Masuk ruangan, semua orang langsung ikut semangat, atau ikut capek.",
        "Kamu jago cari solusi, tapi kadang solusimu datang sebelum orang selesai menjelaskan masalahnya.",
        "Nggak semua orang langsung cocok sama kamu, tapi yang cocok biasanya betah bertahun-tahun.",
        "Kamu suka belajar hal baru, dan cepat banget. Kursus online-mu tamat, orang lain baru selesai registrasi.",
        "Disegani di kantor, tapi di tongkrongan kamu yang paling heboh waktu main tebak-tebakan.",
        "Kamu supel dan cekatan, jadi sering jadi penghubung antar-tim yang sebenarnya bukan tugasmu.",
        "Tiap salah langkah jadi pelajaran. Bedanya, kamu belajar secepat angin, lalu langsung mencoba lagi.",
    ],
    "sabtu_pahing": [
        "Neptumu paling tinggi, 18, dan ambisimu ikut paling tinggi. Target tahunanmu punya subtarget per kuartal.",
        "Kamu pekerja keras, mandiri, dan rapi. Kalendermu lebih penuh dari jadwal praktik dokter spesialis.",
        "Ambisius dan suka mengatur. Kalau jadi ketua panitia, rapat pertama sudah membahas evaluasi akhir.",
        "Kamu disegani, tapi jarang ada yang berani mengajakmu santai tanpa agenda.",
        "Me-time bagimu adalah menyusun rencana lima tahun sambil minum teh hangat.",
        "Energimu seperti angin kencang. Orang lain masih pemanasan, kamu sudah di garis finis.",
        "Kamu mandiri banget sampai tim merasa jadi penonton. Libatkan mereka, hasilnya bisa lebih besar.",
        "Nggak semua orang cocok dengan ritmemu. Itu bukan salah mereka, kamu memang secepat itu.",
    ],
    "sabtu_pon": [
        "Kamu pemimpin alami: tegas, disegani, dan punya banyak teman yang siap ikut ide apa pun darimu.",
        "Energimu kencang, pendirianmu kuat. Kalau sudah memutuskan, rapat hanya formalitas.",
        "Kamu pemaaf, tapi tegas. Kesalahan pertama dimaafkan, kesalahan kedua diajak ngobrol serius.",
        "Hidupmu cenderung berkecukupan karena kamu kerja keras dan tegas soal prioritas.",
        "Sopan dan disegani, jadi orang-orang otomatis merapikan duduknya waktu kamu masuk ruangan.",
        "Nggak semua orang langsung cocok denganmu, tapi semua orang tahu kamu bisa diandalkan.",
        "Kamu kerja seperti angin kencang dan bicara seperti notulen: singkat, jelas, dan tanpa basa-basi.",
        "Temanmu banyak, tapi grup chat yang kamu buat selalu punya aturan tertulis.",
    ],
    "sabtu_wage": [
        "Kamu pekerja keras dengan gaya hidup sederhana. Gajian datang, yang kamu upgrade cuma sepatu kerja.",
        "Energimu seperti angin, dan jiwa petualangmu besar. Libur tiga hari cukup buatmu menjelajah dua kota.",
        "Kamu penurut dan bisa diandalkan, jadi selalu kebagian tugas tambahan tanpa ditanya dulu.",
        "Kamu menarik dan lembut, tapi kalau sudah kerja, kamu berubah jadi mesin produktivitas.",
        "Kamu nggak ribet, tapi kalau sudah punya tujuan perjalanan, nggak ada yang bisa mengubahnya.",
        "Nggak semua orang langsung cocok sama kamu, tapi kebaikanmu biasanya menang di akhir.",
        "Kamu disegani tanpa berusaha. Orang segan karena kamu kerja keras tanpa banyak omong.",
        "Kamu sederhana soal harta, tapi royal soal pengalaman. Tabunganmu habis buat tiket, bukan barang.",
    ],
    "sabtu_kliwon": [
        "Kamu pekerja keras yang pendiam. Orang baru sadar kontribusimu waktu kamu cuti seminggu.",
        "Energimu seperti angin, tapi kamu kalem di luar. Badai di kepalamu nggak pernah kelihatan.",
        "Harga dirimu tinggi dan kamu nggak suka ribut. Kalau tersinggung, kamu menghilang dengan tenang.",
        "Kamu disegani dan misterius. Rekan kerja masih menebak-nebak kamu tim kopi atau tim teh.",
        "Nggak semua orang cocok sama kamu, dan kamu santai saja. Kamu memang bukan untuk semua orang.",
        "Kamu baik hati dengan cara yang sunyi. Bantuanmu datang tanpa pengumuman dan tanpa minta balasan.",
        "Kamu kerja dengan tenang, lalu pulang tepat waktu. Kamu nggak butuh drama untuk kelihatan produktif.",
        "Orang mengira kamu dingin, padahal kamu cuma menghemat energi untuk orang-orang yang benar-benar penting.",
    ],
}

ROAST_DUO = {
    "pesthi": [
        "Kalian terlalu rukun sampai debat paling sengit kalian cuma soal martabak manis atau martabak telur.",
        "Pesthi dibaca tenang dan damai. Saking damainya, grup chat kalian isinya stiker dan 'oke siap' saja.",
        "Kalian cocok banget, sampai orang lain curiga kalian punya kontrak kerja sama rahasia.",
        "Hubungan kalian adem, cuma perlu sesekali kejutan biar nggak berubah jadi rutinitas autopilot.",
    ],
    "pegat": [
        "Petung kalian Pegat, jadi tolong jangan saling talangin dulu sebelum bikin sistem split bill yang jelas.",
        "Komunikasi kalian kadang kayak sinyal di basement: ada, tapi putus-putus. Upgrade pakai ngobrol langsung.",
        "Kalian berdua jago menunda obrolan penting. Masalahnya, obrolan yang ditunda nggak pernah kedaluwarsa.",
        "Pegat bukan vonis, cuma pengingat: urusan uang di antara kalian perlu catatan, bukan ingatan.",
    ],
    "ratu": [
        "Petung kalian Ratu, jadi wajar kalau kalian masuk ruangan seperti tim yang baru menang lomba.",
        "Kalian disegani lingkungan sekitar. Kadang terlalu disegani, sampai orang sungkan mengajak nongkrong.",
        "Duo kalian terasa elegan. Satu-satunya yang kurang elegan: cara kalian rebutan remote TV.",
        "Kalian kompak dan dihormati orang. Pastikan juga saling menghormati waktu salah satu butuh istirahat.",
    ],
    "jodoh": [
        "Hasil kalian Jodoh versi petung. Kalian bisa saling menerima kekurangan, termasuk selera musik yang aneh.",
        "Kalian cocok sampai bisa diam berdua satu jam tanpa merasa canggung. Itu level yang langka.",
        "Kalian saling melengkapi: yang satu lupa bawa charger, yang satu selalu bawa dua.",
        "Kecocokan kalian tinggi, tapi jangan lupa tetap bilang terima kasih. Cocok bukan berarti boleh cuek.",
    ],
    "topo": [
        "Petung kalian Topo: awalnya banyak salah paham, lalu pelan-pelan klik. Kayak install aplikasi pakai sinyal lemah.",
        "Kalian butuh waktu untuk saling paham. Sabar, loading bar-nya memang panjang tapi tetap jalan.",
        "Awal kalian penuh drama dompet tipis, tapi justru dari situ kalian belajar atur uang bareng.",
        "Topo dibaca susah dulu, senang belakangan. Jadi jangan bubar di episode pertama.",
    ],
    "tinari": [
        "Petung kalian Tinari, rezeki gampang datang. Tapi tolong, jangan semua rezeki langsung dipakai checkout.",
        "Kalian berdua sering beruntung bareng, sampai undian doorprize pun kalian menang berdua.",
        "Kalian bawa hoki satu sama lain. Tinggal pastikan hoki itu diimbangi rencana keuangan yang rapi.",
        "Duo kalian kayak voucher cashback: selalu ada untungnya, asal nggak lupa dipakai dengan bijak.",
    ],
    "padu": [
        "Petung kalian Padu, alias sering adu argumen. Kalian bisa debat soal cara lipat baju sampai tengah malam.",
        "Kalian sering beda pendapat, tapi tetap balik lagi. Kayak dua tab browser yang nggak pernah ditutup.",
        "Ribut kecil kalian lebih sering dari update aplikasi, tapi untungnya selalu ada versi baikan.",
        "Padu bukan akhir cerita. Aturan main sederhana: debat boleh, merendahkan jangan.",
    ],
    "sujanan": [
        "Petung kalian Sujanan, soal kepercayaan. Jadi jangan saling kepo HP, bikin kesepakatan terbuka saja.",
        "Kalian perlu hati-hati sama gosip dari luar. Cek ke orangnya langsung sebelum percaya kabar dari grup lain.",
        "Sujanan mengingatkan: transparansi itu hemat energi. Nggak perlu menebak-nebak isi pikiran satu sama lain.",
        "Kalau ada yang mengganjal, bilang. Kalian berdua terlalu jago berasumsi dan terlalu malas konfirmasi.",
    ],
}

ROAST_DISCLAIMER = (
    "Roasting ini candaan yang berangkat dari watak hari, pasaran, dan neptu di primbon. "
    "Ambil lucunya, simpan yang relate, lupakan sisanya."
)

ROAST_SOURCE = "Watak hari, pasaran, dan jumlah neptu dalam primbon Jawa; roasting berdua mengikuti petung sisa bagi 8."
